<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 28 Jun 2024 04:28:14 +0000
// --------------------------------------------------------------------------------

$l['nav_announcements'] = '포럼 공지';
$l['announcements'] = '공지사항';
$l['forum_announcement'] = '포럼 공지: {1}';
$l['error_invalidannouncement'] = '지정된 공지가 잘못되었습니다.';
$l['announcement_edit'] = '이 공지사항 수정';
$l['announcement_qdelete'] = '이 공지 삭제';
$l['announcement_quickdelete_confirm'] = '이 공지를 삭제하시겠습니까?';
