<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 23:56:00 +0000
// --------------------------------------------------------------------------------

$l['archive_fullversion'] = '전체 버전:';
$l['archive_replies'] = '답글';
$l['archive_reply'] = '회신';
$l['archive_pages'] = '페이지:';
$l['archive_note'] = '귀하는 현재 당사 콘텐츠의 축소된 버전을 보고 계십니다. 올바른 형식으로 <a href="{1}">정식 버전을 보십시오</a>.';
$l['archive_nopermission'] = '죄송합니다. 이 리소스에 액세스할 수 있는 권한이 없습니다.';
$l['error_nothreads'] = '현재 이 포럼에는 글타래가 없습니다.';
$l['error_nopermission'] = '이 포럼의 클타래를 볼 수 있는 권한이 없습니다.';
$l['error_unapproved_thread'] = '이 클타래는 승인되지 않았습니다. 이 글타래의 내용을 보려면 <a href="{1}">정식 버전을 확인</a>하세요.';
$l['archive_not_found'] = '요청한 페이지를 이 서버에서 찾을 수 없습니다.';
$l['error_mustlogin'] = '이 게시판에는 모든 사용자가 로그인해야 합니다.';
