<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어 (South Korea)
// Author of the language pack : zardkim
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Mon, 08 Jul 2024 01:30:54 +0000
// --------------------------------------------------------------------------------

$l['avatarep_user_profile'] = '프로필보기';
$l['avatarep_user_messages'] = '메시지 보기';
$l['avatarep_user_sendpm'] = 'PM 보내기';
$l['avatarep_user_sendemail'] = '이메일을 보내기';
$l['avatarep_user_threads'] = '글타래 보기';
$l['avatarep_user_error'] = '오류';
$l['avatarep_user_error_text'] = '이 콘텐츠를 보려면 로그인해야 합니다.';
$l['avatarep_user_alt'] = '{1}의 아바타';
$l['avatarep_user_no_avatar'] = '아바타 없음';
$l['avatarep_retrieving'] = '데이터 검색';
$l['avatarep_loading'] = '로딩중...';
$l['registration_date'] = '등록일:';
$l['reputation'] = '평판:';
$l['total_threads'] = '글타래:';
$l['total_posts'] = '게시물:';
$l['lastvisit'] = '마지막 방문:';
$l['warning_level'] = '경고 수준:';
$l['online_status'] = '상태:';
$l['find_threads'] = '사용자 글타래';
$l['find_posts'] = '사용자 게시물';
$l['guest'] = '손님';
