<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 23:56:35 +0000
// --------------------------------------------------------------------------------

$l['nav_calendar'] = '달력';
$l['nav_viewevent'] = '이벤트 보기';
$l['nav_dayview'] = '일별 보기';
$l['nav_addevent'] = '이벤트 추가';
$l['nav_editevent'] = '이벤트 편집';
$l['nav_move_event'] = '이벤트 이동';
$l['calendar_disabled'] = '관리자가 달력 기능을 비활성화했기 때문에 달력 기능을 사용할 수 없습니다.';
$l['alt_month_1'] = '1월';
$l['alt_month_2'] = '2월';
$l['alt_month_3'] = '3월';
$l['alt_month_4'] = '4월';
$l['alt_month_5'] = '5월';
$l['alt_month_6'] = '6월';
$l['alt_month_7'] = '7월';
$l['alt_month_8'] = '8월';
$l['alt_month_9'] = '9월';
$l['alt_month_10'] = '10월';
$l['alt_month_11'] = '11월';
$l['alt_month_12'] = '12월';
$l['add_private_event'] = '비공개 이벤트 추가';
$l['add_public_event'] = '공개 이벤트 추가';
$l['calendar'] = '달력';
$l['jump_month'] = '해당 월로 이동:';
$l['birthdays_on_day'] = '생일은 {1}입니다';
$l['birthdayhidden'] = '숨김';
$l['event'] = '이벤트';
$l['events'] = '이벤트';
$l['add_event'] = '이벤트 추가';
$l['event_date'] = '이벤트 날짜';
$l['event_recurring_start_date'] = '시작일:';
$l['event_recurring_end_date'] = '종료일:';
$l['event_recurring_repeat_days'] = '이벤트 반복 날짜:';
$l['event_name'] = '이벤트 이름:';
$l['event_details'] = '이벤트 세부정보:';
$l['event_options'] = '옵션:';
$l['private_option'] = '<b>비공개</b> 귀하만 이 이벤트를 볼 수 있습니다. (등록된 사용자만 해당)';
$l['delete_option'] = '<b>삭제:</b> 이 이벤트를 삭제합니다.';
$l['post_event'] = '포스트 이벤트';
$l['day_view'] = '일별 보기';
$l['birthday'] = '생일';
$l['birthdays'] = '생일';
$l['event_author'] = '이벤트 작성자:';
$l['edit_event'] = '이벤트 편집';
$l['view_event'] = '이벤트 보기';
$l['no_events'] = '이 날에는 관련된 이벤트가 없습니다.<p><a href="calendar.php?action=addevent&amp;calendar={1}&amp;day={2}&amp;month={3}&amp;year= {4}">이벤트를 게시하세요</a>.</p>';
$l['years_old'] = '{1} Years Old';
$l['alt_edit'] = '이 이벤트 수정';
$l['alt_delete'] = '이 일정 삭제';
$l['moderator_options'] = '운영자 옵션';
$l['approve_event'] = '이벤트 승인';
$l['unapprove_event'] = '이벤트 승인 취소';
$l['move_event'] = '이벤트 이동';
$l['repeats_every_day'] = '매일 반복됨';
$l['repeats_every_x_days'] = '{1}일마다 반복';
$l['repeats_on_weekdays'] = '월요일부터 금요일까지 반복됨';
$l['every_week_on_days'] = '매주 {1}에 반복됨';
$l['every_week'] = '매주 반복됨';
$l['every_x_weeks_on_days'] = '매 {1}주마다<br />{2}에 반복됨';
$l['every_x_weeks'] = '{1}주마다 반복';
$l['every_month_on_day'] = '매월 {1}<br />일에 반복';
$l['every_x_months_on_day'] = '매 {2}개월의 {1}<br />일에 반복';
$l['every_month_on_weekday'] = '매월 {1} {2}<br />반복';
$l['every_x_months_on_weekday'] = '매 {3}개월마다 {1} {2}<br />반복';
$l['weekday_occurance_1'] = '첫번째';
$l['weekday_occurance_2'] = '두번째';
$l['weekday_occurance_3'] = '세번째';
$l['weekday_occurance_4'] = '네번째';
$l['weekday_occurance_last'] = '마지막';
$l['every_year_on_day'] = '매년 {1} {2}에 반복됩니다.';
$l['every_x_years_on_day'] = '{3}년마다 {1} {2}에 반복됩니다.';
$l['every_year_on_weekday'] = '매년 {3}의 {1} {2}에 반복됩니다.';
$l['every_x_year_on_weekday'] = '{4}년마다 {3}의 {1} {2}에 반복됩니다.';
$l['delete_event'] = '이벤트 삭제';
$l['delete_q'] = '삭제?';
$l['delete_1'] = '이 이벤트를 삭제하려면 왼쪽의 확인란을 선택한 후 오른쪽의 버튼을 클릭하세요.';
$l['delete_2'] = '<b>참고:</b> 이 프로세스는 취소할 수 없습니다.';
$l['delete_now'] = '지금 삭제';
$l['delete_no_checkbox'] = '\'삭제\' 체크박스를 선택하지 않았기 때문에 일정이 삭제되지 않았습니다.';
$l['jump_to_calendar'] = '캘린더로 이동:';
$l['select_calendar'] = '달력:';
$l['type_single'] = '해당일자 이벤트';
$l['type_ranged'] = '원거리 또는 반복 이벤트';
$l['enter_time'] = '시간:';
$l['start_time'] = '시작:';
$l['end_time'] = '마감:';
$l['timezone'] = '시간대:';
$l['ignore_timezone'] = '<strong>시간대 무시:</strong> 이 이벤트는 시청자의 시간대를 사용해야 합니다.';
$l['repeats'] = '반복:';
$l['does_not_repeat'] = '반복하지 않음';
$l['repeats_daily'] = '일일';
$l['repeats_weekdays'] = '매주 평일(월~금)';
$l['repeats_weekly'] = '주간';
$l['repeats_every'] = '반복 간격';
$l['day_or_days'] = 'day(s)';
$l['week_or_weeks_on'] = 'week(s) on';
$l['repeats_monthly'] = '월간';
$l['repeats_yearly'] = '연간';
$l['repeats_on_day'] = '요일에 반복';
$l['of_every'] = 'of every';
$l['month_or_months'] = 'month(s)';
$l['repeats_on_the'] = '에서 반복';
$l['day_of_every'] = '매일';
$l['repeats_on'] = '반복 날짜';
$l['every'] = '매일';
$l['year_or_years'] = 'year(s)';
$l['of'] = 'of';
$l['move_to_calendar'] = '캘린더로 이동:';
$l['weekly_overview'] = '주간 개요';
$l['previous_week'] = '지난주';
$l['next_week'] = '다음 주';
$l['first'] = '첫 번째';
$l['second'] = '두번째';
$l['third'] = '세번째';
$l['fourth'] = '네번째';
$l['last'] = '마지막';
$l['all_day'] = '하루 종일';
$l['starts'] = '시작:';
$l['finishes'] = '마감:';
$l['error_incorrectday'] = '입력하신 날짜가 존재하지 않는 것 같습니다. 돌아가서 다시 시도해 주세요.';
$l['error_invalidevent'] = '지정한 이벤트가 잘못되었거나 존재하지 않습니다.';
$l['invalid_calendar'] = '지정한 달력이 존재하지 않습니다. 올바른 페이지를 방문하고 있습니까?';
$l['redirect_eventdeleted'] = '일정이 성공적으로 삭제되었습니다.<br />이제 캘린더로 돌아갑니다.';
$l['redirect_eventupdated'] = '이벤트가 성공적으로 업데이트되었습니다.<br />이제 해당 이벤트로 돌아갑니다.';
$l['redirect_eventadded'] = '귀하의 이벤트가 성공적으로 추가되었습니다.<br />이제 이벤트로 이동됩니다.';
$l['redirect_eventadded_moderation'] = '귀하의 이벤트가 성공적으로 추가되었지만 공개되기 전에 포럼 중재자의 조정이 필요합니다.<br />이제 캘린더로 돌아갑니다.';
$l['redirect_eventunapproved'] = '이벤트가 성공적으로 승인 취소되었습니다.<br />이제 해당 이벤트로 이동됩니다.';
$l['redirect_eventapproved'] = '이벤트가 성공적으로 승인되었습니다.<br />이제 이벤트로 이동됩니다.';
$l['redirect_eventmoved'] = '이벤트가 성공적으로 이동되었습니다.<br />이제 이벤트로 이동됩니다.';
