<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 28 Jun 2024 02:33:36 +0000
// --------------------------------------------------------------------------------

$l['contact'] = '문의하기';
$l['contact_no_message'] = '보낼 메시지를 제공하지 않았습니다.';
$l['contact_no_subject'] = '제목을 입력해야 합니다.';
$l['contact_no_email'] = '유효한 이메일 주소를 입력해야 합니다.';
$l['contact_success_message'] = '귀하의 메시지가 관리자에게 성공적으로 전송되었습니다.';
$l['contact_subject'] = '제목';
$l['contact_subject_desc'] = '메시지 주제를 간략하게 설명하세요.';
$l['contact_message'] = '메시지';
$l['contact_message_desc'] = '이 분야에 대한 귀하의 우려 사항을 자세히 설명하십시오.';
$l['contact_email'] = '이메일';
$l['contact_email_desc'] = '우리가 다시 연락할 수 있도록 이메일을 입력하세요.';
$l['contact_send'] = '보냄';
$l['subject_too_long'] = '제목이 너무 깁니다. {1}자(현재 {2})보다 짧은 제목을 입력하세요.';
$l['message_too_short'] = '메시지가 너무 짧습니다. {1}자(현재 {2})보다 긴 메시지를 입력하세요.';
$l['message_too_long'] = '메시지가 너무 깁니다. {1}자(현재 {2})보다 짧은 메시지를 입력하세요.';
$l['error_stop_forum_spam_spammer'] = '죄송합니다. {1}은(는) 알려진 스팸 발송자의 이름과 일치하므로 귀하의 연락처 제출이 차단되었습니다.';
$l['error_stop_forum_spam_fetching'] = '죄송합니다. 스팸 발송자 데이터베이스와 비교하여 메시지를 확인하는 중에 문제가 발생했습니다. 데이터베이스에 액세스하지 못했을 가능성이 높습니다. 나중에 다시 시도 해주십시오.';
