<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 28 Jun 2024 03:10:47 +0000
// --------------------------------------------------------------------------------

$l['eventdata_missing_name'] = '이벤트 이름이 누락되었습니다. 이벤트 이름을 입력하세요.';
$l['eventdata_missing_description'] = '이벤트에 대한 설명이 누락되었습니다. 이벤트 설명을 입력해주세요.';
$l['eventdata_invalid_start_date'] = '입력한 이벤트 시작일이 잘못되었습니다. 일, 월, 연도를 지정하고 입력한 날짜가 특정 월에 유효한지 확인해야 합니다.';
$l['eventdata_invalid_start_year'] = '이벤트는 향후 5년 동안만 생성할 수 있습니다. 목록에서 적절한 시작 연도를 선택하세요.';
$l['eventdata_invalid_start_month'] = '입력한 시작 월이 유효한 월이 아닙니다. 유효한 시작월을 입력하세요.';
$l['eventdata_invalid_end_date'] = '입력한 이벤트 종료 날짜가 잘못되었습니다. 일, 월, 연도를 지정하고 입력한 날짜가 특정 월에 유효한지 확인해야 합니다.';
$l['eventdata_invalid_end_year'] = '이벤트는 향후 5년 동안만 생성할 수 있습니다. 목록에서 적절한 종료 연도를 선택하세요.';
$l['eventdata_invalid_end_month'] = '입력한 종료 달이 유효한 달이 아닙니다. 유효한 종료 월을 입력하세요.';
$l['eventdata_invalid_end_day'] = '입력한 종료일이 유효한 날짜가 아닙니다. 선택한 날짜가 이번 달의 날짜 수보다 클 수 있습니다.';
$l['eventdata_cant_specify_one_time'] = '이벤트 시작 시간을 지정하는 경우 이벤트 종료 시간을 입력해야 합니다.';
$l['eventdata_start_time_invalid'] = '입력한 시작 시간이 잘못되었습니다. 유효한 예는 오전 12시, 오전 12시 1분, 00:01입니다.';
$l['eventdata_end_time_invalid'] = '입력한 종료 시간이 잘못되었습니다. 유효한 예는 오전 12시, 오전 12시 1분, 00:01입니다.';
$l['eventdata_invalid_timezone'] = '이 이벤트에 대해 선택한 시간대가 잘못되었습니다.';
$l['eventdata_end_in_past'] = '이벤트 종료 날짜 또는 시간이 시작 날짜 또는 시간보다 이전입니다.';
$l['eventdata_only_ranged_events_repeat'] = '범위 이벤트(시작 날짜와 종료 날짜가 있는 이벤트)만 반복할 수 있습니다.';
$l['eventdata_invalid_repeat_day_interval'] = '잘못된 날짜 반복 간격을 입력했습니다.';
$l['eventdata_invalid_repeat_week_interval'] = '잘못된 주 반복 간격을 입력했습니다.';
$l['eventdata_invalid_repeat_weekly_days'] = '이 이벤트가 발생할 평일을 선택하지 않았습니다.';
$l['eventdata_invalid_repeat_month_interval'] = '잘못된 월 반복 간격을 입력했습니다.';
$l['eventdata_invalid_repeat_year_interval'] = '잘못된 연도 반복 간격을 입력했습니다.';
$l['eventdata_event_wont_occur'] = '이벤트 반복 설정과 함께 시작 및 종료 시간을 사용하면 이 이벤트가 발생하지 않습니다.';
$l['eventdata_no_permission_private_event'] = '비공개 이벤트를 게시할 권한이 없습니다.';
