<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 28 Jun 2024 03:16:55 +0000
// --------------------------------------------------------------------------------

$l['pmdata_too_long_subject'] = '비공개 메시지의 제목이 너무 깁니다. 제목을 더 짧게 입력해 주세요.';
$l['pmdata_code_no_subject'] = '[제목 없음]';
$l['pmdata_missing_subject'] = '메시지 제목을 입력하지 않았습니다. 제목을 입력하세요.';
$l['pmdata_missing_message'] = '보낼 메시지를 입력하지 않으셨습니다. 메시지를 입력해주세요.';
$l['pmdata_message_too_long'] = '메시지가 너무 깁니다. {1}자(현재 {2})보다 짧은 메시지를 입력하세요.';
$l['pmdata_invalid_recipients'] = '지정한 수신자 중 한 명 이상이 등록된 사용자 이름이 아닙니다. 잘못된 수신자: {1}';
$l['pmdata_no_recipients'] = '이 메시지를 보낼 수신자를 입력하지 않았습니다. \'받는 사람\' 필드에 사용자 이름을 하나 이상 입력해야 합니다.';
$l['pmdata_too_many_recipients'] = '한 번에 {1}명의 사용자에게만 메시지를 보낼 수 있습니다.';
$l['pmdata_recipient_is_ignoring'] = '귀하는 무시 목록에 있으므로 {1}에게 메시지를 보낼 수 없습니다.';
$l['pmdata_recipient_has_buddy_only'] = '귀하는 친구 목록에 없기 때문에 {1}에게 메시지를 보낼 수 없습니다.';
$l['pmdata_recipient_pms_disabled'] = '{1}님은 비공개 메시징을 비활성화했습니다. 이 사용자에게 비공개 메시지를 보낼 수 없습니다.';
$l['pmdata_recipient_reached_quota'] = '{1}님이 비공개 메시지 할당량에 도달하여 귀하의 메시지를 보낼 수 없습니다.';
$l['pmdata_pm_flooding'] = '이전 메시지를 보낸 후 너무 빨리 메시지를 보내려고 합니다. {1}초 더 기다려 주세요.';
$l['pmdata_pm_flooding_one_second'] = '이전 메시지를 보낸 후 너무 빨리 메시지를 보내려고 합니다. 1초만 더 기다려주세요.';
