<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 28 Jun 2024 04:31:41 +0000
// --------------------------------------------------------------------------------

$l['warnings_reached_max_warnings_day'] = '하루에 보낼 수 있는 경고 횟수 한도에 도달했기 때문에 아무에게도 경고할 수 없습니다.<br /><br />하루에 보낼 수 있는 최대 경고 횟수는 {1}개입니다.';
$l['warnings_error_invalid_user'] = '선택한 사용자가 존재하지 않습니다.';
$l['warnings_error_invalid_post'] = '선택한 게시물이 존재하지 않습니다.';
$l['warnings_error_cannot_warn_self'] = '자신의 경고 수준을 추가할 수 없습니다.';
$l['warnings_error_user_reached_max_warning'] = '이 사용자는 이미 최대 경고 수준에 도달했으므로 경고를 받을 수 없습니다.';
$l['warnings_error_no_note'] = '이 경고에 대한 관리 메모를 입력하지 않았습니다.';
$l['warnings_error_invalid_type'] = '잘못된 경고 유형을 선택했습니다.';
$l['warnings_error_cant_custom_warn'] = '사용자에게 맞춤 경고를 제공할 권한이 없습니다.';
$l['warnings_error_no_custom_reason'] = '맞춤 경고 이유를 입력하지 않았습니다.';
$l['warnings_error_invalid_custom_points'] = '이 사용자 경고 수준에 추가할 유효한 포인트 수를 입력하지 않았습니다. 0보다 크고 {1}보다 크지 않은 숫자 값을 입력해야 합니다.';
$l['warnings_error_invalid_expires_period'] = '잘못된 만료 유형을 입력했습니다.';
