<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 23:57:12 +0000
// --------------------------------------------------------------------------------

$l['postdata_invalid_user_id'] = '사용자 ID가 존재하지 않습니다. 유효한 사용자 ID를 제공하십시오.';
$l['postdata_firstpost_no_subject'] = '글타래에는 주제가 없습니다. 제목을 입력하세요.';
$l['postdata_missing_subject'] = '제목이 누락되었습니다. 제목을 입력하세요.';
$l['postdata_missing_message'] = '메시지가 없습니다. 메시지를 입력해주세요.';
$l['postdata_message_too_long'] = '메시지가 너무 깁니다. {1}자(현재 {2})보다 짧은 메시지를 입력하세요.';
$l['postdata_message_too_short'] = '메시지가 너무 짧습니다. {1}자보다 긴 메시지를 입력하세요.';
$l['postdata_subject_too_long'] = '제목이 너무 깁니다. 85자(현재 {1}) 미만의 제목을 입력하세요.';
$l['postdata_banned_username'] = '입력하신 사용자 이름은 등록되지 않았을 수 있습니다. 다른 사용자 이름을 입력하세요.';
$l['postdata_bad_characters_username'] = '입력한 사용자 이름에 잘못된 문자가 포함되어 있습니다. 다른 사용자 이름을 입력하세요.';
$l['postdata_invalid_username_length'] = '입력한 사용자 이름의 길이가 잘못되었습니다. {1}~{2}자 사이의 사용자 이름을 입력하세요.';
$l['postdata_username_exists'] = '입력한 사용자 이름이 이미 존재합니다. 다른 사용자 이름을 입력하세요.';
$l['postdata_post_flooding'] = '이전 메시지를 게시한 후 너무 빨리 메시지를 게시하려고 합니다. {1}초 더 기다려 주세요.';
$l['postdata_post_flooding_one_second'] = '이전 메시지를 게시한 후 너무 빨리 메시지를 게시하려고 합니다. 1초만 더 기다려주세요.';
$l['postdata_too_many_images'] = '입력한 메시지에는 {1}개의 이미지가 포함되어 있지만 메시지당 이미지는 {2}개만 허용됩니다. 제한을 충족하려면 메시지의 이미지 수를 줄여주세요.';
$l['postdata_too_many_videos'] = '입력한 메시지에는 {1}개의 동영상이 포함되어 있지만 메시지당 {2}개의 동영상만 허용됩니다. 제한을 충족하려면 메시지의 동영상 개수를 줄여주세요.';
$l['postdata_invalid_prefix'] = '선택한 접두사가 잘못되었습니다. 유효한 접두사를 선택하세요.';
$l['postdata_require_prefix'] = '이 포럼에서는 글타래 접두어를 설정해야 합니다. 유효한 접두사를 선택하세요.';
$l['thread_closed'] = '글타래 마감됨';
$l['thread_opened'] = '글타래 열림';
$l['thread_stuck'] = '글타래 멈춤';
$l['thread_unstuck'] = '글타래 고정해제';
