<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 28 Jun 2024 03:14:36 +0000
// --------------------------------------------------------------------------------

$l['logindata_invalidpwordusername'] = '잘못된 사용자 이름/비밀번호 조합을 입력했습니다. <br /><br />비밀번호를 잊어버린 경우 <a href="member.php?action=lostpw">새 비밀번호를 검색</a>하시기 바랍니다.';
$l['logindata_invalidpwordusernameemail'] = '잘못된 이메일/비밀번호 조합을 입력하셨습니다. <br /><br />비밀번호를 잊어버린 경우 <a href="member.php?action=lostpw">새 비밀번호를 검색</a>하시기 바랍니다.';
$l['logindata_invalidpwordusernamecombo'] = '잘못된 사용자 이름/비밀번호 또는 이메일/비밀번호 조합을 입력했습니다. <br /><br />비밀번호를 잊어버린 경우 <a href="member.php?action=lostpw">새 비밀번호를 검색</a>하시기 바랍니다.';
$l['logindata_regimageinvalid'] = '입력한 이미지 인증 코드가 올바르지 않습니다. 이미지에 표시된 대로 코드를 정확하게 입력하세요.';
$l['logindata_regimagerequired'] = '로그인 프로세스를 계속하려면 이미지 인증 코드를 입력하세요. 이미지에 표시된 대로 코드를 정확하게 입력하세요.';
