<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 28 Jun 2024 04:38:22 +0000
// --------------------------------------------------------------------------------

$l['nav_editpost'] = '게시물 수정';
$l['edit_post'] = '이 게시물 편집';
$l['delete_post'] = '게시물 삭제';
$l['delete_q'] = '삭제?';
$l['delete_1'] = '이 게시물을 삭제하려면 왼쪽의 확인란을 선택한 후 오른쪽의 버튼을 클릭하세요.';
$l['delete_2'] = '<b>참고:</b> 이 게시물이 글타래의 첫 번째 게시물인 경우 삭제하면 전체 글타래가 삭제됩니다.';
$l['subject'] = '주제:';
$l['your_message'] = '나의 메시지:';
$l['post_options'] = '게시물 옵션:';
$l['editreason'] = '이유 편집:';
$l['options_sig'] = '<strong>서명:</strong> 서명을 포함하세요. (등록된 사용자만)';
$l['options_emailnotify'] = '<strong>이메일 알림:</strong> 새 답변이 있을 때마다 이메일을 받습니다. (등록된 사용자만)';
$l['options_disablesmilies'] = '<strong>웃음 비활성화:</strong> 이 게시물에 웃는 얼굴이 표시되지 않도록 합니다.';
$l['preview_post'] = '게시물 미리보기';
$l['update_post'] = '게시물 업데이트';
$l['poll'] = '투표:';
$l['poll_desc'] = '선택적으로 이 글타래에 설문조사를 첨부할 수 있습니다.';
$l['poll_check'] = '설문조사를 게시하고 싶습니다.';
$l['num_options'] = '옵션 수:';
$l['max_options'] = '(최대: {1})';
$l['delete_now'] = '지금 삭제';
$l['edit_time_limit'] = '죄송합니다. 게시물을 편집할 수 없습니다. 관리자는 게시 후 {1}분 이내에만 게시물을 편집할 수 있도록 설정했습니다.';
$l['no_prefix'] = '접두사 없음';
$l['redirect_nodelete'] = '\'삭제\' 체크박스를 선택하지 않으셨기 때문에 게시물이 삭제되지 않았습니다.';
$l['redirect_norestore'] = '\'복원\' 체크박스를 선택하지 않아 게시물이 복원되지 않았습니다.';
$l['redirect_postedited'] = '감사합니다. 게시물이 수정되었습니다.<br />';
$l['redirect_postedited_redirect'] = '이제 글타래로 돌아갑니다.';
$l['redirect_postedited_poll'] = '감사합니다. 이 게시물은 수정되었습니다. <br />설문 게시를 선택하셨으므로 이제 설문 작성 페이지로 이동하게 됩니다.';
$l['error_invalidpost'] = '죄송합니다. 잘못된 주소를 팔로우하신 것 같습니다. 지정된 게시물이 있는지 확인하고 다시 시도해 주세요.';
$l['redirect_threaddeleted'] = '감사합니다. 글타래가 삭제되었습니다.<br />이제 포럼으로 돌아가게 됩니다.';
$l['redirect_postdeleted'] = '감사합니다. 게시물이 삭제되었습니다.<br />이제 글타래로 돌아갑니다.';
$l['redirect_threadrestored'] = '감사합니다. 글타래가 복원되었습니다.<br />이제 포럼으로 돌아가게 됩니다.';
$l['redirect_postrestored'] = '감사합니다. 게시물이 복원되었습니다.<br />이제 글타래로 돌아갑니다.';
$l['redirect_threadclosed'] = '중재자가 이 글타래를 폐쇄했기 때문에 이 글타래의 기존 게시물을 편집할 수 없습니다.';
$l['redirect_post_moderation'] = '관리자는 모든 게시물 편집에 조정이 필요하도록 지정했습니다. 이제 글타래로 돌아갑니다.';
$l['redirect_thread_moderation'] = '관리자는 모든 글타래 편집에 조정이 필요하도록 지정했습니다. 이제 포럼 색인으로 돌아갑니다.';
$l['error_already_delete'] = '죄송합니다. 이 게시물은 이미 삭제되었습니다.';
$l['thread_deleted'] = '글타래가 영구적으로 삭제되었습니다.';
$l['post_deleted'] = '게시물이 영구적으로 삭제되었습니다';
$l['thread_soft_deleted'] = '소프트 삭제된 글타래';
$l['post_soft_deleted'] = '소프트 삭제된 게시물';
$l['thread_restored'] = '복원된 글타래';
$l['post_restored'] = '복원된 게시물';
$l['error_already_deleted'] = '선택한 게시물은 이미 삭제되었습니다.';
