<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어(South Korea)
// Author of the language pack : zardkim
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Mon, 08 Jul 2024 23:48:42 +0000
// --------------------------------------------------------------------------------

$l['post_thread'] = '새 글타래 작성';
$l['moderated_by'] = '운영자:';
$l['nothreads'] = '죄송합니다. 현재 이 포럼에는 지정된 날짜 및 시간 제한 옵션이 있는 글타래가 없습니다.';
$l['nopermission'] = '죄송합니다. 이 포럼의 글타래를 볼 권한이 없습니다.';
$l['search_forum'] = '이 포럼 검색:';
$l['thread'] = '글타래';
$l['author'] = '작성자';
$l['replies'] = '답글';
$l['views'] = '조회';
$l['lastpost'] = '마지막 게시물';
$l['rating'] = '평가';
$l['prefix'] = '접두어:';
$l['prefix_all'] = '접두어: 임의/접두어 없음';
$l['prefix_any'] = '접두어: 모든 접두어';
$l['prefix_none'] = '접두어: 접두어 없음';
$l['markforum_read'] = '이 포럼을 읽은 것으로 표시';
$l['subscribe_forum'] = '이 포럼을 구독하세요';
$l['unsubscribe_forum'] = '이 포럼에서 구독 취소';
$l['clear_stored_password'] = '저장된 포럼 비밀번호 지우기';
$l['sort_by_subject'] = '정렬 기준: 주제';
$l['sort_by_lastpost'] = '정렬 기준: 마지막 게시물';
$l['sort_by_starter'] = '정렬 기준: 작성자';
$l['sort_by_started'] = '정렬 기준: 생성 시간';
$l['sort_by_rating'] = '정렬 기준: 평가';
$l['sort_by_replies'] = '정렬 기준: 답글';
$l['sort_by_views'] = '정렬 기준: 조회수';
$l['sort_order_asc'] = '순서: 오름차순';
$l['sort_order_desc'] = '순서: 내림차순';
$l['datelimit_1day'] = 'From: 오늘';
$l['datelimit_5days'] = 'From: 5일 전';
$l['datelimit_10days'] = 'From: 10일 전';
$l['datelimit_20days'] = 'From: 20일 전';
$l['datelimit_50days'] = 'From: 50일 전';
$l['datelimit_75days'] = 'From: 75일 전';
$l['datelimit_100days'] = 'From: 100일 전';
$l['datelimit_lastyear'] = 'From: 마지막 해';
$l['datelimit_beginning'] = 'From: 처음부터';
$l['new_thread'] = '새 게시물';
$l['new_hot_thread'] = '핫 글타래(신규)';
$l['posts_by_you'] = '내 게시물이 포함됨';
$l['no_new_thread'] = '새 게시물 없음';
$l['hot_thread'] = '핫 글타래(신규 없음)';
$l['closed_thread'] = '닫힌 글타래';
$l['goto_first_unread'] = '읽지 않은 첫 번째 게시물로 이동';
$l['pages'] = '페이지:';
$l['pages_last'] = '마지막';
$l['users_browsing_forum'] = '이 포럼을 탐색하는 사용자:';
$l['users_browsing_forum_guests'] = '{1} 손님';
$l['users_browsing_forum_invis'] = '{1} 비공개 사용자';
$l['delayed_moderation'] = '지연된 운영자';
$l['inline_thread_moderation'] = '인라인 글타래 운영:';
$l['close_threads'] = '글타래 닫기';
$l['open_threads'] = '글타래 열기';
$l['stick_threads'] = '고정 글타래';
$l['unstick_threads'] = '글타래 풀기';
$l['soft_delete_threads'] = '일시 삭제 글타래';
$l['restore_threads'] = '글타래 복원';
$l['delete_threads'] = '글타래를 영구적으로 삭제';
$l['move_threads'] = '글타래 이동/복사';
$l['approve_threads'] = '글타래 승인';
$l['unapprove_threads'] = '글타래 승인 취소';
$l['inline_go'] = '가기';
$l['clear'] = '지우기';
$l['sub_forums_in'] = '\'{1}\'의 포럼';
$l['forum_rules'] = '{1} - 규칙';
$l['subforums'] = '하위 포럼:';
$l['asc'] = '오름차순';
$l['desc'] = '내림차순';
$l['forum_announcements'] = '포럼 공지';
$l['sticky_threads'] = '중요한 글타래';
$l['normal_threads'] = '일반 글타래';
$l['icon_dot'] = '귀하가 작성한 게시물이 포함되어 있습니다.';
$l['icon_no_new'] = '새 게시물이 없음';
$l['icon_new'] = '새 게시물.';
$l['icon_hot'] = '핫 글타래';
$l['icon_close'] = '닫힌 글타래.';
$l['attachment_count'] = '이 글타래에는 첨부 파일 1개가 포함되어 있습니다.';
$l['attachment_count_multiple'] = '이 글타래에는 {1}개의 첨부 파일이 포함되어 있습니다.';
$l['rss_discovery_forum'] = '{1}의 최신 글타래';
$l['forum_unapproved_posts_count'] = '현재 이 포럼에는 승인되지 않은 게시물이 {1}개 있습니다.';
$l['forum_unapproved_post_count'] = '현재 이 포럼에는 승인되지 않은 게시물이 1개 있습니다.';
$l['forum_unapproved_threads_count'] = '현재 이 포럼에는 승인되지 않은 글타래가 {1}개 있습니다.';
$l['forum_unapproved_thread_count'] = '현재 이 포럼에는 승인되지 않은 글타래가 1개 있습니다.';
$l['thread_unapproved_posts_count'] = '현재 이 글타래에는 승인되지 않은 게시물이 {1}개 있습니다.';
$l['thread_unapproved_post_count'] = '현재 이 글타래에는 승인되지 않은 게시물이 1개 있습니다.';
$l['page_selected'] = '이 페이지의 모든 <strong>{1}</strong> 글타래가 선택되었습니다.';
$l['all_selected'] = '이 포럼의 <strong>{1}</strong> 글타래가 모두 선택되었습니다.';
$l['select_all'] = '이 포럼의 <strong>{1}</strong> 글타래를 모두 선택하세요.';
$l['clear_selection'] = '선택 지우기';
$l['deleted_thread'] = '글타래 삭제';
$l['select_a_tool'] = '도구 선택';
$l['error_containsnoforums'] = '죄송합니다. 현재 보고 계신 포럼에는 하위 포럼이 포함되어 있지 않습니다.';
$l['inline_no_tool_selected'] = '검토 작업을 수행하려면 도구를 선택하세요.';
$l['inline_no_post_selected'] = '중재 작업을 수행하려면 하나 이상의 게시물을 선택해야 합니다.';
$l['inline_edit_description'] = '(수정하려면 길게 클릭하세요)';
