<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 01:10:43 +0000
// --------------------------------------------------------------------------------

$l['hello'] = 'Hello World!';
$l['hello_add'] = '추가';
$l['hello_add_message'] = '메시지 추가';
$l['hello_empty'] = '메시지가 없습니다.';
$l['hello_message_empty'] = '메시지는 비워둘 수 없습니다.';
$l['hello_done'] = '새 메시지를 성공적으로 추가했습니다.';
