<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Sat, 29 Jun 2024 05:25:13 +0000
// --------------------------------------------------------------------------------

$l['s1_name'] = '사용자 유지 관리';
$l['s1_desc'] = '포럼 계정을 유지하기 위한 기본 지침입니다.';
$l['s2_name'] = '게시물';
$l['s2_desc'] = '게시, 답변 및 포럼의 기본 사용법입니다.';
