<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Mon, 01 Jul 2024 05:24:07 +0000
// --------------------------------------------------------------------------------

$l['d1_name'] = '사용자 등록';
$l['d1_desc'] = '사용자 등록에 대한 특전 및 특권.';
$l['d1_document'] = '이 포럼의 일부에서는 로그인 및 등록이 필요할 수 있습니다. 등록은 무료이며 완료하는 데 몇 분 정도 걸립니다.
<br /><br />등록을 권장합니다. 일단 등록하시면 메시지를 게시하고, 자신만의 기본 설정을 지정하고, 프로필을 유지할 수 있습니다.
<br /><br />일반적으로 등록이 필요한 기능으로는 구독, 스타일 변경, 개인 메모장 액세스, 포럼 회원에게 이메일 보내기 등이 있습니다.';
$l['d2_name'] = '프로필 업데이트 중';
$l['d2_desc'] = '현재 기록에 있는 데이터를 변경합니다.';
$l['d2_document'] = '머무는 동안 어느 시점에서는 인스턴트 메신저 정보, 비밀번호, 이메일 주소 등 일부 정보를 업데이트해야 한다고 결정할 수도 있습니다.<br /><br /> 사용자 제어판에서 이 정보를 변경할 수 있습니다. <br /><br />이 제어판에 액세스하려면 대부분의 페이지 왼쪽 상단에 있는 "사용자 CP"라는 제목의 링크를 클릭하기만 하면 됩니다. <br /><br />거기에서 "내 프로필" 섹션 아래에 있는 해당 링크를 선택하고 원하는 항목을 변경하거나 업데이트한 다음 페이지 하단에 있는 제출 버튼을 클릭하면 변경 사항이 적용됩니다.';
$l['d3_name'] = 'MyBB에서의 쿠키 사용';
$l['d3_desc'] = 'MyBB는 쿠키를 사용하여 귀하의 등록에 관한 특정 정보를 저장합니다.';
$l['d3_document'] = 'MyBB는 귀하가 등록된 경우 로그인 정보를 저장하고 등록되지 않은 경우 마지막 방문 정보를 저장하기 위해 쿠키를 사용합니다.
<br /><br />쿠키는 귀하의 컴퓨터에 저장되는 작은 텍스트 문서입니다. 이 포럼에서 설정한 쿠키는 이 웹사이트에서만 사용할 수 있으며 보안 위험을 초래하지 않습니다.
<br /><br />이 포럼의 쿠키는 귀하가 읽은 특정 주제와 마지막으로 읽은 시간도 추적합니다.
<br /><br />이 포럼에서 설정한 모든 쿠키를 삭제하려면 <a href="misc.php?action=clearcookies&amp;my_post_key={1}">여기</a>를 클릭하세요.';
$l['d4_name'] = '로그인 및 로그아웃';
$l['d4_desc'] = '로그인 및 로그아웃 방법.';
$l['d4_document'] = '로그인할 때 매번 사용자 이름과 비밀번호를 입력하지 않고도 포럼을 탐색할 수 있도록 컴퓨터에 쿠키를 설정합니다. 로그아웃하면 다른 누구도 귀하처럼 포럼을 탐색할 수 없도록 해당 쿠키가 지워집니다.
<br /><br />로그인하려면 포럼 오른쪽 상단에 있는 로그인 링크를 클릭하세요. 로그아웃하려면 같은 위치에서 로그아웃 링크를 클릭하세요. 로그아웃할 수 없는 경우 컴퓨터에서 쿠키를 삭제해도 동일한 효과가 나타납니다.';
$l['d5_name'] = '새 글타래 게시';
$l['d5_desc'] = '포럼에서 새 글타래를 시작합니다.';
$l['d5_document'] = '관심 있는 포럼에 가서 새 글타래(또는 주제)를 만들고 싶을 때 포럼 상단과 하단에 있는 "새 글타래"라는 제목의 버튼을 선택하기만 하면 됩니다. 관리자가 해당 포럼에 게시하는 것을 직원에게 제한했거나 포럼 전체를 보관했을 수 있으므로 모든 포럼에 새 글타래를 게시할 권한이 없을 수도 있다는 점에 유의하세요.';
$l['d6_name'] = '답글 게시';
$l['d6_desc'] = '포럼 내의 주제에 응답합니다.';
$l['d6_document'] = '방문하는 동안 답변하고 싶은 글타래를 발견할 수 있습니다. 그렇게 하려면 글타래 하단이나 상단에 있는 "새 답장" 버튼을 클릭하세요. 관리자가 특정 포럼에서 특정 개인에게 게시를 제한했을 수도 있다는 점에 유의하세요.
<br /><br />게다가 포럼 운영자가 글타래를 닫아서 사용자가 응답할 수 없게 했을 수도 있습니다. 운영자나 관리자의 도움 없이는 사용자가 이러한 글타래를 열 수 있는 방법이 없습니다.';
$l['d7_name'] = 'MyCode';
$l['d7_desc'] = 'MyCode를 사용하여 게시물을 개선하는 방법을 알아보세요.';
$l['d7_document'] = 'BB 코드라고도 알려진 MyCode를 사용하여 게시물에 효과나 서식을 추가할 수 있습니다. MyCodes는 HTML의 단순화된 버전이며 이미 익숙할 수 있는 HTML 태그와 유사한 형식으로 사용됩니다.
<br /><br />아래 표는 사용 가능한 MyCode에 대한 빠른 안내입니다.
<br /><br />
<table class="tborder" cellpacing="0" cellpadding="5" border="0" style="width:90%">
<몸>
<tr>
<td class="tcat" style="width:55%"><span class="smalltext"><strong>입력</strong></span></td>
<td class="tcat" style="width:35%"><span class="smalltext"><strong>출력</strong></span></td>
<td class="tcat" style="width:10%"><span class="smalltext"><strong>참고</strong></span></td>
</tr>
<tr>
<td class="trow1"><span style="font-weight:bold; color: #ff0000;">[b]</span>이 텍스트는 굵게 표시됩니다<span style="font-weight:bold; color: #ff0000;">[/b]</span></td>
<td class="trow1"><span style="font-weight: 굵은 글씨;" class="mycode_b">이 텍스트는 굵은 글씨입니다</span></td>
<td class="trow1"></td>
</tr>
<tr>
<td class="trow2"><span style="font-weight:bold; color: #ff0000;">[i]</span>이 텍스트는 기울임꼴로 표시됩니다<span style="font-weight:bold; color: #ff0000;">[/i]</span></td>
<td class="trow2"><span style="font-style: italic;" class="mycode_i">이 텍스트는 이탤릭체로 표시됩니다</span></td>
<td class="trow2"></td>
</tr>
<tr>
<td class="trow1"><span style="font-weight:bold; color: #ff0000;">[u]</span>이 텍스트에는 밑줄이 그어져 있습니다<span style="font-weight:bold; color: #ff0000;">[/u]</span></td>
<td class="trow1"><span style="텍스트 장식: 밑줄;" class="mycode_u">이 텍스트에는 밑줄이 그어져 있습니다</span></td>
<td class="trow1"></td>
</tr>
<tr>
<td class="trow2"><span style="font-weight:bold; color: #ff0000;">[s]</span>이 텍스트는 취소되었습니다<span style="font-weight:bold; color : #ff0000;">[/s]</span></td>
<td class="trow2"><span style="텍스트 장식: 라인 통과;" class="mycode_s">이 텍스트는 취소되었습니다</span></td>
<td class="trow2"></td>
</tr>
<tr>
<td class="trow1"><span style="font-weight:bold; 색상: #ff0000;">[url]</span>http://www.example.com/<span style="font- 무게: 굵게; 색상: #ff0000;">[/url]</span></td>
<td class="trow1"><a href="http://www.example.com/" class="mycode_url" rel="nofollow">http://www.example.com/</a>< /td>
<td class="trow1">적절한 프로토콜이 포함된 경우 URL이 자동으로 연결됩니다(유효한 프로토콜은 http, https, ftp, news, irc, ircs 및 irc6입니다).</td>
</tr>
<tr>
<td class="trow2"><span style="font-weight:bold; color: #ff0000;">[url=http://www.example.com/]</span>Example.com<span 스타일 ="font-weight: 굵게; 색상: #ff0000;">[/url]</span></td>
<td class="trow2"><a href="http://www.example.com/" class="mycode_url" rel="nofollow">Example.com</a></td>
<td class="trow2"></td>
</tr>
<tr>
<td class="trow1"><span style="font-weight: 굵은; 색상: #ff0000;">[이메일]</span>example@example.com<span style="font-weight: 굵은; 색상 : #ff0000;">[/이메일]</span></td>
<td class="trow1"><a href="mailto:example@example.com" class="mycode_email">example@example.com</a></td>
<td class="trow1"></td>
</tr>
<tr>
<td class="trow2"><span style="font-weight:bold; color: #ff0000;">[email=example@example.com]</span>저에게 이메일을 보내주세요!<span style="font -중량: 굵게; 색상: #ff0000;">[/email]</span></td>
<td class="trow2"><a href="mailto:example@example.com" class="mycode_email">이메일을 보내주세요.</a></td>
<td class="trow2">이메일 주소 뒤에 <strong>?subject=여기에 제목</strong>을 추가하면 제목을 포함할 수 있습니다.</td>
</tr>
<tr>
<td class="trow1"><span style="font-weight:bold; color: #ff0000;">[quote]</span>인용된 텍스트가 여기에 표시됩니다<span style="font-weight:bold; color : #ff0000;">[/quote]</span></td>
<td class="trow1"><blockquote class="mycode_quote"><cite>인용:</cite>인용된 텍스트가 여기에 있습니다</blockquote></td>
<td class="trow1"></td>
</tr>
<tr>
<td class="trow2"><span style="font-weight:bold; color: #ff0000;">[quote=\'Admin\' pid=\'1\' dateline=\'946684800\']</span>인용된 텍스트는 여기 계세요<span style="font-weight:bold; color: #ff0000;">[/quote]</span></td>
<td class="trow2"><blockquote class="mycode_quote"><cite><span> (01-01-2000, 12:00 AM)</span>관리자 작성: <a href="http:// www.example.com/showthread.php?pid=1#pid1" class="quick_jump" rel="nofollow"></a></cite>인용된 텍스트가 여기에 표시됩니다.</blockquote></td>
<td class="trow2">이 형식은 게시물을 인용할 때 사용됩니다. 게시물에 대한 <strong>pid</strong> 링크, <strong>dateline</strong>은 <a href="https://www.unixtimestamp.com/">UNIX 타임스탬프</a>입니다.</td >
</tr>
<tr>
<td class="trow1"><span style="font-weight:bold; color: #ff0000;">[code]</span>서식이 보존된 텍스트<span style="font-weight:bold; color: #ff0000;">[/코드]</span></td>
<td class="trow1"><div class="codeblock"><div class="title">코드:</div><div class="body" dir="ltr"><code>서식이 보존된 텍스트 </code></div></div></td>
<td class="trow1"></td>
</tr>
<tr>
<td class="trow2"><span style="font-weight:bold; color: #ff0000;">[php]</span>&lt;?php echo "Hello world!";?&gt;<span 스타일 ="font-weight: 굵게; 색상: #ff0000;">[/php]</span></td>
<td class="trow2"><div class="codeblock phpcodeb';
