<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 00:05:40 +0000
// --------------------------------------------------------------------------------

$l['boardstats'] = '통계 보드';
$l['new_posts'] = '포럼에 새 게시물이 포함되어 있습니다.';
$l['no_new_posts'] = '포럼에 새 게시물이 없습니다.';
$l['forum_closed'] = '포럼이 폐쇄되었습니다';
$l['forum_unapproved_posts_count'] = '현재 이 포럼에는 승인되지 않은 게시물이 {1}개 있습니다.';
$l['forum_unapproved_post_count'] = '현재 이 포럼에는 승인되지 않은 게시물이 1개 있습니다.';
$l['forum_unapproved_threads_count'] = '현재 이 포럼에는 승인되지 않은 글타래가 {1}개 있습니다.';
$l['forum_unapproved_thread_count'] = '현재 이 포럼에는 승인되지 않은 글타래가 1개 있습니다.';
$l['forumstats'] = '포럼 통계';
$l['todays_birthdays'] = '오늘의 생일';
$l['birthdayhidden'] = '숨긴 생일';
$l['quick_login'] = '빠른 로그인:';
$l['index_logout'] = '로그 아웃';
$l['private_messages'] = '비공개 메시지';
$l['pms_new'] = '마지막 방문 이후 {1}개의 새 메시지가 있습니다.';
$l['pms_unread_total'] = '(모든 폴더에 읽지 않은 메시지가 {1}개 있고 총 메시지가 {2}개 있습니다.)';
$l['stats_posts_threads'] = '우리 회원들은 {2}개의 글타래에 총 {1}개의 게시물을 작성했습니다.';
$l['stats_numusers'] = '현재 {1}명의 회원이 등록되어 있습니다.';
$l['stats_newestuser'] = '새로운 회원인 <b>{1}</b>을 환영해 주세요.';
$l['stats_mostonline'] = '한때 가장 많은 온라인 사용자는 {2} {3}에 {1} 명이였습니다.';
$l['whos_online'] = 'Who\'s Online';
$l['complete_list'] = '전체 목록';
$l['online_online_plural'] = '사용자';
$l['online_online_singular'] = '사용자';
$l['online_member_plural'] = '회원';
$l['online_member_singular'] = '회원';
$l['online_anon_plural'] = 'are';
$l['online_anon_singular'] = 'is';
$l['online_guest_plural'] = '손님';
$l['online_guest_singular'] = '손님';
$l['online_note'] = '지난 {3}분 동안 {1} {2}이(가) 활동했습니다({4} {5}, 그 중 {6}는 보이지 않음, {8} {9}).';
$l['subforums'] = '하위 포럼:';
$l['board_stats_link_separator'] = ' | ';
