<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Sat, 29 Jun 2024 02:09:47 +0000
// --------------------------------------------------------------------------------

$l['error_no_connection'] = '서버를 통해 연결을 설정하는 중 오류가 발생했습니다.';
$l['error_no_message'] = '지정된 메시지가 없습니다.';
$l['error_no_subject'] = '지정된 제목이 없었습니다.';
$l['error_no_recipient'] = '지정된 수신자가 없습니다.';
$l['error_not_sent'] = 'PHP 메일 기능을 통해 메일을 보내려던 중 오류가 발생했습니다.';
$l['error_status_missmatch'] = '서버의 상태가 예상 결과와 일치하지 않아 다음을 반환합니다.';
$l['error_data_not_sent'] = '이 데이터를 서버로 보낼 수 없습니다:';
$l['error_occurred'] = '하나 이상의 오류가 발생했습니다. 계속하기 전에 다음 오류를 수정하세요.<br />';
