<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 00:06:33 +0000
// --------------------------------------------------------------------------------

$l['nav_group_management'] = '{1} 그룹 관리';
$l['nav_join_requests'] = '가입 요청';
$l['nav_group_memberships'] = '그룹 멤버십';
$l['not_leader_of_this_group'] = '죄송합니다. 귀하는 이 사용자 그룹의 리더가 아닙니다.';
$l['invalid_group'] = '이 사용자 그룹이 존재하지 않습니다.';
$l['pending_requests'] = '대기 중인 가입 요청';
$l['num_requests_pending'] = '현재 이 사용자 그룹에 대해 <strong>{1}</strong> 대기 중인 가입 요청이 있습니다.';
$l['group_management'] = '그룹 관리';
$l['members_of'] = '"{1}"의 구성원';
$l['user_name'] = '사용자 이름';
$l['contact'] = '연락처';
$l['reg_date'] = '가입일자';
$l['post_count'] = '게시물수';
$l['remove_selected'] = '그룹에서 선택한 사용자 제거';
$l['add_member'] = '"{1}"에 구성원 추가';
$l['add_member_submit'] = '그룹에 구성원 추가';
$l['invite_member'] = '"{1}"에 회원 초대';
$l['invite_member_submit'] = '그룹에 회원 초대';
$l['join_requests'] = '가입 요청';
$l['join_requests_title'] = '"{1}"에 대한 가입 요청';
$l['leader'] = '(리더)';
$l['reason'] = '이유';
$l['accept'] = '접수';
$l['ignore'] = '무시';
$l['decline'] = '거절';
$l['action_requests'] = '작업 수행';
$l['join_requests_moderated'] = '가입 요청이 검토되었습니다.<br />이제 요청 목록으로 이동됩니다.';
$l['no_requests'] = '현재 이 그룹에 대해 보류 중인 가입 요청이 없습니다.';
$l['no_users'] = '이 그룹에는 사용자가 없습니다.';
$l['user_added'] = '사용자가 사용자 그룹에 추가되었습니다.';
$l['users_removed'] = '선택한 사용자가 사용자 그룹에서 제거되었습니다.';
$l['group_no_members'] = '현재 이 그룹에는 회원이 없습니다.<br />그룹 관리 페이지로 돌아가려면 <a href="usercp.php?action=usergroups">여기</a>를 클릭하세요.';
$l['group_public_moderated'] = '본 사용자 그룹은 누구나 가입할 수 있는 공개 사용자 그룹입니다. 모든 가입 요청은 그룹 리더가 중재해야 합니다.';
$l['group_public_not_moderated'] = '본 사용자 그룹은 누구나 자유롭게 가입할 수 있는 공개 사용자 그룹입니다.';
$l['group_public_invite'] = '본 사용자 그룹은 가입하기 위해 그룹 리더의 초대가 필요한 공개 사용자 그룹입니다.';
$l['group_private'] = '이 사용자 그룹은 비공개 사용자 그룹입니다. 그룹 리더가 추가한 사용자만 이 그룹에 속할 수 있습니다.';
$l['group_default'] = '이 사용자 그룹은 핵심 사용자 그룹입니다.';
$l['group_leaders'] = '그룹 리더';
$l['no_users_selected'] = '죄송합니다. 제거 대상으로 선택된 사용자가 없는 것 같습니다.<br />뒤로 돌아가서 이 그룹에서 제거할 사용자를 선택하세요.';
$l['error_alreadyingroup'] = '지정된 사용자는 이미 사용자 그룹의 일부입니다.';
$l['error_alreadyinvited'] = '지정된 사용자는 이미 초대되었습니다.';
$l['user_invited'] = '사용자가 사용자 그룹에 가입하도록 초대되었습니다.';
$l['invite_pm_subject'] = '"{1}"에 가입하도록 초대되었습니다.';
$l['invite_pm_message'] = '사용자 그룹 "{1}"에 가입하라는 초대를 받았습니다.

가입하려면 [url={2}/usercp.php?action=usergroups]그룹 멤버십[/url] 페이지로 이동하여 \'초대 수락\'을 클릭하세요.

이 초대는 만료되지 않습니다.';
$l['invite_pm_message_expires'] = '사용자 그룹 "{1}"에 가입하라는 초대를 받았습니다.

가입하려면 [url={2}/usercp.php?action=usergroups]그룹 멤버십[/url] 페이지로 이동하여 \'초대 수락\'을 클릭하세요.

이 초대는 지금부터 {3}일 후에 만료됩니다.';
