<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 02:08:53 +0000
// --------------------------------------------------------------------------------

$l['nav_memberlist'] = '회원 목록';
$l['memberlist_disabled'] = '관리자가 구성원 목록 기능을 비활성화했습니다.';
$l['member_list'] = '회원 목록';
$l['avatar'] = '아바타';
$l['username'] = '사용자 이름';
$l['joined'] = '가입됨';
$l['lastvisit'] = '마지막 방문';
$l['posts'] = '게시물 수';
$l['threads'] = '글타래 수';
$l['referrals'] = '추천';
$l['search_members'] = '회원목록 검색';
$l['website'] = '웹사이트';
$l['sort_by'] = '정렬 기준';
$l['contains'] = '포함:';
$l['exactly'] = '일치:';
$l['sort_by_username'] = '정렬 기준: 사용자 이름';
$l['sort_by_regdate'] = '정렬 기준: 등록 날짜';
$l['sort_by_lastvisit'] = '정렬 기준: 마지막 방문';
$l['sort_by_posts'] = '정렬 기준: 게시물 수';
$l['sort_by_threads'] = '정렬 기준: 글타래 수';
$l['sort_by_referrals'] = '정렬 기준: 추천 회원순';
$l['order_asc'] = '오름차순 정렬';
$l['order_desc'] = '내림차순 정렬';
$l['asc'] = '오름차순';
$l['desc'] = '내림차순';
$l['forumteam'] = '포럼 팀 표시';
$l['advanced_search'] = '고급 검색';
$l['nav_memberlist_search'] = '검색';
$l['search_member_list'] = '회원목록 검색';
$l['search_criteria'] = '검색 조건';
$l['begins_with'] = '다음으로 시작';
$l['username_contains'] = '포함';
$l['username_exact'] = '일치';
$l['search_website'] = '웹 사이트 주소';
$l['search_skype'] = 'Skype 주소';
$l['search_google'] = 'Google Hangouts 주소';
$l['search_icq'] = 'ICQ Number';
$l['search_options'] = '검색 옵션';
$l['per_page'] = '페이지당 결과';
$l['search'] = '검색';
$l['error_no_members'] = '<p>입력하신 검색조건에 맞는 회원을 찾을 수 없습니다.</p><p>다른 검색어를 입력하고 다시 시도해 주세요.</p>';
$l['a'] = 'A';
$l['b'] = 'B';
$l['c'] = 'C';
$l['d'] = 'D';
$l['e'] = 'E';
$l['f'] = 'F';
$l['g'] = 'G';
$l['h'] = 'H';
$l['i'] = 'I';
$l['j'] = 'J';
$l['k'] = 'K';
$l['l'] = 'L';
$l['m'] = 'M';
$l['n'] = 'N';
$l['o'] = 'O';
$l['p'] = 'P';
$l['q'] = 'Q';
$l['r'] = 'R';
$l['s'] = 'S';
$l['t'] = 'T';
$l['u'] = 'U';
$l['v'] = 'V';
$l['w'] = 'W';
$l['x'] = 'X';
$l['y'] = 'Y';
$l['z'] = 'Z';
