<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 00:14:29 +0000
// --------------------------------------------------------------------------------

$l['nav_register'] = '등록';
$l['nav_activate'] = '활성화';
$l['nav_resendactivation'] = '활성화 이메일 다시 보내기';
$l['nav_lostpw'] = '분실한 비밀번호 복구';
$l['nav_resetpassword'] = '암호를 재설정';
$l['nav_login'] = '로그인';
$l['nav_emailuser'] = '이메일 사용자';
$l['nav_referrals'] = '{1}이(가) 추천한 사용자';
$l['nav_profile'] = '{1}의 프로필';
$l['referrals'] = '추천인';
$l['referral_date'] = '추천 날짜:';
$l['referrals_no_user_specified'] = '지정된 사용자가 없습니다.';
$l['referrals_invalid_user'] = '잘못된 사용자가 지정되었습니다.';
$l['member_no_referrals'] = '이 사용자에 대한 추천이 없습니다.';
$l['tpp_option'] = '페이지당 {1}개의 글타래 표시';
$l['ppp_option'] = '페이지당 {1}개의 게시물 표시';
$l['account_activation'] = '계정 활성화';
$l['activate_account'] = '계정 활성화';
$l['activation_code'] = '활성화 코드:';
$l['email_user'] = '{1}에게 이메일 보내기';
$l['email_subject'] = '메일 제목';
$l['email_message'] = '이메일 메시지';
$l['send_email'] = '이메일을 발송';
$l['error_hideemail'] = '수신자가 이메일 주소를 숨기기로 선택했기 때문에 이메일을 보낼 수 없습니다.';
$l['error_no_email_subject'] = '이메일 제목을 입력해야 합니다.';
$l['error_no_email_message'] = '이메일에 보낼 메시지를 입력해야 합니다.';
$l['login'] = '로그인';
$l['pw_note'] = '비밀번호는 대소문자를 구분한다는 점에 유의하세요.';
$l['lostpw_note'] = '비밀번호를 잊어 버렸습니까?';
$l['lost_pw'] = '분실된 계정 비밀번호';
$l['lost_pw_form'] = '분실한 비밀번호 복구 양식';
$l['email_address'] = '이메일 주소:';
$l['request_user_pass'] = '로그인 자격 증명 요청';
$l['profile'] = '{1}의 프로필';
$l['registration_date'] = '등록 날짜:';
$l['date_of_birth'] = '생일:';
$l['birthdayhidden'] = '숨김';
$l['birthday'] = '생일:';
$l['local_time'] = '현지 시각:';
$l['local_time_format'] = '{1} at {2}';
$l['users_forum_info'] = '{1}의 포럼 정보';
$l['joined'] = '가입:';
$l['lastvisit'] = '마지막 방문:';
$l['total_posts'] = '총 게시물 수:';
$l['ppd_percent_total'] = '하루에 {1}개의 게시물 | 총 게시물의 {2}%';
$l['total_threads'] = '총 글타래:';
$l['tpd_percent_total'] = '하루에 {1}개의 글타래 | 총 글타래의 {2}퍼센트';
$l['find_posts'] = '모든 게시물 찾기';
$l['find_threads'] = '모든 글타래 찾기';
$l['members_referred'] = '추천 회원:';
$l['rating'] = '평가:';
$l['users_contact_details'] = '{1}의 연락처 세부정보';
$l['homepage'] = '홈페이지:';
$l['pm'] = '비공개 메시지:';
$l['send_pm'] = '{1}에게 비공개 메시지를 보내세요.';
$l['icq_number'] = 'ICQ Number:';
$l['skype_id'] = 'Skype ID:';
$l['google_id'] = 'Google Hangouts ID:';
$l['avatar'] = '아바타:';
$l['warning_level'] = '경고 수준:';
$l['warn'] = '경고';
$l['away_note'] = '{1}은(는) 현재 자리를 비운 상태입니다.';
$l['away_reason'] = '이유:';
$l['away_since'] = '자리 비움 이후:';
$l['away_returns'] = '돌아온 날짜:';
$l['away_no_reason'] = '명시되지 않음';
$l['ban_note'] = '이 포럼 계정은 현재 차단되어 있습니다.';
$l['ban_by'] = '차단된 사람';
$l['ban_length'] = '차단 기간';
$l['ban_remaining'] = '남음';
$l['users_additional_info'] = '{1}에 대한 추가 정보';
$l['email'] = '이메일:';
$l['send_user_email'] = '{1}에게 이메일을 보내기';
$l['users_signature'] = '{1}의 서명';
$l['agreement'] = '등록 약관';
$l['agreement_1'] = '개인의 사생활을 침해하는 것으로 간주될 수 있거나 모든 종류의 법률을 위반하는 부적절하거나 성적 지향적이거나 모욕적이거나 증오심이 많거나 비방적이거나 위협적인 자료가 포함된 메시지를 편집하거나 제거하려고 시도하는 동안에는 검토가 불가능합니다. 이 토론 시스템에 게시된 모든 메시지. 이러한 이유로 귀하는 이 토론 시스템에 게시된 모든 메시지가 원본 메시지 작성자의 견해와 의견을 표현하며 반드시 이 게시판의 견해를 표현하는 것은 아니라는 점을 인정합니다. 따라서 우리는 게시된 메시지에 대해 책임을 지지 않으며 의무를 지지 않습니다. 우리는 모든 메시지의 정확성과 완전성을 보증하거나 보증하지 않습니다.';
$l['agreement_2'] = '이 토론 시스템에 등록함으로써 귀하는 고의로 허위, 부정확, 모욕, 증오, 희롱, 성적 지향, 위협 또는 개인의 사생활 침해가 있는 자료 또는 관련 법률을 위반할 수 있는 기타 자료를 게시하지 않을 것에 동의합니다.';
$l['agreement_3'] = '이러한 규칙을 준수하지 않으면 귀하의 계정이 해지되거나 계정이 정지되거나 해당 포럼에 대한 액세스가 영구적으로 금지될 수 있습니다. 귀하의 IP 주소는 귀하가 이 토론 시스템에 게시하는 각 게시물과 함께 기록되며 필요한 경우 포럼 직원이 검색할 수 있습니다. 귀하는 당사가 적절하다고 판단되는 경우 언제든지 계정이나 메시지를 제거, 편집 또는 잠글 수 있는 능력과 권리가 있다는 데 동의합니다. 또한 귀하는 이 토론 시스템에 입력한 모든 정보가 데이터베이스에 저장되며 로그인 정보를 저장하기 위해 "쿠키"가 귀하의 컴퓨터에 저장된다는 데 동의합니다.';
$l['agreement_4'] = '귀하가 이 포럼에 제공하는 모든 정보는 귀하의 완전한 동의 없이 제3자에게 공개되지 않습니다. 단, 직원은 귀하의 데이터가 손상되는 해킹 시도에 대해 책임을 지지 않습니다.';
$l['agreement_5'] = '등록 프로세스를 계속하면 위의 규칙과 관리자가 지정한 기타 사항에 동의하게 됩니다.';
$l['registration'] = '등록';
$l['required_fields'] = '필수 입력 사항';
$l['complex_password'] = '<abbr title="대문자, 소문자 및 숫자를 포함하는 최소 {1}자 길이의 비밀번호입니다.">복잡한</abbr> 비밀번호:';
$l['confirm_email'] = '이메일 확인:';
$l['optional_fields'] = '선택 필드';
$l['website_url'] = '웹사이트 URL:';
$l['birthdate'] = '생일:';
$l['additional_info'] = '추가 정보';
$l['required_info'] = '필수 정보';
$l['i_agree'] = '동의함';
$l['account_details'] = '계정 세부정보';
$l['account_prefs'] = '계정 환경설정:';
$l['invisible_mode'] = 'Who\'s Online 목록에서 나를 숨김';
$l['allow_notices'] = '관리자로부터 이메일을 받기';
$l['hide_email'] = '다른 회원들에게 이메일을 숨김';
$l['email_notify'] = '내가 게시한 글타래를 자동으로 구독하기';
$l['receive_pms'] = '다른 사용자로부터 비공개 메시지를 받기';
$l['pm_notice'] = '비공개 메시지를 받으면 알림으로 알려주세요.';
$l['email_notify_newpm'] = '새 비공개 메시지를 받으면 이메일로 알려주세요.';
$l['time_offset'] = 'Time Zone (<abbr title="Daylight Saving Time">DST</abbr> correction excluded):';
$l['time_offset_desc'] = '이 보드가 설정된 시간대와 다른 시간대에 거주하는 경우 아래 목록에서 선택할 수 있습니다.';
$l['dst_correction'] = '일광 절약 시간 수정:';
$l['dst_correction_auto'] = 'DST 설정 자동 감지';
$l['dst_correction_enabled'] = '항상 DST 보정을 사용하십시오.';
$l['dst_correction_disabled'] = 'DST 보정을 사용하지 마십시오.';
$l['redirect_registered_coppa_activate'] = '{1}, {2}에 등록해 주셔서 감사합니다. 귀하의 계정은 성공적으로 생성되었습니다. 그러나 이 계정의 소유자는 13세 미만이므로 이 계정을 사용하려면 먼저 부모의 허락을 받아야 합니다.<br /><br />부모 또는 법적 보호자가 필요합니다. <a href="member.php?action=coppa_form">COPPA 규정 준수 및amp; 허가 양식</a>.<br /><br />이 양식의 완전한 사본을 받으면 계정이 활성화됩니다.';
$l['coppa_compliance'] = 'COPPA 준수';
$l['coppa_desc'] = '이러한 포럼에 등록하려면 <a href="https://www.ftc.gov/enforcement/rules/rulemaking-regulatory-reform-proceedings/childrens-online-privacy"를 준수하기 위해 연령을 확인해야 합니다. -protection-rule" title="아동 온라인 개인정보 보호법" target="_blank" rel="noopener">COPPA</a>. 아래에 생년월일을 입력해 주세요.<br /><br />만 13세 미만인 경우 등록 전 반드시 부모님의 동의를 얻어야 합니다. 부모 또는 법적 보호자는 <a href="member.php?action=coppa_form" target="_blank" rel="noopener">COPPA 규정 준수 및amp; 허가서 양식</a>.';
$l['coppa_desc_for_deny'] = '이러한 포럼에 등록하려면 <a href="https://www.ftc.gov/enforcement/rules/rulemaking-regulatory-reform-proceedings/childrens-online-privacy"를 준수하기 위해 연령을 확인해야 합니다. -protection-rule" title="아동 온라인 개인정보 보호법" target="_blank" rel="noopener">COPPA</a>. 아래에 생년월일을 입력해주세요.';
$l['hide_dob'] = '등록 후 프로필을 편집하여 생년월일과 나이를 숨길 수 있습니다.';
$l['signature'] = '서명:';
$l['continue_registration'] = '등록을 계속 하기';
$l['birthdayprivacy'] = '생년월일 개인 정보 보호:';
$l['birthdayprivacyall'] = '나이와 생년월일 표시';
$l['birthdayprivacynone'] = '나이와 생년월일 숨기기';
$l['birthdayprivacyage'] = '나이만 표시';
$l['leave_this_field_empty'] = '이 필드를 비워 두세요.';
$l['error_need_to_be_thirteen'] = '이 포럼에 등록하려면 13세 이상이어야 합니다.';
$l['coppa_registration'] = 'COPPA 등록 양식';
$l['coppa_form_instructions'] = '이 양식을 인쇄하여 작성한 후 아래 번호로 팩스를 보내거나 제공된 우편 주소로 우편을 보내주십시오.';
$l['fax_number'] = '팩스번호:';
$l['mailing_address'] = '메일링 주소:';
$l['account_information'] = '계정 정보';
$l['parent_details'] = '부모/보호자 세부정보';
$l['full_name'] = '전체 이름:';
$l['relation'] = '관계:';
$l['phone_no'] = '핸드폰 #:';
$l['coppa_parent_agreement'] = '나는 내가 제공한 정보가 사실이며 제공된 비밀번호를 입력하면 모든 정보가 향후 변경될 수 있으며 요청에 따라 이 사용자 계정이 제거될 수 있음을 이해합니다.';
$l['coppa_agreement_1'] = '13세 미만의 사용자가 {1}에 등록하려면 부모 또는 법적 보호자의 허가를 받아야 합니다.';
$l['coppa_agreement_2'] = '부모 또는 법적 보호자는 <a href="member.php?action=coppa_form" target="_blank" rel="noopener">COPPA 규정 준수 및amp; 회원 자격이 부여되기 전의 허가서</a>입니다.';
$l['coppa_agreement_3'] = '원하시면 지금 등록 절차를 시작하실 수 있습니다. 하지만 위의 규정 준수 양식이 접수될 때까지는 계정에 액세스하실 수 없습니다.';
$l['error_invalid_birthday'] = '입력한 생일이 잘못되었습니다. 유효한 생일을 입력하세요.';
$l['error_awaitingcoppa'] = '이 계정은 아직 부모 또는 보호자의 COPPA 확인을 기다리고 있으므로 이 계정을 사용하여 로그인할 수 없습니다.<br /><br />부모 또는 법적 보호자는 <a href="member.php?action=coppa_form">COPPA 준수 및amp; 허가 양식</a>.<br /><br />이 양식의 완전한 사본을 받으면 계정이 활성화됩니다.';
$l['lang_select'] = '언어 설정:';
$l['lang_select_desc'] = '포럼 기본 언어가 아닌 다른 언어를 사용하는 국가에 거주하는 경우 아래에서 설치되어 읽을 수 있는 언어 팩을 선택할 수 있습니다.';
$l['lang_select_default'] = '기본값 사용';
$l['submit_registration'] = '등록을 제출하기!';
$l['confirm_password'] = '비밀번호 확인:';
$l['referrer'] = '추천인:';
$l['referrer_desc'] = '다른 회원이 추천한 경우 아래에 해당 회원의 사용자 이름을 입력할 수 있습니다. 그렇지 않은 경우 이 필드를 비워 두십시오.';
$l['resend_activation'] = '계정 활성화 재전송';
$l['request_activation'] = '활성화 코드 요청';
$l['ppp'] = '페이지당 게시물 수:';
$l['ppp_desc'] = '글타래의 페이지당 표시할 게시물 수를 선택할 수 있습니다.';
$l['tpp'] = '페이지당 글타래 수:';
$l['tpp_desc'] = '글타래 목록의 페이지당 표시할 글타래 수를 선택할 수 있습니다.';
$l['reset_password'] = '암호 재설정';
$l['send_password'] = '새 비밀번호를 보내기!';
$l['registration_errors'] = '등록 시 다음 오류가 발생했습니다.';
$l['timeonline'] = '온라인에서 보낸 시간:';
$l['timeonline_hidden'] = '(숨김)';
$l['registrations_disabled'] = '죄송합니다. 관리자가 새 계정 등록을 비활성화했기 때문에 지금은 등록할 수 없습니다.';
$l['error_username_length'] = '귀하의 사용자 이름이 유효하지 않습니다. 사용자 이름은 {1}~{2}자 이내여야 합니다.';
$l['error_stop_forum_spam_spammer'] = '죄송합니다. 귀하의 {1}이(가) 알려진 스패머의 이름과 일치합니다. 이것이 실수라고 생각되면 관리자에게 문의하십시오.';
$l['error_stop_forum_spam_fetching'] = '죄송합니다. 스팸 발송자 데이터베이스와 비교하여 귀하의 계정을 확인하는 중에 문제가 발생했습니다. 데이터베이스에 액세스하지 못했을 가능성이 높습니다. 나중에 다시 시도 해주십시오.';
$l['none_registered'] = '등록된 항목 없음';
$l['not_specified'] = '명시되지 않았음';
$l['membdayage'] = '({1}세)';
$l['mod_options'] = '운영자 옵션';
$l['edit_in_mcp'] = 'Mod CP에서 이 사용자 편집';
$l['ban_in_mcp'] = 'Mod CP에서 이 사용자를 금지';
$l['edit_ban_in_mcp'] = 'Mod CP의 금지 편집';
$l['lift_ban_in_mcp'] = 'Mod CP의 금지 해제';
$l['purgespammer'] = '스팸 발송자 제거';
$l['edit_usernotes'] = 'Mod CP에서 사용자 메모 편집';
$l['no_usernotes'] = '현재 이 사용자에 대한 메모가 없습니다.';
$l['view_all_notes'] = '모든 노트 보기';
$l['view_notes_for'] = '{1}에 대한 메모 보기';
$l['registration_ip'] = '등록 IP:';
$l['last_known_ip'] = '마지막 접속 IP:';
$l['reputation'] = '평판:';
$l['reputation_vote'] = '비율';
$l['reputation_details'] = '세부사항';
$l['already_logged_in'] = '주의 사항: 귀하는 현재 이미 {1}(으)로 로그인되어 있습니다.';
$l['admin_edit_in_acp'] = 'Admin CP에서 이 사용자 편집';
$l['admin_ban_in_acp'] = 'Admin CP에서 이 사용자를 금지';
$l['admin_lift_ban_in_acp'] = 'Admin CP에서 금지 해제';
$l['admin_edit_ban_in_acp'] = 'Admin CP에서 차단 수정';
$l['admin_options'] = '관리자 옵션';
$l['redirect_registered_activation'] = '{1}, {2}에 등록해 주셔서 감사합니다.<p>등록을 완료하려면 이메일에서 계정 활성화 지침을 확인하세요. 계정이 활성화될 때까지 게시하지 못할 수도 있습니다.';
$l['redirect_emailupdated'] = '귀하의 이메일이 성공적으로 변경되었습니다.<br />이제 포럼 색인으로 돌아가게 됩니다.';
$l['redirect_accountactivated'] = '귀하의 계정이 성공적으로 활성화되었습니다.<br />이제 포럼 색인으로 돌아가게 됩니다.';
$l['redirect_accountactivated_admin'] = '귀하의 이메일이 성공적으로 확인되었습니다.<br />귀하의 등록은 관리자의 승인을 받아야 합니다. 그때까지는 이 포럼에 글을 게시하지 못할 수도 있습니다.<br />이제 포럼 색인으로 돌아가게 됩니다.';
$l['redirect_registered'] = '{1}, {2}에 등록해 주셔서 감사합니다.<br />이제 포럼 색인으로 돌아갑니다.';
$l['redirect_registered_admin_activate'] = '{1}, {2}에 등록해 주셔서 감사합니다.<br />등록은 관리자의 승인을 받아야 합니다. 그때까지는 이 포럼에 글을 게시하지 못할 수도 있습니다.';
$l['redirect_loggedout'] = '성공적으로 로그아웃되었습니다.<br />이제 포럼 색인으로 돌아가게 됩니다.';
$l['redirect_alreadyloggedout'] = '이미 로그아웃했거나 아직 로그인하지 않았습니다.<br />이제 포럼 색인으로 돌아갑니다.';
$l['redirect_lostpwsent'] = '감사합니다. 이제 해당 이메일 주소와 관련된 모든 계정에 비밀번호 재설정 방법에 대한 세부정보가 포함된 이메일이 전송되었습니다.<br /><br />이제 포럼 색인으로 이동하게 됩니다.';
$l['redirect_activationresent'] = '귀하의 활성화 이메일이 제공된 이메일 주소로 다시 전송되었습니다.';
$l['redirect_passwordreset'] = '감사합니다. 귀하의 계정 비밀번호가 재설정되었습니다. 무작위로 생성된 새로운 비밀번호가 귀하의 계정과 연결된 이메일 주소로 전송되었습니다.';
$l['redirect_memberrated'] = '회원이 성공적으로 평가되었습니다.';
$l['redirect_registered_passwordsent'] = '무작위 비밀번호가 생성되어 귀하의 이메일 주소로 전송되었습니다. 로그인하기 전에 이메일에서 이 비밀번호를 확인해야 합니다.';
$l['redirect_validated'] = '감사합니다. 귀하의 계정이 확인되었습니다.<br />이제 포럼 색인으로 이동하게 됩니다.';
$l['error_activated_by_admin'] = '모든 등록은 관리자의 승인을 받아야 하므로 계정 활성화 이메일을 다시 보낼 수 없습니다.';
$l['error_alreadyregistered'] = '죄송합니다. 시스템에 귀하는 이미 등록되어 있으며 여러 계정 등록이 비활성화된 것으로 표시됩니다.';
$l['error_alreadyregisteredtime'] = '지난 {2}시간 동안 귀하의 IP 주소에서 이미 {1}개의 신규 등록이 있었기 때문에 귀하의 등록을 처리할 수 없습니다. 나중에 다시 시도 해주십시오.';
$l['error_badlostpwcode'] = '잘못된 비밀번호 재설정 코드를 입력하셨습니다. 전송된 이메일을 다시 읽어보시거나 포럼 관리자에게 문의하여 추가 도움을 받으시기 바랍니다.';
$l['error_badactivationcode'] = '잘못된 계정 활성화 코드를 입력했습니다. 모든 활성화 이메일을 등록된 이메일 주소로 다시 보내려면 <a href="member.php?action=resendactivation">여기</a>를 클릭하세요.';
$l['error_alreadyactivated'] = '귀하의 계정은 이미 활성화되었거나 이메일 확인이 필요하지 않습니다.';
$l['error_alreadyvalidated'] = '귀하의 이메일은 이미 확인되었습니다.';
$l['error_nothreadurl'] = '귀하의 메시지에는 글타래의 URL이 포함되어 있지 않습니다. 해당 목적에 맞게 "친구에게 보내기" 기능을 사용해 보세요.';
$l['error_bannedusername'] = '등록이 금지된 사용자 이름을 입력하셨습니다. 다른 사용자 이름을 선택하세요.';
$l['error_notloggedout'] = '로그아웃을 진행하기 위한 사용자 ID를 확인할 수 없습니다. 이는 자동으로 로그아웃을 시도하는 악성 Javascript 때문일 수 있습니다. 로그아웃을 원하시면 상단 메뉴의 로그아웃 버튼을 눌러주세요.';
$l['error_regimageinvalid'] = '입력한 이미지 인증 코드가 올바르지 않습니다. 이미지에 표시된 대로 코드를 정확하게 입력하세요.';
$l['error_regimagerequired'] = '로그인 프로세스를 계속하려면 이미지 인증 코드를 입력하세요. 이미지에 표시된 대로 코드를 정확하게 입력하세요.';
$l['error_spam_deny'] = '당사 시스템에서는 귀하가 스팸 발송자일 수 있음을 감지하여 등록이 거부되었습니다. 실수인 경우 관리자에게 문의하시기 바랍니다.';
$l['error_spam_deny_time'] = '당사 시스템에서는 귀하가 스팸 발송자일 수 있음을 감지하여 등록이 거부되었습니다. 자동 가입을 방지하려면 등록에 최소 {1}초가 소요됩니다. {2}초 안에 등록하셨습니다. 실수인 경우 관리자에게 문의하시기 바랍니다.';
$l['js_validator_no_username'] = '사용자 이름을 입력해야 합니다.';
$l['js_validator_invalid_email'] = '유효한 이메일 주소를 입력해야 합니다.';
$l['js_validator_email_match'] = '동일한 이메일 주소를 다시 입력해야 합니다.';
$l['js_validator_no_image_text'] = '위 이미지의 텍스트를 입력해야 합니다.';
$l['js_validator_no_security_question'] = '보안 질문에 대한 답변을 입력해야 합니다.';
$l['js_validator_password_matches'] = '입력한 비밀번호는 일치해야 합니다.';
$l['js_validator_password_length'] = '비밀번호는 {1}자 이상이어야 합니다.';
$l['js_validator_bad_password_security'] = '입력한 비밀번호는 사용자 이름 또는 이메일 주소와 유사합니다. 더 강력한 비밀번호를 입력하세요.';
$l['js_validator_not_empty'] = '이 필드에 대한 값을 선택하거나 입력해야 합니다.';
$l['js_validator_username_length'] = '사용자 이름은 {1}자에서 {2}자 사이여야 합니다.';
$l['security_question'] = '보안 질문';
$l['question_note'] = '제공된 질문에 답해 주세요. 이 프로세스는 자동화된 프로세스를 방지하는 데 사용됩니다.';
$l['error_question_wrong'] = '보안 질문에 제공한 답변이 잘못되었습니다. 다시 시도해 주세요.';
$l['subscription_method'] = '기본 글타래 구독 모드:';
$l['no_auto_subscribe'] = '구독하지 않기';
$l['no_subscribe'] = '알림 없음';
$l['instant_email_subscribe'] = '즉시 이메일 알림';
$l['instant_pm_subscribe'] = '즉시 PM 알림';
$l['remove_from_buddy_list'] = '친구 목록에서 제거';
$l['add_to_buddy_list'] = '친구 목록에 추가';
$l['remove_from_ignore_list'] = '무시 목록에서 제거';
$l['add_to_ignore_list'] = '무시 목록에 추가';
$l['report_user'] = '사용자 신고';
$l['newregistration_subject'] = '{1}에 신규 등록';
$l['newregistration_message'] = '{1},

{2}에 관리자 활성화를 보류 중인 새 사용자가 있습니다.

사용자 이름: {3}

감사합니다,
{2} 직원';
