<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 04:19:45 +0000
// --------------------------------------------------------------------------------

$l['click_no_wait'] = '더 이상 기다리지 않으려면 여기를 클릭하세요.';
$l['redirect_return_forum'] = '<br /><br />또는 <a href="{1}">포럼으로 돌아가세요</a>.';
$l['redirect_emailsent'] = '귀하의 이메일 메시지가 성공적으로 전송되었습니다.';
$l['redirect_loggedin'] = '성공적으로 로그인되었습니다.<br />이제 원래 있던 곳으로 돌아갑니다.';
$l['update_confirm'] = '다음 파일은 이미 첨부되어 있으며 새로 선택한 파일로 업데이트/교체됩니다. {1} 확실합니까?';
$l['error_invalidpworusername'] = '잘못된 사용자 이름/비밀번호 조합을 입력했습니다. <br /><br />비밀번호를 잊어버린 경우 <a href="member.php?action=lostpw">새 비밀번호를 검색</a>을 하시기 바랍니다.';
$l['error_invalidpworusername1'] = '잘못된 이메일/비밀번호 조합을 입력하셨습니다. <br /><br />비밀번호를 잊어버린 경우 <a href="member.php?action=lostpw">새 비밀번호를 검색</a>을 하시기 바랍니다.';
$l['error_invalidpworusername2'] = '잘못된 사용자 이름/비밀번호 또는 이메일/비밀번호 조합을 입력했습니다. <br /><br />비밀번호를 잊어버린 경우 <a href="member.php?action=lostpw">새 비밀번호를 검색</a>을 하시기 바랍니다.';
$l['error_incompletefields'] = '하나 이상의 필수 입력란을 비워두신 것 같습니다. 돌아가서 필수 항목을 입력하세요.';
$l['error_alreadyuploaded'] = '이 게시물에는 이름이 "{1}"인 첨부 파일이 이미 포함되어 있습니다. 파일명을 변경한 후 다시 업로드해주세요. 또는 "첨부 파일 업데이트"를 클릭할 수도 있습니다.';
$l['error_alreadyuploaded_perm'] = '이 게시물에는 이미 같은 이름의 첨부 파일이 포함되어 있습니다. 기존 파일을 제거하거나 파일 이름을 변경한 후 다시 업로드하세요.';
$l['error_updatefailed'] = '"{1}" 파일이 아직 첨부되지 않았으므로 업데이트할 수 없습니다.';
$l['error_nomessage'] = '죄송합니다. 유효한 메시지를 입력하지 않았기 때문에 계속할 수 없습니다. 돌아가서 확인해 해주세요.';
$l['error_invalidemail'] = '유효한 이메일 주소를 입력하지 않았습니다.';
$l['error_nomember'] = '지정한 구성원이 잘못되었거나 존재하지 않습니다.';
$l['error_maxposts'] = '죄송합니다. 일일 게시물 한도를 초과했습니다. 추가 게시를 하려면 내일까지 기다리거나 관리자에게 문의하세요.<br /><br />하루에 작성할 수 있는 최대 게시물 수는 {1}개입니다.';
$l['error_nohostname'] = '입력한 IP에 대한 호스트 이름을 찾을 수 없습니다.';
$l['error_invalidthread'] = '지정된 글타래가 존재하지 않습니다.';
$l['error_invalidpost'] = '지정한 게시물이 존재하지 않습니다.';
$l['error_invalidannouncement'] = '지정한 공지사항이 존재하지 않습니다.';
$l['error_invalidattachment'] = '지정한 첨부 파일이 존재하지 않습니다.';
$l['error_invalidforum'] = '잘못된 포럼';
$l['error_closedinvalidforum'] = '포럼이 폐쇄되었거나, 다른 웹페이지로 리디렉션되거나, 카테고리이기 때문에 이 포럼에 게시할 수 없습니다.';
$l['error_attachtype'] = '첨부한 파일 형식은 허용되지 않습니다. 첨부파일을 제거하거나 다른 유형을 선택하세요.';
$l['error_attachsize'] = '"{1}" 파일이 너무 큽니다. 해당 파일 유형의 최대 크기는 {2}KB입니다.';
$l['error_uploadempty'] = '"{1}" 파일이 비어 있습니다.';
$l['error_uploadsize'] = '업로드한 파일의 크기가 너무 큽니다.';
$l['error_uploadfailed'] = '파일 업로드에 실패했습니다. 유효한 파일을 선택하고 다시 시도하십시오.';
$l['error_uploadfailed_detail'] = '오류 정보:';
$l['error_uploadfailed_php1'] = 'PHP가 반환됨: 업로드된 파일이 php.ini의 upload_max_filesize 지시어를 초과했습니다. 이 오류에 대해서는 포럼 관리자에게 문의하세요.';
$l['error_uploadfailed_php2'] = '업로드된 파일이 지정된 최대 파일 크기를 초과했습니다.';
$l['error_uploadfailed_php3'] = '업로드된 파일이 부분적으로만 업로드되었습니다.';
$l['error_uploadfailed_php4'] = '업로드된 파일이 없습니다.';
$l['error_uploadfailed_php6'] = 'PHP가 반환됨: 임시 폴더가 없습니다. 이 오류에 대해서는 포럼 관리자에게 문의하세요.';
$l['error_uploadfailed_php7'] = 'PHP가 반환됨: 파일을 디스크에 쓰지 못했습니다. 이 오류에 대해서는 포럼 관리자에게 문의하세요.';
$l['error_uploadfailed_phpx'] = 'PHP가 오류 코드를 반환했습니다: {1}. 이 오류에 대해서는 포럼 관리자에게 문의하세요.';
$l['error_uploadfailed_nothingtomove'] = '잘못된 파일을 지정하여 업로드된 파일을 대상 위치로 이동할 수 없습니다.';
$l['error_uploadfailed_movefailed'] = '업로드된 파일을 대상으로 이동하는 중에 문제가 발생했습니다.';
$l['error_uploadfailed_lost'] = '서버에서 첨부 파일을 찾을 수 없습니다.';
$l['error_emailmismatch'] = '입력한 이메일 주소가 일치하지 않습니다. 돌아가서 다시 시도해 주세요.';
$l['error_nopassword'] = '유효한 비밀번호를 입력하지 않았습니다.';
$l['error_usernametaken'] = '선택하신 사용자 이름은 이미 등록되어 있습니다. 이전에 이 포럼에 등록한 경우 <a href="member.php?action=login">로그인</a>하시기 바랍니다.';
$l['error_nousername'] = '사용자 이름을 입력하지 않았습니다.';
$l['error_invalidusername'] = '입력한 사용자 이름이 잘못된 것 같습니다.';
$l['error_invalidpassword'] = '입력한 비밀번호가 올바르지 않습니다. 비밀번호를 잊어버린 경우 <a href="member.php?action=lostpw">여기</a>를 클릭하세요. 그렇지 않으면 돌아가서 다시 시도하세요.';
$l['error_postflooding'] = '죄송합니다. 귀하의 게시물을 처리할 수 없습니다. 관리자가 귀하가 {1}초마다 한 번만 게시할 수 있도록 지정했습니다.';
$l['error_nopermission_guest_1'] = '로그인하지 않았거나 이 페이지를 볼 수 있는 권한이 없습니다. 이는 다음 이유 중 하나 때문일 수 있습니다.';
$l['error_nopermission_guest_2'] = '로그인 또는 등록되지 않았습니다. 로그인하여 원하는 작업을 다시 시도하세요.';
$l['error_nopermission_guest_3'] = '이 페이지에 액세스할 수 있는 권한이 없습니다. 접근해서는 안 되는 관리 페이지나 리소스에 접근하려고 하시나요? 이 작업을 수행하도록 허용된 포럼 규칙을 확인하세요.';
$l['error_nopermission_guest_4'] = '귀하의 계정은 관리자에 의해 비활성화되었거나 계정 활성화를 기다리고 있을 수 있습니다.';
$l['error_nopermission_guest_5'] = '귀하는 적절한 양식이나 링크를 사용하지 않고 이 페이지에 직접 접속했습니다.';
$l['login'] = '로그인';
$l['need_reg'] = '등록이 필요합니까?';
$l['forgot_password'] = '비밀번호를 잊으셨습니까?';
$l['error_nopermission_user_1'] = '이 페이지에 액세스할 수 있는 권한이 없습니다. 이는 다음 이유 중 하나로 인해 발생할 수 있습니다.';
$l['error_nopermission_user_ajax'] = '이 페이지에 액세스할 수 있는 권한이 없습니다.';
$l['error_nopermission_user_2'] = '귀하의 계정은 정지되었거나 이 리소스에 대한 액세스가 금지되었습니다.';
$l['error_nopermission_user_3'] = '이 페이지에 액세스할 수 있는 권한이 없습니다. 접근해서는 안 되는 관리 페이지나 리소스에 접근하려고 하시나요? 이 작업을 수행하도록 허용된 포럼 규칙을 확인하세요.';
$l['error_nopermission_user_4'] = '귀하의 계정은 아직 활성화 또는 조정을 기다리고 있을 수 있습니다.';
$l['error_nopermission_user_5'] = '귀하는 적절한 양식이나 링크를 사용하지 않고 이 페이지에 직접 접속했습니다.';
$l['error_nopermission_user_resendactivation'] = '활성화 코드 재전송';
$l['error_nopermission_user_username'] = '귀하는 현재 사용자 이름 \'{1}\'으로 로그인되어 있습니다.';
$l['logged_in_user'] = '로그인한 사용자';
$l['error_too_many_images'] = '이미지가 너무 많습니다.';
$l['error_too_many_images2'] = '죄송합니다. 이미지가 너무 많아 게시물을 처리할 수 없습니다. 계속하려면 게시물에서 일부 이미지를 제거하세요.';
$l['error_too_many_images3'] = '<b>참고:</b> 게시물당 최대 이미지 수는 다음과 같습니다.';
$l['error_attach_file'] = '파일 첨부 오류';
$l['please_correct_errors'] = '계속하기 전에 다음 오류를 수정하세요.';
$l['error_reachedattachquota'] = '죄송합니다. 첨부 파일 할당량인 {1}에 도달했기 때문에 이 파일을 첨부할 수 없습니다.';
$l['error_maxattachpost'] = '죄송합니다. {1}의 게시물당 허용된 최대 첨부 파일 수에 도달했기 때문에 이 파일을 첨부할 수 없습니다.';
$l['error_invaliduser'] = '지정된 사용자가 잘못되었거나 존재하지 않습니다.';
$l['error_invalidaction'] = '잘못된 작업';
$l['error_messagelength'] = '죄송합니다. 메시지가 너무 길어 게시할 수 없습니다. 메시지를 줄인 후 다시 시도해 주세요.';
$l['error_message_too_short'] = '죄송합니다. 메시지가 너무 짧아 게시할 수 없습니다.';
$l['failed_login_wait'] = '요구되는 시도 횟수 내에 로그인에 실패했습니다. 이제 다시 로그인하려면 {1}시간 {2}분 {3}초를 기다려야 합니다.';
$l['failed_login_again'] = '<br /><strong>{1}</strong>번 더 로그인 시도가 있었습니다.';
$l['error_max_emails_day'] = '지난 24시간 동안 할당된 {1}개의 메시지 전송 할당량을 이미 모두 사용했기 때문에 \'친구에게 스레드 보내기\' 또는 \'사용자에게 이메일 보내기\' 기능을 사용할 수 없습니다.';
$l['attachments_disabled'] = '관리자가 비활성화한 첨부 시스템이므로 사용할 수 없습니다.';
$l['error_attach_filename_length'] = '파일 이름 \'{1}\'이(가) 최대 파일 이름 길이 {2}을(를) 초과합니다. 파일 이름이 더 짧은 파일을 업로드해 주세요.';
$l['emailsubject_lostpw'] = '{1}에서 비밀번호 재설정';
$l['emailsubject_passwordreset'] = '{1}의 새 비밀번호';
$l['emailsubject_subscription'] = '{1}에 대한 새 답글';
$l['emailsubject_randompassword'] = '{1}의 비밀번호';
$l['emailsubject_activateaccount'] = '{1}에서 계정 활성화';
$l['emailsubject_forumsubscription'] = '{1}의 새 글타래';
$l['emailsubject_reportpost'] = '{1}에 신고된 게시물';
$l['emailsubject_reportprofile'] = '{1}의 신고된 사용자';
$l['emailsubject_reportreputation'] = '{1}의 보고된 평판';
$l['emailsubject_reachedpmquota'] = '비공개 메시징 할당량이 {1}에 도달';
$l['emailsubject_changeemail'] = '{1}의 이메일 변경';
$l['emailsubject_newpm'] = '{1} - {2}의 새 비공개 메시지';
$l['emailsubject_newjoinrequest'] = '{1}에 새로운 가입 요청';
$l['emailsubject_sendtofriend'] = '{1}의 흥미로운 토론';
$l['emailsubject_changepassword'] = '{1}의 비밀번호 변경';
$l['emailbit_viewthread'] = '... (자세한 내용을 보려면 글타래를 방문...)';
$l['email_lostpw'] = '{1},

{2}에서 계정 비밀번호 재설정 단계를 완료하려면 웹 브라우저에서 아래 URL로 이동해야 합니다.

{3}/member.php?action=resetpassword&uid={4}&code={5}

위 링크가 제대로 작동하지 않으면 다음으로 이동하세요.

{3}/member.php?action=resetpassword

다음을 입력해야 합니다.
사용자 이름: {1}
활성화 코드: {5}

감사합니다,
{2} 직원';
$l['email_lostpw1'] = '{1},

{2}에서 계정 비밀번호 재설정 단계를 완료하려면 웹 브라우저에서 아래 URL로 이동해야 합니다.

{3}/member.php?action=resetpassword&uid={4}&code={5}

위 링크가 제대로 작동하지 않으면 다음으로 이동하세요.

{3}/member.php?action=resetpassword

다음을 입력해야 합니다.
귀하의 이메일 주소
활성화 코드: {5}

감사합니다,
{2} 직원';
$l['email_lostpw2'] = '{1},

{2}에서 계정 비밀번호 재설정 단계를 완료하려면 웹 브라우저에서 아래 URL로 이동해야 합니다.

{3}/member.php?action=resetpassword&uid={4}&code={5}

위 링크가 제대로 작동하지 않으면 다음으로 이동하세요.

{3}/member.php?action=resetpassword

다음을 입력해야 합니다.
사용자 이름: {1} (또는 귀하의 이메일 주소)
활성화 코드: {5}

감사합니다,
{2} 직원';
$l['email_reportpost'] = '{2}의 {1}님이 다음 게시물을 신고했습니다.

{삼}
{4}/{5}

이 사용자가 이 게시물을 신고한 이유는 다음과 같습니다.
{6}

이 메시지는 이 포럼의 모든 중재자에게 전송되었으며, 중재자가 없는 경우 모든 관리자 및 최고 중재자에게 전송되었습니다.

최대한 빨리 이 게시물을 확인하시기 바랍니다.';
$l['email_reportprofile'] = '{2}의 {1}님이 다음 사용자를 신고했습니다:

{삼}
{4}/{5}

이 사용자가 이 사용자를 신고한 이유는 다음과 같습니다.
{6}

이 메시지는 이 포럼의 모든 중재자에게 전송되었으며, 중재자가 없는 경우 모든 관리자 및 최고 중재자에게 전송되었습니다.

가능한 한 빨리 이 사용자를 확인하시기 바랍니다.';
$l['email_reportreputation'] = '{2}의 {1}님이 다음과 같은 평판을 보고했습니다.

{삼}
{4}/{5}

이 사용자가 이 평판을 보고한 이유는 다음과 같습니다.
{6}

이 메시지는 이 포럼의 모든 중재자에게 전송되었으며, 중재자가 없는 경우 모든 관리자 및 최고 중재자에게 전송되었습니다.

이 평판을 가능한 한 빨리 확인하시기 바랍니다.';
$l['email_report_comment_extra'] = '{1}: {2}';
$l['email_passwordreset'] = '{1},

{2}의 비밀번호가 재설정되었습니다.

귀하의 새 비밀번호는 다음과 같습니다: {3}

포럼에 로그인하려면 이 비밀번호가 필요합니다. 로그인한 후에는 사용자 제어판으로 이동하여 비밀번호를 변경해야 합니다.

감사합니다,
{2} 직원';
$l['email_randompassword'] = '{1},

{2}에 등록해 주셔서 감사합니다. 다음은 귀하의 사용자 이름과 무작위로 생성된 비밀번호입니다. {2}에 로그인하려면 다음 세부정보가 필요합니다.

사용자 이름: {3}
비밀번호: {4}

로그인 후 즉시 비밀번호를 변경하는 것이 좋습니다. 사용자 CP로 이동한 후 왼쪽 메뉴에서 비밀번호 변경을 클릭하면 됩니다.

감사합니다,
{2} 직원';
$l['email_randompassword1'] = '{1},

{2}에 등록해 주셔서 감사합니다. 다음은 귀하의 사용자 이름과 무작위로 생성된 비밀번호입니다. {2}에 로그인하려면 다음 세부정보가 필요합니다.

귀하의 이메일 주소
비밀번호: {4}

로그인 후 즉시 비밀번호를 변경하는 것이 좋습니다. 사용자 CP로 이동한 후 왼쪽 메뉴에서 비밀번호 변경을 클릭하면 됩니다.

감사합니다,
{2} 직원';
$l['email_randompassword2'] = '{1},

{2}에 등록해 주셔서 감사합니다. 다음은 귀하의 사용자 이름과 무작위로 생성된 비밀번호입니다. {2}에 로그인하려면 다음 세부정보가 필요합니다.

사용자 이름: {3} (또는 귀하의 이메일 주소)
비밀번호: {4}

로그인 후 즉시 비밀번호를 변경하는 것이 좋습니다. 사용자 CP로 이동한 후 왼쪽 메뉴에서 비밀번호 변경을 클릭하면 됩니다.

감사합니다,
{2} 직원';
$l['email_sendtofriend'] = '안녕하세요,

{2}의 {1}님이 귀하가 다음 웹페이지를 읽는 데 관심이 있을 것이라고 생각했습니다.

{삼}

{1}에 다음 메시지가 포함되어 있습니다:
-----------------------------
{4}
-----------------------------

감사합니다,
{2} 직원';
$l['email_forumsubscription'] = '{1},
{2}이(가) 방금 {3}에서 글타래를 시작했습니다. 이것은 귀하가 {4}에서 구독하신 포럼입니다.

글타래 제목은 {5}입니다.

다음은 메시지의 일부입니다.
--
{6}
--

글타래를 보려면 다음 URL로 이동하세요.
{7}/{8}

다른 새로운 글타래와 답글도 있을 수 있지만 보드를 다시 방문할 때까지 더 이상 알림을 받을 수 없습니다.

감사합니다,
{4} 직원

-----------------------------
구독 취소 정보:

이 포럼의 새로운 글타래에 대한 알림을 더 이상 받지 않으려면 브라우저에서 다음 URL을 방문하십시오.
{7}/usercp.php?action=removesubscription&type=forum&fid={9}

-----------------------------';
$l['email_activateaccount'] = '{1},

{2}에 등록 절차를 완료하려면 웹 브라우저에서 아래 URL로 이동해야 합니다.

{3}/member.php?action=activate&uid={4}&code={5}

위 링크가 제대로 작동하지 않으면 다음으로 이동하세요.

{3}/member.php?action=활성화

다음을 입력해야 합니다.
사용자 이름: {1}
활성화 코드: {5}

감사합니다,
{2} 직원';
$l['email_activateaccount1'] = '{1},

{2}에 등록 절차를 완료하려면 웹 브라우저에서 아래 URL로 이동해야 합니다.

{3}/member.php?action=activate&uid={4}&code={5}

위 링크가 제대로 작동하지 않으면 다음으로 이동하세요.

{3}/member.php?action=활성화

다음을 입력해야 합니다.
귀하의 이메일 주소
활성화 코드: {5}

감사합니다,
{2} 직원';
$l['email_activateaccount2'] = '{1},

{2}에 등록 절차를 완료하려면 웹 브라우저에서 아래 URL로 이동해야 합니다.

{3}/member.php?action=activate&uid={4}&code={5}

위 링크가 제대로 작동하지 않으면 다음으로 이동하세요.

{3}/member.php?action=활성화

다음을 입력해야 합니다.
사용자 이름: {1} (또는 귀하의 이메일 주소)
활성화 코드: {5}

감사합니다,
{2} 직원';
$l['email_subscription'] = '{1},

{2}님이 귀하가 {3}에서 구독한 글타래에 방금 응답했습니다. 이 글타래의 제목은 {4}입니다.

다음은 메시지의 일부입니다.
-----------------------------
{5}
-----------------------------

글타래를 보려면 다음 URL로 이동하세요.
{6}/{7}

이 글타래에 대한 다른 답변이 있을 수도 있지만 보드를 다시 방문할 때까지 더 이상 알림을 받을 수 없습니다.

감사합니다,
{3} 직원

-----------------------------
구독 취소 정보:

이 글타래에 대한 답변 알림을 더 이상 받고 싶지 않다면 브라우저에서 다음 URL을 방문하세요.
{6}/usercp.php?action=removesubscription&tid={8}

-----------------------------';
$l['email_reachedpmquota'] = '{1},

이것은 귀하의 개인 메시지 받은편지함이 용량에 도달했음을 알려드리기 위해 {2}에서 보낸 자동 이메일입니다.

한 명 이상의 사용자가 귀하에게 비공개 메시지를 보내려고 시도했지만 이로 인해 실패했을 수 있습니다.

현재 저장되어 있는 비공개 메시지 중 일부를 삭제하고 \'휴지통\'에서도 삭제하는 것을 기억하세요.

감사합니다,
{2} 직원
{삼}';
$l['email_changeemail'] = '{1},

귀하의 이메일 주소를 변경해 달라는 요청이 {2}에 접수되었습니다(아래 세부정보 참조).

이전 이메일 주소: {3}
새 이메일 주소: {4}

이러한 변경 사항이 정확하다면 웹 브라우저에서 다음 URL로 이동하여 {2}에서 확인 프로세스를 완료하세요.

{5}/member.php?action=activate&uid={8}&code={6}

위 링크가 제대로 작동하지 않으면 다음으로 이동하세요.

{5}/member.php?action=활성화

다음을 입력해야 합니다.
사용자 이름: {7}
활성화 코드: {6}

새 이메일 주소를 확인하지 않기로 선택하면 프로필이 업데이트되지 않으며 기존 이메일 주소가 계속 포함됩니다.

감사합니다,
{2} 직원
{5}';
$l['email_changeemail_noactivation'] = '{1},

귀하의 이메일 주소를 변경해 달라는 요청이 {2}에 접수되었습니다(아래 세부정보 참조).

이전 이메일 주소: {3}
새 이메일 주소: {4}

이 변경사항은 자동으로 처리되었습니다. 이 변경을 요청하지 않은 경우 관리자에게 문의하세요.

감사합니다,
{2} 직원
{5}';
$l['email_changepassword'] = '{1},

귀하 또는 귀하의 비밀번호에 접근할 수 있는 누군가가 최근에 귀하의 계정 비밀번호를 변경했기 때문에 이 이메일을 받으셨습니다.

사용자 이름: {1}
이메일 주소: {2}

이 변경을 요청하지 않은 경우 관리자에게 문의하세요.

감사합니다,
{3} 직원
{4}';
$l['email_newpm'] = '{1},

{3}에 {2}로부터 새로운 비공개 메시지를 받았습니다:

-----------------------------
{5}
-----------------------------

이 메시지를 보거나 회신하거나 전달하려면 다음 링크를 따르세요.

{4}/private.php

{3}을(를) 방문할 때까지는 새 메시지에 대한 추가 알림을 받지 못함을 참고하세요.

계정 옵션 페이지에서 새 메시지 알림을 비활성화할 수 있습니다.

{4}/usercp.php?action=options

감사합니다,
{3} 직원
{4}';
$l['email_emailuser'] = '{1},

{3}의 {2}님이 다음 메시지를 보냈습니다:
-----------------------------
{5}
-----------------------------

감사합니다,
{3} 직원
{4}

-----------------------------
다른 회원으로부터 이메일 메시지를 받고 싶지 않으신가요?

다른 회원이 귀하에게 이메일을 보내는 것을 원하지 않으면 사용자 제어판을 방문하여 \'다른 회원에게 이메일 숨기기\' 옵션을 활성화하십시오.
{4}/usercp.php?action=options

-----------------------------';
$l['email_groupleader_joinrequest'] = '{1},

{2}님이 {4}에 {3} 가입을 요청했습니다(아래 참조).

이유: {5}

이 요청을 수락하거나 거부하려면 다음으로 이동하세요.

{6}/managegroup.php?gid={7}

감사합니다,
{4} 직원';
$l['email_contact_subject'] = '연락처: {1}';
$l['email_contact'] = '이메일: {1}
포럼 프로필: {2}
IP 주소: {3}
메시지:
{4}';
$l['pmsubject_subscription'] = '{1}에 대한 새 답글';
$l['pm_subscription'] = '{1},

{2}님이 귀하가 구독한 글타래에 방금 응답했습니다. 이 글타래의 제목은 {3}입니다.

다음은 메시지의 일부입니다.
-----------------------------
{4}
-----------------------------

글타래를 보려면 다음 URL로 이동하세요.
[URL]{5}/{6}[/url]

이 글타래에 대한 다른 답변이 있을 수도 있지만 해당 글타래를 다시 방문할 때까지는 더 이상 알림을 받을 수 없습니다.

-----------------------------
구독 취소 정보:

이 글타래에 대한 답변 알림을 더 이상 받고 싶지 않다면 브라우저에서 다음 URL을 방문하세요.
[url]{5}/usercp.php?action=removesubscription&tid={7}[/url]

-----------------------------';
$l['email_broken_task_subject'] = '{1}의 MyBB 작업 오류';
$l['email_broken_task'] = '{1}({2})에서 실행 중인 MyBB 복사본에 작업 시스템에 오류가 발생했습니다.

{3}에 대한 작업 파일이 누락되었습니다.

문제가 해결될 때까지 이 작업은 비활성화되었습니다.';
