<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 03:12:31 +0000
// --------------------------------------------------------------------------------

$l['nav_helpdocs'] = '도움말 문서';
$l['nav_smilies'] = '스마일리 목록';
$l['nav_syndication'] = '최신 글타래 신디케이션(RSS)';
$l['buddy_list'] = '친구 목록';
$l['online'] = '온라인';
$l['online_none'] = '<em>온라인 친구가 없습니다</em>';
$l['offline'] = '오프라인';
$l['offline_none'] = '<em>오프라인 친구가 없습니다</em>';
$l['delete_buddy'] = 'X';
$l['pm_buddy'] = '비공개 메시지 보내기';
$l['last_active'] = '<strong>마지막 활동:</strong> {1}';
$l['close'] = '닫기기';
$l['no_buddies'] = '<em>현재 친구 목록이 비어 있습니다. 사용자 CP를 사용하거나 사용자 프로필을 방문하여 친구 목록에 사용자를 추가하세요.</em>';
$l['help_docs'] = '도움말 문서';
$l['search_help_documents'] = '도움말 문서 검색';
$l['search_by_name'] = '이름으로 검색';
$l['search_by_document'] = '문서로 검색';
$l['enter_keywords'] = '키워드 입력';
$l['search'] = '검색';
$l['redirect_searchresults'] = '감사합니다. 검색이 제출되었으며 이제 결과 목록으로 이동됩니다.';
$l['search_results'] = '검색 결과';
$l['help_doc_results'] = '도움말 문서 결과';
$l['document'] = 'Document';
$l['error_nosearchresults'] = '죄송합니다. 제공하신 검색어 정보를 사용하여 반환된 결과가 없습니다. 검색어를 다시 정의하고 다시 시도하십시오.';
$l['no_help_results'] = '죄송합니다. 제공하신 검색어 정보를 사용하여 반환된 결과가 없습니다.';
$l['error_helpsearchdisabled'] = '관리자가 도움말 문서 검색 기능을 비활성화했습니다.';
$l['smilies_listing'] = '스마일리 목록';
$l['name'] = '이름';
$l['abbreviation'] = '약어';
$l['click_to_add'] = '메시지에 삽입하려면 스마일리를 클릭하세요.';
$l['close_window'] = '창 닫기';
$l['no_smilies'] = '현재 사용할 수 있는 스마일이 없습니다.';
$l['who_posted'] = '누가 게시?';
$l['total_posts'] = '총 게시물 수:';
$l['user'] = '사용자';
$l['num_posts'] = '# 게시물';
$l['forum_rules'] = '{1} - 규칙';
$l['error_invalid_limit'] = '입력한 피드 항목 한도가 잘못되었습니다. 유효한 한도를 지정하십시오.';
$l['syndication'] = '최신 글타래 신디케이션';
$l['syndication_generated_url'] = '생성된 신디케이션 URL:';
$l['syndication_note'] = '아래에서는 특정 RSS 신디케이션 피드에 대한 링크를 생성할 수 있습니다. 링크는 모든 포럼, 포럼당 또는 특정 수의 포럼에 대해 생성될 수 있습니다. 그러면 RSS 리더에 복사할 수 있는 링크가 표시됩니다. <i><a href="https://en.wikipedia.org/wiki/RSS" target="_blank" rel="noopener">RSS란 무엇인가요?</a></i>';
$l['syndication_forum'] = '신디케이트 포럼:';
$l['syndication_forum_desc'] = '오른쪽에서 포럼을 선택해 주세요. 여러 포럼을 선택하려면 Ctrl 키를 사용하세요.';
$l['syndication_version'] = '피드 버전:';
$l['syndication_version_desc'] = '생성하려는 피드 버전을 선택하세요.';
$l['syndication_version_json1'] = 'JSON Feed 1';
$l['syndication_version_atom1'] = 'Atom 1.0';
$l['syndication_version_rss2'] = 'RSS 2.00(기본값)';
$l['syndication_generate'] = '신디케이션 URL 생성';
$l['syndication_limit'] = '한계:';
$l['syndication_limit_desc'] = '한 번에 다운로드할 글타래의 양입니다. 한번에 50개가 최대 한도입니다.';
$l['syndication_threads_time'] = '한 번에 글타래';
$l['syndicate_all_forums'] = '신디케이트 모든 포럼';
$l['redirect_markforumread'] = '선택한 포럼이 읽음으로 표시됨';
$l['redirect_markforumsread'] = '모든 포럼이 읽음으로 표시됨';
$l['redirect_forumpasscleared'] = '이 포럼에 저장된 비밀번호가 삭제되었습니다.';
$l['redirect_cookiescleared'] = '모든 쿠키가 삭제되었습니다.';
$l['error_invalidforum'] = '잘못된 포럼';
$l['error_invalidhelpdoc'] = '지정한 도움말 문서가 존재하지 않는 것 같습니다.';
$l['error_invalidsearch'] = '잘못된 검색이 지정되었습니다. 돌아가서 다시 시도해 주세요.';
$l['error_no_search_support'] = '이 데이터베이스 엔진은 검색을 지원하지 않습니다.';
$l['error_searchflooding'] = '죄송합니다. 검색은 {1}초마다 한 번만 수행할 수 있습니다. 다시 검색을 시도하기 전에 {2}초 더 기다리십시오.';
$l['error_searchflooding_1'] = '죄송합니다. 검색은 {1}초마다 한 번만 수행할 수 있습니다. 다시 검색을 시도하기 전에 1초 더 기다려 주십시오.';
$l['dst_settings_updated'] = '귀하의 일광 절약 시간 설정이 자동으로 조정되었습니다.<br /><br />이제 포럼 색인으로 돌아가게 됩니다.';
