<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 06:34:36 +0000
// --------------------------------------------------------------------------------

$l['nav_newreply'] = '답글 게시';
$l['post_reply_to'] = '{1}에 대한 답글 게시';
$l['post_new_reply'] = '새 답글 게시';
$l['reply_to'] = '글타래에 답장: {1}';
$l['post_subject'] = '게시물 제목:';
$l['your_message'] = '귀하의 메시지:';
$l['post_options'] = '게시물 옵션:';
$l['options_sig'] = '<strong>서명:</strong> 서명을 포함하세요. (등록된 사용자만)';
$l['options_emailnotify'] = '<strong>이메일 알림:</strong> 새 답변이 있을 때마다 이메일을 받습니다. (등록된 사용자만)';
$l['options_disablesmilies'] = '<strong>스마일리 비활성화:</strong> 이 게시물에 스마일리가 표시되지 않도록 합니다.';
$l['post_reply'] = '답글 게시';
$l['preview_post'] = '게시물 미리보기';
$l['mod_options'] = '중재자 옵션:';
$l['close_thread'] = '<strong>글타래 종료</strong>: 이 글타래에 더 이상 게시되지 않도록 합니다.';
$l['stick_thread'] = '<strong>글타래 고정:</strong> 이 글타래를 포럼 상단에 고정합니다.';
$l['forum_rules'] = '{1} - 규칙';
$l['thread_review'] = '글타래 검토(최신 항목부터)';
$l['thread_review_more'] = '이 글타래에는 {1}개 이상의 답변이 있습니다. <a href="{2}" target="_blank">전체 글타래를 읽으세요.</a>';
$l['posted_by'] = '게시자:';
$l['draft_saved'] = '새 게시물이 초안으로 저장되었습니다.<br />이제 초안 목록으로 이동됩니다.';
$l['error_post_already_submitted'] = '당신은 이미 지정된 글타래에 이 답글을 게시했습니다. 답변을 보려면 글타래를 방문하세요.';
$l['multiquote_external_one'] = '이 글타래 외부의 게시물을 1개 선택했습니다.';
$l['multiquote_external'] = '이 글타래 외부의 게시물을 {1}개 선택했습니다.';
$l['multiquote_external_one_deselect'] = '이 게시물 선택 취소';
$l['multiquote_external_deselect'] = '이 게시물 선택 취소';
$l['multiquote_external_one_quote'] = '이 글도 인용';
$l['multiquote_external_quote'] = '이 게시물도 인용';
$l['redirect_newreply'] = '감사합니다. 답변이 게시되었습니다.';
$l['redirect_newreply_moderation'] = '관리자는 모든 새 게시물에 검토가 필요하도록 지정했습니다. 이제 스레드로 돌아갑니다.';
$l['redirect_newreply_post'] = '<br />이제 귀하의 게시물로 이동됩니다.';
$l['redirect_newreplyerror'] = '죄송합니다. 내용 부족으로 인해 답변이 거부되었습니다. <br />이제 글타래로 돌아갑니다.';
$l['redirect_threadclosed'] = '운영자가 글타래를 닫았기 때문에 이 글타래에 답글을 게시할 수 없습니다.';
$l['error_post_noperms'] = '이 초안을 수정할 권한이 없습니다.';
$l['error_stop_forum_spam_spammer'] = '죄송합니다. 귀하의 {1}이(가) 알려진 스패머의 이름과 일치합니다. 이것이 실수라고 생각되면 관리자에게 문의하십시오';
$l['error_stop_forum_spam_fetching'] = '죄송합니다. 스패머 데이터베이스에 대한 답변을 확인하는 중에 문제가 발생했습니다. 데이터베이스에 액세스하지 못했을 가능성이 높습니다. 나중에 다시 시도 해주십시오.';
$l['error_suspendedposting'] = '귀하의 게시 권한은 현재 정지되었습니다 {1}.<br /><br />

정지 날짜: {2}';
$l['error_suspendedposting_temporal'] = '{1}까지';
$l['error_suspendedposting_permanent'] = '영구적으로로';
