<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 02:24:22 +0000
// --------------------------------------------------------------------------------

$l['nav_newthread'] = '새 글타래';
$l['newthread_in'] = '{1}의 새 글타래';
$l['post_new_thread'] = '새 글타래 게시';
$l['thread_subject'] = '글타래 제목:';
$l['your_message'] = '내 메시지:';
$l['post_options'] = '게시물 옵션:';
$l['options_sig'] = '<b>서명:</b> 서명을 포함하세요. (등록된 사용자만)';
$l['options_emailnotify'] = '<b>이메일 알림:</b> 새 답변이 있을 때마다 이메일을 받습니다. (등록된 사용자만)';
$l['options_disablesmilies'] = '<b>스마일리 비활성화:</b> 이 게시물에 스마일리 표시를 비활성화합니다.';
$l['post_thread'] = '글타래 게시';
$l['preview_post'] = '게시물 미리보기';
$l['poll'] = '투표:';
$l['poll_desc'] = '선택적으로 이 글타래에 설문조사를 첨부할 수 있습니다.';
$l['poll_check'] = '설문조사를 게시하고 싶습니다.';
$l['num_options'] = '옵션 수:';
$l['max_options'] = '(최대: {1})';
$l['mod_options'] = '운영자 옵션:';
$l['close_thread'] = '<b>글타래 닫기</b>: 이 글타래에 더 이상 게시하지 못하게 합니다.';
$l['stick_thread'] = '<b>글타래 고정:</b> 이 글타래를 포럼 상단에 고정하세요.';
$l['draft_saved'] = '새 글타래 초안이 성공적으로 저장되었습니다.<br />이제 초안 목록으로 이동됩니다.';
$l['error_post_already_submitted'] = '귀하는 이미 이 포럼에 이 글타래를 게시했습니다. 글타래를 보려면 포럼을 방문하세요.';
$l['no_prefix'] = '접두사 없음';
$l['forum_rules'] = '{1} - 규칙';
$l['multiquote_external_one'] = '다른 글타래에서 하나의 게시물을 선택했습니다.';
$l['multiquote_external'] = '다른 글타래에서 게시물 {1}개를 선택했습니다.';
$l['multiquote_external_one_deselect'] = '이 게시물 선택 취소';
$l['multiquote_external_deselect'] = '이 게시물 선택 취소';
$l['multiquote_external_one_quote'] = '이 글도 인용';
$l['multiquote_external_quote'] = '이 게시물도 인용';
$l['redirect_newthread'] = '감사합니다. 글타래가 게시되었습니다.';
$l['redirect_newthread_poll'] = '<br />이제 설문조사 옵션 및 구성 페이지로 이동됩니다.';
$l['redirect_newthread_moderation'] = '<br />관리자는 모든 새 글타래에 조정이 필요하도록 지정했습니다. 이제 글타래 목록으로 돌아갑니다.';
$l['redirect_newthread_unviewable'] = '<br />이 포럼의 글타래를 볼 수 있는 권한이 없습니다. 이제 포럼으로 돌아갑니다.';
$l['redirect_newthread_thread'] = '<br />이제 새 글타래로 이동됩니다.';
$l['invalidthread'] = '지정된 초안이 존재하지 않거나 해당 초안을 볼 수 있는 권한이 없습니다.';
$l['error_stop_forum_spam_spammer'] = '죄송합니다. 귀하의 {1}이(가) 알려진 스패머의 이름과 일치합니다. 이것이 실수라고 생각되면 관리자에게 문의하십시오';
$l['error_stop_forum_spam_fetching'] = '죄송합니다. 스패머 데이터베이스와 비교하여 스레드를 확인하는 중에 문제가 발생했습니다. 데이터베이스에 액세스하지 못했을 가능성이 높습니다. 나중에 다시 시도 해주십시오.';
$l['error_suspendedposting'] = '귀하의 게시 권한은 현재 정지되었습니다 {1}.<br /><br />

정지 날짜: {2}';
$l['error_suspendedposting_temporal'] = '{1}까지';
$l['error_suspendedposting_permanent'] = '영구적으로';
