<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 00:19:23 +0000
// --------------------------------------------------------------------------------

$l['nav_online'] = 'Who\'s Online';
$l['nav_onlinetoday'] = '오늘 온라인에 있었던 사람';
$l['viewing_announcements'] = '공지사항 보는중 <a href="{1}">{2}</a>';
$l['viewing_announcements2'] = '공지사항 보는중';
$l['viewing_attachment'] = '첨부파일 보는중';
$l['viewing_attachment2'] = '<a href="{3}">{2}</a> 글타래에서 <a href="attachment.php?aid={1}" target="_blank">첨부파일</a> 보는중';
$l['viewing_calendar'] = '<a href="calendar.php">캘린더</a> 보는중';
$l['viewing_event'] = '이벤트 보는중';
$l['viewing_event2'] = '이벤트 <a href="{1}">{2}</a> 보는중';
$l['adding_event'] = '<a href="calendar.php?action=addevent">이벤트 추가중</a>';
$l['editing_event'] = '이벤트 편집 중';
$l['viewing_contact_us'] = '<a href="contact.php">문의하기</a> 보는중';
$l['editing_post'] = '게시물 수정 중';
$l['viewing_forum'] = '포럼 보는중';
$l['viewing_forum2'] = '포럼 <a href="{1}">{2}</a> 보는중';
$l['forum_redirect_to'] = '<a href="{1}">{2}</a>로 리디렉션 중';
$l['viewing_index'] = '{1} <a href="index.php">기본 색인 보는중</a>';
$l['activating_account'] = '계정 활성화중';
$l['viewing_profile'] = '프로필 보는중';
$l['viewing_profile2'] = '<a href="{1}">{2}</a> 프로필 보는중';
$l['registering'] = '<a href="member.php?action=register">등록 중</a>';
$l['logging_in'] = '<a href="member.php?action=login">로그인중</a>';
$l['logging_in_plain'] = '로그인중';
$l['logging_out'] = '로그 아웃중';
$l['emailing_user'] = '사용자에게 이메일 보내는 중';
$l['rating_user'] = '사용자 평가 중';
$l['viewing_memberlist'] = '<a href="memberlist.php">회원 목록</a> 보는중';
$l['viewing_whoposted'] = '게시한 사람 보는중';
$l['viewing_whoposted2'] = '글타래 <a href="{1}">{2}</a>에 게시한 사람 보는중';
$l['marking_read'] = '<a href="misc.php?action=markread&amp;my_post_key={1}">포럼을 읽음으로 표시중</a>';
$l['viewing_helpdocs'] = '<a href="misc.php?action=help">도움말 문서</a> 보는중';
$l['viewing_buddylist'] = '<a href="#" onclick="MyBB.popupWindow(\'/misc.php?action=buddypopup&amp;modal=1\'); return false;">친구 목록</a> 보는중';
$l['viewing_smilies'] = '<a href="misc.php?action=smilies">스마일 목록</a> 보는중';
$l['viewing_syndication'] = '<a href="misc.php?action=syndication">RSS 신디케이션</a> 페이지 보는중';
$l['replying_thread'] = '글타래에 답장하는 중';
$l['replying_thread2'] = '<a href="{1}">{2}</a> 글타래에 답장 중';
$l['posting_thread'] = '새 글타래 게시중';
$l['posting_thread2'] = '<a href="{1}">{2}</a>에 새 글타래 게시중';
$l['viewing_wol'] = '<a href="online.php">Who\'s Online</a>보는 중';
$l['viewing_woltoday'] = '<a href="online.php?action=today">Who Was Online Today</a>보는 중';
$l['creating_poll'] = '새 설문조사 만드는 중';
$l['editing_poll'] = '설문조사 편집중';
$l['viewing_pollresults'] = '설문조사 결과 보는 중';
$l['voting_poll'] = '설문조사에 투표하는 중';
$l['using_modtools'] = '운영자 도구 사용중';
$l['sending_pm'] = '비공개 메시지 보내는 중';
$l['reading_pm'] = '비공개 메시지 읽는 중';
$l['editing_pmfolders'] = 'PM 폴더 편집중';
$l['using_pmsystem'] = 'PM 시스템 사용중';
$l['reporting_post'] = '게시물 신고하는중';
$l['searching_forum'] = '<a href="search.php">검색 중</a> {1}';
$l['reading_thread'] = '글타래 읽는중';
$l['reading_thread2'] = '글타래 <a href="{1}">{2}</a> {3} 읽는 중';
$l['viewing_team'] = '포럼팀 보는중';
$l['viewing_stats'] = '포럼 통계 보는중';
$l['updating_profile'] = '<a href="usercp.php?action=profile">프로필 업데이트 중</a>';
$l['updating_options'] = '<a href="usercp.php?action=options">옵션 업데이트중</a>';
$l['editing_signature'] = '<a href="usercp.php?action=editsig">서명 편집중</a>';
$l['changing_avatar'] = '<a href="usercp.php?action=avatar">아바타 변경중</a>';
$l['viewing_subscriptions'] = '<a href="usercp.php?action=subscriptions">글타래 구독</a> 보기 중';
$l['editing_pad'] = '<a href="usercp.php">개인 패드</a> 편집중';
$l['editing_password'] = '<a href="usercp.php?action=password">비밀번호</a> 편집중';
$l['user_cp'] = '<a href="usercp.php">사용자 제어판</a> 보는중';
$l['viewing_portal'] = '<a href="portal.php">포털</a> 페이지 보는중';
$l['viewing_noperms'] = '권한 없음 페이지 보는중';
$l['unknown_location'] = '<a href="{1}">알 수 없는 위치</a>';
$l['giving_reputation'] = '<a href="{1}">{2}</a>에 대한 평판 제공중';
$l['viewing_reputation_report'] = '<a href="{1}">{2}의 평판</a> 보는중';
$l['viewing_reputation_report2'] = '평판 보는중';
$l['member_resendactivation'] = '계정 활성화 이메일 재전송중';
$l['member_lostpw'] = '<a href="member.php?action=lostpw">분실된 비밀번호</a> 검색 중';
$l['sending_thread'] = '친구에게 글타래 보내는중';
$l['page'] = '페이지';
$l['users_online'] = 'Who\'s Online';
$l['on_username'] = '사용자 이름';
$l['time'] = '시간';
$l['location'] = '위치';
$l['online_today'] = '오늘의 Who Was Online';
$l['refresh_page'] = '이 페이지 새로 고침';
$l['online_online_plural'] = '사용자';
$l['online_online_singular'] = '사용자';
$l['online_member_plural'] = '회원';
$l['online_member_singular'] = '회원';
$l['online_anon_plural'] = 'are';
$l['online_anon_singular'] = 'is';
$l['online_guest_plural'] = '손님';
$l['online_guest_singular'] = '손님';
$l['online_count'] = '지난 {3}분 동안 {1} {2}이(가) 활동했습니다({4} {5}, 그 중 {6}는 보이지 않음, {8} {9}).';
$l['ip'] = 'IP:';
$l['resolves_to'] = '호스트 이름:';
$l['if_resolvable'] = '(해결 가능한 경우)';
$l['admin_options'] = 'Admin Options';
$l['search_regip_users'] = '이 IP로 등록한 사용자를 검색하세요.';
$l['search_postip_users'] = '이 IP로 게시한 사용자를 검색하세요.';
$l['lookup'] = '[조회]';
$l['member_online_today'] = '<strong>1</strong> 오늘의 Was Online 회원';
$l['members_were_online_today'] = '<strong>{1}</strong> 회원이 오늘 온라인에 접속했습니다.';
$l['member_online_hidden'] = '({1} 회원이 보이지 않음)';
$l['members_online_hidden'] = '({1}명의 멤버가 보이지 않음)';
$l['rating_thread'] = '글타래 평가중';
$l['managing_favorites'] = '즐겨찾는 글타래 관리중';
$l['managing_subscriptions'] = '구독된 글타래 관리중';
$l['managing_group'] = '사용자 그룹 관리중';
$l['viewing_modcp'] = '운영자 CP 보는중';
$l['viewing_modlogs'] = '운영자 로그 보는중';
$l['managing_announcements'] = '공지 사항 관리중';
$l['search_for_user'] = '사용자 검색 중';
$l['managing_warninglogs'] = '경고 로그 관리중';
$l['searching_ips'] = 'IP 검색 중';
$l['viewing_reports'] = '신고된 게시물 보는중';
$l['adding_announcement'] = '공지 사항 추가중';
$l['deleting_announcement'] = '공지사항 삭제중';
$l['editing_announcement'] = '공지 사항 편집중';
$l['managing_modqueue'] = '중재 대기열 관리중';
$l['editing_user_profiles'] = '사용자 프로필 편집중';
$l['managing_bans'] = '차단 관리중';
$l['revoking_warning'] = '경고 취소중';
$l['warning_user'] = '사용자에게 경고중';
$l['viewing_warning'] = '경고 보는중';
$l['managing_warnings'] = '경고 관리중';
$l['changing_dst'] = 'DST 스위치 변경중';
$l['printing_thread'] = '글타래 인쇄중';
$l['printing_thread2'] = '글타래 <a href="{1}">{2}</a> 인쇄 중';
$l['managing_buddyignorelist'] = '친구/무시 목록 관리';
