<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어 (South Korea)
// Author of the language pack : zardkim
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Mon, 08 Jul 2024 01:35:08 +0000
// --------------------------------------------------------------------------------

$l['ougc_customlang'] = 'OUGC 사용자 정의 언어';
$l['ougc_customlang_desc'] = '코어 업그레이드 중에 덮어쓰이지 않는 사용자 정의 언어 파일을 로드합니다.';
$l['theme_bootbb_header_toggle'] = '네비게이션 전환';
$l['theme_bootbb_header_forum'] = '포럼';
$l['theme_bootbb_header_misc'] = '기타';
$l['theme_bootbb_boardstats_threads'] = '글타래';
$l['theme_bootbb_boardstats_posts'] = '게시물';
$l['theme_bootbb_boardstats_users_online'] = '사용자가 가장 많은 온라인';
$l['theme_bootbb_boardstats_users'] = '사용자';
$l['theme_bootbb_stats_top_poster'] = '오늘의 인기 게시물';
$l['theme_bootbb_stats_popular_forum'] = '가장 인기 있는 포럼';
$l['theme_bootbb_stats_posts'] = '게시물';
$l['theme_bootbb_stats_threads'] = '글타래';
$l['theme_bootbb_footer_about_title'] = '우리 커뮤니티 소개';
$l['theme_bootbb_footer_about_text'] = '우리 커뮤니티의 다양한 주제에 대해 토론하고 즐거운 시간을 보내십시오. 환영합니다';
$l['theme_bootbb_footer_quicklinks'] = '빠른 링크';
$l['theme_bootbb_footer_facebook'] = '팬 되기';
$l['theme_bootbb_footer_twitter'] = '우리를 팔로우';
$l['theme_bootbb_footer_reachus'] = '우리에게 연락';
$l['theme_bootbb_forumdisplay_rss'] = 'RSS 피드';
$l['welcome_newposts'] = '새 게시물';
$l['welcome_todaysposts'] = '오늘의 게시물';
$l['toplinks_memberlist'] = '회원';
