<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Mon, 01 Jul 2024 04:59:26 +0000
// --------------------------------------------------------------------------------

$l['nav_postpoll'] = '설문조사 게시';
$l['nav_editpoll'] = '설문조사 수정';
$l['nav_pollresults'] = '설문조사 결과';
$l['edit_poll'] = '설문조사 수정';
$l['delete_poll'] = '설문조사 삭제';
$l['delete_q'] = '삭제?';
$l['delete_note'] = '이 설문조사를 삭제하려면 왼쪽 상자를 선택하고 오른쪽 버튼을 클릭하세요.';
$l['delete_note2'] = '<b>참고:</b> 이 설문조사가 삭제되면 복원할 수 있는 방법이 없습니다.';
$l['question'] = '질문:';
$l['num_options'] = '옵션 수:';
$l['max_options'] = '최대:';
$l['poll_options'] = '설문조사 옵션:';
$l['update_options'] = '업데이트 옵션';
$l['poll_options_note'] = '설문조사 옵션은 짧고 간단해야 합니다.';
$l['options'] = '옵션:';
$l['option_multiple'] = '<b>객관식 허용:</b> 사용자는 둘 이상의 옵션에 투표할 수 있습니다.';
$l['option_multiple_maxoptions'] = '사용자당 최대 옵션 수(0은 제한 없음):';
$l['option_public'] = '<b>공개 설문조사:</b> 어떤 사용자가 어떤 옵션에 투표했는지 확인할 수 있는 기능을 사용자에게 제공합니다.';
$l['option_closed'] = '<b>설문조사 종료:</b> 이 옵션을 선택하면 투표가 종료됩니다.';
$l['poll_timeout'] = '설문조사 시간 초과:';
$l['timeout_note'] = '사람들이 이 설문조사에 투표할 수 있는 일수입니다.<br />(이 설문조사가 시간 초과되지 않도록 하려면 0으로 설정하세요.)';
$l['days_after'] = '일 후:';
$l['update_poll'] = '설문조사 업데이트';
$l['option'] = '옵션';
$l['votes'] = '투표:';
$l['post_new_poll'] = '새 설문조사 게시';
$l['days'] = '날';
$l['poll_results'] = '설문조사 결과';
$l['poll_total'] = '총:';
$l['poll_votes'] = '투표수';
$l['redirect_pollposted'] = '귀하의 설문조사가 게시되었습니다.<br />이제 글타래로 돌아가게 됩니다.';
$l['redirect_pollpostedmoderated'] = '귀하의 설문조사가 게시되었지만 귀하의 글타래는 아직 조정 대기 중입니다.<br />포럼으로 돌아가게 됩니다.';
$l['redirect_pollupdated'] = '설문조사가 업데이트되었습니다.<br />이제 글타래로 돌아갑니다.';
$l['redirect_votethanks'] = '투표해 주셔서 감사합니다.<br />이제 글타래로 돌아갑니다.';
$l['redirect_unvoted'] = '이 글타래에 대한 귀하의 투표가 제거되었습니다.<br />이제 글타래로 돌아가게 됩니다.';
$l['redirect_polldeleted'] = '감사합니다. 설문조사가 글타래에서 성공적으로 제거되었습니다.<br />이제 글타래로 돌아갑니다.';
$l['error_polloptiontoolong'] = '입력한 하나 이상의 설문조사 옵션이 허용되는 한도보다 깁니다. 돌아가서 길이를 줄여주세요.';
$l['error_polloptionsequence'] = '입력한 하나 이상의 설문 ​​옵션에 사용하면 안 되는 시퀀스(<strong>||~|~||</strong>)가 포함되어 있습니다. 돌아가서 삭제해 주세요.';
$l['error_noquestionoptions'] = '설문조사에 대한 질문을 입력하지 않았거나 옵션이 충분하지 않습니다. 설문조사에 포함할 수 있는 최소 옵션 수는 2개입니다.<br />뒤로 돌아가서 이 오류를 수정하세요.';
$l['error_pollalready'] = '글타래에 이미 설문조사가 있습니다!';
$l['error_nopolloptions'] = '지정된 설문 옵션이 잘못되었거나 존재하지 않습니다.';
$l['error_maxpolloptions'] = '너무 많은 옵션에 투표했습니다. {1}개 옵션에만 투표하실 수 있습니다.<br />돌아가서 다시 시도해 주세요.';
$l['error_alreadyvoted'] = '당신은 이미 이 설문조사에 투표하셨습니다.';
$l['error_notvoted'] = '이 설문조사에 투표하지 않으셨습니다.';
$l['error_invalidpoll'] = '지정된 설문조사가 잘못되었거나 존재하지 않습니다.';
$l['error_pollclosed'] = '종료된 설문조사에는 투표할 수 없습니다.';
$l['poll_time_limit'] = '죄송합니다. 글타래에 설문조사를 추가할 수 없습니다. 관리자는 게시 후 {1}시간 이내에만 설문조사를 추가할 수 있도록 설정했습니다.';
$l['poll_deleted'] = '삭제된 설문조사';
$l['poll_edited'] = '편집된 설문조사';
