<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Mon, 01 Jul 2024 03:55:27 +0000
// --------------------------------------------------------------------------------

$l['nav_portal'] = '포탈';
$l['posted_by'] = '게시자:';
$l['forum'] = '포럼:';
$l['replies'] = '답글';
$l['no_replies'] = '닶글 없음';
$l['latest_threads'] = '최신 글타래';
$l['latest_threads_replies'] = '답글:';
$l['latest_threads_views'] = '조회수:';
$l['latest_threads_lastpost'] = '마지막 게시물:';
$l['private_messages'] = '비공개 메시지';
$l['pms_received_new'] = '{1}, 읽지 않은 메시지가 <b>{2}</b>개 있습니다.';
$l['pms_unread'] = '읽지 않은 메시지';
$l['pms_total'] = '총 메시지';
$l['search_forums'] = '포럼 검색';
$l['advanced_search'] = '고급 검색';
$l['forum_stats'] = '포럼 통계';
$l['num_members'] = '회원:';
$l['latest_member'] = '최근 회원:';
$l['num_threads'] = '포럼 글타래:';
$l['num_posts'] = '포럼 게시물:';
$l['full_stats'] = '전체 통계';
$l['welcome'] = '환영합니다, {1}';
$l['guest_welcome_registration'] = '우리 사이트에 게시물을 게시하려면 먼저 <a href="{1}">등록</a>해야 합니다.';
$l['username'] = '사용자 이름';
$l['password'] = '비밀번호';
$l['login'] = '로그인!';
$l['member_welcome_lastvisit'] = '마지막 방문:';
$l['since_then'] = '방문 이후 일어난 일:';
$l['new_announcements'] = '{1}개의 새 공지사항';
$l['new_announcement'] = '새 공지사항 1개';
$l['new_threads'] = '{1}개의 새 글타래';
$l['new_thread'] = '새 글타래 1개';
$l['new_posts'] = '{1}개의 새 게시물';
$l['new_post'] = '새 게시물 1개';
$l['view_new'] = '새 게시물 보기';
$l['view_todays'] = '오늘의 게시물 보기';
$l['online'] = '온라인 사용자';
$l['online_user'] = '현재 온라인 사용자는 1명입니다.';
$l['online_users'] = '현재 <b>{1}</b>명의 온라인 사용자가 있습니다.';
$l['online_counts'] = '<b>{1}</b> 회원 | <b>{2}</b> 손님';
$l['print_this_item'] = '이 항목을 인쇄';
$l['send_to_friend'] = '이 항목을 친구에게 보내기';
$l['latest_announcements'] = '최신 공지사항';
$l['portal_disabled'] = '관리자가 포털 기능을 비활성화했으므로 포털 기능을 사용할 수 없습니다.';
