<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Sat, 29 Jun 2024 05:25:00 +0000
// --------------------------------------------------------------------------------

$l['forum'] = '포럼:';
$l['printable_version'] = '인쇄 가능한 버전';
$l['pages'] = '페이지:';
$l['thread'] = '글타래:';
