<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 00:22:46 +0000
// --------------------------------------------------------------------------------

$l['nav_pms'] = '비공개 메시지';
$l['nav_send'] = '작성하기';
$l['nav_tracking'] = '메시지 추적';
$l['nav_folders'] = '폴더 관리';
$l['nav_empty'] = '빈 폴더';
$l['nav_export'] = '메시지 내보내기';
$l['nav_search'] = '검색';
$l['nav_results'] = '결과';
$l['new_pm'] = '새로운 메시지';
$l['old_pm'] = '오래된 메시지';
$l['reply_pm'] = '회신 대상';
$l['fwd_pm'] = '전달 된 메시지';
$l['pms_disabled'] = '관리자가 비활성화한 개인 메시징 기능은 사용할 수 없습니다.';
$l['private_messaging'] = '비공개 메시지';
$l['inbox'] = '받은편지함';
$l['compose_message2'] = '메시지 작성';
$l['manage_folders'] = '폴더 관리';
$l['pm_search_results'] = '비공개 메시지 검색 결과';
$l['message_title'] = '메시지 제목';
$l['sender'] = '보내는 사람';
$l['sentto'] = '다음에 전송';
$l['date_sent'] = '보낸 날짜/시간';
$l['desc'] = '내림차순';
$l['asc'] = '오름차순';
$l['delete_pm'] = '삭제';
$l['move_to'] = '다음으로 이동';
$l['or'] = '또는';
$l['selected_messages'] = '선택한 메시지';
$l['go'] = '가기!';
$l['pmspaceused'] = 'PM이 사용된 공간';
$l['jump_folder'] = '폴더로 이동:';
$l['archive_messages'] = '비공개 메시지 내보내기';
$l['archive_note'] = '다음 도구를 사용하면 선택한 폴더의 비공개 메시지, 특정 날짜 이후에 보낸 메시지, 읽은 메시지 및 나중에 볼 수 있도록 임시 보관된 메시지를 대량으로 다운로드할 수 있습니다.';
$l['folders'] = '폴더:';
$l['all_folders'] = '모든 폴더';
$l['date_limit'] = '날짜 제한:';
$l['date_limit_older'] = '다음보다 오래된 메시지 내보내기';
$l['date_limit_newer'] = '다음 날짜 이후의 메시지 내보내기';
$l['date_limit_disregard'] = '날짜 무시';
$l['date_limit_days'] = '일';
$l['export_unread'] = '읽지 않은 메시지를 내보내시겠습니까?';
$l['delete_archived'] = '내보낸 메시지를 삭제하시겠습니까?';
$l['delete_archived_note'] = '메시지를 내보낸 후 폴더에서 메시지를 삭제하시겠습니까?';
$l['export_format'] = '내보내기 파일 형식:';
$l['export_format_note'] = '첨부파일을 다운로드할 파일 형식을 선택하세요.';
$l['export_html'] = 'HTML 파일(.html)';
$l['export_txt'] = '텍스트 파일(.txt)';
$l['export_csv'] = '가져오기 가능한 MS Excel 파일(.csv)';
$l['private_messages_for'] = '{1}에 대한 비공개 메시지';
$l['exported_date'] = '내보냄: {1}, {2}';
$l['subject'] = '제목:';
$l['to'] = '에게:';
$l['from'] = '부터:';
$l['sent'] = '보냄:';
$l['export_messages2'] = '메시지 다운로드';
$l['empty_folders'] = '개인 메시지 폴더 비우기';
$l['empty_folders2'] = '빈 폴더';
$l['empty_note'] = '여기서 선택한 폴더의 비공개 메시지를 한 번에 삭제할 수 있습니다. 메시지를 삭제하려는 폴더를 선택하고 \'삭제\'를 클릭하기만 하면 됩니다. 이러한 변경 사항은 취소할 수 없습니다.<br /><strong>참고: 메시지가 삭제되면 복구할 방법이 없습니다.</strong>';
$l['num_messages'] = '메시지 수';
$l['empty_q'] = '빈 폴더?';
$l['keep_unread'] = '읽지 않은 메시지 보관';
$l['pm_folders'] = '개인 메시징 폴더';
$l['existing_folders'] = '기존 폴더';
$l['edit_folder_note'] = '여기에서 현재 개인 메시지 폴더의 이름을 변경할 수 있습니다. 폴더를 삭제하려면 폴더 이름을 삭제하세요. 일부 폴더는 제거할 수 없습니다.<br /><strong>참고: 폴더를 삭제하면 그 안에 있는 모든 메시지도 삭제됩니다.</strong>';
$l['new_folders'] = '새 폴더 추가';
$l['add_folders_note'] = '여기서 추가 메시지 폴더를 생성할 수 있습니다. 텍스트 상자를 모두 채울 필요는 없습니다.';
$l['update_folders'] = '폴더 업데이트';
$l['cannot_be_removed'] = '제거할 수 없습니다.';
$l['reached_warning'] = '경고. 메시지 한도에 도달했습니다.';
$l['reached_warning2'] = '메시지를 받으려면 오래된 메시지를 삭제해야 합니다.';
$l['deny_receipt'] = '[수신거부]';
$l['viewing_pm'] = 'PM 보기:';
$l['reply'] = '회신';
$l['reply_to_all'] = '모두에게 답장';
$l['forward'] = '전달';
$l['compose_pm'] = '비공개 메시지 작성';
$l['compose_to'] = '수신자:';
$l['compose_bcc'] = '숨은참조:';
$l['compose_bcc_show'] = '숨은참조';
$l['compose_bcc_show_title'] = '다른 사용자에게 숨은 참조 메시지를 숨길 수 있는 숨은 참조 입력 상자를 표시합니다.';
$l['separate_names'] = '여러 사용자 이름을 쉼표로 구분하세요.';
$l['max_recipients'] = '<br />이 메시지를 최대 <strong>{1}</strong>명에게 보낼 수 있습니다.';
$l['compose_subject'] = '제목:';
$l['compose_message'] = '메시지:';
$l['compose_options'] = '옵션:';
$l['message_icon'] = '메시지 아이콘:';
$l['options_sig'] = '<strong>서명:</strong> 이 메시지에 서명을 포함하세요.';
$l['options_disable_smilies'] = '<strong>스마일 비활성화:</strong> 이 메시지에 스마일 표정이 표시되지 않도록 합니다.';
$l['options_save_copy'] = '<strong>사본 저장:</strong> 보낸 편지함 폴더에 이 메시지의 사본을 저장합니다.';
$l['options_read_receipt'] = '<strong>읽음 확인 요청:</strong> 이 메시지를 읽었을 때 메시지를 받습니다.';
$l['send_message'] = '문자 보내기';
$l['save_draft'] = '임시 보관함에 저장';
$l['preview'] = '미리보기';
$l['select_buddy'] = '또는 친구를 선택:';
$l['pm_tracking'] = '개인 메시지 추적';
$l['read_messages'] = '읽은 메시지';
$l['unread_messages'] = '읽지 않은 메시지';
$l['q'] = '?';
$l['dateread'] = '읽은 날짜';
$l['stop_tracking'] = '추적 중지';
$l['datesent'] = '보낸 날짜';
$l['cancel'] = '취소';
$l['export_date_sent'] = '날짜';
$l['export_folder'] = '폴더';
$l['export_subject'] = '제목';
$l['export_to'] = '에게';
$l['export_from'] = '부터';
$l['export_message'] = '메시지';
$l['not_sent'] = 'N/A (전송되지 않음)';
$l['at'] = 'at';
$l['nomessages'] = '이 폴더에는 비공개 메시지가 없습니다.';
$l['details'] = '세부사항';
$l['message'] = '메시지';
$l['buddy_list'] = '친구 목록';
$l['multiple_recipients'] = '<em>다중 수신자</em>';
$l['bcc'] = '숨은참조:';
$l['reply_title'] = '이 비공개 메시지에 답장하세요.';
$l['forward_title'] = '이 비공개 메시지를 다른 사용자에게 전달하세요.';
$l['delete_title'] = '이 비공개 메시지 삭제';
$l['you_replied_on'] = '당신은 {1}에 이 메시지에 답장했습니다.';
$l['you_forwarded_on'] = '이 메시지를 {1}에 전달했습니다.';
$l['you_replied'] = '당신은 이 메시지에 응답했습니다. {1}';
$l['you_forwarded'] = '이 메시지를 전달했습니다. {1}';
$l['select_from_buddies'] = '친구 중에서 선택';
$l['no_readmessages'] = '현재 추적 중인 읽은 메시지가 없습니다.';
$l['no_unreadmessages'] = '현재 추적 중인 읽지 않은 메시지가 없습니다.';
$l['stop_tracking_all'] = '모든 메시지 추적 중지';
$l['enter_keywords'] = '키워드 입력';
$l['advanced_search'] = '고급 검색';
$l['search_pms'] = 'PM 검색';
$l['advanced_private_message_search'] = '고급 비공개 메시지 검색';
$l['search_criteria'] = '검색 조건';
$l['keywords'] = '키워드';
$l['search_in_subject'] = '제목으로 검색';
$l['search_in_message'] = '메시지에서 검색';
$l['message_status'] = '메시지 상태';
$l['message_status_new'] = '새로운';
$l['message_status_replied_to'] = '답변한';
$l['message_status_forwarded'] = '전달한';
$l['message_status_read'] = '읽은';
$l['folder'] = '폴더';
$l['search_options'] = '검색 옵션';
$l['sort_by'] = '정렬 기준';
$l['sort_by_subject'] = '정렬 기준: 제목';
$l['sort_by_sender'] = '정렬 기준: 보낸 사람';
$l['sort_by_date'] = '정렬 기준: 날짜';
$l['ascending_order'] = '오름차순 정렬';
$l['descending_order'] = '내림차순 정렬';
$l['search_private_messages'] = '비공개 메시지 검색';
$l['check_all'] = '모두 체크';
$l['error_nopmsarchive'] = '죄송합니다. 지정한 기준과 일치하는 비공개 메시지가 없습니다.';
$l['error_invalidpmfoldername'] = '죄송합니다. 입력한 폴더 이름에 허용되지 않는 문자가 포함되어 있습니다.';
$l['error_emptypmfoldername'] = '죄송합니다. 입력한 폴더 이름에 텍스트가 포함되어 있지 않습니다. 폴더 이름을 입력하거나, 폴더를 삭제하려면 이름을 완전히 비워두세요.';
$l['error_invalidpmrecipient'] = '입력한 수신자가 잘못되었거나 존재하지 않습니다. 돌아가서 올바른 값을 입력하세요.';
$l['error_invalidmovefid'] = '메시지를 이동하려는 폴더가 잘못되었습니다. 돌아가서 다시 시도해 주세요.';
$l['error_invalidpm'] = '잘못된 PM';
$l['error_pmrecipientreachedquota'] = '비공개 메시지 할당량에 도달했기 때문에 {1}에게 비공개 메시지를 보낼 수 없습니다. 메시지가 지워질 때까지 메시지를 보낼 수 없습니다. 이에 대한 이메일이 사용자에게 전송되었습니다. 나중에 메시지를 보내보세요.';
$l['error_recipientpmturnedoff'] = '{1}님은 비공개 메시지를 수신하지 않기로 선택했거나 수신이 허용되지 않을 수 있습니다. 따라서 귀하는 이 사용자에게 비공개 메시지를 보낼 수 없습니다.';
$l['error_pmsturnedoff'] = '현재 귀하의 프로필에는 비공개 메시지가 비활성화되어 있습니다.<br />비공개 메시지 시스템을 사용하려면 이 설정을 활성화해야 합니다.';
$l['error_recipientignoring'] = '죄송합니다. {1}님에게 보내는 비공개 메시지를 처리할 수 없습니다. 이 작업을 수행할 권한이 없습니다.';
$l['error_pm_already_submitted'] = '지난 5시간 이내에 동일한 수신자에게 동일한 비공개 메시지를 이미 제출했습니다.';
$l['error_nopms'] = '이 기능에 액세스하려면 하나 이상의 비공개 메시지가 있어야 합니다.';
$l['error_minsearchlength'] = '하나 이상의 검색어가 최소 길이보다 짧습니다. 최소 검색어 길이는 {1}자입니다.<br /><br />전체 구문을 검색하려는 경우 큰따옴표로 묶으세요. 예를 들어, "빠른 갈색 여우가 게으른 개를 뛰어넘는다".';
$l['error_nosearchresults'] = '죄송합니다. 제공하신 검색어 정보를 사용하여 반환된 결과가 없습니다. 검색어를 다시 정의하고 다시 시도하십시오.';
$l['error_no_search_support'] = '이 데이터베이스 엔진은 검색을 지원하지 않습니다.';
$l['error_nosearchterms'] = '검색어를 입력하지 않으셨습니다. 최소한 검색할 검색어나 사용자 이름을 입력해야 합니다.';
$l['error_searchflooding_1'] = '죄송합니다. 검색은 {1}초마다 한 번만 수행할 수 있습니다. 다시 검색을 시도하기 전에 1초 더 기다려 주십시오.';
$l['error_searchflooding'] = '죄송합니다. 검색은 {1}초마다 한 번만 수행할 수 있습니다. 다시 검색을 시도하기 전에 {2}초 더 기다리십시오.';
$l['error_invalidsearch'] = '잘못된 검색이 지정되었습니다. 돌아가서 다시 시도해 주세요.';
$l['redirect_pmsaved'] = '비공개 메시지가 임시 보관함 폴더에 저장되었습니다.';
$l['redirect_pmstrackingstopped'] = '선택한 PM의 추적이 중지되었습니다.';
$l['redirect_pmstrackingcanceled'] = '선택한 읽지 않은 PM이 수신자의 받은 편지함에서 삭제되었습니다.';
$l['redirect_allpmstrackingstopped'] = '모든 읽기 PM 추적이 중지되었습니다.';
$l['redirect_pmsmoved'] = '선택한 비공개 메시지가 이동되었습니다.';
$l['redirect_pmsdeleted'] = '선택한 비공개 메시지가 삭제되었습니다.';
$l['redirect_pmsent'] = '감사합니다. 귀하의 비공개 메시지가 성공적으로 전송되었습니다.<br />이제 비공개 메시지 받은 편지함으로 돌아가게 됩니다.';
$l['redirect_pmfoldersupdated'] = '감사합니다. 비공개 메시지 폴더가 성공적으로 업데이트되었습니다.<br />이제 비공개 메시지 받은 편지함으로 돌아가게 됩니다.';
$l['redirect_pmfoldersemptied'] = '선택한 개인 메시지 폴더가 성공적으로 비워졌습니다.<br />이제 개인 메시지 받은 편지함으로 돌아갑니다.';
$l['redirect_searchresults'] = '감사합니다. 검색이 제출되었으며 이제 결과 목록으로 이동됩니다.';
$l['quick_reply'] = '빠른 답변';
$l['message_note'] = '여기에 이 ​​메시지에 대한 답장을 입력하세요.';
$l['send_reply'] = '답장 보내기';
$l['quickreply_signature'] = '서명';
$l['quickreply_disable_smilies'] = '스마일리 비활성화';
$l['quickreply_save_copy'] = '복사본을 저장';
$l['quickreply_read_receipt'] = '읽음 확인 요청';
