<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Mon, 01 Jul 2024 02:52:19 +0000
// --------------------------------------------------------------------------------

$l['redirect_threadrated'] = '감사합니다. 글타래가 성공적으로 평가되었습니다. 이제 글타래로 돌아갑니다.';
$l['error_invalidrating'] = '이 글타래에 대해 잘못된 등급을 선택했습니다. 돌아가서 다시 시도해 주세요.';
$l['error_alreadyratedthread'] = '죄송합니다. 당신은 이미 이 글타래를 평가하셨습니다.';
$l['error_cannotrateownthread'] = '죄송합니다. 자신의 글타래를 평가할 수 없습니다.';
$l['thread_doesnt_exist'] = '존재하지 않는 글타래는 평가할 수 없습니다.';
$l['rating_votes_average'] = '{1} 투표 - 평균 5점 만점에 {2}점';
$l['one_star'] = '별 5개 중 1개';
$l['two_stars'] = '별 5개 중 2개';
$l['three_stars'] = '별 5개 중 3개';
$l['four_stars'] = '별 5개 중 4개';
$l['five_stars'] = '별 5개 중 5개';
$l['rating_added'] = '당신의 평가가 추가되었습니다!';
