<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Mon, 01 Jul 2024 02:49:39 +0000
// --------------------------------------------------------------------------------

$l['report_reason'] = '신고 이유:';
$l['report_to_mod'] = '운영자에게 콘텐츠 신고';
$l['close_window'] = '창 닫기';
$l['report_content'] = '신고 내용';
$l['report_reason_post'] = '게시물 신고';
$l['report_reason_profile'] = '프로필 신고';
$l['report_reason_reputation'] = '평판 보고';
$l['report_reason_rules'] = '포럼 규칙 위반';
$l['report_reason_bad'] = '부적절한 콘텐츠';
$l['report_reason_spam'] = '스팸 콘텐츠';
$l['report_reason_wrong'] = '잘못된 포럼';
$l['report_reason_other'] = '기타';
$l['success_report_voted'] = '해당 콘텐츠를 신고해 주셔서 감사합니다.<br />포럼 팀원이 곧 신고 내용을 확인할 것입니다.';
$l['error_report_length'] = '신고 사유를 자세히 기재해 주세요.';
$l['error_invalid_report'] = '이 {1}은(는) 존재하지 않거나 보고가 허용되지 않습니다.';
$l['error_invalid_report_reason'] = '선택한 이유가 잘못되었습니다.';
$l['error_comment_required'] = '선택한 사유에 대한 추가 설명이 필요합니다.';
$l['error_report_duplicate'] = '이 콘텐츠는 이미 다른 회원이 신고했습니다.<br />아래에서 이 콘텐츠를 신고할 수도 있습니다.';
$l['report_reason_other_description'] = '이 콘텐츠를 신고하는 이유에 대한 추가 정보를 제공해 주세요.';
