<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Mon, 01 Jul 2024 02:47:19 +0000
// --------------------------------------------------------------------------------

$l['nav_reputation'] = '평판 보고서';
$l['nav_profile'] = '{1}의 프로필';
$l['reputation_disabled'] = '평판 시스템은 관리자가 비활성화했기 때문에 사용할 수 없습니다.';
$l['reputation'] = '평판';
$l['error'] = '오류';
$l['add_no_uid'] = '평판을 부여할 사용자를 지정하지 않았습니다.';
$l['add_no_permission'] = '사용자에게 평판 등급을 부여할 권한이 없습니다.';
$l['add_disabled'] = '이 사용자 그룹의 사용자에게는 평판을 추가할 수 없습니다.';
$l['add_yours'] = '자신의 평판을 높일 수는 없습니다.';
$l['add_invalidpower'] = '목록에서 잘못된 등급을 선택했습니다.';
$l['add_maxperday'] = '귀하는 이미 오늘 허용된 만큼의 평판 등급을 부여했습니다.';
$l['add_maxperuser'] = '귀하는 이미 이 사용자에게 오늘 가능한 한 많은 평판 등급을 부여했습니다.';
$l['add_maxperthread'] = '귀하는 이미 이 사용자에게 오늘 가능한 한 많은 평판 등급(한 글타래에서)을 부여했습니다.';
$l['add_no_comment'] = '이 사용자에게 평판 등급을 부여하려면 최소 {1}자의 설명을 입력해야 합니다.';
$l['add_toolong'] = '{1}자 이하의 이유를 입력해야 합니다.';
$l['add_negative_disabled'] = '관리자가 부정적인 평판을 비활성화했습니다.';
$l['add_neutral_disabled'] = '관리자가 중립 평판을 비활성화했습니다.';
$l['add_positive_disabled'] = '관리자가 긍정적인 평판을 비활성화했습니다.';
$l['add_all_rep_disabled'] = '관리자가 모든 유형의 평판을 비활성화했습니다. 이 사용자를 평가할 수 없습니다.';
$l['reputation_report'] = '{1}에 대한 평판 보고서';
$l['reputation_members'] = '회원으로부터의 평판:';
$l['reputation_posts'] = '게시물의 평판:';
$l['summary'] = '요약';
$l['total_reputation'] = '총 평판';
$l['post_reputation'] = '평판 게시';
$l['positive_count'] = '긍정적인 점';
$l['neutral_count'] = '중립';
$l['negative_count'] = '네거티브';
$l['last_week'] = '지난주';
$l['last_month'] = '지난 달';
$l['last_6months'] = '지난 6개월';
$l['all_time'] = '모든 시간';
$l['comments'] = '코멘트';
$l['close_window'] = '창 닫기';
$l['add_reputation_vote'] = '{1}에 대한 평판 등급 추가';
$l['add_reputation_to_post'] = '이 평판은 {1}님의 게시물에 대한 것입니다.<br />';
$l['neg_rep_disabled'] = '<span class="smalltext">* - <em>부정적 평판은 현재 비활성화되어 있습니다</em></span>';
$l['pos_rep_disabled'] = '<span class="smalltext">* - <em>현재 긍정적인 평판이 비활성화되어 있습니다</em></span>';
$l['neu_rep_disabled'] = '<span class="smalltext">* - <em>현재 중립 평판이 비활성화되어 있습니다</em></span>';
$l['no_comment_needed'] = '귀하는 프로필에 링크된 이 사용자의 게시물로 인해 평판을 추가하고 있습니다. 댓글은 필수사항은 아니지만, 남기고 싶으신 분은 아래에 적어주세요.<br />';
$l['no_comment'] = '[코멘트 없음]';
$l['vote_added'] = '등급이 추가됨';
$l['vote_updated'] = '등급이 업데이트됨';
$l['vote_deleted'] = '평가가 삭제';
$l['vote_added_message'] = '이 사용자에 대한 귀하의 평판 등급이 성공적으로 추가되었습니다.';
$l['vote_updated_message'] = '이 사용자에 대한 귀하의 평판 등급이 성공적으로 업데이트되었습니다.';
$l['vote_deleted_message'] = '이 사용자의 평판 등급이 삭제되었습니다.';
$l['update_reputation_vote'] = '{1}에 대한 평판 등급 업데이트';
$l['positive'] = '긍정적인';
$l['negative'] = '부정적인';
$l['neutral'] = '중립적';
$l['user_comments'] = '{1}에 대한 귀하의 의견:';
$l['add_vote'] = '평가 추가';
$l['update_vote'] = '업데이트 등급';
$l['delete_vote'] = '삭제';
$l['report_vote'] = '보고서';
$l['power_positive'] = '긍정 ({1})';
$l['power_neutral'] = '중립적';
$l['power_negative'] = '부정({1})';
$l['show_all'] = '표시: 모든 투표';
$l['show_positive'] = '표시: 긍정적인 평가';
$l['show_neutral'] = '표시: 중립 등급';
$l['show_negative'] = '표시: 부정적인 평가';
$l['sort_updated'] = '정렬 기준: 마지막 업데이트';
$l['sort_username'] = '정렬 기준: 사용자 이름';
$l['last_updated'] = '마지막 업데이트: {1}';
$l['postrep_given'] = '<a href="{1}">{2}님의 게시물</a> {3}<br />에 부여된 평가';
$l['postrep_given_nolink'] = '{1}님의 게시물에 부여된 평가<br />';
$l['postrep_given_thread'] = 'in <a href="{1}">{2}</a>';
$l['no_reputation_votes'] = '이 사용자는 현재 아래 지정된 기준에 따른 평판 등급이 없습니다.';
$l['delete_reputation_confirm'] = '이 평판 등급을 삭제하시겠습니까?';
$l['delete_reputation_log'] = '{1}(UID: {2})의 평판 등급이 삭제되었습니다.';
$l['reputations_disabled_group'] = '이 사용자 그룹의 사용자에 대해서는 평판 시스템이 비활성화됩니다.';
$l['rate_user'] = '사용자 평가';
