<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 00:25:04 +0000
// --------------------------------------------------------------------------------

$l['nav_search'] = '검색';
$l['nav_results'] = '결과';
$l['pages'] = '페이지:';
$l['pages_last'] = '마지막';
$l['search'] = '검색';
$l['search_keyword'] = '키워드 검색';
$l['search_username'] = '사용자 이름으로 검색';
$l['search_entire_post'] = '전체 게시물 검색';
$l['search_titles_only'] = '제목만 검색';
$l['match_username'] = '정확한 사용자 이름과 일치';
$l['search_forums'] = '포럼에서 검색';
$l['search_all_forums'] = '모든 공개 포럼 검색';
$l['search_options'] = '검색 옵션';
$l['threads_at_least'] = '최소한의 글타래 찾기';
$l['threads_at_most'] = '최대 글타래 찾기';
$l['find_anydate'] = '게시 날짜에 상관없이 게시물 찾기';
$l['find_yesterday'] = '어제 게시물 찾기';
$l['find_lastweek'] = '일주일 전 게시물 찾기';
$l['find_2weeks'] = '2주 전 게시물 찾기';
$l['find_month'] = '한 달 전 게시물 찾기';
$l['find_3months'] = '3개월 전 게시물 찾기';
$l['find_6months'] = '6개월 전 게시물 찾기';
$l['find_year'] = '1년 전 게시물 찾기';
$l['and_newer'] = '그리고 최신';
$l['and_older'] = '그리고 오래된';
$l['sorting_options'] = '정렬 옵션';
$l['sort_lastpost'] = '마지막 게시 날짜를 기준으로 결과 정렬';
$l['sort_author'] = '작성자별로 결과 정렬';
$l['sort_forum'] = '포럼별로 결과 정렬';
$l['sort_views'] = '조회수를 기준으로 결과 정렬';
$l['sort_replies'] = '응답 수를 기준으로 결과 정렬';
$l['sort_in'] = 'in';
$l['sort_asc'] = '오름차순';
$l['sort_desc'] = '내림차순';
$l['sort_order'] = '순서로';
$l['asc'] = '오름차순';
$l['desc'] = '내림차순';
$l['display_options'] = '디스플레이 옵션';
$l['show_results_as'] = '결과 표시 형식';
$l['show_results_threads'] = '글타래';
$l['show_results_posts'] = '게시물';
$l['search_results'] = '검색 결과';
$l['post'] = '게시글';
$l['author'] = '작성자';
$l['forum'] = '포럼';
$l['replies'] = '답글';
$l['views'] = '조회수';
$l['posted'] = '게시됨';
$l['thread'] = '글타래';
$l['lastpost'] = '마지막 게시물';
$l['post_thread'] = '글타래:';
$l['post_subject'] = '게시글:';
$l['replies2'] = '답글';
$l['selectall'] = '추가 결과를 모두 선택하시겠습니까?';
$l['any_prefix'] = '접두사가 있는 글타래 찾기';
$l['no_prefix'] = '접두사 없음';
$l['inline_thread_moderation'] = '인라인 글타래 조정:';
$l['close_threads'] = '글타래 닫기';
$l['open_threads'] = '글타래 열기';
$l['stick_threads'] = '글타래 고정';
$l['unstick_threads'] = '글타래 고정해제';
$l['soft_delete_threads'] = '글타래 일시 삭제';
$l['restore_threads'] = '글타래 복원';
$l['delete_threads'] = '글타래를 영구적으로 삭제';
$l['move_threads'] = '글타래 이동/복사';
$l['approve_threads'] = '글타래 승인';
$l['unapprove_threads'] = '글타래 승인 취소';
$l['inline_soft_delete_posts'] = '일시 삭제 게시물';
$l['inline_restore_posts'] = '게시물 복원';
$l['inline_delete_posts'] = '게시물을 영구적으로 삭제';
$l['inline_merge_posts'] = '게시물 병합';
$l['inline_split_posts'] = '게시물 분할';
$l['inline_move_posts'] = '게시물 이동';
$l['inline_approve_posts'] = '게시물 승인';
$l['inline_unapprove_posts'] = '게시물 승인 취소';
$l['inline_post_moderation'] = '인라인 게시물 조정:';
$l['inline_go'] = '가기';
$l['clear'] = '지우기';
$l['icon_dot'] = '귀하가 작성한 게시물이 포함되어 있습니다.';
$l['icon_no_new'] = '새 게시물이 없음';
$l['icon_new'] = '새 게시물.';
$l['icon_hot'] = '핫 글타래';
$l['icon_close'] = '닫힌 글타래.';
$l['attachment_count'] = '이 글타래에는 첨부 파일 1개가 포함되어 있습니다.';
$l['attachment_count_multiple'] = '이 글타래에는 {1}개의 첨부 파일이 포함되어 있습니다.';
$l['goto_first_unread'] = '읽지 않은 첫 번째 게시물로 이동';
$l['page_selected'] = '이 페이지의 모든 <strong>{1}</strong> 결과가 선택되었습니다.';
$l['all_selected'] = '이 검색의 모든 <strong>{1}</strong> 결과가 선택되었습니다.';
$l['select_all'] = '이 검색에서 모든 <strong>{1}</strong> 결과를 ​​선택하세요.';
$l['clear_selection'] = '명확한 선택.';
$l['results'] = '결과';
$l['mod_options'] = '운영자 옵션';
$l['display_all'] = '모두 표시';
$l['display_only_approved'] = '디스플레이만 승인됨';
$l['display_only_unapproved'] = '승인되지 않은 것만 표시';
$l['display_only_softdeleted'] = '일시 삭제된 항목만 표시';
$l['redirect_searchresults'] = '감사합니다. 검색이 제출되었으며 이제 결과 목록으로 이동됩니다.';
$l['error_minsearchlength'] = '하나 이상의 검색어가 최소 길이보다 짧습니다. 최소 검색어 길이는 {1}자입니다.<br /><br />전체 구문을 검색하려는 경우 큰따옴표로 묶으세요. 예를 들어, "빠른 갈색 여우가 게으른 개를 뛰어넘는다".';
$l['error_nosearchresults'] = '죄송합니다. 제공하신 검색어 정보를 사용하여 반환된 결과가 없습니다. 검색어를 다시 정의하고 다시 시도하십시오.';
$l['error_no_search_support'] = '이 데이터베이스 엔진은 검색을 지원하지 않습니다.';
$l['error_nosearchterms'] = '검색어를 입력하지 않으셨습니다. 최소한 검색할 검색어나 사용자 이름을 입력해야 합니다.';
$l['error_searchflooding_1'] = '죄송합니다. 검색은 {1}초마다 한 번만 수행할 수 있습니다. 다시 검색을 시도하기 전에 1초 더 기다려 주십시오.';
$l['error_searchflooding'] = '죄송합니다. 검색은 {1}초마다 한 번만 수행할 수 있습니다. 다시 검색을 시도하기 전에 {2}초 더 기다리십시오.';
$l['error_invalidsearch'] = '잘못된 검색이 지정되었습니다. 돌아가서 다시 시도해 주세요.';
