<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Sat, 29 Jun 2024 05:24:16 +0000
// --------------------------------------------------------------------------------

$l['nav_sendthread'] = '친구에게 글타래 보내기';
$l['send_thread'] = '친구에게 보내기';
$l['recipient'] = '받는 사람:';
$l['recipient_note'] = '여기에 친구의 이메일 주소를 입력하세요.';
$l['subject'] = '제목:';
$l['message'] = '메시지:';
$l['error_nosubject'] = '글타래를 보내려면 메시지 제목을 입력해야 합니다.';
$l['error_nomessage'] = '이 글타래를 친구에게 보내기 전에 메시지를 입력해야 합니다.';
