<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 06:35:58 +0000
// --------------------------------------------------------------------------------

$l['delete_poll'] = '설문조사 삭제';
$l['open_thread'] = '글타래 열기';
$l['close_thread'] = '글타래 닫기';
$l['stick_thread'] = '글타래 고정';
$l['unstick_thread'] = '글타래 고정해제';
$l['author'] = '작성자';
$l['message'] = '메시지';
$l['threaded'] = '글타래 모드';
$l['linear'] = 'Linear Mode';
$l['next_oldest'] = '다음으로 오래된 것';
$l['next_newest'] = '다음 최신';
$l['view_printable'] = '인쇄 가능한 버전 보기';
$l['send_thread'] = '이 글타래를 친구에게 보내기';
$l['subscribe_thread'] = '이 글타래를 구독';
$l['unsubscribe_thread'] = '이 글타래를 구독해제';
$l['add_poll_to_thread'] = '이 글타래에 설문조사 추가';
$l['moderation_options'] = '운영자 옵션:';
$l['select_a_tool'] = '도구 선택';
$l['delayed_moderation'] = '지연된 조정';
$l['thread_notes'] = '글타래 메모 편집/보기';
$l['approve_thread'] = '글타래 승인';
$l['unapprove_thread'] = '글타래 승인 취소';
$l['soft_delete_thread'] = '소프트 삭제 글타래';
$l['restore_thread'] = '글타래 복원';
$l['delete_thread'] = '글타래를 영구적으로 삭제';
$l['delete_posts'] = '선택한 게시물 삭제';
$l['move_thread'] = '글타래 이동/복사';
$l['split_thread'] = '글타래 분할';
$l['merge_threads'] = '글타래 병합';
$l['remove_redirects'] = '리디렉션 제거';
$l['remove_subscriptions'] = '모든 구독 제거';
$l['poll'] = '투표:';
$l['show_results'] = '결과 보기';
$l['edit_poll'] = '설문조사 수정';
$l['public_note'] = '<b>참고:</b> 이것은 공개 설문조사이므로 다른 사용자가 귀하가 투표한 내용을 볼 수 있습니다.';
$l['total'] = '합계';
$l['vote'] = '투표!';
$l['total_votes'] = '{1} 투표';
$l['you_voted'] = '* 이 항목에 투표하셨습니다.';
$l['poll_closed'] = '이 설문조사는 종료되었습니다.';
$l['poll_closes'] = '이 설문조사는 다음 날짜에 종료됩니다: {1}';
$l['already_voted'] = '당신은 이미 이 설문조사에 투표하셨습니다.';
$l['no_voting_permission'] = '이 설문조사에 투표할 권한이 없습니다.';
$l['undo_vote'] = '투표 취소';
$l['quick_reply'] = '빠른 답글';
$l['message_note'] = '여기에 이 ​​메시지에 대한 답장을 입력하세요.';
$l['signature'] = '서명';
$l['email_notify'] = '이메일 알림';
$l['disable_smilies'] = '스마일 비활성화';
$l['post_reply'] = '답글 게시';
$l['post_reply_img'] = '답글 게시';
$l['new_reply'] = '새 답글';
$l['search_button'] = '검색색';
$l['post_thread'] = '글타래 게시';
$l['preview_post'] = '게시물 미리보기';
$l['rating_average'] = '{1} 투표 - {2} 평균';
$l['rate_thread'] = '이 글타래 평가:';
$l['thread_rating'] = '글타래 등급:';
$l['similar_threads'] = '관련 글타래&hellip;';
$l['thread'] = '글타래';
$l['replies'] = '답글';
$l['views'] = '조회';
$l['lastpost'] = '마지막 게시물';
$l['messages_in_thread'] = '이 글타래의 메시지';
$l['users_browsing_thread'] = '이 글타래를 탐색하는 사용자:';
$l['users_browsing_thread_guests'] = '{1} 손님';
$l['users_browsing_thread_invis'] = '{1} 비공개 사용자';
$l['users_browsing_thread_reading'] = '읽기&hellip;';
$l['inline_soft_delete_posts'] = '일시 삭제 게시물';
$l['inline_restore_posts'] = '게시물 복원';
$l['inline_delete_posts'] = '게시물을 영구적으로 삭제';
$l['inline_merge_posts'] = '게시물 병합';
$l['inline_split_posts'] = '게시물 분할';
$l['inline_move_posts'] = '게시물 이동';
$l['inline_approve_posts'] = '게시물 승인';
$l['inline_unapprove_posts'] = '게시물 승인 취소';
$l['inline_post_moderation'] = '인라인 게시물 조정:';
$l['inline_no_tool_selected'] = '검토 작업을 수행하려면 도구를 선택하세요.';
$l['inline_no_post_selected'] = '중재 작업을 수행하려면 하나 이상의 게시물을 선택해야 합니다.';
$l['inline_go'] = 'Go';
$l['clear'] = 'Clear';
$l['thread_closed'] = '글타래 마감됨';
$l['no_subject'] = '제목 없음';
$l['error_nonextnewest'] = '이전에 본 글타래보다 최신 글타래가 없습니다.';
$l['error_nonextoldest'] = '이전에 본 것보다 오래된 글타래가 없습니다.';
$l['quickreply_multiquote_selected'] = '인용할 게시물을 하나 이상 선택했습니다.';
$l['quickreply_multiquote_now'] = '지금 이 게시물을 인용';
$l['or'] = 'or';
$l['quickreply_multiquote_deselect'] = '선택 취소';
$l['search_thread'] = '글타래 검색';
$l['enter_keywords'] = '키워드 입력';
$l['view_thread_notes'] = '글타래 메모';
$l['view_all_notes'] = '모든 노트 보기';
$l['save_changes'] = '변경 사항 저장';
$l['cancel_edit'] = '편집 취소';
$l['quick_edit_update_error'] = '답글을 수정하는 중에 오류가 발생했습니다.';
$l['quick_reply_post_error'] = '답글을 게시하는 중에 오류가 발생했습니다.';
$l['quick_delete_error'] = '답글을 삭제하는 중에 오류가 발생했습니다.';
$l['quick_delete_success'] = '게시물이 성공적으로 삭제되었습니다.';
$l['quick_delete_thread_success'] = '글타래가 성공적으로 삭제되었습니다.';
$l['quick_restore_error'] = '답글을 복원하는 중에 오류가 발생했습니다.';
$l['quick_restore_success'] = '게시물이 성공적으로 복원되었습니다.';
$l['post_deleted_error'] = '삭제된 게시물에는 이 작업을 수행할 수 없습니다.';
