<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 00:27:23 +0000
// --------------------------------------------------------------------------------

$l['nav_showteam'] = '포럼 팀';
$l['forum_team'] = '포럼 팀';
$l['moderators'] = '운영자';
$l['username'] = '사용자 이름';
$l['lastvisit'] = '마지막 방문';
$l['email'] = '이메일';
$l['pm'] = '오후';
$l['mod_forums'] = '포럼';
$l['mod_groups'] = '그룹';
$l['online'] = '온라인';
$l['offline'] = '오프라인';
$l['away'] = '자리비움';
$l['group_leaders'] = '그룹 리더';
$l['group_members'] = '회원';
$l['no_members'] = '이 그룹에는 회원이 없습니다.';
$l['showteam_disabled'] = '관리자가 포럼 팀 목록 기능을 비활성화했습니다.';
$l['error_noteamstoshow'] = '표시할 포럼 회원이 없습니다.';
