<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Mon, 01 Jul 2024 00:15:21 +0000
// --------------------------------------------------------------------------------

$l['nav_stats'] = '보드 통계';
$l['stats_disabled'] = '관리자가 통계 페이지를 비활성화했기 때문에 통계 페이지를 볼 수 없습니다.';
$l['board_stats'] = '보드 통계';
$l['none'] = '없음';
$l['totals'] = '합계';
$l['averages'] = '평균';
$l['posts'] = '게시물:';
$l['threads'] = '글타래:';
$l['members'] = '회원:';
$l['ppd'] = '일일 게시물 수:';
$l['tpd'] = '일일 글타래:';
$l['mpd'] = '일일 회원 수:';
$l['ppm'] = '회원별 게시물 수:';
$l['tpm'] = '멤버당 글타래 수:';
$l['rpt'] = '글타래당 응답:';
$l['no_posts'] = '없음';
$l['general'] = '일반';
$l['newest_member'] = '신규 회원:';
$l['members_posted'] = '게시한 회원:';
$l['todays_top_poster'] = '오늘의 인기 포스터: <b>{1}</b>(<b>{2}</b> 게시물)';
$l['popular_forum'] = '가장 인기 있는 포럼: <b>{1}</b>(<b>{2}</b> 게시물, <b>{3}</b> 스레드)';
$l['most_popular'] = '가장 인기 있는 &hellip;';
$l['most_replied_threads'] = '가장 많이 응답된 글타래';
$l['most_viewed_threads'] = '가장 많이 본 글타래';
$l['not_enough_info_stats'] = '죄송합니다. 이 게시판에는 통계를 생성할 정보가 충분하지 않습니다. 통계를 생성하려면 이 보드에 최소한 1명의 구성원과 1개의 글타래가 포함되어 있어야 합니다.';
$l['replies'] = '답글';
$l['views'] = '조회수';
$l['top_referrer'] = '상위 추천자: <strong>{1}</strong> (<strong>{2}</strong> 추천)';
