<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Mon, 01 Jul 2024 05:31:11 +0000
// --------------------------------------------------------------------------------

$l['ucp_nav_width'] = '180';
$l['ucp_nav_menu'] = '메뉴';
$l['ucp_nav_messenger'] = '메신저';
$l['ucp_nav_compose'] = '새 메시지 작성';
$l['ucp_nav_tracking'] = '추적';
$l['ucp_nav_edit_folders'] = '폴더 편집';
$l['ucp_nav_profile'] = '내 프로필';
$l['ucp_nav_edit_profile'] = '프로필 수정';
$l['ucp_nav_edit_options'] = '편집 옵션';
$l['ucp_nav_change_email'] = '이메일 변경';
$l['ucp_nav_change_pass'] = '비밀번호 변경';
$l['ucp_nav_change_username'] = '사용자 이름 변경';
$l['ucp_nav_edit_sig'] = '서명 변경';
$l['ucp_nav_change_avatar'] = '아바타 변경';
$l['ucp_nav_misc'] = 'Miscellaneous';
$l['ucp_nav_editlists'] = '친구/무시 목록';
$l['ucp_nav_favorite_threads'] = '즐겨찾는 글타래';
$l['ucp_nav_subscribed_threads'] = '구독한 글타래';
$l['ucp_nav_forum_subscriptions'] = '포럼 구독';
$l['ucp_nav_drafts'] = '저장된 임시글';
$l['ucp_nav_drafts_active'] = '<strong>저장된 임시글({1})</strong>';
$l['ucp_nav_notepad'] = '개인용 메모장';
$l['ucp_nav_view_profile'] = '프로필보기';
$l['ucp_nav_home'] = '사용자 CP 홈';
$l['ucp_nav_usergroups'] = '그룹 멤버십';
$l['ucp_nav_attachments'] = '첨부파일 관리';
