<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Sat, 29 Jun 2024 04:06:15 +0000
// --------------------------------------------------------------------------------

$l['nav_profile'] = '{1}의 프로필';
$l['nav_warning_log'] = 'Warning Log';
$l['nav_add_warning'] = '사용자에게 경고';
$l['nav_view_warning'] = '경고 세부정보';
$l['warning_for_post'] = '&hellip; Post:';
$l['already_expired'] = '만료됨';
$l['details_username'] = '사용자 이름';
$l['warning_active'] = '활동적인';
$l['warning_revoked'] = '취소됨';
$l['warning_log'] = '경고 로그';
$l['warning'] = '경고';
$l['issued_by'] = 'Issued By';
$l['date_issued'] = 'Date Issued';
$l['expiry_date'] = '만료';
$l['active_warnings'] = '활성화된 경고';
$l['expired_warnings'] = '만료된 경고';
$l['warning_points'] = '({1}포인트)';
$l['no_warnings'] = '이 사용자는 경고를 받지 못했거나 모두 제거되었습니다.';
$l['warn_user'] = '사용자에게 경고';
$l['post'] = '게시글:';
$l['warning_note'] = '관리자 참고사항:';
$l['details_warning_note'] = '관리 메모';
$l['warning_type'] = '경고 유형:';
$l['custom'] = '고객의 이유';
$l['reason'] = '이유:';
$l['points'] = '포인트:';
$l['details_reason'] = '이유';
$l['warn_user_desc'] = '여기에서 해당 사용자가 하나 이상의 규칙을 위반한 경우 경고 수준을 높일 수 있습니다.';
$l['send_pm'] = '사용자에게 알림:';
$l['send_user_warning_pm'] = '이 사용자에게 이 경고를 알리는 비공개 메시지를 보냅니다.';
$l['send_pm_subject'] = '제목:';
$l['warning_pm_subject'] = '경고를 받았습니다.';
$l['send_pm_message'] = '메시지:';
$l['warning_pm_message'] = '친애하는 {1}님

귀하는 {2} 직원으로부터 경고를 받았습니다.
--

--';
$l['send_pm_options'] = '옵션:';
$l['send_pm_options_anonymous'] = '<strong>익명 PM</strong>: 익명 사용자로 이 비공개 메시지를 보냅니다.';
$l['expiration_never'] = 'permanently';
$l['expiration_hours'] = 'hours';
$l['expiration_days'] = 'days';
$l['expiration_weeks'] = 'weeks';
$l['expiration_months'] = 'months';
$l['redirect_warned_banned'] = '<br /><br />사용자가 {1} 그룹 {2}로도 이동되었습니다.';
$l['redirect_warned_suspended'] = '<br /><br />이 사용자의 게시 권한이 정지되었습니다{1}.';
$l['redirect_warned_moderate'] = '<br /><br />이제 이 사용자의 모든 게시물이 검토됩니다({1}).';
$l['redirect_warned_pmerror'] = '<br /><br />PM이 발송되지 않았으니 주의하시기 바랍니다.';
$l['redirect_warned'] = '{1}의 경고 수준이 {2}%로 높아졌습니다.{3}<br /><br />이제 원래 있던 곳으로 돌아갑니다.';
$l['error_warning_system_disabled'] = '경고 시스템은 게시판 관리자에 의해 비활성화되어 있으므로 사용할 수 없습니다.';
$l['error_cant_warn_group'] = '이 그룹의 사용자에게 경고할 권한이 없습니다.';
$l['error_invalid_user'] = '선택한 사용자가 존재하지 않습니다.';
$l['details'] = '세부내용';
$l['view'] = '조회회';
$l['current_warning_level'] = '현재 경고 수준: <strong>{1}%</strong> ({2}/{3})';
$l['warning_details'] = '경고 세부정보';
$l['revoke_warning'] = '이 경고를 취소';
$l['revoke_warning_desc'] = '이 경고를 취소하려면 아래에 이유를 입력하세요. 이 경고로 인해 부과된 금지나 정지는 제거되지 않습니다.';
$l['warning_is_revoked'] = '이 경고는 취소되었습니다.';
$l['revoked_by'] = '취소자';
$l['date_revoked'] = '취소된 날짜';
$l['warning_already_revoked'] = '이 경고는 이미 취소되었습니다.';
$l['no_revoke_reason'] = '이 경고를 취소하려는 이유를 입력하지 않았습니다.';
$l['redirect_warning_revoked'] = '이 경고는 성공적으로 취소되었으며 사용자 경고 포인트가 감소했습니다.<br /><br />이제 경고 메시지로 돌아갑니다.';
$l['result'] = '결과:';
$l['result_banned'] = '사용자는 금지된 그룹({1}) {2}으로 이동됩니다.';
$l['result_suspended'] = '게시 권한이 정지됩니다. {1}';
$l['result_moderated'] = '게시물이 검토됩니다. {1}';
$l['result_period'] = 'for {1} {2}';
$l['result_period_perm'] = 'permanently';
$l['hour_or_hours'] = 'Hour(s)';
$l['day_or_days'] = 'Day(s)';
$l['week_or_weeks'] = 'Week(s)';
$l['month_or_months'] = 'Month(s)';
$l['expires'] = '만료:';
$l['new_warning_level'] = '새로운 경고 수준:';
$l['error_cant_warn_user'] = '이 사용자에게 경고할 권한이 없습니다.';
$l['existing_post_warnings'] = '이 게시물에 대한 기존 경고';
