<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Sat, 29 Jun 2024 02:55:29 +0000
// --------------------------------------------------------------------------------

$l['no_new_subject'] = '새로운 제목을 입력하지 않으셨습니다.';
$l['post_moderation'] = '당신의 게시물은 이제 검토 중입니다.';
$l['thread_moderation'] = '당신의 글타래는 현재 검토 중입니다.';
$l['post_doesnt_exist'] = '지정한 게시물이 존재하지 않습니다.';
$l['thread_doesnt_exist'] = '지정된 글타래가 존재하지 않습니다.';
$l['thread_closed_edit_subjects'] = '이 글타래는 닫혀 있으며 제목을 편집할 수 없습니다.';
$l['no_permission_edit_subject'] = '이 글타래 제목를 편집할 권한이 없습니다.';
$l['thread_closed_edit_message'] = '이 글타래는 닫혀 있으며 그 안의 메시지를 편집할 수 없습니다.';
$l['no_permission_edit_post'] = '이 메시지를 편집할 권한이 없습니다.';
$l['edit_time_limit'] = '메시지가 게시된 후 {1}분 동안만 메시지를 편집할 수 있습니다.';
$l['postbit_edited'] = '이 게시물은 마지막으로 수정됨: {1} 에 의해';
$l['postbit_editreason'] = '편집 이유';
$l['save_changes'] = '변경 사항 저장';
$l['cancel_edit'] = '편집 취소';
$l['answer_valid_not_exists'] = '답변하려는 질문이 존재하지 않습니다.';
$l['captcha_not_exists'] = '새로고침하려는 이미지 확인 이미지가 존재하지 않습니다.';
$l['captcha_valid_not_exists'] = '확인하려는 이미지 인증 이미지가 존재하지 않는 것 같습니다.';
$l['captcha_does_not_match'] = '입력한 이미지 인증 코드가 올바르지 않습니다. 이미지에 표시된 대로 코드를 정확하게 입력하세요.';
$l['captcha_matches'] = '입력하신 이미지 인증코드가 정확합니다.';
$l['answer_does_not_match'] = '입력하신 답변이 올바르지 않습니다.';
$l['banned_username'] = '입력한 사용자 이름은 관리자가 허용하지 않았습니다.';
$l['banned_characters_username'] = '사용자 이름에 잘못된 문자가 하나 이상 포함되어 있습니다.';
$l['complex_password_fails'] = '비밀번호에는 대문자, 소문자, 숫자가 필요합니다.';
$l['username_taken'] = '{1}은(는) 이미 다른 회원에 의해 등록되었습니다';
$l['username_available'] = '{1}을(를) 사용할 수 있습니다';
$l['invalid_username'] = '{1}은(는) 등록된 회원의 사용자 이름이 아닙니다.';
$l['valid_username'] = '{1}은(는) 유효한 리퍼러입니다.';
$l['buddylist_error'] = '친구 목록에 친구가 없는 것 같습니다. 이것을 사용하기 전에 몇 가지를 추가하십시오.';
$l['close'] = '닫기';
$l['select_buddies'] = '친구 선택';
$l['select_buddies_desc'] = '한 명 이상의 친구를 수신자로 추가하려면 아래에서 선택하고 확인을 클릭하세요.';
$l['selected_recipients'] = '선택된 수신자';
$l['ok'] = '확인';
$l['cancel'] = '취소';
$l['online'] = '온라인';
$l['offline'] = '오프라인';
$l['edited_post'] = '수정된 게시물';
$l['usergroup'] = '사용자 그룹';
