<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어(South Korea)
// Author of the language pack : zardkim
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Mon, 08 Jul 2024 03:07:21 +0000
// --------------------------------------------------------------------------------

$l['avatarep_name'] = '마지막 게시자 아바타';
$l['avatarep_descrip'] = '아바타가 존재하지 않는 포럼의 가능한 모든 영역에 아바타를 표시합니다.';
$l['avatarep_config'] = '플러그인 구성';
$l['avatarep_style_usernames'] = '스타일 사용자 이름 플러그인이 있습니다(아바타 옵션에서 형식화된 이름 옵션을 비활성화하거나 오류가 발생하지 않도록 포럼에서 스타일 사용자 이름을 제거하세요).';
$l['avatarep_disabled_msg'] = '플러그인 비활성화됨';
$l['avatarep_title'] = '[플러그인] 마지막 게시물 아바타';
$l['avatarep_title_descrip'] = '이 플러그인 구성(아바타 옵션)';
$l['avatarep_power'] = '플러그인 활성화/비활성화';
$l['avatarep_power_descrip'] = '이 플러그인을 활성화하려면 선택하세요.';
$l['avatarep_forum'] = '포럼의 아바타';
$l['avatarep_forum_descrip'] = '포럼 목록에 마지막 게시자 아바타를 표시합니다.';
$l['avatarep_thread_owner'] = '글타래의 아바타';
$l['avatarep_thread_owner_descrip'] = '글타래 목록에 소유자 아바타 표시';
$l['avatarep_thread_lastposter'] = '글타래의 아바타';
$l['avatarep_thread_lastposter_descrip'] = '글타래 목록에 마지막 게시자 아바타를 표시합니다.';
$l['avatarep_thread_announcements'] = '공지사항의 아바타';
$l['avatarep_thread_announcements_descrip'] = '공지사항 사용자의 아바타를 표시합니다.';
$l['avatarep_portal'] = '포털의 아바타 - 최신 글타래';
$l['avatarep_portal_descrip'] = '포털에 공지사항 사용자의 아바타 표시';
$l['avatarep_search'] = '검색에서 아바타';
$l['avatarep_search_descrip'] = '검색결과에 아바타 표시';
$l['avatarep_menu'] = '모달박스 팝업';
$l['avatarep_menu_descrip'] = '사용자의 모든 아바타에 대해 선택된 마우스 이벤트에 대한 멋진 팝업 메뉴를 표시합니다.';
$l['avatarep_menu_events'] = '마우스 이벤트';
$l['avatarep_menu_events_descrip'] = '모달박스를 표시하려면 마우스 이벤트를 선택하세요.';
$l['avatarep_letter_avatar'] = '기본 아바타 외 아바타 문자';
$l['avatarep_letter_avatar_descrip'] = '문자 대신 기본 아바타를 표시하려면 아니요를 선택하세요.';
$l['avatarep_format'] = '형식이 지정된 사용자 이름 표시';
$l['avatarep_format_descrip'] = 'HTML 코드가 구성된 모든 사용자 그룹의 형식 이름을 표시합니다.';
$l['avatarep_private'] = '비공개 메시지의 아바타';
$l['avatarep_private_descrip'] = '비공개 메시지에 아바타 표시';
$l['avatarep_latest_threads'] = '최신 글타래의 아바타';
$l['avatarep_latest_threads_descrip'] = '최신 글타래에 대해 Portal 및 SideBoxes 플러그인에 아바타를 표시합니다.';
$l['avatarep_thread_lastposter_mark'] = '응답한 긅타래 표시';
$l['avatarep_thread_lastposter_mark_descrip'] = '글타래에 응답하면 아바타 마우스 오버시 글타래 소유자를 표시합니다(추가 쿼리 필요).';
$l['avatarep_thread_contributor'] = '아바타 기여자 표시';
$l['avatarep_thread_contributor_descrip'] = 'showthread에 글타래 소유자의 아바타를 표시하지만 해당 글타래에 응답한 경우에는 귀하의 아바타도 표시됩니다.';
$l['avatarep_usercp'] = '사용자 제어판의 아바타';
$l['avatarep_usercp_descrip'] = '나열된 글타래의 아바타를 사용자 cp에 표시합니다.';
$l['avatarep_usercp_fsubs'] = 'usercp 포럼 구독에 아바타 표시';
$l['avatarep_usercp_fsubs_desc'] = 'usercp를 구독하기 위해 끌어올리지 마십시오.';
$l['avatarep_similar_threads'] = '비슷한 글타래 템플릿에 대한 아바타를 showthread에 표시합니다.';
$l['avatarep_similar_threads_desc'] = 'showthread 유사한 글타래드 템플릿에 아바타를 표시하지 않으려면 비활성화하십시오.';
$l['avatarep_usercp_tsubs'] = '구독한 글타래 템플릿에 대한 아바타를 usercp에 표시합니다.';
$l['avatarep_usercp_tsubs_desc'] = 'usercp 구독 글타래 템플릿에 아바타를 표시하지 않으려면 비활성화하세요.';
$l['avatarep_postbit'] = 'Postbit에서 기본 아바타를 문자로 바꾸시겠습니까?';
$l['avatarep_postbit_desc'] = '아바타 문자 표시 옵션이 활성화된 경우에만 사용자의 기본 아바타가 문자로 대체됩니다.';
$l['avatarep_onerror'] = '흰색 또는 깨진 아바타를 기본으로 표시합니다.';
$l['avatarep_onerror_descrip'] = 'img가 제거되거나 손상된 것처럼 아바타를 로드할 때 일부 오류가 발생하면 기본 아바타가 나타납니다(img 태그 js 함수가 거기에서 검증되지 않아 오류로 인해 w3c 검증이 중단됩니다. w3c로 검증하려면 이 옵션을 비활성화하십시오).';
