<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 04:35:20 +0000
// --------------------------------------------------------------------------------

$l['spiders_bots'] = '스파이더/봇';
$l['spiders_bots_desc'] = '이 섹션에서는 검색 엔진 스파이더 &amp; 귀하의 포럼에서 봇을 자동으로 감지합니다. 특정 봇이 마지막으로 방문한 시간도 확인할 수 있습니다.';
$l['add_new_bot'] = '새 봇 추가';
$l['add_new_bot_desc'] = '여기에서 포럼에서 감지되기를 원하는 새 봇을 추가할 수 있습니다.';
$l['edit_bot'] = '봇 편집';
$l['edit_bot_desc'] = '여기에서 기존 봇을 편집할 수 있습니다.';
$l['bot'] = '봇';
$l['last_visit'] = '마지막 방문';
$l['no_bots'] = '이 포럼에서는 검색 엔진 스파이더나 웹 크롤러를 추적하지 않습니다.';
$l['name'] = '이름';
$l['name_desc'] = '식별하려는 이 봇의 이름을 입력하세요.';
$l['user_agent'] = '사용자 에이전트 문자열';
$l['user_agent_desc'] = '봇 사용자 에이전트와 일치할 문자열을 입력하세요(부분 일치는 허용됨).';
$l['language_str'] = '언어';
$l['language_desc'] = '보드를 볼 때 봇이 사용할 언어 팩을 선택하세요.';
$l['theme'] = '테마마';
$l['theme_desc'] = '보드를 볼 때 봇이 사용할 테마를 선택하세요.';
$l['user_group'] = '사용자 그룹';
$l['user_group_desc'] = '이 보드에 대해 적용될 사용자 그룹 권한을 선택하세요. (참고: 기본 손님 그룹에서 이를 변경하는 것은 권장되지 않습니다.)';
$l['save_bot'] = '봇 저장';
$l['use_board_default'] = '보드 기본값 사용';
$l['error_invalid_bot'] = '지정한 봇이 존재하지 않습니다.';
$l['error_missing_name'] = '이 봇의 이름을 입력하지 않았습니다.';
$l['error_missing_agent'] = '이 봇에 대한 사용자 에이전트 문자열을 입력하지 않았습니다.';
$l['success_bot_created'] = '봇이 성공적으로 생성되었습니다.';
$l['success_bot_updated'] = '봇이 성공적으로 업데이트되었습니다.';
$l['success_bot_deleted'] = '선택한 봇이 성공적으로 삭제되었습니다.';
$l['confirm_bot_deletion'] = '이 봇을 삭제하시겠습니까?';
