<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 08:00:48 +0000
// --------------------------------------------------------------------------------

$l['configuration'] = '환경설정';
$l['bbsettings'] = '설정';
$l['banning'] = '차단';
$l['custom_profile_fields'] = '사용자 정의 프로필 필드';
$l['smilies'] = '스마일리';
$l['word_filters'] = '단어 필터';
$l['mycode'] = 'MyCode';
$l['languages'] = '언어';
$l['post_icons'] = '게시물 아이콘';
$l['help_documents'] = '도움말 문서';
$l['plugins'] = '플러그인';
$l['attachment_types'] = '첨부파일 유형';
$l['moderator_tools'] = '중재자 도구';
$l['spiders_bots'] = '스파이더/봇';
$l['calendars'] = '달력';
$l['warning_system'] = '경고 시스템';
$l['thread_prefixes'] = '글타래 접두어';
$l['security_questions'] = '보안 질문';
$l['report_reasons'] = '신고 이유';
$l['can_manage_settings'] = '설정을 관리할까요?';
$l['can_manage_banned_accounts'] = '차단된 계정을 관리할까요?';
$l['can_manage_custom_profile_fields'] = '사용자 정의 프로필 필드를 관리할까요?';
$l['can_manage_smilies'] = '스마일리를 관리할까요?';
$l['can_manage_bad_words'] = '단어 필터를 관리할까요?';
$l['can_manage_custom_mycode'] = '맞춤형 MyCode를 관리할까요?';
$l['can_manage_language_packs'] = '언어 팩을 관리할까요?';
$l['can_manage_post_icons'] = '게시물 아이콘을 관리할까요?';
$l['can_manage_help_documents'] = '도움말 문서를 관리할까요?';
$l['can_manage_plugins'] = '플러그인을 관리할까요?';
$l['can_manage_attachment_types'] = '첨부파일 유형을 관리할까요?';
$l['can_manage_spiders_bots'] = '스파이더/봇을 관리할까요?';
$l['can_manage_calendars'] = '캘린더를 관리할까요?';
$l['can_manage_warning_system'] = '경고 시스템을 관리할까요?';
$l['can_manage_mod_tools'] = '중재자 도구를 관리할까요?';
$l['can_manage_thread_prefixes'] = '글타래 접두사를 관리할까요?';
$l['can_manage_security_questions'] = '보안 질문을 관리할까요?';
$l['can_manage_report_reasons'] = '신고 사유를 관리할까요?';
