<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 04:22:17 +0000
// --------------------------------------------------------------------------------

$l['report_reasons'] = '신고 이유';
$l['report_reasons_desc'] = '여기에서는 사용자가 콘텐츠를 신고할 때 선택할 수 있는 이유를 만들고 관리할 수 있습니다.';
$l['add_new_reason'] = '새로운 이유 추가';
$l['add_new_reason_desc'] = '사용자가 콘텐츠를 신고할 때 선택해야 하는 새로운 이유를 추가합니다.';
$l['edit_reason'] = '이유 편집';
$l['edit_reason_desc'] = '사용자가 콘텐츠를 신고할 때 선택하는 이유를 편집합니다.';
$l['applies_to'] = '적용 대상';
$l['order'] = '순서';
$l['extra_comment'] = '의견이 필요?';
$l['options'] = '옵션';
$l['delete_reason'] = '삭제 이유';
$l['no_report_reasons'] = '현재 귀하의 포럼에는 신고 이유가 없습니다.';
$l['reason_title'] = '제목';
$l['reason_title_desc'] = '내용을 신고하는 이유의 제목을 입력하세요.';
$l['requires_extra'] = '추가 설명이 필요하십니까?';
$l['requires_extra_desc'] = '이 이유를 선택하면 사용자에게 추가 설명을 입력하도록 요구하시겠습니까?';
$l['save_reason'] = '이유 저장';
$l['content_colon'] = '콘텐츠:';
$l['all_content'] = '모든 콘텐츠';
$l['select_content'] = '콘텐츠 선택';
$l['report_content_'] = '없음';
$l['report_content_all'] = '모두';
$l['report_content_post'] = '게시글';
$l['report_content_profile'] = '프로필';
$l['report_content_reputation'] = '평판';
$l['report_reason_rules'] = '포럼 규칙 위반';
$l['report_reason_bad'] = '부적절한 콘텐츠';
$l['report_reason_spam'] = '스팸 콘텐츠';
$l['report_reason_wrong'] = '잘못된 포럼';
$l['report_reason_other'] = '기타';
$l['default_report_reason'] = '기본';
$l['custom_report_reason'] = '커스텀';
$l['update_reasons_order'] = '이유 순서 업데이트';
$l['error_cannot_modify_reason'] = '이 이유는 수정할 수 없습니다.';
$l['error_cannot_delete_reason'] = '이 이유는 삭제할 수 없습니다.';
$l['error_invalid_reason'] = '잘못된 이유를 선택했습니다.';
$l['error_missing_title'] = '이러한 이유로 제목을 입력하지 않았습니다.';
$l['error_missing_extra'] = '이러한 이유로 추가 정보를 원하는지 선택하지 않으셨습니다.';
$l['success_reasons_disporder_updated'] = '신고 이유 표시 순서가 성공적으로 업데이트되었습니다.';
$l['success_reason_created'] = '이유가 성공적으로 생성되었습니다.';
$l['success_reason_updated'] = '이유가 성공적으로 업데이트되었습니다.';
$l['success_reason_deleted'] = '이유가 삭제되었습니다.';
$l['confirm_reason_deletion'] = '이 이유를 삭제하시겠습니까?';
