<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 07:47:54 +0000
// --------------------------------------------------------------------------------

$l['help_documents'] = '도움말 문서';
$l['add_new_section'] = '새 섹션 추가';
$l['add_new_section_desc'] = '여기에서 새로운 도움말 섹션을 추가할 수 있습니다.';
$l['add_new_document'] = '새 문서 추가';
$l['add_new_document_desc'] = '여기에서 새로운 도움말 문서를 추가할 수 있습니다.';
$l['edit_section'] = '섹션 편집';
$l['edit_section_desc'] = '여기서 도움말 섹션을 편집할 수 있습니다.';
$l['edit_document'] = '문서 편집';
$l['edit_document_desc'] = '여기서 도움말 문서를 편집할 수 있습니다.';
$l['manage_help_documents'] = '도움말 문서 관리';
$l['manage_help_documents_desc'] = '이 섹션에서는 도움말 문서를 관리할 수 있습니다.';
$l['title'] = '제목';
$l['short_description'] = '간단한 설명';
$l['display_order'] = '표시 순서';
$l['enabled'] = '활성화?';
$l['use_translation'] = '번역을 사용?';
$l['add_section'] = '섹션 추가';
$l['add_document'] = '문서 추가';
$l['save_section'] = '섹션 저장';
$l['save_document'] = '문서 저장';
$l['section'] = '섹션';
$l['document'] = '문서';
$l['id'] = 'ID';
$l['custom_doc_sec'] = '사용자 정의 문서/섹션';
$l['default_doc_sec'] = '기본 문서/섹션';
$l['no_help_documents'] = '현재 귀하의 포럼에는 도움말 문서가 없습니다.';
$l['section_document'] = '섹션/문서';
$l['error_section_missing_name'] = '섹션의 이름을 지정해야 합니다.';
$l['error_section_missing_description'] = '섹션에 대한 간단한 설명을 지정해야 합니다.';
$l['error_section_missing_enabled'] = '"활성화 여부"에 대해 예 또는 아니요를 지정해야 합니다.';
$l['error_section_missing_translation'] = '"번역을 사용하시겠습니까?"에 대해 예 또는 아니요를 지정해야 합니다.';
$l['error_missing_sid'] = '문서의 섹션을 지정해야 합니다.';
$l['error_document_missing_name'] = '문서의 이름을 지정해야 합니다.';
$l['error_document_missing_description'] = '문서에 대한 간단한 설명을 지정해야 합니다.';
$l['error_document_missing_document'] = '문서를 지정해야 합니다.';
$l['error_document_missing_enabled'] = '"활성화 여부"에 대해 예 또는 아니요를 지정해야 합니다.';
$l['error_document_missing_translation'] = '"번역을 사용하시겠습니까?"에 대해 예 또는 아니요를 지정해야 합니다.';
$l['error_invalid_sid'] = '잘못된 문서 ID가 지정되었습니다.';
$l['error_missing_section_id'] = '지정된 섹션이 존재하지 않습니다.';
$l['error_missing_hid'] = '지정한 문서가 존재하지 않습니다.';
$l['success_help_section_added'] = '도움말 섹션이 성공적으로 추가되었습니다.';
$l['success_help_document_added'] = '도움말 문서가 성공적으로 추가되었습니다.';
$l['success_help_section_updated'] = '도움말 섹션이 성공적으로 업데이트되었습니다.';
$l['success_help_document_updated'] = '도움말 문서가 성공적으로 업데이트되었습니다.';
$l['success_section_deleted'] = '선택한 도움말 섹션이 삭제되었습니다.';
$l['success_document_deleted'] = '선택한 도움말 문서가 성공적으로 삭제되었습니다.';
$l['confirm_section_deletion'] = '이 섹션을 삭제하시겠습니까?';
$l['confirm_document_deletion'] = '이 문서를 삭제하시겠습니까?';
