<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 08:07:43 +0000
// --------------------------------------------------------------------------------

$l['custom_mycode'] = '사용자 MyCode';
$l['mycode'] = 'MyCode';
$l['mycode_desc'] = '사용자 정의 MyCode를 사용하면 회원이 메시지에 사용할 추가 MyCode를 생성할 수 있습니다.';
$l['add_new_mycode'] = '새 MyCode 추가';
$l['add_new_mycode_desc'] = '여기에서 포럼에 새로운 사용자 정의 MyCode를 추가할 수 있습니다. 저장하기 전에 양식 아래의 MyCode Sandbox를 사용하여 정규식 및 교체를 테스트할 수 있습니다.';
$l['edit_mycode_desc'] = '여기에서 사용자 정의 MyCode를 편집할 수 있습니다. 변경 사항을 저장하기 전에 양식 아래의 MyCode Sandbox를 사용하여 정규식 및 교체를 테스트할 수 있습니다.';
$l['title'] = '제목';
$l['short_description'] = '간단한 설명';
$l['regular_expression'] = '정규식';
$l['regular_expression_desc'] = '특정 문자 조합을 검색하는 정규식을 입력하세요. 정규 표현식이 유효하고 안전한지 확인해야 합니다. 유효성 검사는 수행되지 않습니다.';
$l['replacement'] = '대체식';
$l['replacement_desc'] = '정규 표현식의 대체 항목을 입력하세요.';
$l['example'] = '예시:';
$l['enabled'] = '활성화?';
$l['parse_order'] = '파싱 순서';
$l['parse_order_desc'] = 'MyCode는 다른 MyCode에 비해 오름차순으로 구문 분석됩니다.';
$l['edit_mycode'] = 'MyCode 편집';
$l['activate_mycode'] = 'MyCode 활성화';
$l['deactivate_mycode'] = 'MyCode 비활성화';
$l['delete_mycode'] = 'MyCode 삭제';
$l['no_mycode'] = '현재는 사용자 정의 MyCode가 없습니다.';
$l['save_mycode'] = 'MyCode 저장';
$l['add_mycode'] = 'MyCode 추가';
$l['changes_not_saved'] = '변경사항이 아직 저장되지 않았습니다.';
$l['sandbox'] = '샌드박스';
$l['sandbox_desc'] = '변경 사항을 저장하기 전에 이 영역을 사용하여 위의 정규식 및 대체를 테스트할 수 있습니다.';
$l['test_value'] = '테스트 값';
$l['test_value_desc'] = '아래 상자에 테스트할 텍스트를 입력하세요.';
$l['result_html'] = 'HTML 결과';
$l['result_html_desc'] = '아래 텍스트 영역에는 테스트 값에 대한 정규식을 사용한 결과 HTML이 표시됩니다.';
$l['result_actual'] = '실제 결과';
$l['result_actual_desc'] = '아래 영역은 HTML이 렌더링될 때의 실제 결과를 보여줍니다.';
$l['test'] = 'MyCode 테스트';
$l['error_missing_title'] = '제목을 입력하지 않으셨습니다.';
$l['error_missing_regex'] = '정규식을 입력하지 않았습니다.';
$l['error_regex_already_available'] = '다른 MyCode에 이미 정의된 정규식을 입력했습니다. 이 MyCode에 대해 다른 정규식을 제공하십시오.';
$l['error_missing_replacement'] = '대체식을 입력하지 않았습니다.';
$l['error_invalid_mycode'] = '지정한 MyCode가 존재하지 않습니다.';
$l['success_added_mycode'] = 'MyCode가 성공적으로 추가되었습니다.';
$l['success_deleted_mycode'] = '선택한 MyCode가 성공적으로 삭제되었습니다.';
$l['success_updated_mycode'] = '선택한 MyCode가 성공적으로 삭제되었습니다.';
$l['success_deactivated_mycode'] = '선택한 MyCode가 성공적으로 비활성화되었습니다.';
$l['success_activated_mycode'] = '선택한 MyCode가 성공적으로 활성화되었습니다.';
$l['confirm_mycode_deletion'] = '이 MyCode를 삭제하시겠습니까?';
$l['mycode_sandbox_test_error'] = '테스트 결과를 가져오는 중에 오류가 발생했습니다.';
