<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Sat, 06 Jul 2024 05:14:28 +0000
// --------------------------------------------------------------------------------

$l['warning_system'] = '경고 시스템';
$l['warning_types'] = '경고 유형';
$l['warning_types_desc'] = '여기에서는 직원이 사용자에게 발행할 수 있는 다양한 경고 유형 목록을 관리할 수 있습니다.';
$l['add_warning_type'] = '새 경고 유형 추가';
$l['add_warning_type_desc'] = '여기에서 미리 정의된 새로운 경고 유형을 생성할 수 있습니다. 사용자에게 경고할 때 경고 유형을 선택할 수 있으며 이 유형에 대해 추가할 포인트 수는 물론 이 유형의 경고가 만료되기 전의 기간을 정의할 수 있습니다.';
$l['edit_warning_type'] = '경고 유형 편집';
$l['edit_warning_type_desc'] = '여기서 이 경고 유형을 편집할 수 있습니다. 사용자에게 경고할 때 경고 유형을 선택할 수 있으며 이 유형에 대해 추가할 포인트 수는 물론 이 유형의 경고가 만료되기 전의 기간을 정의할 수 있습니다.';
$l['warning_levels'] = '경고 수준';
$l['warning_levels_desc'] = '경고 수준은 사용자가 특정 경고 수준(최대 경고 지점의 백분율)에 도달할 때 사용자에게 발생하는 상황을 정의합니다. 사용자를 금지하거나 권한을 일시 중지할 수 있습니다.';
$l['add_warning_level'] = '새 경고 수준 추가';
$l['add_warning_level_desc'] = '여기에서 새로운 경고 수준을 생성할 수 있습니다. 경고 수준은 사용자가 최대 경고 수준의 특정 비율에 도달할 때 사용자에게 취해지는 조치입니다.';
$l['edit_warning_level'] = '경고 수준 편집';
$l['edit_warning_level_desc'] = '경고 수준은 사용자가 최대 경고 수준의 특정 비율에 도달할 때 사용자에게 취해지는 조치입니다.';
$l['percentage'] = '백분율';
$l['action_to_take'] = '취해야 할 조치';
$l['move_banned_group'] = '{1} {2}에 대한 차단 그룹({3})으로 이동';
$l['move_banned_group_permanent'] = '차단된 그룹({1})으로 영구적으로 이동';
$l['suspend_posting'] = '{1} {2}에 대한 게시 권한 일시 중지';
$l['suspend_posting_permanent'] = '게시 권한을 영구적으로 정지합니다.';
$l['moderate_new_posts'] = '{1} {2}에 대한 새 게시물 검토';
$l['moderate_new_posts_permanent'] = '새 게시물을 영구적으로 검토';
$l['no_warning_levels'] = '현재 귀하의 포럼에는 경고 수준이 없습니다.';
$l['warning_type'] = '경고 유형';
$l['points'] = '포인트';
$l['expires_after'] = '다음 이후 만료';
$l['no_warning_types'] = '현재 귀하의 포럼에는 경고 유형이 없습니다.';
$l['warning_points_percentage'] = '최대 경고 지점의 비율';
$l['warning_points_percentage_desc'] = '1에서 100 사이의 숫자 값을 입력하세요.';
$l['action_to_be_taken'] = '취해야 할 조치';
$l['action_to_be_taken_desc'] = '사용자가 위 수준에 도달하면 수행할 작업을 선택합니다.';
$l['ban_user'] = '사용자 차단';
$l['banned_group'] = '차단된 그룹:';
$l['ban_length'] = '차단 기간:';
$l['suspend_posting_privileges'] = '게시 권한 일시 중지';
$l['suspension_length'] = '서스펜션 길이:';
$l['moderate_posts'] = '게시물 검토';
$l['moderation_length'] = '검토 기간:';
$l['save_warning_level'] = '경고 수준 저장';
$l['title'] = '제목';
$l['points_to_add'] = '추가 포인트';
$l['points_to_add_desc'] = '사용자 경고 수준에 추가할 포인트 수입니다.';
$l['warning_expiry'] = '경고 만료';
$l['warning_expiry_desc'] = '이 경고가 표시된 후 얼마 후에 만료되기를 원하시나요?';
$l['save_warning_type'] = '경고 유형 저장';
$l['expiration_hours'] = '시간';
$l['expiration_days'] = '일';
$l['expiration_weeks'] = '주';
$l['expiration_months'] = '월';
$l['expiration_never'] = 'Never';
$l['expiration_permanent'] = '영구적인';
$l['error_invalid_warning_level'] = '지정된 경고 수준이 존재하지 않습니다.';
$l['error_invalid_warning_percentage'] = '이 경고 수준에 유효한 백분율 값을 입력하지 않았습니다. 백분율 값은 1에서 100 사이여야 합니다.';
$l['error_invalid_warning_type'] = '지정된 경고 유형이 존재하지 않습니다.';
$l['error_missing_action_type'] = '이 새로운 경고 수준을 할당하기 위해 수행할 작업 중 하나를 선택하십시오.';
$l['error_missing_type_title'] = '이 경고 유형의 제목을 입력하지 않았습니다.';
$l['error_missing_type_points'] = '이 유형의 경고를 제공할 때 추가할 유효한 포인트 수를 입력하지 않았습니다. 0보다 크고 {1}보다 크지 않은 숫자를 입력해야 합니다.';
$l['success_warning_level_created'] = '경고 수준이 성공적으로 생성되었습니다.';
$l['success_warning_level_updated'] = '경고 수준이 성공적으로 업데이트되었습니다.';
$l['success_warning_level_deleted'] = '선택한 경고 수준이 성공적으로 삭제되었습니다.';
$l['success_warning_type_created'] = '경고 유형이 성공적으로 생성되었습니다.';
$l['success_warning_type_updated'] = '경고 유형이 성공적으로 업데이트되었습니다.';
$l['success_warning_type_deleted'] = '선택한 경고 유형이 성공적으로 삭제되었습니다.';
$l['confirm_warning_level_deletion'] = '이 경고 수준을 삭제하시겠습니까?';
$l['confirm_warning_type_deletion'] = '이 경고 유형을 삭제하시겠습니까?';
