<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 04:32:19 +0000
// --------------------------------------------------------------------------------

$l['smilies'] = '스마일리';
$l['manage_smilies'] = '스마일리 관리';
$l['manage_smilies_desc'] = '이 섹션에서는 스마일리를 편집하고 삭제할 수 있습니다.';
$l['add_smilie'] = '새 스마일리 추가';
$l['add_smilie_desc'] = '여기에서 새 스마일리를 하나 추가할 수 있습니다.';
$l['add_multiple_smilies'] = '여러 스마일리 추가';
$l['add_multiple_smilies_desc'] = '여기에서는 한 번에 여러 개의 새로운 스마일리를 추가할 수 있습니다.';
$l['edit_smilie'] = '스마일리 편집';
$l['edit_smilie_desc'] = '여기서는 하나의 스마일리를 편집할 수 있습니다.';
$l['mass_edit'] = '대량 편집';
$l['mass_edit_desc'] = '여기서 모든 스마일리를 한 번에 쉽게 편집할 수 있습니다.';
$l['no_smilies'] = '현재 귀하의 포럼에는 스마일리가 없습니다.';
$l['image'] = '이미지';
$l['name'] = '이름';
$l['text_replace'] = '대치 텍스트';
$l['text_replace_desc'] = '스마일리를 바꿀 텍스트입니다(한 줄에 하나씩 입력).';
$l['image_path'] = '이미지 경로';
$l['image_path_desc'] = '스마일리 이미지로 경로입니다. 다양한 테마에 다양한 스마일리를 사용하려면 <strong>{theme}</strong>을 사용하여 각 테마의 이미지 디렉터리를 나타내세요.';
$l['order'] = '순서';
$l['display_order'] = '표시 순서';
$l['display_order_desc'] = '스마일리 목록에 표시되는 순서입니다. 이 숫자는 다른 스마일리의 숫자와 같아서는 안 됩니다.';
$l['mass_edit_show_clickable'] = '클릭 가능하게 표시?';
$l['show_clickable'] = '클릭 가능한 목록에 표시?';
$l['show_clickable_desc'] = '게시물 편집기의 클릭 가능한 스마일리 목록에 이 스마일리를 표시하시겠습니까?';
$l['include'] = '추가?';
$l['path_to_images'] = '이미지 경로';
$l['path_to_images_desc'] = '이미지가 들어있는 폴더 경로입니다.';
$l['smilie_delete'] = '삭제?';
$l['save_smilie'] = '스마일리 저장';
$l['save_smilies'] = '스마일리 저장';
$l['show_smilies'] = '스마일리 보기';
$l['reset'] = '리셋';
$l['error_missing_name'] = '이 스마일리의 이름을 입력하지 않았습니다.';
$l['error_missing_text_replacement'] = '이 스마일리에 대한 대체 텍스트를 입력하지 않았습니다.';
$l['error_missing_path'] = '이 스마일리의 경로를 입력하지 않았습니다.';
$l['error_missing_path_multiple'] = '경로를 입력하지 않았습니다.';
$l['error_missing_order'] = '이 스마일리 표시 순서를 입력하지 않았습니다.';
$l['error_duplicate_order'] = '이 스마일리에 유효한 표시 순서를 입력하지 않았습니다.';
$l['error_missing_clickable'] = '"클릭 가능 표시" 옵션에 대해 예 또는 아니요를 지정하지 않았습니다.';
$l['error_no_smilies'] = '지정된 디렉터리에 스마일리가 없거나 디렉터리의 모든 스마일리가 이미 추가되었습니다.';
$l['error_no_images'] = '지정된 디렉터리에 이미지가 없습니다.';
$l['error_none_included'] = '포함할 스마일리를 선택하지 않았습니다.';
$l['error_invalid_path'] = '유효한 경로를 입력하지 않았습니다.';
$l['error_invalid_smilie'] = '지정한 스마일리가 존재하지 않습니다.';
$l['success_smilie_added'] = '스마일리가 성공적으로 추가되었습니다.';
$l['success_multiple_smilies_added'] = '선택한 스마일리가 성공적으로 추가되었습니다.';
$l['success_smilie_updated'] = '스마일리 성공적으로 업데이트되었습니다.';
$l['success_multiple_smilies_updated'] = '스마일리가 성공적으로 업데이트되었습니다.';
$l['success_smilie_deleted'] = '선택한 스마일리가 성공적으로 삭제되었습니다.';
$l['success_mass_edit_updated'] = '스마일리가 성공적으로 업데이트되었습니다.';
$l['confirm_smilie_deletion'] = '이 스마일리를 삭제하시겠습니까?';
