<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 00:32:07 +0000
// --------------------------------------------------------------------------------

$l['languages'] = '언어';
$l['languages_desc'] = '포럼에 설치한 언어 팩은 다음과 같습니다. 언어 파일을 편집하거나, 다른 언어로 파일을 편집하거나, 언어 속성을 편집하도록 선택할 수 있습니다.';
$l['find_language_packs'] = '언어 팩 찾기';
$l['language_files'] = '언어 파일';
$l['language_files_desc'] = '다음은 프런트 엔드 및 관리자 제어판 모두에 대해 선택한 언어 내의 파일입니다. 여기에서 해당 파일을 편집하도록 선택할 수 있습니다.';
$l['quick_phrases'] = '빠른 문구';
$l['quick_phrases_desc'] = '일반적으로 수정되는 언어 문구에 빠르게 액세스할 수 있습니다.';
$l['edit_with'] = '{1}로 편집';
$l['edit_language_variables'] = '언어 변수 편집';
$l['edit_language_variables_desc'] = '여기에서 원하는 대로 다양한 언어 문자열을 편집할 수 있습니다.';
$l['edit_properties_desc'] = '여기에서 언어 팩 속성을 편집할 수 있습니다.';
$l['installed_language_packs'] = 'Installed Language Packs';
$l['front_end'] = '프런트엔드';
$l['admin_cp'] = 'Admin CP';
$l['save_language_file'] = '언어 파일 저장';
$l['nav_editing_set'] = '언어 세트 속성 편집';
$l['edit_properties'] = '언어 팩 속성 편집';
$l['friendly_name'] = '친숙한 이름';
$l['language_in_html'] = '&lt;html&gt;의 언어 꼬리표';
$l['charset'] = '캐릭터 셋';
$l['admin'] = 'Admin CP 언어 변수가 포함되어 있나요?';
$l['rtl'] = '오른쪽에서 왼쪽으로?';
$l['quickphrases_agreement'] = '등록 계약 - 제목';
$l['quickphrases_agreement_1'] = '등록 계약 - 단락 1';
$l['quickphrases_agreement_2'] = '등록 계약 - 2항';
$l['quickphrases_agreement_3'] = '등록 계약 - 3항';
$l['quickphrases_agreement_4'] = '등록 계약 - 4항';
$l['quickphrases_agreement_5'] = '등록 계약 - 5항';
$l['quickphrases_error_nopermission_guest_1'] = '권한 없음 메시지 - 단락 1';
$l['quickphrases_error_nopermission_guest_2'] = '권한 없음 메시지 - 단락 2';
$l['quickphrases_error_nopermission_guest_3'] = '권한 없음 메시지 - 단락 3';
$l['quickphrases_error_nopermission_guest_4'] = '권한 없음 메시지 - 단락 4';
$l['no_languages'] = '언어 없음';
$l['no_language_files_front_end'] = '프런트엔드 언어 파일이 없습니다.';
$l['no_language_files_admin_cp'] = 'Admin CP 언어 파일을 찾을 수 없습니다.';
$l['error_invalid_set'] = '잘못된 언어 세트가 지정되었습니다.';
$l['error_invalid_file'] = '잘못된 언어 파일이 지정되었습니다.';
$l['error_cannot_write_to_file'] = '파일에 쓸 수 없습니다. 이 언어 세트에 대한 파일 권한을 확인하고 다시 시도하세요.';
$l['error_folders_fail'] = '요청한 언어 팩 폴더에 액세스하는 중에 문제가 발생했습니다. 해당 파일이 존재하고 쓰기 가능한지 확인하세요.';
$l['alert_note_cannot_write'] = '언어 파일을 편집하려면 먼저 이 언어 세트의 파일을 CHMOD하여 서버가 해당 파일에 쓸 수 있는 권한을 갖도록 해야 합니다.';
$l['success_langfile_updated'] = '언어 파일이 성공적으로 업데이트되었습니다.';
$l['success_langprops_updated'] = '언어 속성이 성공적으로 업데이트되었습니다.';
$l['success_quickphrases_updated'] = '빠른 언어 문구가 성공적으로 업데이트되었습니다.';
$l['issues'] = '이슈';
$l['phrases'] = '구문';
$l['issues_ok'] = '여기서는 모든 것이 괜찮을 것 같습니다.';
$l['issues_nothingtocompare'] = '여기서는 비교할 것이 없습니다.';
$l['issues_warning'] = '이 파일에 주의가 필요할 수 있습니다.
반드시 확인해 주시기 바랍니다.';
