<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 00:30:40 +0000
// --------------------------------------------------------------------------------

$l['attachment_types'] = '첨부파일 유형';
$l['attachment_types_desc'] = '여기서는 사용자가 게시물에 첨부할 수 있는 파일 형식을 정의하는 첨부 파일 형식을 만들고 관리할 수 있습니다. 참고: 첨부 파일 유형을 비활성화하면 해당 유형의 기존 첨부 파일에 액세스할 수 없게 됩니다.';
$l['add_new_attachment_type'] = '새 첨부 파일 유형 추가';
$l['add_attachment_type'] = '첨부파일 유형 추가';
$l['add_attachment_type_desc'] = '새로운 첨부 파일 유형을 추가하면 회원이 이 유형의 파일을 게시물에 첨부할 수 있습니다. 확장자, MIME 유형, 최대 크기를 제어하고 각 첨부 파일 유형에 대해 작은 아이콘을 표시할 수 있습니다.';
$l['edit_attachment_type'] = '첨부파일 유형 편집';
$l['edit_attachment_type_desc'] = '확장자, MIME 유형, 최대 크기를 제어하고 이 첨부 파일 유형에 대해 작은 MIME 유형을 표시할 수 있습니다.';
$l['extension'] = '확장자';
$l['maximum_size'] = '최대 크기';
$l['no_attachment_types'] = '현재 당신의 포럼에는 첨부 파일 유형이 없습니다.';
$l['name'] = '이름';
$l['name_desc'] = '첨부파일 유형의 이름을 입력하세요.';
$l['file_extension'] = '파일 확장자';
$l['file_extension_desc'] = '여기에 업로드를 허용할 파일 확장자를 입력하세요. (확장자 앞에 마침표는 포함하지 마세요.) (예: txt)';
$l['mime_type'] = 'MIME 유형';
$l['mime_type_desc'] = '이 유형의 파일을 다운로드할 때 서버에서 보낸 MIME 유형을 입력하세요(<a href="http://www.freeformatter.com/mime-types-list.html">여기에서 목록 보기</a>)';
$l['maximum_file_size'] = '최대 파일 크기(Kilobytes)';
$l['maximum_file_size_desc'] = '이 첨부 파일 유형의 업로드를 위한 최대 파일 크기 킬로바이트 (1 MB = 1024 KB)';
$l['limit_intro'] = '최대 파일 크기가 다음 PHP 제한 중 최소값보다 작은지 확인하세요.';
$l['limit_post_max_size'] = '최대 게시물 크기: {1}';
$l['limit_upload_max_filesize'] = '업로드 최대 파일 크기: {1}';
$l['attachment_icon'] = '첨부파일 아이콘';
$l['attachment_icon_desc'] = '이 유형의 첨부 파일에 대해 작은 첨부 아이콘을 표시하려면 여기에 해당 경로를 입력하십시오. {theme}은 테마별 첨부 아이콘을 지정할 수 있는 뷰어 테마의 이미지 디렉토리로 대체됩니다.';
$l['save_attachment_type'] = '첨부파일 유형 저장';
$l['error_invalid_attachment_type'] = '잘못된 첨부 파일 유형을 선택했습니다.';
$l['error_missing_mime_type'] = '이 첨부 파일 유형에 대한 MIME 유형을 입력하지 않았습니다.';
$l['error_missing_extension'] = '이 첨부 파일 유형에 대한 파일 확장자를 입력하지 않았습니다.';
$l['success_attachment_type_created'] = '첨부 파일 유형이 성공적으로 생성되었습니다.';
$l['success_attachment_type_updated'] = '첨부 파일 유형이 성공적으로 업데이트되었습니다.';
$l['success_attachment_type_deleted'] = '첨부 파일 유형이 성공적으로 삭제되었습니다.';
$l['confirm_attachment_type_deletion'] = '이 첨부파일 유형을 삭제하시겠습니까?';
$l['success_activated_attachment_type'] = '선택한 첨부 파일 유형이 성공적으로 활성화되었습니다.';
$l['success_deactivated_attachment_type'] = '선택한 첨부 파일 유형이 성공적으로 비활성화되었습니다.';
$l['enabled'] = '활성화?';
$l['forcedownload'] = '강제 다운로드';
$l['forcedownload_desc'] = '이 기능을 활성화하면 항상 첨부 파일이 파일로 다운로드됩니다.';
$l['avatar_file'] = '아바타 파일';
$l['avatar_file_desc'] = '이 첨부 파일 유형을 아바타에 사용하도록 허용하시겠습니까?';
$l['available_to_groups'] = '그룹에서 이용 가능';
$l['available_in_forums'] = '포럼에서 사용 가능';
