<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 07:34:42 +0000
// --------------------------------------------------------------------------------

$l['banning'] = '차단';
$l['banned_ips'] = '차단된 IP';
$l['banned_ips_desc'] = '여기에서는 보드 액세스가 차단된 IP 주소를 관리할 수 있습니다.';
$l['banned_accounts'] = '차단된 계정';
$l['disallowed_usernames'] = '허용되지 않는 사용자 이름';
$l['disallowed_usernames_desc'] = '여기에서는 사용자가 등록하거나 사용할 수 없는 사용자 이름 목록을 관리합니다. 이 기능은 사용자 이름을 예약하는 데에도 특히 유용합니다.';
$l['disallowed_email_addresses'] = '허용되지 않는 이메일 주소';
$l['disallowed_email_addresses_desc'] = '여기서는 사용자가 등록하거나 사용할 수 없는 이메일 주소 목록을 관리합니다.';
$l['banned_ip_addresses'] = '차단된 IP 주소';
$l['username'] = '사용자 이름';
$l['date_disallowed'] = '허용되지 않는 날짜';
$l['last_attempted_use'] = '마지막 시도 사용';
$l['email_address'] = '이메일 주소';
$l['ip_address'] = 'IP 주소';
$l['ban_date'] = '차단일';
$l['last_access'] = '마지막 접속';
$l['no_bans'] = '현재로서는 차단이 설정되어 있지 않습니다.';
$l['add_disallowed_username'] = '허용되지 않는 사용자 이름 추가';
$l['username_desc'] = '참고: 와일드카드 일치를 나타내려면 *를 사용하십시오.';
$l['disallow_username'] = '사용자 이름을 허용하지 않음';
$l['add_disallowed_email_address'] = '허용되지 않는 이메일 주소 추가';
$l['email_address_desc'] = '참고: 와일드카드 일치를 나타내려면 *를 사용하십시오.';
$l['disallow_email_address'] = '이메일 주소 허용 안함';
$l['ban_an_ip_address'] = 'IP 주소 차단';
$l['ip_address_desc'] = '참고: IP 주소 범위를 금지하려면 *(예: 127.0.0.*) 또는 CIDR 표기법(예: 127.0.0.0/8)을 사용하세요.';
$l['ban_ip_address'] = 'IP 주소 차단';
$l['error_missing_ban_input'] = '차단할 값을 입력하지 않았습니다.';
$l['error_invalid_filter'] = '지정한 필터가 존재하지 않습니다.';
$l['error_filter_already_banned'] = '입력한 필터는 이미 차단되었습니다.';
$l['success_ip_banned'] = 'IP 주소가 성공적으로 차단되었습니다.';
$l['success_username_disallowed'] = '사용자 이름이 허용되지 않았습니다.';
$l['success_email_disallowed'] = '이메일 주소가 허용되지 않았습니다.';
$l['success_ban_deleted'] = '지정된 금지가 성공적으로 삭제되었습니다.';
$l['confirm_ban_deletion'] = '이 차단을 삭제하시겠습니까?';
