<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 00:56:34 +0000
// --------------------------------------------------------------------------------

$l['security_questions'] = '보안 질문';
$l['security_questions_desc'] = '여기서는 등록 중에 무작위로 표시되는 보안 질문을 생성하고 관리할 수 있습니다.';
$l['add_new_question'] = '새 질문 추가';
$l['add_new_question_desc'] = '등록 시 사용할 보안 질문에 대한 질문과 답변을 추가합니다.';
$l['edit_question'] = '질문 편집';
$l['edit_question_desc'] = '여기서 보안 질문을 편집합니다.';
$l['preview_question'] = '질문 미리보기';
$l['options'] = '옵션';
$l['shown'] = '표시됨';
$l['correct'] = '맞음';
$l['incorrect'] = '틀림';
$l['disable_question'] = '질문 비활성화';
$l['enable_question'] = '질문 활성화';
$l['delete_question'] = '질문 삭제';
$l['no_security_questions'] = '현재 귀하의 포럼에는 보안 질문이 없습니다.';
$l['question'] = '질문';
$l['question_desc'] = '등록시 답변을 원하는 질문을 입력하세요.';
$l['answers'] = '답변';
$l['answers_desc'] = '위 질문에 대한 답변을 입력하세요. 각 답변을 별도의 줄에 입력하세요.';
$l['active'] = '활성화';
$l['save_question'] = '질문 저장';
$l['error_invalid_question'] = '잘못된 질문을 선택했습니다.';
$l['error_missing_question'] = '이 질문에 대한 질문을 입력하지 않았습니다.';
$l['error_missing_answer'] = '이 질문에 대한 답변을 입력하지 않았습니다.';
$l['success_question_created'] = '질문이 성공적으로 생성되었습니다.';
$l['success_question_updated'] = '질문이 성공적으로 업데이트되었습니다.';
$l['success_question_disabled'] = '질문이 비활성화되었습니다.';
$l['success_question_enabled'] = '질문이 성공적으로 활성화되었습니다.';
$l['success_question_deleted'] = '질문이 성공적으로 삭제되었습니다.';
$l['confirm_question_deletion'] = '이 질문을 삭제하시겠습니까?';
