<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 00:50:37 +0000
// --------------------------------------------------------------------------------

$l['mod_tools'] = '중재자 도구';
$l['thread_tools'] = '글타래 도구';
$l['thread_tools_desc'] = '사용자 정의 중재자 도구를 사용하면 글타래와 게시물 모두에 사용할 수 있는 중재자 작업 조합을 만들 수 있습니다. 그런 다음 포럼을 관리할 때 기본 도구처럼 사용할 수 있습니다. 여기에서 사용자 정의 글타래 도구를 관리할 수 있습니다.';
$l['add_thread_tool'] = '글타래 도구 추가';
$l['add_new_thread_tool'] = '새 글타래 도구 추가';
$l['add_thread_tool_desc'] = '여기에서 새로운 사용자 정의 글타래 조정 도구를 추가할 수 있습니다. 이 도구는 기본 조정 도구와 함께 나열된 인라인 글타래 조정 및 글타래 자체 내에서 모두 액세스할 수 있습니다.';
$l['post_tools'] = '게시물 도구';
$l['post_tools_desc'] = '사용자 정의 중재자 도구를 사용하면 글타래와 게시물 모두에 사용할 수 있는 중재자 작업 조합을 만들 수 있습니다. 그런 다음 포럼을 관리할 때 기본 도구처럼 사용할 수 있습니다. 여기에서 사용자 정의 게시 도구를 관리할 수 있습니다.';
$l['add_post_tool'] = '게시물 도구 추가';
$l['add_new_post_tool'] = '새 게시물 도구 추가';
$l['add_post_tool_desc'] = '여기에서 새로운 사용자 정의 게시물 조정 도구를 추가할 수 있습니다. 이 도구는 기본 조정 도구와 함께 나열된 글타래 내에서 액세스할 수 있습니다.';
$l['edit_post_tool'] = '게시물 편집 도구';
$l['edit_post_tool_desc'] = '여기에서 게시 도구의 설정과 작업을 편집할 수 있습니다.';
$l['edit_thread_tool'] = '글타래 도구 편집';
$l['edit_thread_tool_desc'] = '여기서 글타래 도구의 설정과 작업을 편집할 수 있습니다.';
$l['no_thread_tools'] = '귀하의 포럼에는 글타래 도구 설정이 없습니다.';
$l['no_post_tools'] = '귀하의 포럼에는 게시 도구 설정이 없습니다.';
$l['confirm_thread_tool_deletion'] = '이 글타래 도구를 삭제하시겠습니까?';
$l['confirm_post_tool_deletion'] = '이 게시 도구를 삭제하시겠습니까?';
$l['success_post_tool_deleted'] = '선택한 게시물 운영자 도구가 성공적으로 삭제되었습니다.';
$l['success_thread_tool_deleted'] = '선택한 글타래 조정 도구가 성공적으로 삭제되었습니다.';
$l['error_invalid_post_tool'] = '지정된 게시 도구가 존재하지 않습니다.';
$l['error_invalid_thread_tool'] = '지정된 글타래 도구가 존재하지 않습니다.';
$l['general_options'] = '일반 옵션';
$l['short_description'] = '간단한 설명';
$l['available_in_forums'] = '포럼에서 사용 가능';
$l['available_to_groups'] = '그룹 이용 가능';
$l['show_confirmation'] = '확인 페이지 표시';
$l['save_thread_tool'] = '글타래 도구 저장';
$l['title'] = '타이틀';
$l['thread_moderation'] = '글타래 조정';
$l['approve_unapprove'] = '글타래를 승인/비승인?';
$l['no_change'] = '변경 없음';
$l['approve'] = '승인';
$l['unapprove'] = '승인 취소';
$l['stick'] = '고정';
$l['unstick'] = '고정해제';
$l['open'] = '열기';
$l['close'] = '닫기';
$l['toggle'] = '토글';
$l['days'] = '일';
$l['no_prefix'] = '접두사 없음';
$l['restore'] = '복원';
$l['softdelete'] = '소프트 삭제';
$l['forum_to_move_to'] = '이동할 포럼:';
$l['leave_redirect'] = '리디렉션을 종료하시겠습니까?';
$l['delete_redirect_after'] = '다음 날짜 이후 리디렉션 삭제';
$l['do_not_move_thread'] = '글타래를 이동하지 않기';
$l['do_not_copy_thread'] = '글타래를 복사하지 않기';
$l['move_thread'] = '글타래를 이동?';
$l['move_thread_desc'] = '글타래를 이동하는 경우 "일 후 리디렉션 삭제"는 리디렉션이 남을 경우에만 채워집니다.';
$l['forum_to_copy_to'] = '복사할 포럼:';
$l['copy_thread'] = '글타래 복사?';
$l['open_close_thread'] = '글타래 열기/닫기?';
$l['stick_unstick_thread'] = '글타래 고정/고정해제?';
$l['softdelete_restore_thread'] = '글타래 소프트 삭제/복원?';
$l['delete_thread'] = '글타래를 영구적으로 삭제?';
$l['merge_thread'] = '글타래를 병합?';
$l['merge_thread_desc'] = '인라인 중재에 사용되는 경우에만 해당됩니다.';
$l['delete_poll'] = '설문조사를 삭제?';
$l['delete_redirects'] = '리디렉션을 삭제?';
$l['remove_subscriptions'] = '글타래 구독을 제거?';
$l['recount_rebuild'] = 'Recount & Rebuild?';
$l['apply_thread_prefix'] = '글타래 접두어를 적용?';
$l['new_subject'] = '새로운 제목?';
$l['new_subject_desc'] = '글타래의 새 제목을 입력합니다.';
$l['subject_message_replacements'] = '대체 사용가능';
$l['subject_message_replacements_desc'] = '{subject}는 원래 제목을 나타냅니다. {username}은 중재자의 사용자 이름을 나타냅니다. {author}는 글타래 작성자의 사용자 이름을 나타냅니다.';
$l['add_new_reply'] = '새 답변 추가';
$l['add_new_reply_desc'] = '응답하지 않으려면 공백으로 두십시오.';
$l['reply_subject'] = '답글 제목.';
$l['reply_subject_desc'] = '응답이 이루어진 경우에만 사용됩니다.';
$l['success_mod_tool_created'] = '조정 도구가 성공적으로 생성되었습니다.';
$l['success_mod_tool_updated'] = '중재 도구가 성공적으로 업데이트되었습니다.';
$l['inline_post_moderation'] = '인라인 게시물 조정';
$l['delete_posts'] = '게시물을 영구적으로 삭제?';
$l['merge_posts'] = '게시물을 병합?';
$l['merge_posts_desc'] = '인라인 중재에서 사용되는 경우에만 해당됩니다.';
$l['approve_unapprove_posts'] = '게시물을 승인/승인 취소?';
$l['softdelete_restore_posts'] = '게시물을 소프트 삭제/복원?';
$l['split_posts'] = '게시물 분할';
$l['split_posts2'] = '게시물을 분할?';
$l['do_not_split'] = '게시물을 분할하지 마십시오';
$l['split_to_same_forum'] = '동일한 포럼으로 분할';
$l['close_split_thread'] = '분할 글타래를 닫기?';
$l['stick_split_thread'] = '분할 글타래 고정?';
$l['unapprove_split_thread'] = '분할 글타래를 승인 취소?';
$l['split_thread_prefix'] = '분할 글타래 접두사';
$l['split_thread_subject'] = '글타래 제목 분할';
$l['split_thread_subject_desc'] = '게시물을 분할하는 경우에만 필요합니다.';
$l['add_new_split_reply'] = '분할 글타래에 답글 추가';
$l['add_new_split_reply_desc'] = '응답하지 않으려면 공백으로 두십시오.';
$l['split_reply_subject'] = '답글 제목';
$l['split_reply_subject_desc'] = '답변이 있는 경우에만 사용됩니다.';
$l['save_post_tool'] = '게시물 도구 저장';
$l['send_private_message'] = '비공개 메시지 보내기';
$l['private_message_message'] = '메시지';
$l['private_message_message_desc'] = '글타래 작성자에게 보낼 메시지입니다. 이 기능을 비활성화하려면 비워 두세요.';
$l['private_message_subject'] = '제목';
$l['private_message_subject_desc'] = '비공개 메시지의 제목을 입력하세요.';
$l['error_missing_title'] = '이 도구의 이름을 입력하세요.';
$l['error_missing_description'] = '이 도구에 대한 간단한 설명을 입력하세요.';
$l['error_no_forums_selected'] = '이 도구를 사용할 수 있는 포럼을 선택하십시오.';
$l['error_no_groups_selected'] = '이 도구를 사용할 수 있는 그룹을 선택하십시오.';
$l['error_forum_is_category'] = '카테고리형 포럼을 대상 포럼으로 선택할 수 없습니다.';
