<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Thu, 04 Jul 2024 04:11:28 +0000
// --------------------------------------------------------------------------------

$l['board_settings'] = '보드 설정';
$l['change_settings'] = '설정 변경';
$l['change_settings_desc'] = '이 섹션에서는 보드와 관련된 다양한 설정을 모두 관리할 수 있습니다. 시작하려면 아래에서 그룹을 선택하여 해당 그룹과 관련된 설정을 관리하세요.';
$l['add_new_setting'] = '새 설정 추가';
$l['add_new_setting_desc'] = '이 섹션에서는 보드에 새 설정을 추가할 수 있습니다.';
$l['modify_existing_settings'] = '설정 수정';
$l['modify_existing_settings_desc'] = '이 섹션에서는 포럼의 기존 설정을 수정할 수 있습니다.';
$l['add_new_setting_group'] = '새 설정 그룹 추가';
$l['add_new_setting_group_desc'] = '이 섹션에서는 설정 그룹을 생성하여 개별 설정을 분류할 수 있습니다.';
$l['edit_setting_group'] = '설정 그룹 편집';
$l['edit_setting_group_desc'] = '이 섹션에서는 기존 설정 그룹을 편집할 수 있습니다.';
$l['title'] = '제목';
$l['description'] = '설명';
$l['group'] = '그룹';
$l['display_order'] = '표시 순서';
$l['name'] = '식별자';
$l['name_desc'] = '이 고유 식별자는 설정 배열에서 이 설정을 참조하는 데 사용됩니다(스크립트, 번역 및 템플릿에서).';
$l['group_name_desc'] = '이 고유 식별자는 번역 시스템에 사용됩니다.';
$l['text'] = '텍스트';
$l['numeric_text'] = '숫자 텍스트';
$l['textarea'] = '텍스트 영역';
$l['yesno'] = '예 / 아니요 선택';
$l['onoff'] = 'On/Off 선택';
$l['select'] = '선택 상자';
$l['radio'] = '라디오 버튼';
$l['checkbox'] = '체크박스';
$l['language_selection_box'] = '언어 선택 상자';
$l['forum_selection_box'] = '포럼 선택 상자';
$l['forum_selection_single'] = '단일 포럼 선택 상자';
$l['group_selection_box'] = '그룹 선택 상자';
$l['group_selection_single'] = '단일 그룹 선택 상자';
$l['adminlanguage'] = '관리 언어 선택 상자';
$l['cpstyle'] = '제어판 스타일 선택 상자';
$l['prefix_selection_box'] = '접두어 선택 상자';
$l['php'] = 'Evaluated PHP';
$l['type'] = '유형';
$l['extra'] = '엑스트라';
$l['extra_desc'] = '이 설정이 선택, 라디오 또는 확인란인 경우 표시할 항목의 키 쌍(키=항목) 목록을 입력하세요. 항목을 새 줄로 구분하세요. PHP인 경우 평가할 PHP를 입력하세요.';
$l['value'] = '값';
$l['insert_new_setting'] = '새 설정 삽입';
$l['edit_setting'] = '설정 편집';
$l['delete_setting'] = '설정 삭제';
$l['setting_configuration'] = '설정 구성';
$l['update_setting'] = '설정 업데이트';
$l['save_settings'] = '설정 저장';
$l['setting_groups'] = '그룹 설정';
$l['bbsettings'] = '설정';
$l['insert_new_setting_group'] = '새 설정 그룹 삽입';
$l['setting_group_setting'] = '그룹 설정/설정';
$l['order'] = '순서';
$l['delete_setting_group'] = '설정 그룹 삭제';
$l['save_display_orders'] = '표시 순서 저장';
$l['update_setting_group'] = '설정 그룹 업데이트';
$l['modify_setting'] = '설정 수정';
$l['search'] = '검색';
$l['plugin_settings'] = '플러그인 설정';
$l['show_all_settings'] = '모든 설정 표시';
$l['settings_search'] = '설정 검색';
$l['confirm_setting_group_deletion'] = '이 설정 그룹을 삭제하시겠습니까?';
$l['confirm_setting_deletion'] = '이 설정을 삭제하시겠습니까?';
$l['error_format_dimension'] = '정의된 {1} 형식이 잘못되었습니다.';
$l['error_field_minnamelength'] = '최소 이름 길이는 최대 이름 길이보다 클 수 없습니다.';
$l['error_field_minpasswordlength'] = '최소 비밀번호 길이는 최대 비밀번호 길이보다 클 수 없습니다.';
$l['error_field_minpasswordlength_complex'] = '복잡한 비밀번호를 사용할 경우 최소 비밀번호 길이는 3자 이상일 수 없습니다.';
$l['error_field_postmaxavatarsize'] = '최대 아바타 크기';
$l['error_field_useravatardims'] = '기본 아바타 크기';
$l['error_field_maxavatardims'] = '최대 아바타 크기';
$l['error_field_memberlistmaxavatarsize'] = '최대 표시 아바타 크기';
$l['error_missing_title'] = '이 설정에 대한 제목을 입력하지 않았습니다.';
$l['error_missing_group_title'] = '이 설정 그룹의 제목을 입력하지 않았습니다.';
$l['error_invalid_gid'] = '이 설정을 적용할 유효한 그룹을 선택하지 않았습니다.';
$l['error_invalid_gid2'] = '잘못된 설정 그룹에 대한 링크를 따라가셨습니다. 존재하는지 확인하세요.';
$l['error_missing_name'] = '이 설정에 대한 식별자를 입력하지 않았습니다.';
$l['error_missing_group_name'] = '이 설정 그룹의 식별자를 입력하지 않았습니다.';
$l['error_invalid_type'] = '이 설정에 유효한 유형을 선택하지 않았습니다.';
$l['error_invalid_sid'] = '지정된 설정이 존재하지 않습니다.';
$l['error_duplicate_name'] = '지정된 식별자는 이미 "{1}" 설정에 사용되었습니다. 고유해야 합니다.';
$l['error_duplicate_group_name'] = '지정된 식별자는 이미 "{1}" 설정 그룹에 사용되었습니다. 고유해야 합니다.';
$l['error_no_settings_found'] = '지정된 검색 문구에 대한 설정을 찾을 수 없습니다.';
$l['error_cannot_edit_default'] = '기본 설정 및 그룹은 편집하거나 제거할 수 없습니다.';
$l['error_cannot_edit_php'] = '이는 편집할 수 없는 특수한 유형의 설정입니다.';
$l['error_ajax_search'] = '설정을 검색하는 중에 문제가 발생:';
$l['error_ajax_unknown'] = '설정을 검색하는 중 알 수 없는 오류가 발생했습니다.';
$l['error_chmod_settings_file'] = '설정 파일 "./inc/settings.php"에는 쓸 수 없습니다. 666으로 CHMOD를 요청하세요.<br />CHMODing에 대한 자세한 내용은 <a href="https://docs.mybb.com/1.8/administration/security/file-permissions" target="_blank" rel="을 참조하세요. noopener">MyBB 문서</a>.';
$l['error_admin_email_settings_empty'] = '<div class="smalltext" style="font-weight: Normal;">설정은 비워 둘 수 없으며 유효한 이메일 주소여야 하므로 <strong>관리자 이메일</strong>은 저장되지 않았습니다. </div>';
$l['success_setting_added'] = '설정이 성공적으로 생성되었습니다.';
$l['success_setting_updated'] = '설정이 성공적으로 업데이트되었습니다.';
$l['success_setting_deleted'] = '선택한 설정이 성공적으로 삭제되었습니다.';
$l['success_settings_updated'] = '설정이 성공적으로 업데이트되었습니다.';
$l['success_settings_updated_hiddencaptchaimage'] = '<div class="smalltext" style="font-weight: Normal;">충돌로 인해 <strong>숨겨진 CAPTCHA 필드</strong> 설정이 <strong>{1}</strong>로 되돌아갔습니다. 등록 양식의 <strong>{2}</strong> 필드를 사용하세요.</div>';
$l['success_settings_updated_username_method_conflict'] = '<div class="smalltext" style="font-weight: Normal;">현재 이메일을 여러 번 등록할 수 있으므로 <b>허용된 로그인 방법</b> 설정이 업데이트되지 않았습니다.</ div>';
$l['success_settings_updated_username_method'] = '<div class="smalltext" style="font-weight: Normal;">현재 여러 사용자가 동일한 이메일 주소를 사용하고 있기 때문에 <b>허용된 로그인 방법</b> 설정이 업데이트되지 않았습니다. .</div>';
$l['success_settings_updated_allowmultipleemails'] = '<div class="smalltext" style="font-weight: Normal;"><b>이메일을 여러 번 등록하도록 허용하시겠습니까?</b> 설정은 <b>로그인 허용이 설정되어 있으므로 활성화할 수 없습니다. 방법</b> 설정을 통해 사용자는 이메일 주소로 로그인할 수 있습니다.</div>';
$l['success_settings_updated_captchaimage'] = '<div class="smalltext" style="font-weight: Normal;">등록 및amp; 게시</strong> 설정이 공개/개인 키 부족으로 인해 <strong>MyBB 기본 보안문자</strong>로 되돌아갔습니다.</div>';
$l['success_settings_updated_minsearchword'] = '<div class="smalltext" style="font-weight: Normal;"><strong>최소 검색어 길이</strong> 설정은 데이터베이스 시스템 구성과 일치하도록 설정되어 있습니다.</div>';
$l['success_display_orders_updated'] = '설정 표시 순서가 성공적으로 업데이트되었습니다.';
$l['success_setting_group_added'] = '설정 그룹이 성공적으로 생성되었습니다.';
$l['success_setting_group_updated'] = '설정 그룹이 성공적으로 업데이트되었습니다.';
$l['success_setting_group_deleted'] = '선택한 설정 그룹이 성공적으로 삭제되었습니다.';
$l['success_duplicate_settings_deleted'] = '모든 중복 설정 그룹이 성공적으로 삭제되었습니다.';
$l['searching'] = '검색 중&hellip;';
$l['search_error'] = '검색결과를 가져오는 중에 오류 발생:';
$l['search_done'] = '완료!';
