<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 08:15:41 +0000
// --------------------------------------------------------------------------------

$l['post_icons'] = '게시물 아이콘';
$l['add_post_icon'] = '새 게시물 아이콘 추가';
$l['add_post_icon_desc'] = '여기에 하나의 새 게시물 아이콘을 추가할 수 있습니다.';
$l['add_multiple_post_icons'] = '여러 게시물 아이콘 추가';
$l['add_multiple_post_icons_desc'] = '여기에서 여러 개의 새 게시물 아이콘을 추가할 수 있습니다.';
$l['edit_post_icon'] = '게시물 아이콘 편집';
$l['edit_post_icon_desc'] = '여기서 게시물 아이콘을 편집할 수 있습니다.';
$l['manage_post_icons'] = '게시물 아이콘 관리';
$l['manage_post_icons_desc'] = '이 섹션에서는 게시물 아이콘을 편집, 삭제 및 관리할 수 있습니다.';
$l['name_desc'] = '게시물 아이콘의 이름입니다.';
$l['image_path'] = '이미지 경로';
$l['image_path_desc'] = '게시물 아이콘 이미지 경로입니다. 테마별로 다른 게시물 아이콘 이미지를 사용하려면 <strong>{theme}</strong>을 사용하여 각 테마의 이미지 디렉토리를 나타내세요.';
$l['save_post_icon'] = '게시물 아이콘 저장';
$l['reset'] = '리셋';
$l['path_to_images'] = '이미지 경로';
$l['path_to_images_desc'] = '이미지가 들어있는 폴더 경로입니다.';
$l['show_post_icons'] = '게시물 아이콘 표시';
$l['image'] = '이미지';
$l['add'] = '추가?';
$l['save_post_icons'] = '게시물 아이콘 저장';
$l['no_post_icons'] = '현재 귀하의 포럼에는 게시물 아이콘이 없습니다.';
$l['error_missing_name'] = '이 게시물 아이콘의 이름을 입력하지 않았습니다.';
$l['error_missing_path'] = '이 게시물 아이콘의 경로를 입력하지 않았습니다.';
$l['error_missing_path_multiple'] = '경로를 입력하지 않았습니다.';
$l['error_invalid_path'] = '유효한 경로를 입력하지 않았습니다.';
$l['error_no_images'] = '지정된 디렉터리에 게시물 아이콘이 없거나 디렉터리의 모든 게시물 아이콘이 이미 추가되었습니다.';
$l['error_none_included'] = '포함할 게시물 아이콘을 선택하지 않았습니다.';
$l['error_invalid_post_icon'] = '지정한 게시물 아이콘이 존재하지 않습니다.';
$l['success_post_icon_added'] = '게시물 아이콘이 성공적으로 추가되었습니다.';
$l['success_post_icons_added'] = '선택한 게시물 아이콘이 성공적으로 추가되었습니다.';
$l['success_post_icon_updated'] = '게시물 아이콘이 성공적으로 업데이트되었습니다.';
$l['success_post_icon_deleted'] = '선택한 게시물 아이콘이 성공적으로 삭제되었습니다.';
$l['confirm_post_icon_deletion'] = '이 게시물 아이콘을 삭제하시겠습니까?';
