<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 08:23:16 +0000
// --------------------------------------------------------------------------------

$l['custom_profile_fields'] = '사용자 정의 프로필 필드';
$l['custom_profile_fields_desc'] = '이 섹션에서는 사용자 정의 프로필 필드를 편집, 삭제 및 관리할 수 있습니다.';
$l['add_profile_field'] = '프로필 필드 추가';
$l['add_new_profile_field'] = '새 프로필 필드 추가';
$l['add_new_profile_field_desc'] = '여기에서 새로운 사용자 정의 프로필 필드를 추가할 수 있습니다.';
$l['edit_profile_field'] = '프로필 필드 편집';
$l['edit_profile_field_desc'] = '여기에서 사용자 정의 프로필 필드를 편집할 수 있습니다.';
$l['title'] = '제목';
$l['short_description'] = '간단한 설명';
$l['maximum_length'] = '최대 길이';
$l['maximum_length_desc'] = '입력할 수 있는 최대 문자 수입니다. 이는 텍스트 상자와 텍스트 영역에만 적용됩니다.';
$l['field_length'] = '필드 길이';
$l['field_length_desc'] = '이 길이의 필드입니다. 이는 단일 및 다중 선택 상자에만 적용됩니다.';
$l['display_order'] = '표시 순서';
$l['display_order_desc'] = '다른 사용자 정의 프로필 필드와 관련된 사용자 정의 프로필 필드의 순서입니다. 이 숫자는 다른 필드와 동일하면 안 됩니다.';
$l['text'] = '텍스트 상자';
$l['textarea'] = '텍스트 영역';
$l['select'] = '선택 상자';
$l['multiselect'] = '다중 옵션 선택 상자';
$l['radio'] = '라디오 버튼';
$l['checkbox'] = '체크박스';
$l['field_type'] = '필드 유형';
$l['field_type_desc'] = '표시될 필드 유형입니다.';
$l['field_regex'] = '정규식';
$l['field_regex_desc'] = '사용자 입력과 일치해야 하는 정규식을 입력하세요. 정규식이 유효하고 안전한지 확인해야 하며 유효성 검사는 수행되지 않습니다. 무엇이든 비워두세요.<br />
<strong>예:</strong> ([a-z0-9_\\- ,.+]+)';
$l['selectable_options'] = '선택 가능한 옵션?';
$l['selectable_options_desc'] = '각 옵션을 별도의 줄에 입력하세요. 이는 선택 상자, 확인란 및 라디오 버튼 유형에만 적용됩니다.';
$l['required'] = '필수 여부?';
$l['required_desc'] = '등록 또는 프로필 편집 중에 이 필드를 채워야 합니까? 필드가 숨겨져 있거나 필드를 편집할 수 없는 경우에는 이 사항이 적용되지 않습니다.';
$l['show_on_registration'] = '등록 시 표시하시겠습니까?';
$l['show_on_registration_desc'] = '이 필드를 등록 양식에 표시해야 합니까? 필드를 편집할 수 없는 경우에는 이 사항이 적용되지 않습니다. 필수 필드는 등록 시 항상 나타납니다.';
$l['display_on_profile'] = '프로필에 표시하시겠습니까?';
$l['display_on_profile_desc'] = '이 필드를 사용자 프로필에 표시할까요?';
$l['display_on_postbit'] = '포스트비트에 표시할까요?';
$l['display_on_postbit_desc'] = '이 필드를 사용자 게시물에 표시할까요?';
$l['viewableby'] = '볼 수 있는 사람';
$l['viewableby_desc'] = '이 프로필 필드를 보려면 허용된 그룹을 선택하세요.';
$l['editableby'] = '편집 가능자';
$l['editableby_desc'] = '이 프로필 필드를 편집하도록 허용된 그룹을 선택하세요.';
$l['min_posts_enabled'] = '최소 게시물 수?';
$l['min_posts_enabled_desc'] = '이 필드는 특정 게시물 수를 가진 사용자에게만 제공되어야 합니까? 그렇다면 여기에서 필요한 최소 게시물 수를 설정하세요.';
$l['parser_options'] = '파서 옵션';
$l['parse_allowhtml'] = '예, 이 프로필 필드에 HTML을 허용합니다.';
$l['parse_allowmycode'] = '예, 이 프로필 필드에 MyCode를 허용합니다.';
$l['parse_allowsmilies'] = '예, 이 프로필 필드에 스마일리를 허용합니다.';
$l['parse_allowimgcode'] = '예, 이 프로필 필드에 [img] 코드를 허용합니다.';
$l['parse_allowvideocode'] = '예, 이 프로필 필드에 [video] 코드를 허용합니다.';
$l['save_profile_field'] = '프로필 필드 저장';
$l['name'] = '이름';
$l['registration'] = '등록?';
$l['editable'] = '편집 가능?';
$l['profile'] = '프로필?';
$l['postbit'] = '포스트빗?';
$l['edit_field'] = '필드 편집';
$l['delete_field'] = '필드 삭제';
$l['no_profile_fields'] = '현재 귀하의 포럼에는 사용자 정의 프로필 필드가 없습니다.';
$l['error_missing_name'] = '이 사용자 정의 프로필 필드에 제목을 입력하지 않았습니다.';
$l['error_missing_description'] = '이 사용자 정의 프로필 필드에 대한 설명을 입력하지 않았습니다.';
$l['error_invalid_fid'] = '선택한 프로필 필드가 존재하지 않습니다.';
$l['success_profile_field_added'] = '사용자 정의 프로필 필드가 성공적으로 생성되었습니다.';
$l['success_profile_field_saved'] = '사용자 정의 프로필 필드가 성공적으로 저장되었습니다.';
$l['success_profile_field_deleted'] = '선택한 사용자 정의 프로필 필드가 성공적으로 삭제되었습니다.';
$l['confirm_profile_field_deletion'] = '이 프로필 필드를 삭제하시겠습니까?';
