<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 00:31:24 +0000
// --------------------------------------------------------------------------------

$l['calendars'] = '달력';
$l['manage_calendars'] = '달력 관리';
$l['manage_calendars_desc'] = '이 섹션에서는 보드의 달력을 관리할 수 있습니다. 하나 이상의 캘린더에 대한 표시 순서를 변경하는 경우 페이지 하단에 있는 양식을 제출해야 합니다.';
$l['add_calendar'] = '새 달력 추가';
$l['add_calendar_desc'] = '여기에서 새 달력을 만들 수 있습니다.';
$l['edit_calendar'] = '달력 편집';
$l['edit_calendar_desc'] = '여기에서 이 달력의 설정을 편집할 수 있습니다.';
$l['calendar'] = '달력';
$l['order'] = '순서';
$l['no_calendars'] = '현재 귀하의 포럼에는 캘린더가 없습니다.';
$l['save_calendar_orders'] = '달력 표시 순서 저장';
$l['name'] = '이름';
$l['display_order'] = '표시 순서';
$l['display_order_desc'] = '달력 선택에 달력이 표시되는 순서입니다. 표시 순서가 1인 달력이 기본적으로 달력 페이지에 표시됩니다.';
$l['week_start'] = '주의 시작';
$l['week_start_desc'] = '여기에서 이 달력에 대해 주가 시작되는 요일을 설정할 수 있습니다.';
$l['sunday'] = '일요일';
$l['monday'] = '월요일';
$l['tuesday'] = '화요일';
$l['wednesday'] = '수요일';
$l['thursday'] = '목요일';
$l['friday'] = '금요일';
$l['saturday'] = '토요일';
$l['event_limit'] = '이벤트 제한';
$l['event_limit_desc'] = '특정 날짜의 모든 이벤트에 대한 단일 링크가 표시되기 전에 표시될 이벤트 수가 대신 표시됩니다.';
$l['show_birthdays'] = '생일을 표시하시겠습니까?';
$l['show_birthdays_desc'] = '이 캘린더에 등록된 사용자의 생일을 표시하시겠습니까?';
$l['moderate_events'] = 'Moderate New Events?';
$l['moderate_events_desc'] = '이 옵션을 \'예\'로 설정하면 캘린더 권한에 \'조정 대기열 우회\'가 설정된 구성원이 만든 이벤트를 제외한 모든 이벤트가 조정됩니다.';
$l['allow_html'] = '이벤트에서 HTML을 허용하시겠습니까?';
$l['allow_mycode'] = '이벤트에서 MyCode를 허용하시겠습니까?';
$l['allow_img'] = '이벤트에 [IMG] 코드를 허용하시겠습니까?';
$l['allow_video'] = '이벤트에 [VIDEO] 코드를 허용하시겠습니까?';
$l['allow_smilies'] = '이벤트에서 스마일리를 허용하시겠습니까?';
$l['save_calendar'] = '달력 저장';
$l['permissions'] = '권한';
$l['edit_permissions'] = '캘린더 권한 편집';
$l['calendar_permissions_for'] = '다음에 대한 캘린더 권한';
$l['permissions_group'] = '그룹';
$l['permissions_view'] = '보기';
$l['permissions_post_events'] = '이벤트 게시';
$l['permissions_bypass_moderation'] = 'Bypass Moderation';
$l['permissions_moderator'] = '운영자 권한';
$l['permissions_all'] = '모두?';
$l['permissions_use_group_default'] = '그룹 기본값 사용';
$l['save_permissions'] = '권한 저장';
$l['error_invalid_calendar'] = '지정한 달력이 존재하지 않습니다.';
$l['error_missing_name'] = '이 캘린더의 이름을 입력하지 않았습니다.';
$l['error_missing_order'] = '이 캘린더의 표시 순서를 입력하지 않았습니다.';
$l['success_calendar_created'] = '달력이 성공적으로 생성되었습니다.';
$l['success_calendar_updated'] = '달력이 성공적으로 업데이트되었습니다.';
$l['success_calendar_permissions_updated'] = '캘린더 권한이 성공적으로 업데이트되었습니다.';
$l['success_calendar_deleted'] = '선택한 캘린더가 성공적으로 삭제되었습니다.';
$l['success_calendar_orders_updated'] = '달력 표시 순서가 성공적으로 업데이트되었습니다.';
$l['confirm_calendar_deletion'] = '이 캘린더를 삭제하시겠습니까?';
