<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 07:30:14 +0000
// --------------------------------------------------------------------------------

$l['bad_words'] = '단어 필터';
$l['edit_bad_word'] = '필터 편집';
$l['edit_bad_word_desc'] = '여기에서 필터와 교체를 편집할 수 있습니다.';
$l['bad_word_filters'] = '단어 필터';
$l['bad_word_filters_desc'] = '이 기능을 사용하면 포럼 게시물에서 자동으로 대체되는 단어나 문구 목록을 관리할 수 있습니다. 욕설 등을 대체하는 데 유용합니다.';
$l['bad_word'] = '단어';
$l['bad_word_desc'] = '필터링하려는 단어를 입력하세요. \'*\' 기호는 모든 문자 수를 나타내고 \'+\' 기호는 단일 문자(공백 및 새 줄 제외)를 나타냅니다.';
$l['bad_word_max'] = '필터링된 단어는 100자를 초과할 수 없습니다.';
$l['replacement'] = '대체 단어';
$l['replacement_desc'] = '필터링된 단어를 대체할 문자열을 입력합니다(공백인 경우 별표가 표시됩니다).';
$l['regex'] = '정규식';
$l['regex_desc'] = '"Word" 필드를 정규식으로 처리합니다.';
$l['replacement_word_max'] = '대체 단어는 100자를 초과할 수 없습니다.';
$l['error_replacement_word_invalid'] = '대체 단어는 해당 단어 필터와 동일할 수 없습니다.';
$l['save_bad_word'] = '필터 저장';
$l['no_bad_words'] = '현재로서는 설정된 단어 필터가 없습니다.';
$l['add_bad_word'] = '필터 추가';
$l['add_bad_word_desc'] = '여기에서 단어 필터와 대체 단어를 추가할 수 있습니다.';
$l['error_missing_bad_word'] = '단어필터를 입력하지 않았습니다.';
$l['error_invalid_regex'] = '지정된 정규 표현식이 잘못되었습니다.';
$l['error_invalid_bid'] = '지정한 필터가 존재하지 않습니다.';
$l['error_bad_word_filtered'] = '입력한 필터가 이미 존재합니다.';
$l['success_added_bad_word'] = '필터가 성공적으로 추가되었습니다.';
$l['success_deleted_bad_word'] = '필터가 성공적으로 삭제되었습니다.';
$l['success_updated_bad_word'] = '필터가 성공적으로 업데이트되었습니다.';
$l['confirm_bad_word_deletion'] = '이 필터를 삭제하시겠습니까?';
