<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 08:12:14 +0000
// --------------------------------------------------------------------------------

$l['plugins'] = '플러그인';
$l['plugins_desc'] = '이 섹션에서는 포럼의 <strong>inc/plugins</strong> 디렉토리에 업로드한 플러그인을 활성화, 비활성화 및 관리할 수 있습니다. 플러그인을 보기에서 숨기되 저장된 정보는 잃지 않으려면 비활성화 링크를 클릭하세요.';
$l['plugin_updates'] = '플러그인 업데이트';
$l['plugin_updates_desc'] = '이 섹션에서는 모든 플러그인의 업데이트를 확인할 수 있습니다.';
$l['browse_plugins'] = '플러그인 찾아보기';
$l['browse_plugins_desc'] = '여기에서 MyBB 시리즈와 호환되는 플러그인에 대한 공식 MyBB 수정 사이트를 찾아볼 수 있습니다.';
$l['browse_all_plugins'] = '모든 플러그인 찾아보기';
$l['plugin'] = '플러그인';
$l['active_plugin'] = '활성 플러그인';
$l['inactive_plugin'] = '비활성 플러그인';
$l['your_version'] = '현재 버전';
$l['latest_version'] = '최신 버전';
$l['download'] = '다운로드';
$l['deactivate'] = '비활성화';
$l['activate'] = '활성화';
$l['install_and_activate'] = '설치 &amp; 활성화';
$l['uninstall'] = '제거';
$l['created_by'] = '작성자:';
$l['no_plugins'] = '현재 귀하의 포럼에는 플러그인이 없습니다.';
$l['no_active_plugins'] = '귀하의 포럼에 활성화된 플러그인이 없습니다.';
$l['no_inactive_plugins'] = '사용 가능한 비활성 플러그인이 없습니다.';
$l['plugin_incompatible'] = '이 플러그인은 MyBB {1}과(와) 호환되지 않습니다';
$l['recommended_plugins_for_mybb'] = 'MyBB {1}에 권장되는 플러그인';
$l['browse_results_for_mybb'] = 'MyBB {1}에 대한 결과 찾아보기';
$l['search_for_plugins'] = '플러그인 검색';
$l['search'] = '검색';
$l['error_vcheck_no_supported_plugins'] = '설치된 플러그인 중 버전 확인을 지원하는 플러그인이 없습니다.';
$l['error_vcheck_communications_problem'] = 'MyBB 수정 버전 서버와 통신하는 중에 문제가 발생했습니다. 몇 분 후에 다시 시도하십시오.';
$l['error_vcheck_vulnerable'] = '[취약한 플러그인]:';
$l['error_vcheck_vulnerable_notes'] = '이 제출물은 현재 MyBB 직원에 의해 취약한 것으로 표시되었습니다. 이 수정 사항을 완전히 제거하는 것이 좋습니다. 아래 참고 사항을 참조하세요.';
$l['error_no_input'] = '오류 코드 1: 입력이 지정되지 않았습니다.';
$l['error_no_pids'] = '오류 코드 2: 플러그인 ID가 지정되지 않았습니다.';
$l['error_communication_problem'] = 'MyBB 수정 서버와 통신하는 중에 문제가 발생했습니다. 몇 분 후에 다시 시도하십시오.';
$l['error_invalid_plugin'] = '선택한 플러그인이 존재하지 않습니다.';
$l['error_no_results_found'] = '지정한 키워드에 대한 결과를 찾을 수 없습니다.';
$l['success_plugins_up_to_date'] = '축하합니다. 모든 플러그인이 최신 상태입니다.';
$l['success_plugin_activated'] = '선택한 플러그인이 성공적으로 활성화되었습니다.';
$l['success_plugin_deactivated'] = '선택한 플러그인이 성공적으로 비활성화되었습니다.';
$l['success_plugin_installed'] = '선택한 플러그인이 성공적으로 설치 및 활성화되었습니다.';
$l['success_plugin_uninstalled'] = '선택한 플러그인이 성공적으로 제거되었습니다.';
