<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 04:41:25 +0000
// --------------------------------------------------------------------------------

$l['thread_prefixes'] = '글타래 접두어';
$l['thread_prefixes_in'] = '"{1}"의 글타래 접두어';
$l['thread_prefixes_desc'] = '글타래 접두어를 사용하면 사용자가 글타래에 할당할 수 있는 접두어를 정의할 수 있습니다. 그런 다음 포럼 내에서 접두어를 기준으로 글타래를 필터링할 수 있습니다.';
$l['add_new_thread_prefix'] = '새 글타래 접두어 추가';
$l['add_new_thread_prefix_desc'] = '여기에서 새 글타래 접두어를 추가하고 이를 사용할 수 있는 위치와 이를 사용할 수 있는 사용자 그룹을 정의할 수 있습니다.';
$l['edit_prefix'] = '접두어 편집';
$l['edit_prefix_desc'] = '여기에서 글타래 접두어를 편집하고 표시 방법, 사용 가능한 위치 및 이를 사용할 수 있는 사용자 그룹을 변경할 수 있습니다.';
$l['edit_thread_prefix'] = '글타래 접두어 편집';
$l['delete_thread_prefix'] = '글타래 접두사 삭제';
$l['prefix_options'] = '접두어 옵션';
$l['save_thread_prefix'] = '글타래 접두어 저장';
$l['prefix'] = '접두어';
$l['forums'] = '포럼에서 사용 가능';
$l['prefix_desc'] = '선택 메뉴에 표시될 접두어의 일반 텍스트 버전입니다.';
$l['display_style'] = '디스플레이 스타일';
$l['display_style_desc'] = '긑타래 제목 옆에 접두어가 표시되는 방식입니다. 여기에 HTML 마크업을 입력하거나 위의 일반 텍스트 버전과 동일하게 사용할 수 있습니다.';
$l['available_in_forums'] = '포럼에서 사용 가능';
$l['available_to_groups'] = '그룹 이용 가능';
$l['no_thread_prefixes'] = '글타래 접두어 설정이 없습니다.';
$l['confirm_thread_prefix_deletion'] = '이 글타래 접두어를 삭제하시겠습니까? 참고: 삭제 후 이 접두어를 사용하는 사용자 정의 중재자 도구를 업데이트해야 합니다.';
$l['success_thread_prefix_created'] = '글타래 접두어가 성공적으로 생성되었습니다.';
$l['success_thread_prefix_updated'] = '글타래 접두어가 성공적으로 업데이트되었습니다.';
$l['success_thread_prefix_deleted'] = '글타래 접두어가 성공적으로 삭제되었습니다. 이 접두어를 사용하는 맞춤 중재자 도구를 업데이트하세요.';
$l['error_missing_prefix'] = '추가하려는 접두어를 입력하세요.';
$l['error_missing_display_style'] = '이 접두어의 표시 스타일을 입력하세요.';
$l['error_no_forums_selected'] = '이 접두어를 사용할 수 있는 포럼을 선택하세요.';
$l['error_no_groups_selected'] = '이 접두어를 사용할 수 있는 그룹을 선택하세요.';
$l['error_invalid_prefix'] = '지정된 글타래 접두어가 존재하지 않습니다.';
