<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Thu, 04 Jul 2024 04:12:28 +0000
// --------------------------------------------------------------------------------

$l['moderation_queue'] = '중재 대기열';
$l['threads'] = '글타래';
$l['threads_desc'] = '여기에서 중재 대기열의 글타래를 보고 승인할 수 있습니다.';
$l['posts'] = '게시물';
$l['posts_desc'] = '여기에서 중재 대기열에 있는 게시물을 보고 승인할 수 있습니다.';
$l['attachments'] = '첨부파일';
$l['attachments_desc'] = '여기에서 검토 대기열의 첨부 파일을 보고 승인할 수 있습니다.';
$l['threads_awaiting_moderation'] = '검토 대기 중인 글타래';
$l['posts_awaiting_moderation'] = '검토 대기 중인 게시물';
$l['attachments_awaiting_moderation'] = '검토 대기 중인 첨부 파일';
$l['error_no_posts'] = '현재 검토 대기 중인 게시물이 없습니다.';
$l['error_no_attachments'] = '현재 검토 대기 중인 첨부 파일이 없습니다.';
$l['error_no_threads'] = '현재 조정 대기 중인 글타래, 게시물 또는 첨부 파일이 없습니다.';
$l['success_threads'] = '선택한 게시물이 성공적으로 검토되었습니다.';
$l['success_posts'] = '선택한 게시물이 성공적으로 검토되었습니다.';
$l['success_attachments'] = '선택한 첨부 파일이 성공적으로 검토되었습니다.';
$l['subject'] = '제목';
$l['author'] = '작성자';
$l['posted'] = '게시됨';
$l['ignore'] = '무시';
$l['approve'] = '승인';
$l['forum'] = '포럼:';
$l['thread'] = '글타래:';
$l['post'] = '게시물:';
$l['re'] = '답:';
$l['filename'] = '파일 이름';
$l['uploadedby'] = '업로드한 사람';
$l['controls'] = '컨트롤';
$l['mark_as_ignored'] = '모두 무시로 표시';
$l['mark_as_deleted'] = '모두 삭제 대상으로 표시';
$l['mark_as_approved'] = '모두 승인됨으로 표시';
$l['perform_action'] = '작업 수행';
