<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 05:03:45 +0000
// --------------------------------------------------------------------------------

$l['forums_and_posts'] = '포럼 &amp; 게시물';
$l['forum_management'] = '포럼 관리';
$l['forum_announcements'] = '포럼 공지';
$l['moderation_queue'] = '중재 대기열';
$l['attachments'] = '첨부파일';
$l['can_manage_forums'] = '포럼을 관리할 수 있나요?';
$l['can_manage_forum_announcements'] = '포럼 공지사항을 관리할 수 있나요?';
$l['can_moderate'] = '게시물, 글타래, 첨부 파일을 검토할 수 있나요?';
$l['can_manage_attachments'] = '첨부파일을 관리할 수 있나요?';
