<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 04:46:28 +0000
// --------------------------------------------------------------------------------

$l['forum_announcements'] = '포럼 공지';
$l['forum_announcements_desc'] = '여기서 게시판의 공지사항을 관리할 수 있습니다. 글로벌 공지사항은 모든 포럼에 표시되는 반면, 개별 포럼에 설정된 공지사항은 해당 포럼과 모든 하위 포럼에 표시됩니다.';
$l['add_announcement'] = '공지사항 추가';
$l['add_announcement_desc'] = '여기에서 단일 포럼 또는 모든 포럼에 대한 공지사항을 추가할 수 있습니다.';
$l['update_announcement'] = '공지사항 업데이트';
$l['preview_announcement'] = '공지사항 미리보기';
$l['update_announcement_desc'] = '여기에서 공지사항 세부정보를 업데이트할 수 있습니다.';
$l['start_date_desc'] = '이 날짜와 시간(GMT 기준)에 공지사항이 선택한 포럼에 표시됩니다.';
$l['end_date_desc'] = '이 날짜와 시간(GMT 기준)에 공지사항이 포럼에서 숨겨집니다. 공지사항을 삭제하거나 종료일을 편집할 때까지 이 공지사항을 종료하지 않도록 선택할 수 있습니다.';
$l['forums_to_appear_in_desc'] = '공지 사항은 아래에서 선택한 포럼에 표시됩니다. 공지사항은 선택한 포럼과 선택한 포럼의 모든 하위 포럼에 표시됩니다.';
$l['announcement'] = '공지';
$l['global_announcements'] = '글로벌 공지';
$l['no_global_announcements'] = '현재 글로벌 포럼 공지가 없습니다.';
$l['no_forums'] = '현재 포럼 공지사항을 표시할 포럼 설정이 없습니다.';
$l['confirm_announcement_deletion'] = '이 공지사항을 삭제하시겠습니까?';
$l['success_announcement_deleted'] = '선택한 공지사항이 성공적으로 삭제되었습니다.';
$l['success_added_announcement'] = '선택한 공지사항이 성공적으로 생성되었습니다.';
$l['success_updated_announcement'] = '선택한 공지사항이 성공적으로 업데이트되었습니다.';
$l['error_invalid_announcement'] = '유효한 공지사항을 입력해 주세요.';
$l['error_missing_title'] = '제목을 입력하지 않았습니다.';
$l['error_missing_message'] = '메시지를 입력하지 않았습니다.';
$l['error_missing_forum'] = '포럼을 선택하지 않았습니다.';
$l['error_invalid_start_date'] = '공지사항의 시작일이 잘못되었습니다.';
$l['error_invalid_end_date'] = '공지사항의 종료일이 잘못되었습니다.';
$l['error_end_before_start'] = '종료일은 시작일 이후여야 합니다.';
$l['add_an_announcement'] = '공지사항 추가';
$l['update_an_announcement'] = '공지사항 업데이트';
$l['save_announcement'] = '공지사항 저장';
$l['title'] = '제목';
$l['start_date'] = '시작일';
$l['end_date'] = '종료일';
$l['message'] = '메시지';
$l['forums_to_appear_in'] = '표시되는 포럼';
$l['allow_html'] = 'HTML을 허용?';
$l['allow_mycode'] = 'MyCode를 허용?';
$l['allow_smilies'] = '스마일리를 허용?';
$l['time'] = '시간:';
$l['set_time'] = '시간 설정';
$l['announcement_preview'] = '공지사항 미리보기';
