<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 04:58:17 +0000
// --------------------------------------------------------------------------------

$l['attachments'] = '첨부파일';
$l['stats'] = '통계';
$l['find_attachments'] = '첨부파일 찾기';
$l['find_attachments_desc'] = '첨부 파일 검색 시스템을 사용하면 사용자가 귀하의 포럼에 첨부한 특정 파일을 검색할 수 있습니다. 아래에 검색어를 입력하여 시작하세요. 모든 필드는 선택 사항이며 값이 포함되어 있지 않으면 기준에 포함되지 않습니다.';
$l['find_orphans'] = '분리된 첨부파일 찾기';
$l['find_orphans_desc'] = '분리된 첨부 파일은 어떤 이유로 데이터베이스나 파일 시스템에서 누락된 첨부 파일입니다. 이 유틸리티는 해당 항목을 찾아 제거하는 데 도움이 됩니다.';
$l['attachment_stats'] = '첨부파일 통계';
$l['attachment_stats_desc'] = '다음은 현재 포럼에 있는 첨부 파일에 대한 몇 가지 일반적인 통계입니다.';
$l['error_nothing_selected'] = '삭제할 첨부 파일을 하나 이상 선택하세요.';
$l['error_no_attachments'] = '포럼에 아직 첨부파일이 없습니다. 첨부 파일이 게시되면 이 섹션에 액세스할 수 있습니다.';
$l['error_not_all_removed'] = '일부 분리된 첨부 파일만 성공적으로 삭제되었으며 다른 첨부 파일은 업로드 디렉터리에서 제거할 수 없습니다.';
$l['error_count'] = '첨부 파일 {1}개를 제거할 수 없습니다.';
$l['error_invalid_username'] = '입력한 사용자 이름이 잘못되었습니다.';
$l['error_invalid_forums'] = '선택한 하나 이상의 포럼이 잘못되었습니다.';
$l['error_no_results'] = '지정된 검색 기준에 맞는 첨부 파일을 찾을 수 없습니다.';
$l['error_not_found'] = '업로드 디렉터리에서 첨부 파일을 찾을 수 없습니다.';
$l['error_not_attached'] = '첨부파일이 업로드된 지 24시간이 넘었지만 게시물에 첨부되지 않았습니다.';
$l['error_does_not_exist'] = '이 첨부 파일에 대한 스레드나 게시물이 더 이상 존재하지 않습니다.';
$l['success_deleted'] = '선택한 첨부 파일이 성공적으로 삭제되었습니다.';
$l['success_orphan_deleted'] = '선택한 분리된 첨부 파일이 성공적으로 삭제되었습니다.';
$l['success_count'] = '{1}개의 첨부 파일이 성공적으로 제거되었습니다.';
$l['success_no_orphans'] = '귀하의 포럼에는 분리된 첨부 파일이 없습니다.';
$l['confirm_delete'] = '선택한 첨부파일을 삭제하시겠습니까?';
$l['general_stats'] = '일반통계';
$l['stats_attachment_stats'] = '첨부 파일 - 첨부 파일 통계';
$l['num_uploaded'] = '<strong>아니요. 업로드된 첨부파일</strong>';
$l['space_used'] = '<strong>사용된 첨부 공간</strong>';
$l['bandwidth_used'] = '<strong>예상 대역폭 사용량</strong>';
$l['average_size'] = '<strong>평균 첨부파일 크기</strong>';
$l['size'] = '크기';
$l['posted_by'] = '게시자';
$l['thread'] = '글타래래';
$l['downloads'] = '다운로드';
$l['date_uploaded'] = '업로드된 날짜';
$l['popular_attachments'] = '가장 인기 있는 첨부 파일 상위 5개';
$l['largest_attachments'] = '가장 큰 첨부 파일 상위 5개';
$l['users_diskspace'] = '가장 많은 디스크 공간을 사용하는 상위 5명의 사용자';
$l['username'] = '사용자 이름';
$l['total_size'] = '전체 크기';
$l['orphan_results'] = '분리된 첨부 파일 검색 - 결과';
$l['orphan_attachments_search'] = '분리된 첨부파일 검색';
$l['reason_orphaned'] = '분리가 된 이유';
$l['reason_not_in_table'] = '첨부파일 표에 없음';
$l['reason_file_missing'] = '첨부파일이 없습니다';
$l['reason_thread_deleted'] = '글타래가 삭제되었습니다.';
$l['reason_post_never_made'] = '게시물이 작성되지 않았습니다.';
$l['unknown'] = '알 수 없음';
$l['results'] = '결과';
$l['step1'] = '1 단계';
$l['step2'] = '2 단계';
$l['step1of2'] = '2단계 중 1단계 - 파일 시스템 검사';
$l['step2of2'] = '2/2단계 - 데이터베이스 스캔';
$l['step1of2_line1'] = '잠시 기다려 주십시오. 현재 파일 시스템에서 분리된 첨부 파일을 검색하고 있습니다.';
$l['step2of2_line1'] = '잠시 기다려 주십시오. 현재 데이터베이스에서 분리된 첨부 파일을 검색하고 있습니다.';
$l['step_line2'] = '이 프로세스가 완료되면 자동으로 다음 단계로 리디렉션됩니다.';
$l['scanning'] = '스캔 중&hellip;';
$l['index_find_attachments'] = '첨부 파일 - 첨부 파일 찾기';
$l['find_where'] = '다음 위치에서 첨부파일을 찾으세요&hellip;';
$l['name_contains'] = '다음 파일 이름이 포함';
$l['name_contains_desc'] = '파일 이름에 지정된 쿼리가 포함된 첨부 파일을 검색합니다. 예를 들어, .zip 파일 확장자를 사용하여 첨부 파일을 찾으려면 .zip을 입력합니다.';
$l['type_contains'] = '파일 형식 포함';
$l['forum_is'] = '포럼은';
$l['username_is'] = '게시물의의 사용자 이름은 다음과 같습니다.';
$l['poster_is'] = '게시물은';
$l['poster_is_either'] = '사용자 또는 게스트';
$l['poster_is_user'] = '사용자만';
$l['poster_is_guest'] = '손님만';
$l['more_than'] = '이상';
$l['greater_than'] = '보다 큰';
$l['is_exactly'] = '정확하게';
$l['less_than'] = '미만';
$l['date_posted_is'] = '게시된 날짜와 다음과 같음';
$l['days_ago'] = '며칠 전에';
$l['file_size_is'] = '파일 크기는';
$l['kb'] = 'KB';
$l['download_count_is'] = '다운로드 횟수는';
$l['display_options'] = '디스플레이 옵션';
$l['filename'] = '파일 이름';
$l['filesize'] = '파일 크기';
$l['download_count'] = '다운로드 횟수';
$l['post_username'] = '게시물 사용자 이름';
$l['asc'] = '오름차순';
$l['desc'] = '내림차순';
$l['sort_results_by'] = '정렬 기준 결과';
$l['results_per_page'] = '페이지당 결과';
$l['in'] = 'in';
$l['button_delete_orphans'] = '선택된 분리파일 삭제';
$l['button_delete_attachments'] = '선택한 첨부파일 삭제';
$l['button_find_attachments'] = '첨부파일 찾기';
