<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Thu, 04 Jul 2024 04:52:13 +0000
// --------------------------------------------------------------------------------

$l['today_rel'] = '<span title="{1}">오늘</span>';
$l['yesterday_rel'] = '<span title="{1}">어제</span>';
$l['today'] = '오늘';
$l['yesterday'] = '어제';
$l['size_yb'] = 'YB';
$l['size_zb'] = 'ZB';
$l['size_eb'] = 'EB';
$l['size_pb'] = 'PB';
$l['size_tb'] = 'TB';
$l['size_gb'] = 'GB';
$l['size_mb'] = 'MB';
$l['size_kb'] = 'KB';
$l['size_bytes'] = 'bytes';
$l['na'] = 'N/A';
$l['mybb_admin_panel'] = 'MyBB 제어판';
$l['mybb_admin_cp'] = 'MyBB Admin CP';
$l['logged_in_as'] = '다음 계정으로 로그인됨';
$l['view_board'] = '포럼 보기';
$l['logout'] = '로그 아웃';
$l['generated_in'] = '<a href="{2}" target="_blank">{3}개의 쿼리</a>를 사용하여 {1}에서 생성되었습니다. 메모리 사용량: {4}';
$l['enter_username_and_password'] = '계속하려면 {1}과 비밀번호를 입력하세요.';
$l['login_username'] = '사용자 이름';
$l['login_email'] = '이메일';
$l['login_username_and_password'] = '사용자 이름/이메일';
$l['mybb_admin_login'] = 'MyBB 제어판 - 로그인';
$l['return_to_forum'] = '포럼으로 돌아가기';
$l['please_login'] = '로그인 해주세요';
$l['username'] = '사용자 이름:';
$l['username1'] = '이메일:';
$l['username2'] = '사용자 이름/이메일:';
$l['password'] = '비밀번호:';
$l['secret_pin'] = 'Secret PIN:';
$l['login'] = '로그인';
$l['lost_password'] = '비밀번호를 잊어 버렸습니까?';
$l['error_invalid_admin_session'] = '잘못된 관리 세션입니다.';
$l['error_admin_session_expired'] = '귀하의 관리 세션이 만료되었습니다.';
$l['error_invalid_ip'] = '귀하의 IP 주소는 이 세션에 유효하지 않습니다.';
$l['error_mybb_admin_lockedout'] = '이 계정은 잠겨 있습니다.';
$l['error_mybb_admin_lockedout_message'] = '귀하의 계정은 현재 {1}번 로그인에 실패하여 잠겼습니다. 계정을 잠금 해제하는 방법에 대한 지침이 포함된 이메일을 보내드렸습니다.';
$l['error_mybb_not_admin_account'] = '관리 제어판에 접근할 수 있는 권한이 없습니다.';
$l['error_invalid_username'] = '입력한 사용자 이름이 잘못되었습니다.';
$l['error_invalid_uid'] = '입력한 사용자 ID가 잘못되었습니다.';
$l['error_invalid_token'] = '입력한 활성화 코드가 잘못되었습니다.';
$l['success_logged_out'] = '성공적으로 로그아웃되었습니다.';
$l['error_invalid_username_password'] = '입력한 {1} 및 비밀번호 조합이 유효하지 않습니다.';
$l['confirm_action'] = '이 작업을 수행하시겠습니까?';
$l['home'] = '홈';
$l['name'] = '이름';
$l['size'] = '크기';
$l['controls'] = '컨트롤';
$l['view'] = '조회';
$l['yes'] = '예';
$l['no'] = '아니요';
$l['cancel'] = '취소';
$l['options'] = '옵션';
$l['proceed'] = '진행하다';
$l['ok'] = 'OK';
$l['error'] = '오류';
$l['edit'] = '편집';
$l['never'] = 'Never';
$l['legend'] = 'Legend';
$l['version'] = '버전';
$l['languagevar'] = '언어';
$l['use_default'] = '기본값 사용';
$l['file'] = '파일';
$l['go'] = '가기';
$l['clear'] = '지우기';
$l['unknown'] = '알 수 없음';
$l['year'] = '연';
$l['year_short'] = 'y';
$l['years'] = '연';
$l['years_short'] = 'y';
$l['month'] = '월';
$l['month_short'] = 'm';
$l['months'] = '월';
$l['months_short'] = 'm';
$l['week'] = '주';
$l['week_short'] = 'w';
$l['weeks'] = '주';
$l['weeks_short'] = 'w';
$l['day'] = '일';
$l['day_short'] = 'd';
$l['days'] = '일';
$l['days_short'] = 'd';
$l['hour'] = '시';
$l['hour_short'] = 'h';
$l['hours'] = '시';
$l['hours_short'] = 'h';
$l['minute'] = '분';
$l['minute_short'] = 'm';
$l['minutes'] = '분';
$l['minutes_short'] = 'm';
$l['second'] = '초';
$l['second_short'] = 's';
$l['seconds'] = '초';
$l['seconds_short'] = 's';
$l['permanent'] = '영구적으로';
$l['all_forums'] = '모든 포럼';
$l['all_groups'] = '모든 그룹';
$l['all_prefix'] = '모든 접두어';
$l['select_forums'] = '포럼 선택';
$l['select_groups'] = '그룹 선택';
$l['select_prefix'] = '접두어 선택';
$l['forums_colon'] = '포럼:';
$l['groups_colon'] = '그룹:';
$l['prefix_colon'] = '접두어:';
$l['none'] = '없음';
$l['mybb_acp'] = 'MyBB ACP';
$l['pages'] = '페이지';
$l['previous'] = '이전';
$l['page'] = '페이지';
$l['next'] = '다음';
$l['delete'] = '삭제';
$l['reset'] = '리셋';
$l['and'] = '그리고';
$l['on'] = 'On';
$l['off'] = 'Off';
$l['alt_enabled'] = '활성화됨';
$l['alt_disabled'] = '비활성화됨';
$l['enable'] = '활성';
$l['disable'] = '비활성';
$l['saved'] = '저장됨';
$l['guest'] = '손님';
$l['rel_in'] = 'In ';
$l['rel_ago'] = '전에';
$l['rel_less_than'] = '미만';
$l['rel_time'] = '<span title="{5}{6}">{1}{2} {3} {4}</span>';
$l['rel_minutes_single'] = '분';
$l['rel_minutes_plural'] = '분';
$l['rel_hours_single'] = '시간';
$l['rel_hours_plural'] = '시간';
$l['quote'] = '인용:';
$l['wrote'] = '작성함:';
$l['code'] = 'Code:';
$l['php_code'] = 'PHP Code:';
$l['linkback'] = '원본 게시물';
$l['january'] = '1월';
$l['february'] = '2월';
$l['march'] = '3월';
$l['april'] = '4월';
$l['may'] = '5월';
$l['june'] = '6월';
$l['july'] = '7월';
$l['august'] = '8월';
$l['september'] = '9월';
$l['october'] = '10월';
$l['november'] = '11월';
$l['december'] = '12월';
$l['access_denied'] = '접근 불가';
$l['access_denied_desc'] = '관리 제어판의 이 부분에 액세스할 수 있는 권한이 없습니다.';
$l['cannot_perform_action_super_admin_general'] = '죄송합니다. 최고 관리자가 아니기 때문에 이 작업을 수행할 수 없습니다.<br /><br />이 작업을 수행하려면 inc/config의 최고 관리자 목록에 사용자 ID를 추가해야 합니다. php.php.';
$l['loading_text'] = '로딩중<br />잠시만 기다려주세요&hellip;';
$l['timezone_gmt_minus_1200'] = '(GMT -12:00) Howland and Baker Islands';
$l['timezone_gmt_minus_1100'] = '(GMT -11:00) Nome, Midway Island';
$l['timezone_gmt_minus_1000'] = '(GMT -10:00) Hawaii, Papeete';
$l['timezone_gmt_minus_950'] = '(GMT -9:30) Marquesas Islands';
$l['timezone_gmt_minus_900'] = '(GMT -9:00) Alaska';
$l['timezone_gmt_minus_800'] = '(GMT -8:00) Pacific Time';
$l['timezone_gmt_minus_700'] = '(GMT -7:00) Mountain Time';
$l['timezone_gmt_minus_600'] = '(GMT -6:00) Central Time, Mexico City';
$l['timezone_gmt_minus_500'] = '(GMT -5:00) Eastern Time, Bogota, Lima, Quito';
$l['timezone_gmt_minus_450'] = '(GMT -4:30) Caracas';
$l['timezone_gmt_minus_400'] = '(GMT -4:00) Atlantic Time, La Paz, Halifax';
$l['timezone_gmt_minus_350'] = '(GMT -3:30) Newfoundland';
$l['timezone_gmt_minus_300'] = '(GMT -3:00) Brazil, Buenos Aires, Georgetown, Falkland Is.';
$l['timezone_gmt_minus_200'] = '(GMT -2:00) Mid-Atlantic, South Georgia and the South Sandwich Islands';
$l['timezone_gmt_minus_100'] = '(GMT -1:00) Azores, Cape Verde Islands';
$l['timezone_gmt'] = '(GMT) Casablanca, Dublin, Edinburgh, London, Lisbon, Monrovia';
$l['timezone_gmt_100'] = '(GMT +1:00) Berlin, Bratislava, Brussels, Copenhagen, Madrid, Paris, Prague, Rome, Warsaw';
$l['timezone_gmt_200'] = '(GMT +2:00) Athens, Istanbul, Cairo, Jerusalem, South Africa';
$l['timezone_gmt_300'] = '(GMT +3:00) Kaliningrad, Minsk, Baghdad, Riyadh, Nairobi';
$l['timezone_gmt_350'] = '(GMT +3:30) Tehran';
$l['timezone_gmt_400'] = '(GMT +4:00) Moscow, Abu Dhabi, Baku, Muscat, Tbilisi';
$l['timezone_gmt_450'] = '(GMT +4:30) Kabul';
$l['timezone_gmt_500'] = '(GMT +5:00) Islamabad, Karachi, Tashkent';
$l['timezone_gmt_550'] = '(GMT +5:30) Mumbai, Kolkata, Chennai, New Delhi';
$l['timezone_gmt_575'] = '(GMT +5:45) Kathmandu';
$l['timezone_gmt_600'] = '(GMT +6:00) Almaty, Dhaka, Yekaterinburg';
$l['timezone_gmt_650'] = '(GMT +6:30) Yangon';
$l['timezone_gmt_700'] = '(GMT +7:00) Bangkok, Hanoi, Jakarta';
$l['timezone_gmt_800'] = '(GMT +8:00) Beijing, Hong Kong, Perth, Singapore, Taipei, Manila';
$l['timezone_gmt_850'] = '(GMT +8:30) Pyongyang';
$l['timezone_gmt_875'] = '(GMT +8:45) Eucla';
$l['timezone_gmt_900'] = '(GMT +9:00) Osaka, Sapporo, Seoul, Tokyo, Irkutsk';
$l['timezone_gmt_950'] = '(GMT +9:30) Adelaide, Darwin';
$l['timezone_gmt_1000'] = '(GMT +10:00) Melbourne, Papua New Guinea, Sydney, Yakutsk';
$l['timezone_gmt_1050'] = '(GMT +10:30) Lord Howe Island';
$l['timezone_gmt_1100'] = '(GMT +11:00) Magadan, New Caledonia, Solomon Islands, Vladivostok';
$l['timezone_gmt_1150'] = '(GMT +11:30) Norfolk Island';
$l['timezone_gmt_1200'] = '(GMT +12:00) Auckland, Wellington, Fiji, Marshall Islands';
$l['timezone_gmt_1275'] = '(GMT +12:45) Chatham Islands';
$l['timezone_gmt_1300'] = '(GMT +13:00) Samoa, Tonga, Tokelau';
$l['timezone_gmt_1400'] = '(GMT +14:00) Line Islands';
$l['timezone_gmt_short'] = 'GMT {1}({2})';
$l['confirm_delete_logs'] = '선택한 로그 항목을 정리하시겠습니까?';
$l['confirm_delete_all_logs'] = '모든 로그 항목을 정리하시겠습니까?';
$l['selected_logs_deleted'] = '선택한 로그 항목이 삭제되었습니다.';
$l['all_logs_deleted'] = '모든 로그 항목이 삭제되었습니다.';
$l['delete_selected'] = '선택 항목 삭제';
$l['delete_all'] = '필터링된 모든 항목 삭제';
$l['encountered_errors'] = '다음 오류가 발생:';
$l['invalid_post_verify_key'] = '인증 코드 불일치가 발생했습니다. 아래 작업을 수행할 것인지 확인해 주세요.';
$l['invalid_post_verify_key2'] = '인증 코드 불일치가 발생했습니다. 이 페이지에 올바르게 액세스하고 있는지 다시 한번 확인하세요.';
$l['unknown_error'] = '알 수 없는 오류가 발생했습니다.';
$l['editor_bold'] = '진하게';
$l['editor_italic'] = '이태릭';
$l['editor_underline'] = '밑줄';
$l['editor_strikethrough'] = '가운데줄';
$l['editor_subscript'] = 'Subscript';
$l['editor_superscript'] = 'Superscript';
$l['editor_alignleft'] = '왼쪽 정렬';
$l['editor_center'] = '가운데 정렬';
$l['editor_alignright'] = '오른쪽 정렬';
$l['editor_justify'] = 'Justify';
$l['editor_fontname'] = '글꼴 이름';
$l['editor_fontsize'] = '글꼴 크기';
$l['editor_fontcolor'] = '글꼴 색상';
$l['editor_removeformatting'] = '서식 지우기';
$l['editor_cut'] = '잘라내기';
$l['editor_copy'] = '복사';
$l['editor_paste'] = '붙여넣기';
$l['editor_cutnosupport'] = '귀하의 브라우저는 잘라내기 명령을 허용하지 않습니다. 키보드 단축키 Ctrl/Cmd-X를 사용하세요.';
$l['editor_copynosupport'] = '귀하의 브라우저는 복사 명령을 허용하지 않습니다. 키보드 단축키 Ctrl/Cmd-C를 사용하세요.';
$l['editor_pastenosupport'] = '귀하의 브라우저는 붙여넣기 명령을 허용하지 않습니다. 키보드 단축키 Ctrl/Cmd-V를 사용하세요.';
$l['editor_pasteentertext'] = '다음 상자 안에 텍스트를 붙여넣으세요.';
$l['editor_pastetext'] = '텍스트 붙여넣기';
$l['editor_numlist'] = '번호가 매겨진 목록';
$l['editor_bullist'] = '글머리 기호 목록';
$l['editor_undo'] = '실행 취소';
$l['editor_redo'] = '재실행';
$l['editor_rows'] = '행:';
$l['editor_cols'] = '열:';
$l['editor_inserttable'] = '표 삽입';
$l['editor_inserthr'] = '수평선 삽입';
$l['editor_code'] = 'Code';
$l['editor_php'] = 'PHP';
$l['editor_width'] = '너비(선택사항):';
$l['editor_height'] = '높이(선택 사항):';
$l['editor_insertimg'] = '이미지 삽입';
$l['editor_email'] = '이메일:';
$l['editor_insertemail'] = '이메일을 삽입';
$l['editor_url'] = 'URL:';
$l['editor_insertlink'] = '링크 삽입';
$l['editor_unlink'] = '링크 해제';
$l['editor_more'] = '더 보기';
$l['editor_insertemoticon'] = '이모티콘을 삽입';
$l['editor_videourl'] = '비디오 URL:';
$l['editor_videotype'] = '비디오 형식:';
$l['editor_insert'] = '삽입';
$l['editor_insertyoutubevideo'] = 'YouTube 동영상 삽입';
$l['editor_currentdate'] = '현재 날짜 삽입';
$l['editor_currenttime'] = '현재 시간 삽입';
$l['editor_print'] = '인쇄';
$l['editor_viewsource'] = '소스보기';
$l['editor_description'] = '설명 (선택 사항):';
$l['editor_enterimgurl'] = '이미지 URL을 입력:';
$l['editor_enteremail'] = '이메일 주소를 입력:';
$l['editor_enterdisplayedtext'] = '표시된 텍스트를 입력:';
$l['editor_enterurl'] = 'URL 입력:';
$l['editor_enteryoutubeurl'] = 'YouTube 동영상 URL 또는 ID를 입력:';
$l['editor_insertquote'] = '인용문을 삽입';
$l['editor_invalidyoutube'] = '잘못된 YouTube 동영상';
$l['editor_dailymotion'] = 'Dailymotion';
$l['editor_metacafe'] = 'MetaCafe';
$l['editor_mixer'] = 'Mixer';
$l['editor_vimeo'] = 'Vimeo';
$l['editor_youtube'] = 'Youtube';
$l['editor_facebook'] = 'Facebook';
$l['editor_liveleak'] = 'LiveLeak';
$l['editor_insertvideo'] = '비디오 삽입';
$l['editor_maximize'] = '최대화';
$l['missing_task'] = '오류: 작업 파일이 존재하지 않습니다.';
$l['task_backup_cannot_write_backup'] = '오류: 데이터베이스 백업 작업이 백업 디렉터리에 쓸 수 없습니다.';
$l['task_backup_ran'] = '데이터베이스 백업 작업이 성공적으로 실행되었습니다.';
$l['task_checktables_ran'] = '테이블 확인 작업이 손상된 테이블 없이 성공적으로 실행되었습니다.';
$l['task_checktables_ran_found'] = '참고: 테이블 확인 작업이 성공적으로 실행되어 {1} 테이블을 복구했습니다.';
$l['task_dailycleanup_ran'] = '일일 정리 작업이 성공적으로 실행되었습니다.';
$l['task_hourlycleanup_ran'] = '시간별 정리 작업이 성공적으로 실행되었습니다.';
$l['task_logcleanup_ran'] = '로그 정리 작업이 성공적으로 실행되어 이전 로그를 정리했습니다.';
$l['task_promotions_ran'] = '프로모션 작업이 성공적으로 실행되었습니다.';
$l['task_threadviews_ran'] = '글타래 보기 작업이 성공적으로 실행되었습니다.';
$l['task_usercleanup_ran'] = '사용자 정리 작업이 성공적으로 실행되었습니다.';
$l['task_massmail_ran'] = '대량 메일 작업이 성공적으로 실행되었습니다.';
$l['task_userpruning_ran'] = '사용자 정리 작업이 성공적으로 실행되었습니다.';
$l['task_delayedmoderation_ran'] = '지연된 조정 작업이 성공적으로 실행되었습니다.';
$l['task_massmail_ran_errors'] = '"{1}"(으)로 보내는 데 하나 이상의 문제가 발생했습니다.
{2}';
$l['task_versioncheck_ran'] = '버전 확인 작업이 성공적으로 실행되었습니다.';
$l['task_versioncheck_ran_errors'] = '버전 확인을 위해 MyBB에 연결할 수 없습니다.';
$l['task_recachestylesheets_ran'] = '다시 캐시된 {1} 스타일시트.';
$l['task_sendmailqueue_ran'] = '메일 보내기 대기열 작업이 최대 {1}개의 메시지를 보냈습니다.';
$l['massmail_username'] = '사용자 이름';
$l['email_addr'] = '이메일 주소';
$l['board_name'] = '보드 이름';
$l['board_url'] = '보드 URL';
$l['lockout_unlock'] = '관리자 제어판 잠금 해제';
$l['enter_username_and_token'] = '계속하려면 사용자 이름과 활성화 코드를 입력하세요.';
$l['unlock_token'] = '활성화 코드:';
$l['unlock_account'] = '계정 잠금 해제';
$l['locked_out_subject'] = '{1}에서 관리자 계정이 잠겼습니다.';
$l['locked_out_message'] = '{1},

{3}번의 로그인 시도 실패로 인해 {2}의 관리자 계정이 잠겼습니다.

계정을 잠금 해제하려면 웹 브라우저에서 아래 URL로 이동하십시오.

{4}/{5}/index.php?action=unlock&uid={7}&token={6}

위 링크가 제대로 작동하지 않으면 다음으로 이동하세요.

{4}/{5}/index.php?action=unlock

다음을 입력해야 합니다.
사용자 이름: {1}
활성화 코드: {6}

감사합니다,
{2} 직원';
$l['comma'] = ', ';
$l['search_for_a_user'] = '사용자 검색';
$l['mybb_engine'] = 'MyBB 엔진';
$l['my2fa'] = '2단계 인증';
$l['my2fa_failed'] = '코드가 잘못되었습니다. 지금 로그아웃되었습니다.';
$l['my2fa_code'] = '인증번호를 입력해주세요';
$l['my2fa_label'] = '인증코드:';
$l['my2fa_no_codes'] = '참고: 복구 코드를 모두 사용했습니다. 새로운 세트를 생성하려면 <a href="index.php?module=home-preferences&amp;action=recovery_codes">복구 코드 페이지</a>를 방문하세요.';
