<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 07:26:16 +0000
// --------------------------------------------------------------------------------

$l['hello_desc'] = '인덱스 페이지에 메시지를 생성하고 이를 각 게시물에 추가할 수 있는 샘플 플러그인입니다.';
$l['setting_group_hello'] = 'Hello World!';
$l['setting_group_hello_desc'] = 'Hello World! 설정 플러그인.';
$l['setting_hello_display1'] = '메시지 색인 표시';
$l['setting_hello_display1_desc'] = '인덱스에 메시지를 표시하지 않으려면 no로 설정합니다.';
$l['setting_hello_display2'] = '메시지 포스트비트 표시';
$l['setting_hello_display2_desc'] = '모든 게시물 아래에 메시지를 표시하지 않으려면 no로 설정하세요.';
$l['hello_uninstall'] = 'Hello World! 제거';
$l['hello_uninstall_message'] = '데이터베이스에서 모든 메시지를 삭제하시겠습니까?';
