<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Wed, 03 Jul 2024 00:59:26 +0000
// --------------------------------------------------------------------------------

$l['preferences_and_personal_notes'] = '환경설정 및 개인 메모';
$l['prefs_and_personal_notes_description'] = '여기에서 관리자 제어판 기본 설정을 관리하고 개인 메모를 남길 수 있습니다.';
$l['preferences'] = '환경설정';
$l['global_preferences'] = '글로벌 환경설정';
$l['acp_theme'] = '관리자 제어판 테마';
$l['select_acp_theme'] = '관리자 제어판에서 사용할 테마를 선택하세요.';
$l['acp_language'] = '관리자 제어판 언어';
$l['select_acp_language'] = '관리자 제어판에서 사용할 언어를 선택하세요.';
$l['notes_not_shared'] = '이 메모는 다른 관리자와 공유되지 않습니다.';
$l['save_notes_and_prefs'] = '개인 메모 및 환경 설정 저장';
$l['personal_notes'] = '개인 메모';
$l['codemirror'] = 'Turn on / off Code Mirror';
$l['use_codemirror_desc'] = '이 기본 설정을 사용하면 문제/느린 로딩이 발생하는 경우 코드 미러(구문 강조를 위한 템플릿 편집 및 스타일시트 편집에 사용됨)를 끌 수 있습니다.';
$l['success_preferences_updated'] = '기본 설정이 성공적으로 업데이트되었습니다.';
$l['use_2fa_desc'] = '2단계 인증은 관리자 계정을 보호하는 방법입니다. 활성화한 후에는 아래에 앱으로 스캔해야 하는 QR 코드가 표시됩니다. <a href="https://docs.mybb.com/1.8/administration/security/2fa/" target="_blank " rel="noopener">Google Authenticator 또는 Authy</a>와 같습니다. 해당 앱은 모든 acp 로그인에 입력해야 하는 토큰을 생성합니다.';
$l['my2fa_qr'] = '2단계 인증 코드';
$l['recovery_codes_desc'] = '<a href="index.php?module=home-preferences&amp;action=recovery_codes">복구 코드</a>를 확인하세요.';
$l['recovery_codes'] = '복구 코드';
$l['recovery_codes_warning'] = '<b>참고:</b> 코드는 페이지를 방문할 때마다 다시 생성되며 한 번만 사용할 수 있습니다.';
$l['print_recovery_codes'] = '복구 코드 인쇄';
