<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Thu, 04 Jul 2024 05:10:25 +0000
// --------------------------------------------------------------------------------

$l['dashboard'] = '대시보드';
$l['dashboard_description'] = '이 섹션에서는 귀하의 보드와 관련된 다양한 통계 중 일부를 볼 수 있습니다. 다른 관리자가 볼 수 있도록 다른 메모를 추가할 수도 있습니다.';
$l['mybb_server_stats'] = 'MyBB 및 서버 통계';
$l['forum_stats'] = '포럼 통계';
$l['mybb_version'] = 'MyBB 버전';
$l['threads'] = '글타래';
$l['new_today'] = '오늘의 신규';
$l['unapproved'] = '미승인';
$l['php_version'] = 'PHP 버전';
$l['posts'] = '게시물';
$l['sql_engine'] = 'SQL 엔진';
$l['users'] = '사용자';
$l['registered_users'] = '등록 된 사용자';
$l['active_users'] = '활동하는 사용자';
$l['registrations_today'] = '오늘 등록';
$l['awaiting_activation'] = '활성화 대기 중';
$l['server_load'] = '서버 로드';
$l['attachments'] = '첨부파일';
$l['used'] = '사용됨';
$l['reported_posts'] = '신고된 게시물';
$l['unread_reports'] = '읽지 않은 신고서';
$l['version_check'] = '업데이트 확인';
$l['last_update_check_two_weeks'] = '마지막 <a href="{1}">MyBB 버전 확인</a>이 2주 이상 지났습니다.';
$l['new_version_available'] = '현재 {1}을(를) 실행 중이며 일반적으로 사용 가능한 최신 릴리스는 {2}입니다.';
$l['version_check_description'] = '여기에서 현재 MyBB의 최신 복사본을 실행하고 있는지 확인하고 MyBB에서 직접 최신 공지 사항을 볼 수 있습니다.';
$l['latest_mybb_announcements'] = '최신 MyBB 공지 사항';
$l['no_announcements'] = '저장된 공지사항이 없습니다. <a href="index.php?module=home&amp;action=version_check">업데이트를 확인하세요</a>.';
$l['your_version'] = '내 버전';
$l['latest_version'] = '최신 버전';
$l['update_forum'] = '<a href="https://mybb.com" target="_blank" rel="noopener">MyBB 웹사이트</a>를 방문하여 MyBB를 최신 버전으로 업그레이드하세요.';
$l['read_more'] = '더 읽기';
$l['success_up_to_date'] = '축하합니다. 최신 버전의 MyBB를 설치되어 있습니다.';
$l['error_out_of_date'] = '귀하의 MyBB 사본이 최신 버전이 아닙니다.';
$l['error_communication'] = '버전 서버와 통신하는 중에 문제가 발생했습니다. 몇 분 후에 다시 시도하십시오.';
$l['error_fetch_news'] = 'MyBB가 MyBB 웹사이트에서 최신 공지사항을 성공적으로 가져오지 못했습니다.';
$l['news_description'] = '<a href="https://blog.mybb.com/" target="_blank" rel="noopener">MyBB 블로그</a>의 최신 뉴스.';
$l['admin_notes_public'] = '이 메모는 모든 관리자에게 공개됩니다.';
$l['admin_notes'] = '관리자 메모';
$l['save_notes'] = '메모 저장';
$l['success_notes_updated'] = '관리자 메모가 성공적으로 업데이트되었습니다.';
