<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Sat, 29 Jun 2024 05:29:43 +0000
// --------------------------------------------------------------------------------

$l['home'] = '홈';
$l['dashboard'] = '대시보드';
$l['preferences'] = '환경설정';
$l['mybb_credits'] = 'MyBB Credits';
$l['add_new_forum'] = '새 포럼 추가';
$l['search_for_users'] = '사용자 검색';
$l['themes'] = '테마';
$l['templates'] = '템플릿';
$l['plugins'] = '플러그인';
$l['database_backups'] = '데이터베이스 백업';
$l['quick_access'] = '빠른 접근';
$l['online_admins'] = '온라인 관리자';
$l['ipaddress'] = 'IP 주소:';
$l['mybb_documentation'] = 'MyBB 문서';
