<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : 한국어(South Korea)
// Author of the language pack : zardkim
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Mon, 08 Jul 2024 04:15:40 +0000
// --------------------------------------------------------------------------------

$l['template_sets'] = '템플릿 세트';
$l['template_set'] = '템플릿 세트';
$l['templates'] = '{1} 템플릿';
$l['manage_template_sets'] = '템플릿 세트 관리';
$l['manage_template_sets_desc'] = '여기에서 템플릿 세트를 관리하고, 이러한 세트를 사용하여 템플릿을 보고, 보드 레이아웃 사용자 정의를 시작할 수 있습니다.';
$l['add_set'] = '세트 추가';
$l['add_set_desc'] = '여기에서 새 템플릿 세트를 만들 수 있습니다. 새로운 템플릿 세트는 마스터 MyBB 템플릿의 복사본을 생성하고 이미 가지고 있는 다른 템플릿 세트의 변경 사항을 방해하지 않고 편집할 수 있도록 해줍니다.';
$l['add_template'] = '템플릿 추가';
$l['add_template_desc'] = '여기에서 새 템플릿을 만들 수 있습니다.';
$l['add_template_group'] = '템플릿 그룹 추가';
$l['add_template_group_desc'] = '템플릿을 함께 조합하려면 템플릿 그룹을 추가하세요.';
$l['search_replace'] = '검색/바꾸기';
$l['search_replace_desc'] = '이 도구를 사용하면 템플릿 제목이나 특정 텍스트가 포함된 템플릿을 검색하고 선택적으로 자동으로 다른 텍스트로 바꿀 수 있습니다.';
$l['find_updated'] = '업데이트된 템플릿 찾기';
$l['find_updated_desc'] = 'MyBB의 새 버전에서 변경된 템플릿을 찾아 변경 사항을 적절하게 적용할 수 있습니다.';
$l['edit_template'] = '템플릿 편집';
$l['editing_template'] = '템플릿 편집: {1}';
$l['edit_template_desc'] = '여기서 템플릿의 코드, 제목 또는 세트를 편집할 수 있습니다.';
$l['edit_set'] = '세트 편집';
$l['edit_set_desc'] = '여기서 이 템플릿 세트의 속성을 편집할 수 있습니다.';
$l['manage_templates'] = '템플릿 관리';
$l['manage_templates_desc'] = '여기서 이 템플릿 세트에 대한 템플릿을 관리할 수 있습니다. 템플릿을 편집하려면 해당 링크를 클릭하거나 "전체 편집"을 선택하여 별도의 페이지에서 모든 속성을 편집하세요.';
$l['diff_report'] = '차이점 보고서';
$l['diff_report_desc'] = '템플릿 간의 차이점 분석을 수행하고 사용자 정의된 복사본과 최신 마스터 복사본 간에 변경된 내용을 정확하게 보여줍니다.';
$l['title'] = '제목';
$l['save'] = '저장';
$l['search_for'] = '검색 대상';
$l['replace_with'] = '다음으로 바꾸기(선택 사항)';
$l['reset'] = '리셋';
$l['find_templates'] = '템플릿 찾기';
$l['find_and_replace'] = '찾기 및 바꾸기';
$l['search_template_names'] = '템플릿 제목 검색';
$l['ungrouped_templates'] = '그룹 해제된 템플릿';
$l['search_noneset'] = '검색 문자열을 입력하지 않았습니다.';
$l['search_results'] = '템플릿 검색 결과';
$l['search_header'] = '{2}에서 "{1}" 검색 중';
$l['search_updated'] = '업데이트됨 {1}';
$l['search_found'] = '{1}에서 찾았습니다.';
$l['search_created_custom'] = '{1}에 대한 맞춤 템플릿을 생성했습니다.';
$l['search_edit'] = '편집';
$l['search_change_original'] = '원본 변경';
$l['search_noresults'] = '\'<strong>{1}</strong>\' 문자열이 포함된 템플릿을 찾을 수 없습니다.';
$l['search_noresults_title'] = '제목이 \'<strong>{1}</strong>\'인 템플릿을 찾을 수 없습니다.';
$l['default_templates'] = '기본 템플릿';
$l['edit_template_breadcrumb'] = '템플릿 편집:';
$l['global_templates'] = '글로벌 템플릿';
$l['master_templates'] = '마스터 템플릿';
$l['not_used_by_any_themes'] = '어떤 테마에서도 사용되지 않음';
$l['used_by'] = '사용처:';
$l['used_by_all_themes'] = '모든 테마에서 사용됨';
$l['expand_templates'] = '템플릿 확장';
$l['edit_template_set'] = '템플릿 세트 편집';
$l['delete_template_set'] = '템플릿 세트 삭제';
$l['empty_template_set'] = '<em>이 세트에는 템플릿이 없습니다.</em>';
$l['inline_edit'] = '인라인 편집';
$l['full_edit'] = '전체 편집';
$l['revert_to_orig'] = '원본으로 되돌리기';
$l['delete_template'] = '템플릿 삭제';
$l['edit_in'] = 'Edit in';
$l['group_calendar'] = '달력';
$l['group_forumdisplay'] = '포럼 디스플레이';
$l['group_index'] = '색인 페이지';
$l['group_error'] = '에러 메시지';
$l['group_memberlist'] = '회원 목록';
$l['group_multipage'] = '다중 페이지 매김';
$l['group_private'] = '비공개 메시지';
$l['group_portal'] = '포탈';
$l['group_postbit'] = '게시물 Bit';
$l['group_posticons'] = '게시물 아이콘';
$l['group_showthread'] = '글타래 표시';
$l['group_usercp'] = '사용자 제어판';
$l['group_online'] = 'Who\'s Online';
$l['group_forumbit'] = '포럼 Bit';
$l['group_editpost'] = '게시물 수정';
$l['group_forumjump'] = '포럼 점프';
$l['group_moderation'] = '중재';
$l['group_nav'] = '네비게이션';
$l['group_search'] = '검색';
$l['group_showteam'] = '포럼 팀 표시';
$l['group_reputation'] = '평판';
$l['group_newthread'] = '새 글타래';
$l['group_newreply'] = '새 답변';
$l['group_member'] = '회원';
$l['group_warning'] = '경고 시스템';
$l['group_global'] = '글로벌';
$l['group_header'] = '헤더';
$l['group_managegroup'] = '그룹 관리';
$l['group_misc'] = 'Miscellaneous';
$l['group_modcp'] = '중재자 제어판';
$l['group_announcement'] = '공지사항';
$l['group_polls'] = '설문조사';
$l['group_post'] = '게시물';
$l['group_printthread'] = '글타래 인쇄';
$l['group_report'] = '보고서';
$l['group_smilieinsert'] = '스마일리 삽입기';
$l['group_stats'] = '통계';
$l['group_xmlhttp'] = 'XMLHTTP';
$l['group_footer'] = '바닥글';
$l['group_video'] = 'Video MyCode';
$l['group_sendthread'] = '글타래 보내기';
$l['group_mycode'] = 'MyCode';
$l['expand'] = '확장';
$l['collapse'] = '접기';
$l['save_continue'] = '저장하고 계속 편집';
$l['save_close'] = '저장하고 목록으로 돌아가기';
$l['template_name'] = '템플릿 이름';
$l['template_name_desc'] = '템플릿의 이름입니다. 기본 템플릿에서 이를 변경하면 템플릿이 새 이름으로 사용자 정의 템플릿으로 저장됩니다.';
$l['template_set_desc'] = '이 템플릿은 어떤 템플릿 세트에 포함되어야 합니까?';
$l['template_group_prefix'] = '템플릿 그룹 접두어';
$l['template_group_prefix_desc'] = '그룹 템플릿의 접두사 이름입니다. 이는 이미 존재하지 않아야 합니다. 예를 들어 <em>hello_world</em>, <em>hello_foobar</em> 및 <em>hello_foo</em> 템플릿을 그룹화하려면 여기에 <strong>hello</strong>를 입력하세요.';
$l['template_group_title'] = '템플릿 그룹 제목';
$l['template_group_title_desc'] = '접두어 그룹의 제목입니다. 이는 템플릿 목록에 표시됩니다. 예를 들어 <em>hello</em> 템플릿의 경우 여기에 <strong>Hello</strong>를 입력하세요.';
$l['edit_template_group'] = '템플릿 그룹 편집';
$l['editing_template_group'] = '템플릿 그룹 편집 중 {1}';
$l['delete_template_group'] = '템플릿 그룹 삭제';
$l['save_template_group'] = '템플릿 그룹 저장';
$l['templates_the_same'] = '선택한 두 템플릿은 모두 동일하므로 비교할 수 없습니다.';
$l['master_updated_ins'] = '이전 버전과 이번 버전 사이에 변경된 사항은 다음과 같이 강조 표시됩니다.';
$l['master_updated_del'] = '템플릿(이전 템플릿)에 적용한 모든 사용자 정의는 다음과 같이 강조 표시됩니다.';
$l['template_diff_analysis'] = '템플릿 차이 분석';
$l['search_names_header'] = '"{1}"을(를) 포함하는 템플릿 이름 검색 중';
$l['updated_template_welcome1'] = '편집 - 버전 간 업데이트를 통합하기 위해 이 템플릿 세트의 현재 템플릿을 편집할 수 있습니다.';
$l['updated_template_welcome2'] = '되돌리기 - 사용자 정의된 템플릿을 마스터 개정으로 되돌리지만 사용자 정의 변경 사항은 모두 손실됩니다.';
$l['updated_template_welcome3'] = '차이점 - 템플릿 간의 차이점 분석을 수행하고 사용자 정의된 복사본과 최신 마스터 복사본 간에 변경된 내용을 정확하게 보여줍니다.';
$l['no_global_templates'] = '현재 글로벌 템플릿이 없습니다.';
$l['no_updated_templates'] = '현재 마지막 업그레이드 이후 업데이트된 템플릿이 없습니다.';
$l['confirm_template_set_deletion'] = '이 템플릿 세트를 삭제하시겠습니까?';
$l['confirm_template_group_delete'] = '이 템플릿 그룹을 삭제하시겠습니까? 이 작업은 그룹의 템플릿을 제거하지 않습니다.';
$l['confirm_template_deletion'] = '이 템플릿을 삭제하시겠습니까?';
$l['confirm_template_revertion'] = '이 템플릿을 되돌리시겠습니까?';
$l['error_security_problem'] = '템플릿에서 잠재적인 보안 문제가 발견되었습니다. 변경 사항을 검토하거나 MyBB 그룹에 지원을 문의하세요.';
$l['error_missing_input'] = '이 템플릿(tid 및 sid)을 편집하는 데 필요한 모든 입력이 있는지 확인하십시오.';
$l['error_already_exists'] = '템플릿 제목이 이미 사용 중입니다. 다른 제목을 사용해 주세요.';
$l['error_invalid_template'] = '유효한 템플릿을 선택하세요.';
$l['error_missing_set_title'] = '템플릿 세트 제목을 선택하세요.';
$l['error_invalid_input'] = '템플릿 세트 ID가 올바른지 확인하세요.';
$l['error_invalid_set'] = '유효한 템플릿 세트를 선택하세요.';
$l['error_invalid_template_set'] = '잘못된 템플릿 세트가 선택되었습니다.';
$l['error_themes_attached_template_set'] = '이 템플릿 세트에 테마가 첨부되어 있으므로 이 템플릿 세트를 삭제할 수 없습니다.';
$l['error_missing_group_prefix'] = '템플릿 그룹의 접두어를 입력하세요.';
$l['error_invalid_group_title'] = '밑줄(_)은 구분 기호로 사용되므로 템플릿 그룹 접두사에서는 금지됩니다. 다른 접두사를 선택하세요.';
$l['error_missing_group_title'] = '템플릿 그룹의 제목을 입력하세요.';
$l['error_duplicate_group_prefix'] = '이 접두어를 사용하는 템플릿 그룹이 이미 존재합니다. 다른 접두어를 입력하세요.';
$l['error_missing_template_group'] = '템플릿 그룹을 찾을 수 없습니다.';
$l['error_default_template_group'] = '기본 템플릿 그룹은 편집하거나 제거할 수 없습니다.';
$l['success_template_saved'] = '선택한 템플릿이 성공적으로 저장되었습니다.';
$l['success_template_deleted'] = '선택한 템플릿이 성공적으로 삭제되었습니다.';
$l['success_template_reverted'] = '선택한 템플릿이 성공적으로 되돌려졌습니다.';
$l['success_template_set_saved'] = '선택한 템플릿 세트가 성공적으로 저장되었습니다.';
$l['success_template_set_deleted'] = '선택한 템플릿 세트가 성공적으로 삭제되었습니다.';
$l['success_template_group_saved'] = '선택한 템플릿 그룹이 성공적으로 저장되었습니다.';
$l['success_template_group_deleted'] = '선택한 템플릿 그룹이 성공적으로 삭제되었습니다.';
