<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Sat, 06 Jul 2024 04:33:26 +0000
// --------------------------------------------------------------------------------

$l['themes'] = '테마';
$l['themes_desc'] = '여기에서 포럼에 설정된 테마를 관리할 수 있습니다. 테마를 사용하면 포럼의 모양을 사용자 정의할 수 있습니다. 현재 설정되어 있는 테마 목록은 아래와 같습니다.';
$l['create_new_theme'] = '새 테마 만들기';
$l['create_new_theme_desc'] = '여기에서 기본값을 기반으로 새 테마를 만들 수 있습니다. <strong>템플릿 세트, 스타일시트 및 기타 설정은 상위 테마에서 상속됩니다.</strong>';
$l['import_a_theme'] = '테마 가져오기';
$l['import_a_theme_desc'] = '여기에서 새로운 테마를 가져올 수 있습니다. 컴퓨터나 원격 URL에서 테마를 가져올 수 있습니다.';
$l['edit_stylesheets'] = '스타일시트 편집';
$l['edit_stylesheets_desc'] = '여기에서 이 테마에 사용되는 스타일시트를 쉽게 관리할 수 있습니다. 스타일시트는 CSS를 기반으로 하며 이 테마의 글꼴, 색상 및 기타 시각적 측면을 정의합니다. 이 테마에 첨부된 스타일시트 목록은 다음과 같습니다.';
$l['add_stylesheet'] = '스타일시트 추가';
$l['add_stylesheet_desc'] = '여기에서 이 테마에 새 스타일시트를 추가할 수 있습니다. 스타일시트에는 이 테마의 모양을 사용자 정의할 수 있는 CSS가 포함되어 있습니다. 생성 후 스타일시트 편집 페이지로 이동됩니다.';
$l['browse_themes'] = '테마 찾아보기';
$l['browse_themes_desc'] = '여기서 귀하의 MyBB 시리즈와 호환되는 테마에 대한 공식 MyBB 수정 사이트를 찾아볼 수 있습니다.';
$l['browse_all_themes'] = '모든 테마 찾아보기';
$l['export_theme'] = '테마 내보내기';
$l['export_theme_desc'] = '여기에서 테마와 사용자 정의 템플릿을 내보낼 수 있습니다. 테마 내보내기는 테마를 다른 사람과 공유하거나 다른 포럼으로 가져오려는 경우 유용합니다.';
$l['duplicate_theme'] = '테마 복제';
$l['duplicate_theme_desc'] = '여기에서 테마를 복제할 수 있습니다. 이는 다른 버전을 개발하려는 경우 도움이 됩니다.';
$l['colors_manage'] = '색상 관리';
$l['colors_attached_to'] = '색상 설정';
$l['colors_setting'] = '기본 색상';
$l['colors_setting_desc'] = '이 테마가 기본 색상으로 사용할 색상을 선택하세요. 이 색상에 첨부된 스타일시트가 사용됩니다.';
$l['colors_no_color_setting'] = '사용 가능한 색상이 없습니다. 이 기능을 사용하려면 아래 색상 목록을 만드십시오.';
$l['colors_add'] = '색상 관리';
$l['colors_add_desc'] = '이 테마에 사용할 수 있는 색상 목록입니다. 이는 키 쌍(키=항목) 색상의 목록이어야 합니다(예: <em>blue=Blue</em>). 항목을 새 줄로 구분하세요.';
$l['colors_please_select'] = '없음';
$l['colors_add_edit_desc'] = '이 스타일시트를 첨부할 색상을 선택하세요. 하나 이상의 색상을 선택할 수 있습니다.';
$l['colors_specific_color'] = '특정 색상';
$l['include_custom_only'] = '사용자 정의된 항목만 포함하시겠습니까?';
$l['include_custom_only_desc'] = '상위 테마에서 상속된 항목(CSS 및 스타일시트)을 포함하려면 "아니요"를 선택하십시오. 그렇지 않으면 사용자 정의된 요소만 내보내집니다.';
$l['include_templates'] = '내보내기에도 템플릿을 포함하시겠습니까?';
$l['include_templates_desc'] = '이 테마에 사용된 사용자 정의 템플릿도 내보내려면 예를 선택하세요.';
$l['edit_stylesheet_simple_mode'] = '스타일시트 편집: 단순 모드';
$l['edit_stylesheet_simple_mode_desc'] = '여기에서 테마의 스타일시트를 쉽게 편집할 수 있습니다. 단순 모드를 사용하면 CSS에 대한 지식이 거의 또는 전혀 없어도 이 스타일시트의 CSS를 사용자 정의할 수 있습니다. 아래 항목을 선택하여 시작하세요.';
$l['edit_stylesheet_advanced_mode'] = '스타일시트 편집: 고급 모드';
$l['edit_stylesheet_advanced_mode_desc'] = '여기에서 이 스타일시트를 플랫 파일처럼 편집할 수 있습니다. CSS 스타일시트의 내용은 아래 텍스트 영역에 표시됩니다.';
$l['theme'] = '테마';
$l['num_users'] = '# 사용자';
$l['edit_theme'] = '테마 편집';
$l['delete_theme'] = '테마 삭제';
$l['set_as_default'] = '기본값으로 설정';
$l['default_theme'] = '기본 테마';
$l['force_on_users'] = '사용자에게 강제 적용';
$l['delete_revert'] = '삭제/복귀';
$l['local_file'] = '로컬 파일';
$l['url'] = 'URL';
$l['import_from'] = '다음에서 가져오기';
$l['import_from_desc'] = '가져올 파일을 선택하세요. 컴퓨터나 URL에서 테마 파일을 가져올 수 있습니다. <strong>안전하고 신뢰할 수 있는 출처에서만</strong> 테마를 사용하세요.';
$l['parent_theme'] = '상위 테마';
$l['parent_theme_desc'] = '이 테마가 하위 테마가 되어야 하는 테마를 선택하세요.';
$l['new_name'] = '새 이름';
$l['new_name_desc'] = '가져온 테마의 새 이름입니다. 비워두면 테마 파일에 있는 이름이 사용됩니다.';
$l['advanced_options'] = '고급 옵션';
$l['ignore_version_compatibility'] = '버전 호환성 무시';
$l['ignore_version_compat_desc'] = '이 테마는 생성된 MyBB 버전에 관계없이 설치되어야 합니까?';
$l['import_stylesheets'] = '스타일시트 가져오기';
$l['import_stylesheets_desc'] = '이 테마에 사용자 정의 스타일시트가 포함되어 있으면 이를 가져와야 합니까?';
$l['import_templates'] = '템플릿 가져오기';
$l['import_templates_desc'] = '이 테마에 사용자 정의 템플릿이 포함되어 있으면 해당 템플릿을 가져와야 합니까?';
$l['import_theme'] = '테마 가져오기';
$l['new_name_duplicate_desc'] = '복제된 테마의 새 이름입니다.';
$l['duplicate_stylesheets'] = '중복된 스타일시트';
$l['duplicate_stylesheets_desc'] = '이 테마에 사용자 정의 스타일시트가 포함된 경우 이를 복제해야 합니까?';
$l['duplicate_templates'] = '중복 템플릿';
$l['duplicate_templates_desc'] = '이 테마에 사용자 정의 템플릿이 포함되어 있으면 이를 복제해야 합니까?';
$l['create_a_theme'] = '테마 만들기';
$l['name'] = '이름';
$l['name_desc'] = '새 테마의 이름을 지정합니다.';
$l['display_order'] = '순서';
$l['edit_theme_properties'] = '테마 속성 편집';
$l['name_desc_edit'] = '테마 이름을 지정합니다.';
$l['allowed_user_groups'] = '허용된 사용자 그룹';
$l['allowed_user_groups_desc'] = '이 테마를 사용할 수 있는 사용자 그룹을 지정합니다. \'모든 사용자 그룹\'을 선택하면 다른 선택보다 우선 적용됩니다. 여러 사용자 그룹을 선택하려면 Ctrl 키를 누른 채 선택하세요.';
$l['all_user_groups'] = '모든 사용자 그룹';
$l['template_set'] = '템플릿 세트';
$l['template_set_desc'] = '테마가 사용해야 하는 템플릿 세트를 지정합니다. 선택한 템플릿 세트는 테마를 표시하는 데 사용되는 마크업(HTML)을 정의합니다.';
$l['editor_theme'] = '에디터 스타일';
$l['editor_theme_desc'] = '이 테마에서 MyCode 편집기에 사용할 스타일을 지정합니다. 편집기 스타일은 <strong>jscripts/sceditor/themes</strong> 폴더에서 찾을 수 있습니다.';
$l['img_directory'] = '이미지 디렉토리';
$l['img_directory_desc'] = '이 테마에 사용된 이미지 위치의 루트 디렉터리입니다. 이는 스타일시트가 아닌 템플릿에 사용되는 이미지의 디렉토리만 지정한다는 점에 유의하세요.';
$l['logo'] = '보드 로고';
$l['logo_desc'] = '이 테마에 사용된 보드 로고의 위치(각 페이지 상단에 나타나는 로고)입니다.';
$l['table_spacing'] = '테이블 간격';
$l['table_spacing_desc'] = '테이블 셀 내부 패딩의 너비(픽셀)입니다. 이는 <em>table</em> 태그의 HTML <em>cellpadding</em> 속성입니다.';
$l['inner_border'] = '내부 테이블 테두리 너비';
$l['inner_border_desc'] = '각 테이블 셀 사이의 패딩 양(픽셀)입니다. 이는 <em>table</em> 태그의 HTML <em>cellspacing</em> 속성입니다.';
$l['save_theme_properties'] = '테마 속성 저장';
$l['save_stylesheet_order'] = '스타일시트 순서 저장';
$l['background'] = '백그라운드';
$l['extra_css_atribs'] = '추가 CSS 속성';
$l['color'] = '색상';
$l['width'] = '너비';
$l['text_decoration'] = '텍스트 장식';
$l['font_family'] = '글꼴 패밀리';
$l['font_size'] = '글꼴 크기';
$l['font_style'] = '글꼴 스타일';
$l['font_weight'] = '글꼴 두께';
$l['stylesheets'] = '스타일시트';
$l['inherited_from'] = '다음에서 상속됨';
$l['attached_to'] = '다음에 첨부됨';
$l['attached_to_nothing'] = '아무것도 첨부되지 않은';
$l['attached_to_desc'] = '스타일시트를 전체적으로 첨부하거나 특정 파일에 첨부할 수 있습니다. 특정 파일에 첨부하는 경우 각 파일 내의 특정 작업에 첨부할 수 있습니다.';
$l['actions'] = '액션';
$l['of'] = 'of';
$l['attached_to_all_pages'] = '모든 페이지에 첨부';
$l['properties'] = '속성';
$l['edit_style'] = '스타일 편집';
$l['stylesheets_in'] = '스타일시트에서';
$l['stylesheet_properties'] = '스타일시트 속성';
$l['stylesheet_inherited_default'] = '이 스타일시트는 현재 {1}에서 상속됩니다. 변경하면 상속이 중단되고 스타일시트가 이 테마에 복사됩니다.';
$l['stylesheet_inherited'] = '이 스타일시트는 현재 {1}에서 상속됩니다. 변경하면 상속이 중단되고 스타일시트가 이 테마에 복사됩니다. 상속을 유지하려면 {1}에서 이 스타일시트를 편집하세요.';
$l['globally'] = '글로벌하게';
$l['specific_files'] = '특정 파일';
$l['specific_actions'] = '특정 조치';
$l['specific_actions_desc'] = '작업은 쉼표로 구분됩니다.';
$l['file'] = '파일';
$l['add_another'] = '다른 항목 추가';
$l['edit_stylesheet_properties_for'] = '스타일시트 속성 편집';
$l['file_name'] = '파일 이름';
$l['file_name_desc'] = '스타일시트의 이름으로 일반적으로 <strong>[.css]</strong>로 끝납니다.';
$l['save_stylesheet_properties'] = '스타일시트 속성 저장';
$l['saved'] = '저장됨';
$l['editing'] = '편집 중';
$l['selector'] = '선택자';
$l['save_changes'] = '변경 사항 저장';
$l['save_changes_and_close'] = '변경 사항을 저장하고 닫기';
$l['save_changes_js'] = '먼저 변경사항을 저장하시겠습니까?';
$l['delete_confirm_js'] = '정말로 삭제하시겠습니까?';
$l['import_stylesheet_from'] = '이 테마의 다른 스타일시트에서 가져오기';
$l['write_own'] = '나만의 콘텐츠 작성';
$l['save_stylesheet'] = '스타일시트 저장';
$l['add_stylesheet_to'] = '스타일시트 추가';
$l['full_stylesheet_for'] = '전체 스타일시트:';
$l['recommended_themes_for_mybb'] = 'MyBB {1} 추천 테마';
$l['browse_results_for_mybb'] = 'MyBB {1}에 대한 결과 찾아보기';
$l['search_for_themes'] = '테마 검색';
$l['search'] = '검색';
$l['download'] = '다운로드';
$l['created_by'] = '만든 사람';
$l['theme_thumbnail'] = '테마 썸네일';
$l['error_invalid_stylesheet'] = '잘못된 스타일시트를 선택했습니다.';
$l['error_invalid_theme'] = '잘못된 테마를 선택했습니다.';
$l['error_missing_name'] = '이 테마의 이름을 입력하세요.';
$l['error_missing_url'] = '테마를 가져오려면 유효한 URL을 입력하세요.';
$l['error_theme_already_exists'] = '같은 이름의 테마가 이미 존재합니다. 다른 이름을 지정하십시오.';
$l['error_theme_security_problem'] = '테마에서 잠재적인 보안 문제가 발견되었습니다. 수입되지 않았습니다. 지원이 필요하면 작성자나 MyBB 그룹에 문의하세요.';
$l['error_local_file'] = '로컬 파일을 열 수 없습니다. 존재합니까? 확인하신 후 다시 시도해 주세요.';
$l['error_uploadfailed'] = '업로드에 실패했습니다. 다시 시도해 주세요.';
$l['error_uploadfailed_detail'] = '오류 세부정보:';
$l['error_uploadfailed_php1'] = 'PHP가 반환됨: 업로드된 파일이 php.ini의 upload_max_filesize 지시어를 초과했습니다. 이 오류에 대해서는 포럼 관리자에게 문의하세요.';
$l['error_uploadfailed_php2'] = '업로드된 파일이 지정된 최대 파일 크기를 초과했습니다.';
$l['error_uploadfailed_php3'] = '업로드된 파일이 부분적으로만 업로드되었습니다.';
$l['error_uploadfailed_php4'] = '업로드된 파일이 없습니다.';
$l['error_uploadfailed_php6'] = 'PHP가 반환됨: 임시 폴더가 없습니다. 이 오류에 대해서는 포럼 관리자에게 문의하세요.';
$l['error_uploadfailed_php7'] = 'PHP가 반환되었습니다. 파일을 디스크에 쓰지 못했습니다. 이 오류에 대해서는 포럼 관리자에게 문의하세요.';
$l['error_uploadfailed_phpx'] = 'PHP가 오류 코드를 반환했습니다: {1}. 이 오류에 대해서는 포럼 관리자에게 문의하세요.';
$l['error_uploadfailed_lost'] = '서버에서 파일을 찾을 수 없습니다.';
$l['error_uploadfailed_nocontents'] = 'MyBB가 업로드한 파일에서 테마를 찾을 수 없습니다. 파일이 올바른지, 손상되지 않았는지 확인하세요.';
$l['error_invalid_version'] = '이 테마는 MyBB의 다른 버전용으로 작성되었습니다. 이 오류를 무시하려면 "버전 호환성 무시"를 확인하십시오.';
$l['error_missing_stylesheet_name'] = '이 스타일시트의 이름을 입력하세요.';
$l['error_missing_stylesheet_extension'] = '이 스타일시트는 올바른 파일 확장자로 끝나야 합니다(예: {1}<em>.css</em>)';
$l['error_invalid_parent_theme'] = '선택한 상위 테마가 존재하지 않습니다. 유효한 상위 테마를 선택하세요.';
$l['error_invalid_templateset'] = '선택한 템플릿 세트가 존재하지 않습니다. 유효한 템플릿 세트를 선택하세요.';
$l['error_invalid_color'] = '정의된 색상 세트 "{1}"에 잘못된 문자가 있거나 규정된 형식이 아닙니다. 색상 이름과 값에는 숫자, 유니코드 문자, 밑줄만 허용되며 \'=\'로 구분해야 합니다.';
$l['error_invalid_editortheme'] = '선택한 편집기 테마가 존재하지 않습니다. 유효한 편집기 테마를 선택하세요.';
$l['error_inheriting_stylesheets'] = '이 테마에서 스타일시트를 상속하는 다른 테마가 아직 있기 때문에 이 테마를 삭제할 수 없습니다.';
$l['error_cannot_parse'] = 'MyBB는 단순 편집기에 대해 이 스타일시트를 구문 분석할 수 없습니다. 고급 모드에서만 편집할 수 있습니다.';
$l['error_communication_problem'] = 'MyBB 테마 서버와 통신하는 중에 문제가 발생했습니다. 몇 분 후에 다시 시도하십시오.';
$l['error_no_results_found'] = '지정된 키워드에 대한 결과를 찾을 수 없습니다.';
$l['error_no_color_picked'] = '이 스타일시트를 첨부할 색상을 지정하지 않았습니다.';
$l['error_no_display_order'] = '스타일시트의 표시 순서를 찾는 동안 오류가 발생했습니다. 페이지를 새로고침한 후 다시 시도하세요.';
$l['success_duplicated_theme'] = '선택한 테마가 성공적으로 복제되었습니다.';
$l['success_imported_theme'] = '선택한 테마를 성공적으로 가져왔습니다.';
$l['success_theme_created'] = '테마가 성공적으로 생성되었습니다.';
$l['success_theme_deleted'] = '선택한 테마가 성공적으로 삭제되었습니다.';
$l['success_stylesheet_properties_updated'] = '선택한 스타일시트의 속성이 성공적으로 업데이트되었습니다.';
$l['success_stylesheet_updated'] = '선택한 스타일시트가 성공적으로 업데이트되었습니다.';
$l['success_stylesheet_deleted'] = '선택한 스타일시트가 삭제/복원되었습니다.';
$l['success_theme_set_default'] = '선택한 테마가 이제 포럼 기본값이 됩니다.';
$l['success_theme_forced'] = '모든 사용자는 선택한 테마를 성공적으로 사용하도록 강제되었습니다.';
$l['success_theme_properties_updated'] = '선택 테마의 속성이 성공적으로 업데이트되었습니다.';
$l['success_stylesheet_added'] = '이 테마의 스타일시트가 성공적으로 생성되었습니다.';
$l['success_stylesheet_order_updated'] = '스타일시트의 표시 순서가 성공적으로 업데이트되었습니다.';
$l['confirm_theme_deletion'] = '이 테마를 삭제하시겠습니까?';
$l['confirm_stylesheet_deletion'] = '이 스타일시트를 삭제하거나 되돌리시겠습니까?';
$l['confirm_theme_forced'] = '모든 사용자에게 이 테마를 적용하시겠습니까? 테마의 액세스 수준이 재설정될 수 있습니다.';
$l['theme_info_fetch_error'] = '스타일 정보를 가져오는 중에 오류가 발생했습니다.';
$l['theme_info_save_error'] = '스타일 정보를 저장하는 중에 오류가 발생했습니다.';
$l['saving'] = '저장&hellip;';
