<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Sat, 29 Jun 2024 05:28:18 +0000
// --------------------------------------------------------------------------------

$l['templates_and_style'] = '템플릿 &amp; 스타일';
$l['themes'] = '테마';
$l['templates'] = '템플릿';
$l['can_manage_themes'] = '테마를 관리하시겠습니까?';
$l['can_manage_templates'] = '템플릿을 관리하시겠습니까?';
