<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 05 Jul 2024 03:52:34 +0000
// --------------------------------------------------------------------------------

$l['database_backups'] = '데이터베이스 백업';
$l['database_backups_desc'] = '여기에서는 현재 웹 서버의 MyBB Backups 디렉터리에 저장되어 있는 데이터베이스 백업 목록을 찾을 수 있습니다.';
$l['new_database_backup'] = '새 데이터베이스 백업';
$l['new_backup'] = '새 백업';
$l['new_backup_desc'] = '여기에서 데이터베이스 복사본을 백업할 수 있습니다.';
$l['backups'] = '백업';
$l['existing_database_backups'] = '기존 데이터베이스 백업';
$l['backup_saved_to'] = '백업이 다음 위치에 저장되었습니다.';
$l['download'] = '다운로드';
$l['table_selection'] = '테이블 선택';
$l['backup_options'] = '백업 옵션';
$l['table_select_desc'] = '여기에서 이 작업을 수행하려는 데이터베이스 테이블을 선택할 수 있습니다. 여러 테이블을 선택하려면 Ctrl 키를 누른 채 선택하세요.';
$l['select_all'] = '모두 선택';
$l['deselect_all'] = '모두 선택 취소';
$l['select_forum_tables'] = '포럼 테이블 선택';
$l['file_type'] = '파일 유형';
$l['file_type_desc'] = '데이터베이스 백업을 저장할 파일 형식을 선택하세요.';
$l['gzip_compressed'] = 'GZIP 압축';
$l['plain_text'] = '일반 텍스트';
$l['save_method'] = '저장 방법';
$l['save_method_desc'] = '백업을 저장하는 데 사용할 방법을 선택하십시오.';
$l['backup_directory'] = '백업 디렉토리';
$l['backup_contents'] = '백업 내용';
$l['backup_contents_desc'] = '백업에 포함할 정보를 선택하세요.';
$l['structure_and_data'] = '구조와 데이터';
$l['structure_only'] = '구조만';
$l['data_only'] = '데이터만';
$l['analyze_and_optimize'] = '선택한 테이블 분석 및 최적화';
$l['analyze_and_optimize_desc'] = '백업 중에 선택한 테이블을 분석하고 최적화하시겠습니까?';
$l['perform_backup'] = '백업 수행';
$l['backup_filename'] = '백업 파일 이름';
$l['file_size'] = '파일 크기';
$l['creation_date'] = '생산 일';
$l['no_backups'] = '현재 아직 백업된 내용이 없습니다.';
$l['error_file_not_specified'] = '다운로드할 데이터베이스 백업을 지정하지 않았습니다.';
$l['error_invalid_backup'] = '선택한 백업 파일이 잘못되었거나 존재하지 않습니다.';
$l['error_backup_doesnt_exist'] = '지정한 백업이 존재하지 않습니다.';
$l['error_backup_not_deleted'] = '백업이 삭제되지 않았습니다.';
$l['error_tables_not_selected'] = '백업할 테이블을 선택하지 않았습니다.';
$l['error_no_zlib'] = 'PHP용 zlib 라이브러리가 활성화되지 않았습니다. GZIP 압축 백업을 생성할 수 없습니다.';
$l['alert_not_writable'] = '백업 디렉터리(Admin CP 디렉터리 내)에 쓸 수 없습니다. 서버에는 백업을 저장할 수 없습니다.';
$l['confirm_backup_deletion'] = '이 백업을 삭제하시겠습니까?';
$l['success_backup_deleted'] = '백업이 성공적으로 삭제되었습니다.';
$l['success_backup_created'] = '백업이 성공적으로 생성되었습니다.';
