<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 05 Jul 2024 03:47:57 +0000
// --------------------------------------------------------------------------------

$l['mod_logs'] = '중재자 로그';
$l['mod_logs_desc'] = '여기에서 중재자 로그를 보고, 정리하고, 검색할 수 있습니다. 이러한 로그에는 모든 사용자가 수행할 수 있는 작업(자신의 게시물/글타래 삭제)과 중재자가 수행하는 기타 모든 작업이 포함됩니다.';
$l['prune_mod_logs'] = '중재자 로그 제거';
$l['prune_mod_logs_desc'] = '여기에서 지정된 기준과 일치하는 중재자 로그를 정리할 수 있습니다.';
$l['no_modlogs'] = '선택한 기준에 해당하는 로그 항목이 없습니다.';
$l['username'] = '사용자 이름';
$l['na_deleted'] = '해당 없음 - 삭제되었습니다.';
$l['date'] = '날짜';
$l['action'] = '동작';
$l['information'] = '정보';
$l['ipaddress'] = 'IP 주소';
$l['forum'] = '포럼:';
$l['thread'] = '글타래:';
$l['post'] = '게시물:';
$l['user_info'] = '사용자:';
$l['announcement'] = '공지사항:';
$l['filter_moderator_logs'] = '중재자 로그 필터링';
$l['forum_moderator'] = '포럼 중재자:';
$l['sort_by'] = '정렬 기준:';
$l['results_per_page'] = '페이지당 결과:';
$l['all_moderators'] = '모든 중재자';
$l['older_than'] = '이전의';
$l['forum_name'] = '포럼 이름';
$l['thread_subject'] = '글타래 제목';
$l['asc'] = '오름차순';
$l['desc'] = '내림차순';
$l['in'] = 'in';
$l['order'] = '순서';
$l['days'] = '일';
$l['prune_moderator_logs'] = '중재자 로그 정리';
$l['date_range'] = '날짜 범위:';
$l['success_pruned_mod_logs'] = '중재자 로그가 성공적으로 정리되었습니다.';
$l['note_logs_locked'] = '보안상의 이유로 24시간 미만의 로그는 정리할 수 없습니다.';
