<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 05 Jul 2024 04:21:40 +0000
// --------------------------------------------------------------------------------

$l['warning_logs'] = '경고 로그';
$l['warning_logs_desc'] = '이 섹션에서는 사용자에게 발행된 경고 기록을 볼 수 있습니다.';
$l['warned_user'] = '경고받은 사용자';
$l['warning'] = '경고';
$l['date_issued'] = '발행 날짜';
$l['expires'] = '만료';
$l['expiry_date'] = '만료일';
$l['issued_date'] = '발행일';
$l['issued_by'] = '발행자';
$l['details'] = '세부';
$l['filter_warning_logs'] = '경고 로그 필터링';
$l['filter_warned_user'] = '경고된 사용자:';
$l['filter_issued_by'] = '경고 발행자:';
$l['filter_reason'] = '이유 포함:';
$l['sort_by'] = '정렬 기준:';
$l['results_per_page'] = '페이지당 결과:';
$l['view'] = '보기';
$l['no_warning_logs'] = '볼 수 있는 경고 로그가 없습니다.';
$l['revoked'] = '취소됨';
$l['post'] = '게시물';
$l['asc'] = '오름차순';
$l['desc'] = '내림차순';
$l['in'] = 'in';
$l['order'] = '순서';
$l['warning_details'] = '경고 세부정보';
$l['warning_note'] = '관리 메모';
$l['already_expired'] = '만료됨';
$l['warning_revoked'] = '취소됨';
$l['warning_active'] = '활동동';
$l['error_invalid_warning'] = '잘못된 경고가 지정되었습니다.';
$l['revoke_warning'] = '이 경고를 취소하세요';
$l['revoke_warning_desc'] = '이 경고를 취소하려면 아래에 이유를 입력하세요. 이 경고로 인해 부과된 차단이나 정지는 제거되지 않습니다.';
$l['reason'] = '이유:';
$l['warning_is_revoked'] = '이 경고는 취소되었습니다.';
$l['revoked_by'] = '취소자:';
$l['date_revoked'] = '취소된 날짜:';
$l['error_already_revoked'] = '이 경고는 이미 취소되었습니다.';
$l['error_no_revoke_reason'] = '이 경고를 취소하려는 이유를 입력하지 않았습니다.';
$l['redirect_warning_revoked'] = '이 경고는 취소되었으며 사용자 경고 포인트가 성공적으로 감소되었습니다.';
$l['warning_points'] = '({1}포인트)';
