<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Thu, 04 Jul 2024 05:38:38 +0000
// --------------------------------------------------------------------------------

$l['statistics'] = '통계';
$l['overall_statistics'] = '종합통계';
$l['overall_statistics_desc'] = '여기에서 포럼의 전반적인 통계를 볼 수 있습니다. 모든 시간은 UTC 기준입니다.';
$l['date_range'] = '날짜 범위';
$l['date'] = '날짜';
$l['users'] = '사용자';
$l['threads'] = '글타래';
$l['posts'] = '게시물';
$l['from'] = '에서';
$l['to'] = '에게';
$l['increase'] = '증가';
$l['no_change'] = '변경 없음';
$l['decrease'] = '감소';
$l['error_no_results_found_for_criteria'] = '제공하신 기간에 해당하는 결과를 찾을 수 없습니다. 다른 기간을 사용해 보세요.';
$l['error_no_statistics_available_yet'] = '죄송합니다. 현재 귀하의 포럼에 사용할 수 있는 통계 데이터가 없습니다.';
