<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 05 Jul 2024 04:30:14 +0000
// --------------------------------------------------------------------------------

$l['system_health'] = '시스템 상태';
$l['system_health_desc'] = '여기에서 시스템 상태에 대한 정보를 볼 수 있습니다.';
$l['utf8_conversion'] = 'UTF-8 변환';
$l['utf8_conversion_desc'] = '현재 데이터베이스 테이블을 UTF-8 형식으로 변환하고 있습니다. 포럼 및 이 테이블의 규모에 따라 이 프로세스는 몇 시간까지 걸릴 수 있습니다. 프로세스가 완료되면 UTF-8 변환 기본 페이지로 돌아갑니다.';
$l['utf8_conversion_desc2'] = '이 도구는 데이터베이스 테이블이 UTF-8 형식인지 확인하고 그렇지 않은 경우 변환할 수 있도록 합니다.';
$l['convert_all'] = '모두 변환';
$l['converting_to_utf8'] = 'MyBB는 현재 "{1}" 테이블을 {2} 인코딩에서 UTF-8 언어 인코딩으로 변환하고 있습니다.';
$l['convert_to_utf8'] = '"{1}" 테이블을 {2} 인코딩에서 UTF-8 언어 인코딩으로 변환하려고 합니다.';
$l['convert_all_to_utf'] = '모든 테이블을 {1} 인코딩에서 UTF-8 언어 인코딩으로 변환하려고 합니다.';
$l['convert_all_to_utf8mb4'] = '모든 테이블을 {1} 인코딩에서 4바이트 UTF-8 유니코드 언어 인코딩으로 변환하려고 합니다.';
$l['converting_to_utf8mb4'] = 'MyBB는 현재 "{1}" 테이블을 {2} 인코딩에서 4바이트 UTF-8 유니코드 언어 인코딩으로 변환하고 있습니다.';
$l['please_wait'] = '잠시만 기다려주세요&hellip;';
$l['converting_table'] = '테이블 변환: {1}';
$l['convert_table'] = '테이블 변환';
$l['convert_tables'] = '모든 테이블 변환';
$l['convert_database_table'] = '데이터베이스 테이블 변환';
$l['convert_database_tables'] = '모든 데이터베이스 테이블 변환';
$l['table'] = '테이블';
$l['status_utf8'] = 'UTF-8 상태';
$l['status_utf8mb4'] = '4-Byte UTF-8 Support<br />(requires MySQL 5.5.3 or above)';
$l['not_available'] = '사용 불가';
$l['all_tables'] = '모든 테이블';
$l['convert_now'] = '지금 변환';
$l['totals'] = '합계';
$l['attachments'] = '첨부파일';
$l['total_database_size'] = '총 데이터베이스 크기';
$l['attachment_space_used'] = '사용된 첨부파일 공간';
$l['total_cache_size'] = '총 캐시 크기';
$l['estimated_attachment_bandwidth_usage'] = '예상 첨부 대역폭 사용량';
$l['max_upload_post_size'] = '최대 업로드/포스트 크기';
$l['average_attachment_size'] = '평균 첨부 파일 크기';
$l['stats'] = '통계';
$l['task'] = '작업업';
$l['run_time'] = '실행 시간';
$l['next_3_tasks'] = '다음 3가지 작업';
$l['no_tasks'] = '현재 실행 중인 작업이 없습니다.';
$l['backup_time'] = '백업 시간';
$l['no_backups'] = '현재 아직 백업된 내용이 없습니다.';
$l['existing_db_backups'] = '기존 데이터베이스 백업';
$l['writable'] = '쓰기 가능';
$l['not_writable'] = '쓰기 불가능';
$l['please_chmod_777'] = 'Please CHMOD to 777.';
$l['chmod_info'] = 'CHMOD 설정을 아래 파일에 지정된 설정으로 변경하세요. CHMODing에 대한 자세한 내용은 다음을 참조하세요.';
$l['file'] = '파일';
$l['location'] = '위치';
$l['settings_file'] = '설정 파일';
$l['config_file'] = '구성 파일';
$l['file_upload_dir'] = '파일 업로드 디렉토리';
$l['avatar_upload_dir'] = '아바타 업로드 디렉토리';
$l['language_files'] = '언어 파일';
$l['backup_dir'] = '백업 디렉토리';
$l['cache_dir'] = '캐시 디렉토리';
$l['themes_dir'] = '테마 디렉토리';
$l['chmod_files_and_dirs'] = 'CHMOD 파일 및 디렉터리';
$l['notice_process_long_time'] = '이 프로세스는 포럼 및 이 테이블의 크기에 따라 최대 몇 시간이 걸릴 수 있습니다. <strong>이 프로세스는 취소할 수 없으므로 데이터베이스 백업을 만드는 것이 좋습니다.</strong>';
$l['notice_mb4_warning'] = '4바이트 UTF-8을 지원하려면 MySQL 5.5.3 이상이 필요합니다. 다른 버전이 있는 MySQL 서버에서는 데이터베이스를 가져올 수 없습니다.';
$l['check_templates'] = '템플릿 확인';
$l['check_templates_desc'] = '알려진 보안 문제가 있는지 설치된 모든 템플릿을 확인합니다.';
$l['check_templates_title'] = '템플릿 보안 확인';
$l['check_templates_info'] = '이 프로세스에서는 포럼과 포럼이 실행되는 서버에 영향을 미칠 수 있는 보안 문제에 대해 템플릿을 확인합니다. 테마를 많이 설치한 경우 시간이 걸릴 수 있습니다.
<br /><br />프로세스를 시작하려면 아래 \'진행\' 버튼을 누르세요.';
$l['check_templates_info_desc'] = '아래 템플릿은 알려진 보안 문제와 일치합니다. 검토해 보세요.';
$l['full_edit'] = '전체 편집';
$l['error_chmod'] = '필요한 파일 및 디렉터리에 적절한 CHMOD 설정이 없습니다.';
$l['error_invalid_table'] = '지정한 테이블이 존재하지 않습니다.';
$l['error_db_encoding_not_set'] = '현재 MyBB 설정은 아직 이 도구를 사용하도록 설정되지 않았습니다. 설정 방법에 대한 자세한 내용은 <a href="https://docs.mybb.com/1.8/administration/utf-8-setup/">MyBB 문서</a>를 참조하세요.';
$l['error_not_supported'] = '현재 데이터베이스 엔진은 UTF-8 변환 도구에서 지원되지 않습니다.';
$l['error_invalid_input'] = '템플릿을 확인하는 중에 문제가 발생했습니다. 다시 시도하거나 MyBB 그룹에 지원을 문의하세요.';
$l['error_master_templates_altered'] = '마스터 템플릿이 변경되었습니다. 이를 변경하는 방법에 대한 지원을 받으려면 MyBB 그룹에 문의하세요.';
$l['error_utf8mb4_version'] = '귀하의 MySQL 버전은 4바이트 UTF-8 인코딩을 지원하지 않습니다.';
$l['warning_multiple_encodings'] = '데이터베이스에서 다른 인코딩을 사용하지 않는 것이 좋습니다. 이로 인해 예기치 않은 동작이나 MySQL 오류가 발생할 수 있습니다.';
$l['warning_utf8mb4_config'] = '완전한 4바이트 UTF-8 지원을 위해서는 <i>$config[\'database\'][\'encoding\'] = \'utf8\';</i>을 <i>$config[\'database\'][\'로 변경해야 합니다. 인코딩\'] = \'utf8mb4\';</i> inc/config.php에 있습니다.';
$l['success_templates_checked'] = '템플릿이 성공적으로 확인되었습니다. 보안 문제가 발견되지 않았습니다!';
$l['success_all_tables_already_converted'] = '모든 테이블은 이미 변환되었거나 이미 UTF-8 형식입니다.';
$l['success_table_converted'] = '선택한 테이블 "{1}"이(가) UTF-8로 성공적으로 변환되었습니다.';
$l['success_chmod'] = '필요한 모든 파일과 디렉터리에는 적절한 CHMOD 설정이 있습니다.';
