<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Thu, 04 Jul 2024 05:37:44 +0000
// --------------------------------------------------------------------------------

$l['user_email_log'] = '사용자 이메일 로그';
$l['user_email_log_desc'] = '한 회원이 다른 회원에게 보낸 모든 이메일과 \'친구에게 스레드 보내기\' 기능을 통해 보낸 이메일은 모두 기록되어 아래에 표시됩니다. 여기에서 이 기능을 남용할 가능성이 있는 사용자를 식별할 수 있습니다.';
$l['prune_user_email_log'] = '사용자 이메일 로그 정리';
$l['close_window'] = '창 닫기';
$l['user_email_log_viewer'] = '사용자 이메일 로그 뷰어';
$l['to'] = '에게';
$l['from'] = '부터';
$l['ip_address'] = 'IP 주소';
$l['subject'] = '제목';
$l['date'] = '날짜';
$l['email'] = '이메일';
$l['date_sent'] = '보낸 날짜';
$l['deleted'] = '삭제됨';
$l['sent_using_send_thread_feature'] = '친구에게 글타래 보내기 기능을 사용하여 보냈습니다.';
$l['thread'] = '글타래:';
$l['find_emails_by_user'] = '이 사용자가 보낸 모든 이메일 찾기';
$l['find'] = '찾기';
$l['deleted_user'] = '삭제 된 사용자';
$l['email_sent_to_user'] = '사용자에게 이메일이 전송됨';
$l['email_sent_using_contact_form'] = '문의 양식을 사용하여 보낸 이메일';
$l['no_logs'] = '선택한 기준에 해당하는 로그 항목이 없습니다.';
$l['filter_user_email_log'] = '사용자 이메일 로그 필터링';
$l['username_is'] = '사용자 이름은';
$l['email_contains'] = '이메일 주소 포함';
$l['subject_contains'] = '제목 포함';
$l['find_emails_to_user'] = '이 사용자에게 보낸 모든 이메일 찾기';
$l['error_invalid_user'] = '입력한 사용자 이름이 존재하지 않습니다.';
