<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Thu, 04 Jul 2024 05:31:27 +0000
// --------------------------------------------------------------------------------

$l['cache'] = '캐시:';
$l['cache_manager'] = '캐시 관리자';
$l['cache_manager_description'] = '여기에서는 MyBB를 최적화하는 방법으로 사용되는 캐시를 관리할 수 있습니다. 캐시를 재구축하면 캐시를 생성하고 다시 동기화하는 데 필요한 모든 데이터가 사용됩니다. 캐시를 다시 로드하면 선택한 캐시 처리기(디스크, eaccelerator, memcache 등)로 캐시가 다시 로드됩니다. 다시 로드는 데이터베이스나 파일 시스템에서 xcache, eaccelerator 또는 다른 캐시 처리기로 전환할 때 유용합니다.';
$l['rebuild_cache'] = '캐시 재구축';
$l['reload_cache'] = '캐시 다시 로드';
$l['rebuild_reload_all'] = '(모두 다시 빌드 및 다시 로드)';
$l['error_cannot_rebuild'] = '이 캐시는 다시 작성할 수 없습니다.';
$l['error_empty_cache'] = '캐시가 비어 있습니다.';
$l['error_incorrect_cache'] = '잘못된 캐시가 지정되었습니다.';
$l['error_no_cache_specified'] = '보려는 캐시를 지정하지 않았습니다.';
$l['success_cache_rebuilt'] = '캐시가 성공적으로 재구축되었습니다.';
$l['success_cache_reloaded'] = '캐시가 성공적으로 다시 로드되었습니다.';
