<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 05 Jul 2024 04:08:21 +0000
// --------------------------------------------------------------------------------

$l['task_manager'] = '작업 관리자';
$l['add_new_task'] = '새 작업 추가';
$l['add_new_task_desc'] = '여기에서 보드에서 자동으로 실행되는 새로운 예약 작업을 생성할 수 있습니다.';
$l['edit_task'] = '작업 편집';
$l['edit_task_desc'] = '아래에서 이 예약된 작업에 대한 다양한 설정을 편집할 수 있습니다.';
$l['task_logs'] = '작업 로그';
$l['view_task_logs'] = '작업 로그 보기';
$l['view_task_logs_desc'] = '작업이 실행되고 로깅이 활성화되면 결과 또는 오류가 아래에 나열됩니다. 30일이 지난 항목은 자동으로 삭제됩니다.';
$l['scheduled_tasks'] = '예약된 작업';
$l['scheduled_tasks_desc'] = '여기에서는 보드에서 자동으로 실행되는 작업을 관리할 수 있습니다. 지금 작업을 실행하려면 작업 오른쪽에 있는 아이콘을 클릭하세요.';
$l['title'] = '제목';
$l['short_description'] = '간단한 설명';
$l['task_file'] = '작업 파일';
$l['task_file_desc'] = '이 작업을 실행할 작업 파일을 선택하세요.';
$l['time_minutes'] = '시간: 분';
$l['time_minutes_desc'] = '이 작업을 실행해야 하는 쉼표로 구분된 분 목록(0-59)을 입력하십시오. 이 작업을 1분마다 실행하려면 \'*\'를 입력하세요.';
$l['time_hours'] = '시간: 시';
$l['time_hours_desc'] = '이 작업을 실행해야 하는 시간 목록(0-23)을 쉼표로 구분하여 입력하세요. 이 작업을 매시간 실행하려면 \'*\'를 입력하세요.';
$l['time_days_of_month'] = '시간: 매월 일';
$l['time_days_of_month_desc'] = '이 작업을 실행해야 하는 날짜(1-31)를 쉼표로 구분하여 입력하세요. 이 작업을 매일 실행해야 하거나 아래에서 평일을 지정하려면 \'*\'를 입력하세요.';
$l['every_weekday'] = '평일마다';
$l['sunday'] = '일요일';
$l['monday'] = '월요일';
$l['tuesday'] = '화요일';
$l['wednesday'] = '수요일';
$l['thursday'] = '목요일';
$l['friday'] = '금요일';
$l['saturday'] = '토요일';
$l['time_weekdays'] = '시간: 평일';
$l['time_weekdays_desc'] = '이 작업을 실행할 평일을 선택하세요. CTRL을 누르고 있으면 여러 요일이 선택됩니다. 이 작업을 평일마다 실행하거나 위에서 미리 정의된 날짜를 입력한 경우 \'주중마다\'를 선택하세요.';
$l['every_month'] = '매 달';
$l['time_months'] = '시간: 월';
$l['time_months_desc'] = '이 작업을 실행할 달을 선택하세요. Ctrl 키를 누르고 있으면 여러 달이 선택됩니다. 이 작업을 매달 실행하려면 \'매월\'을 선택하세요.';
$l['enabled'] = '작업 활성화?';
$l['enable_logging'] = '로깅을 활성화?';
$l['save_task'] = '작업 저장';
$l['task'] = '작업';
$l['date'] = '날짜';
$l['data'] = '데이터';
$l['no_task_logs'] = '현재 예약된 작업에 대한 로그 항목이 없습니다.';
$l['next_run'] = '다음 실행';
$l['run_task_now'] = '지금 작업 실행';
$l['disable_task'] = '작업 비활성화';
$l['run_task'] = '작업 실행';
$l['enable_task'] = '작업 활성화';
$l['delete_task'] = '작업 삭제';
$l['error_invalid_task'] = '지정된 작업이 존재하지 않습니다.';
$l['error_missing_title'] = '이 예약된 작업의 제목을 입력하지 않았습니다.';
$l['error_missing_description'] = '이 예약된 작업에 대한 설명을 입력하지 않았습니다.';
$l['error_invalid_task_file'] = '선택한 작업 파일이 존재하지 않습니다.';
$l['error_invalid_minute'] = '입력하신 분이 유효하지 않습니다.';
$l['error_invalid_hour'] = '입력한 시간이 잘못되었습니다.';
$l['error_invalid_day'] = '입력한 날짜가 잘못되었습니다.';
$l['error_invalid_weekday'] = '선택하신 평일이 잘못되었습니다.';
$l['error_invalid_month'] = '선택한 달이 잘못되었습니다.';
$l['success_task_created'] = '작업이 성공적으로 생성되었습니다.';
$l['success_task_updated'] = '선택한 작업이 성공적으로 업데이트되었습니다.';
$l['success_task_deleted'] = '선택한 작업이 성공적으로 삭제되었습니다.';
$l['success_task_enabled'] = '선택한 작업이 성공적으로 활성화되었습니다.';
$l['success_task_disabled'] = '선택한 작업이 성공적으로 비활성화되었습니다.';
$l['success_task_run'] = '선택한 작업이 성공적으로 실행되었습니다.';
$l['confirm_task_deletion'] = '이 예약된 작업을 삭제하시겠습니까?';
$l['confirm_task_enable'] = '<strong>경고:</strong> cron을 통해서만 실행되는 작업을 활성화하려고 합니다(<a href="https://docs.mybb.com/1.8/administration/task- 자세한 내용은 관리자" target="_blank" rel="noopener">MyBB 문서</a>를 참조하세요). 계속하다?';
$l['no_tasks'] = '현재 귀하의 포럼에는 작업이 없습니다.';
