<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Sat, 29 Jun 2024 05:27:20 +0000
// --------------------------------------------------------------------------------

$l['optimize_database'] = '데이터베이스 최적화';
$l['table_selection'] = '테이블 선택';
$l['tables_select_desc'] = '여기에서 이 작업을 수행하려는 데이터베이스 테이블을 선택할 수 있습니다. 여러 테이블을 선택하려면 Ctrl 키를 누른 채 선택하세요.';
$l['select_all'] = '모두 선택';
$l['deselect_all'] = '모두 선택 취소';
$l['select_forum_tables'] = '포럼 테이블 선택';
$l['optimize_selected_tables'] = '선택한 테이블 최적화';
$l['error_no_tables_selected'] = '최적화할 데이터베이스 테이블을 선택하지 않았습니다.';
$l['success_tables_optimized'] = '선택한 테이블이 성공적으로 최적화되고 분석되었습니다.';
