<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Thu, 04 Jul 2024 03:20:20 +0000
// --------------------------------------------------------------------------------

$l['tools_and_maintenance'] = '도구 &amp; 유지';
$l['maintenance'] = '유지';
$l['logs'] = '로그';
$l['system_health'] = '시스템 건강상태';
$l['cache_manager'] = '캐시 관리자';
$l['task_manager'] = '작업 관리자';
$l['recount_and_rebuild'] = 'Recount &amp; Rebuild';
$l['view_php_info'] = 'PHP 정보 보기';
$l['database_backups'] = '데이터베이스 백업';
$l['optimize_database'] = '데이터베이스 최적화';
$l['file_verification'] = '파일 검증';
$l['administrator_log'] = '관리자 로그';
$l['moderator_log'] = '중재자 로그';
$l['user_email_log'] = '사용자 이메일 로그';
$l['system_mail_log'] = '시스템 메일 로그';
$l['user_warning_log'] = '사용자 경고 로그';
$l['spam_log'] = '스팸 로그';
$l['statistics'] = '통계';
$l['can_access_system_health'] = '시스템 상태 액세스?';
$l['can_manage_cache'] = '캐시를 관리?';
$l['can_manage_tasks'] = '예약된 작업을 관리?';
$l['can_manage_db_backup'] = '백업 데이터베이스를 관리?';
$l['can_optimize_db'] = '데이터베이스를 최적화?';
$l['can_recount_and_rebuild'] = 'Can recount and rebuild?';
$l['can_manage_admin_logs'] = '관리자 로그를 관리?';
$l['can_manage_mod_logs'] = '중재자 로그를 관리?';
$l['can_manage_user_mail_log'] = '사용자 메일 로그를 관리?';
$l['can_manage_system_mail_log'] = '시스템 메일 로그를 관리?';
$l['can_manage_user_warning_log'] = '사용자 경고 로그를 관리?';
$l['can_manage_spam_log'] = '스팸 로그를 관리?';
$l['can_view_php_info'] = 'PHP 정보를 보기?';
$l['can_manage_file_verification'] = '파일 확인을 관리?';
$l['can_view_statistics'] = '통계 보기?';
