<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Thu, 04 Jul 2024 05:31:45 +0000
// --------------------------------------------------------------------------------

$l['file_verification'] = '파일 검증';
$l['checking'] = '확인 중&hellip;';
$l['file_verification_message'] = '이 프로세스는 모든 MyBB 기본 파일을 검사하여 유효성을 확인합니다. 계속하려면 예를 누르세요.<br /> <small>이 프로세스에서는 사용자 정의 수정과 파일의 실제 손상을 구별할 수 없습니다. 따라서 이 프로세스에서 "손상"으로 반환되는 파일을 되돌릴 때는 주의해야 합니다. 손상되거나 누락된 파일은 <a href="https://mybb.com/download" target="_blank" rel="noopener">원본 MyBB 패키지</a>에서 복사하여 교체할 수 있습니다.</small>';
$l['error_communication'] = 'MyBB 서버와 통신하는 중에 문제가 발생했습니다. 몇 분 후에 다시 시도하십시오.';
$l['file'] = '파일';
$l['no_corrupt_files_found'] = '축하합니다! 설치시 손상된 파일이 발견되지 않았습니다.';
$l['found_problems'] = '발견된 문제';
$l['no_problems_found'] = '발견된 문제 없음';
$l['changed'] = '변경됨';
$l['missing'] = '누락됨';
$l['status'] = '상태';
