<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Thu, 04 Jul 2024 05:34:29 +0000
// --------------------------------------------------------------------------------

$l['system_email_log'] = '시스템 이메일 로그';
$l['system_email_log_desc'] = 'MyBB에서 생성되어 전송 시 오류를 반환한 모든 이메일은 MyBB에 의해 기록되며 아래에 표시됩니다. 이 섹션은 특히 SMTP 구성 문제를 식별하거나 서버의 메일 지원을 식별하는 데 유용합니다.';
$l['prune_system_email_log'] = '시스템 이메일 로그 정리';
$l['filter_system_email_log'] = '시스템 이메일 로그 필터링';
$l['close_window'] = '창 닫기';
$l['user_email_log_viewer'] = '사용자 이메일 로그 뷰어';
$l['smtp_code'] = 'SMTP 코드:';
$l['smtp_server_response'] = 'SMTP 서버 응답:';
$l['to'] = '에게';
$l['from'] = '부터';
$l['subject'] = '제목';
$l['date'] = '날짜';
$l['email'] = '이메일';
$l['date_sent'] = '보낸 날짜';
$l['error_message'] = '에러 메시지';
$l['find'] = '찾기';
$l['no_logs'] = '선택한 기준에 해당하는 로그 항목이 없습니다.';
$l['subject_contains'] = '제목 포함';
$l['error_message_contains'] = '에러 메시지 포함';
$l['to_address_contains'] = '받는 사람 주소 포함';
$l['from_address_contains'] = '보내는 사람 주소 포함';
$l['find_emails_to_addr'] = '이 주소로 전송된 모든 이메일 찾기';
