<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Thu, 04 Jul 2024 03:13:19 +0000
// --------------------------------------------------------------------------------

$l['spam_logs'] = '스팸 로그';
$l['spam_logs_desc'] = '이 섹션에서는 스팸 필터에 의해 차단된 사용자의 기록을 볼 수 있습니다.';
$l['prune_spam_logs'] = '스팸 로그 정리';
$l['prune_spam_logs_desc'] = '여기서는 지정된 기준과 일치하는 스팸 로그를 정리할 수 있습니다.';
$l['spam_username'] = '사용자 이름';
$l['spam_email'] = '이메일 주소';
$l['spam_ip'] = 'IP 주소';
$l['spam_date'] = '날짜';
$l['spam_confidence'] = '신뢰';
$l['no_spam_logs'] = '아직 스팸 필터에 의해 차단된 사용자는 없습니다.';
$l['success_pruned_spam_logs'] = '스팸 로그가 성공적으로 정리되었습니다.';
$l['note_logs_locked'] = '보안상의 이유로 24시간 미만의 로그는 정리할 수 없습니다.';
$l['all_usernames'] = '모든 사용자 이름';
$l['all_emails'] = '모든 이메일 주소';
$l['date_range'] = '날짜 범위:';
$l['older_than'] = '이전의';
$l['days'] = '일';
$l['filter_spam_logs'] = '스팸 로그 필터링';
$l['asc'] = '오름차순';
$l['desc'] = '내림차순';
$l['search_ip_on_sfs'] = 'Stop Forum Spam에서 이 IP를 검색하세요.';
$l['search'] = '검색';
$l['in'] = 'in';
$l['order'] = '순서';
$l['sort_by'] = '정렬 기준';
$l['results_per_page'] = '페이지당 결과';
