<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 05 Jul 2024 04:01:49 +0000
// --------------------------------------------------------------------------------

$l['recount_rebuild'] = 'Recount &amp; Rebuild';
$l['recount_rebuild_desc'] = '여기에서 &amp; 포럼의 동기화 오류를 수정하려면 데이터를 다시 작성하세요.';
$l['data_per_page'] = '페이지당 데이터 항목';
$l['recount_stats'] = 'Recount 통계';
$l['recount_stats_desc'] = '그러면 포럼 색인 및 통계 페이지에서 귀하의 포럼 통계가 계산되고 업데이트됩니다.';
$l['recount_reputation'] = '평판 Recount';
$l['recount_reputation_desc'] = '이것은 각 사용자의 평판을 recount합니다.';
$l['recount_warning'] = 'Recount 경고 사항';
$l['recount_warning_desc'] = '이는 각 사용자의 활성 경고 포인트를 다시 계산합니다.';
$l['recount_private_messages'] = '비공개 메시지 Recount';
$l['recount_private_messages_desc'] = '그러면 각 사용자의 비공개 메시지 수가 계산됩니다.';
$l['recount_referrals'] = '추천 Recount';
$l['recount_referrals_desc'] = '각 사용자의 추천 횟수를 계산합니다.';
$l['recount_thread_ratings'] = '글타래 평판 Recount';
$l['recount_thread_ratings_desc'] = '그러면 각 글타래의 평판이 다시 계산됩니다.';
$l['rebuild_forum_counters'] = '포럼 카운터 Rebulid';
$l['rebuild_forum_counters_desc'] = '이것이 실행되면 게시물/글타래 카운터와 각 포럼의 마지막 게시물이 올바른 값을 반영하도록 업데이트됩니다.';
$l['rebuild_thread_counters'] = '글타래 카운터 Rebuild';
$l['rebuild_thread_counters_desc'] = '이것이 실행되면 게시/보기 카운터와 각 글타래의 마지막 게시가 올바른 값을 반영하도록 업데이트됩니다.';
$l['rebuild_poll_counters'] = '설문조사 Rebuild';
$l['rebuild_poll_counters_desc'] = '이것이 실행되면 각 투표의 투표 카운터와 총 투표 수가 올바른 값을 반영하도록 업데이트됩니다.';
$l['recount_user_posts'] = '사용자 게시물 수 Recount';
$l['recount_user_posts_desc'] = '이것이 실행되면 각 사용자의 게시물 수가 데이터베이스의 게시물과 게시물 수가 비활성화된 포럼을 기반으로 현재 실시간 값을 반영하도록 업데이트됩니다.';
$l['recount_user_threads'] = '사용자 글타래 수 Recount';
$l['recount_user_threads_desc'] = '이것이 실행되면 각 사용자의 글타래 수가 업데이트되어 데이터베이스의 글타래와 글타래 수가 비활성화된 포럼을 기반으로 현재 라이브 값을 반영합니다.';
$l['rebuild_attachment_thumbs'] = '첨부 파일 썸네일 Rebuild';
$l['rebuild_attachment_thumbs_desc'] = '이렇게 하면 첨부 파일 썸네일을 다시 작성하여 현재 너비와 높이 치수를 사용하고 있는지 확인하고 누락된 썸네일도 다시 작성합니다.';
$l['success_rebuilt_forum_counters'] = '포럼 카운터가 성공적으로 재구축되었습니다.';
$l['success_rebuilt_thread_counters'] = '글타래 카운터가 성공적으로 다시 작성되었습니다.';
$l['success_rebuilt_poll_counters'] = '설문조사가 성공적으로 재구축되었습니다.';
$l['success_rebuilt_user_post_counters'] = '사용자 게시물 수가 성공적으로 계산되었습니다.';
$l['success_rebuilt_user_thread_counters'] = '사용자 글타래 수가 성공적으로 계산되었습니다.';
$l['success_rebuilt_attachment_thumbnails'] = '첨부 파일 썸네일이 성공적으로 다시 작성되었습니다.';
$l['success_rebuilt_forum_stats'] = '포럼 통계가 성공적으로 Rebuild 되었습니다.';
$l['success_rebuilt_reputation'] = '사용자 평판이 성공적으로 Rebuild 되었습니다.';
$l['success_rebuilt_warning'] = '사용자 경고 지점이 성공적으로 Rebuild 되었습니다.';
$l['success_rebuilt_private_messages'] = '사용자 개인 메시지 수가 성공적으로 계산되었습니다.';
$l['success_rebuilt_referral'] = '사용자 추천 횟수가 성공적으로 계산되었습니다.';
$l['success_rebuilt_thread_ratings'] = '글타래 등급이 성공적으로 계산되었습니다.';
$l['confirm_proceed_rebuild'] = 'Recount & Rebuild 프로세스를 계속하려면 "진행"을 클릭하세요.';
$l['automatically_redirecting'] = '자동으로 리디렉션 &hellip;';
