<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Thu, 04 Jul 2024 03:07:04 +0000
// --------------------------------------------------------------------------------

$l['mass_mail'] = '대량메일';
$l['mass_mail_queue'] = '대량 메일 대기열';
$l['mass_mail_queue_desc'] = '여기에서는 현재 전송 중이거나 앞으로 전송 대기 중인 대량 메일을 관리할 수 있습니다.';
$l['create_mass_mail'] = '새 메일링 만들기';
$l['create_mass_mail_desc'] = '여기에서 새로운 대량 메일링을 생성하고 옵션을 설정할 수 있습니다.';
$l['mass_mail_archive'] = '대량 메일링 아카이브';
$l['mass_mail_archive_desc'] = '이미 발송된 대량 메일의 로그를 확인할 수 있습니다.';
$l['edit_mass_mail'] = '대량 메일링 편집';
$l['edit_mass_mail_desc'] = '여기서는 대량 메일링과 해당 옵션을 편집할 수 있습니다.';
$l['send_mass_mail'] = '대량 메일 보내기';
$l['email_addr'] = '이메일 주소';
$l['board_name'] = '보드 이름';
$l['board_url'] = '보드 URL';
$l['personalize_message'] = '이 메시지를 개인화:';
$l['message_settings'] = '메시지 설정';
$l['subject'] = '제목';
$l['subject_desc'] = '메시지 제목을 입력해주세요.';
$l['send_via_email'] = '이메일로 보내기';
$l['send_via_pm'] = '비공개 메시지로 보내기';
$l['message_type'] = '메시지 유형';
$l['deliver_immediately'] = '즉시 발송';
$l['deliver_specific'] = '특정 날짜에 발송';
$l['delivery_date'] = '발송 날짜';
$l['delivery_date_desc'] = '대량 메일 발송을 원하는 날짜와 시간을 선택해주세요.';
$l['per_page'] = '페이지 당';
$l['per_page_desc'] = '페이지당 실행할 대량 메일링 개수를 입력해 주세요.';
$l['plain_text_only'] = '일반 텍스트만';
$l['html_only'] = 'HTML만';
$l['html_and_plain_text'] = 'HTML 및 일반 텍스트';
$l['message_format'] = '메시지 형식';
$l['define_html_message'] = 'HTML 메시지 정의';
$l['define_html_message_desc'] = '메시지의 HTML 버전을 입력하세요.';
$l['auto_gen_plain_text'] = '텍스트 버전 자동 생성 시도';
$l['define_text_version'] = '텍스트 버전 정의';
$l['define_text_version_desc'] = '메시지의 텍스트 버전을 입력하세요.';
$l['define_the_recipients'] = '수신자 정의';
$l['username_contains'] = '사용자 이름에 다음이 포함.&hellip;';
$l['email_addr_contains'] = '이메일 주소 포함&hellip;';
$l['members_of'] = '다음 그룹의 구성원&hellip;';
$l['greater_than'] = '보다 큰';
$l['is_exactly'] = '정확하게';
$l['less_than'] = '미만';
$l['more_than'] = '이상';
$l['post_count_is'] = '게시물 수는';
$l['hours'] = '시간';
$l['days'] = '일';
$l['weeks'] = '주';
$l['months'] = '월';
$l['years'] = '연';
$l['ago'] = '전에';
$l['user_last_active'] = '사용자가 마지막으로 활동한지';
$l['user_registered'] = '사용자 등록된지';
$l['save_mass_mail'] = '대량 메일 저장';
$l['additional_user_groups_desc'] = '여러 그룹을 선택하려면 Ctrl을 사용하세요.';
$l['step_four'] = '4단계';
$l['delivery_method'] = '발송 방법';
$l['private_message'] = '비공개 메시지';
$l['email'] = '이메일';
$l['message'] = '메시지';
$l['text_based'] = '텍스트 기반';
$l['preview'] = '미리보기';
$l['mass_mail_preview'] = '대량 이메일 미리보기';
$l['html_based'] = 'HTML 기반';
$l['total_recipients'] = '총 수신자 수';
$l['change_recipient_conds'] = '수신자 조건 변경';
$l['review_message'] = '메시지 검토';
$l['define_delivery_date'] = '발송 날짜 정의';
$l['schedule_for_delivery'] = '발송 일정';
$l['username'] = '사용자 이름';
$l['step_three'] = '3단계';
$l['next_step'] = '다음 단계';
$l['step_two'] = '2 단계';
$l['review_text_version'] = '텍스트 버전 검토';
$l['review_text_version_desc'] = '자동으로 생성된 텍스트 버전을 검토하세요.';
$l['step_one'] = '1 단계';
$l['status'] = '상태';
$l['recipients'] = '수신자';
$l['delivered'] = '배달됨';
$l['canceled'] = '취소됨';
$l['resend'] = '재전송';
$l['no_archived_messages'] = '이전에 발송했거나 취소한 대량 메일이 없습니다.';
$l['draft'] = '임시보관함함';
$l['queued'] = '대기 중';
$l['delivering'] = '배달 중';
$l['na'] = 'N/A';
$l['mass_mail_cancel_confirmation'] = '이 대량 메일 발송을 취소하시겠습니까?';
$l['no_unsent_messages'] = '발송되지 않았거나 대기 중이거나 현재 전송 중인 대량 메일이 없습니다.';
$l['error_invalid_mid'] = '잘못된 대량 메일을 선택했습니다.';
$l['error_only_in_future'] = '앞으로는 대량 메일만 전달할 수 있습니다.';
$l['error_no_users'] = '검색 기준에 따라 사용자가 반환되지 않았습니다. 기준을 조정하고 다시 시도하세요.';
$l['error_missing_plain_text'] = '이 메시지의 일반 텍스트 버전을 입력하지 않았습니다.';
$l['error_missing_subject'] = '이 대량 메일의 제목을 입력하지 않았습니다.';
$l['error_missing_message'] = '보낼 메시지를 입력하지 않았습니다.';
$l['error_missing_html'] = '이 메시지의 HTML 버전을 입력하지 않았습니다.';
$l['error_delete_invalid_mid'] = '삭제하려는 잘못된 대량 메일을 선택했습니다.';
$l['success_mass_mail_saved'] = '대량메일이 성공적으로 저장되었습니다.';
$l['success_mass_mail_deleted'] = '선택한 대량 메일이 성공적으로 삭제되었습니다.';
$l['success_mass_mail_resent'] = '대량 메일링이 성공적으로 복사되었습니다. 아래에서 검토해 보세요.';
$l['success_mass_mail_canceled'] = '대량메일 발송이 성공적으로 취소되었습니다.';
$l['mass_mail_deletion_confirmation'] = '이 대량 메일을 삭제하시겠습니까?';
