<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 07:24:03 +0000
// --------------------------------------------------------------------------------

$l['users_and_groups'] = '사용자 &amp; 그룹';
$l['users'] = '사용자';
$l['awaiting_activation'] = '활성화 대기 중';
$l['groups'] = '그룹';
$l['user_titles'] = '사용자 타이틀';
$l['banning'] = '차단';
$l['admin_permissions'] = '관리자 권한';
$l['mass_mail'] = '대량메일';
$l['group_promotions'] = '그룹 프로모션';
$l['can_manage_users'] = '사용자를 관리하겠습니까?';
$l['can_manage_awaiting_activation'] = '활성화 대기를 관리할까요?';
$l['can_manage_user_groups'] = '사용자 그룹을 관리할까요?';
$l['can_manage_user_titles'] = '사용자 타이틀을 관리할까요?';
$l['can_manage_user_bans'] = '사용자 차단을 관리할까요?';
$l['can_manage_admin_permissions'] = '관리자 권한을 관리할까요?';
$l['can_send_mass_mail'] = '대량메일 발송이 가능한가요?';
$l['can_manage_group_promotions'] = '그룹 프로모션을 관리할 수 있나요?';
