<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Thu, 04 Jul 2024 05:44:20 +0000
// --------------------------------------------------------------------------------

$l['awaiting_activation'] = '활성화 대기 중';
$l['awaiting_activation_desc'] = '여기에서 활성화를 기다리는 사용자를 관리할 수 있습니다. 이메일 활성화를 기다리고 있는 사용자는 여기에서 활성화된 경우 이메일을 확인할 필요가 없습니다.';
$l['manage_awaiting_activation'] = '활성화 대기 관리';
$l['no_users_awaiting_activation'] = '현재 활성화를 기다리는 사용자가 없습니다.';
$l['username'] = '사용자 이름';
$l['registered'] = '등록됨';
$l['last_active'] = '마지막 활동';
$l['email'] = '이메일';
$l['ipaddress'] = 'IP 주소';
$l['type'] = '유형';
$l['email_activation'] = '이메일 활성화를 기다리는 중';
$l['administrator_activation'] = '관리자 활성화 대기 중';
$l['admin_activation_coppa'] = '관리자 활성화 대기 중(COPPA)';
$l['activate_users'] = '사용자 활성화';
$l['delete_users'] = '사용자 삭제';
$l['confirm_activate_users'] = '선택한 사용자를 활성화하시겠습니까?';
$l['confirm_delete_users'] = '선택한 사용자를 삭제하시겠습니까?';
$l['no_users_selected'] = '사용자를 선택하지 않았습니다.';
$l['success_users_deleted'] = '선택한 사용자가 삭제되었습니다.';
$l['success_users_activated'] = '선택한 사용자가 활성화되었습니다.';
$l['emailsubject_activateaccount'] = '{1}에서 계정 활성화';
$l['email_adminactivateaccount'] = '{1},

관리자가 {2}에 귀하의 포럼 계정을 활성화했습니다.

계속하려면 다음으로 이동하세요.

{삼}

가입하신 아이디로 로그인이 가능합니다.

감사합니다,
{2} 직원';
