<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 05 Jul 2024 03:12:55 +0000
// --------------------------------------------------------------------------------

$l['user_group_promotions'] = '사용자 그룹 프로모션';
$l['user_group_promotions_desc'] = '여기에서 사용자 그룹 프로모션을 관리할 수 있습니다.';
$l['edit_promotion'] = '프로모션 수정';
$l['edit_promotion_desc'] = '여기에서 보드에 자동으로 실행되는 프로모션을 편집할 수 있습니다.';
$l['add_new_promotion'] = '새 프로모션 추가';
$l['add_new_promotion_desc'] = '여기에서 보드에서 자동으로 실행되는 새로운 프로모션을 만들 수 있습니다.';
$l['title'] = '제목';
$l['short_desc'] = '간단한 설명';
$l['post_count'] = '게시물 수';
$l['thread_count'] = '글타래 수';
$l['reputation'] = '평판';
$l['referrals'] = '추천';
$l['time_registered'] = '등록된 시간';
$l['time_online'] = '온라인 시간';
$l['promo_requirements'] = '프로모션 요구 사항';
$l['promo_requirements_desc'] = '이 프로모션이 충족해야 하는 기준을 선택하세요. Ctrl 키를 누르고 있으면 여러 기준이 선택됩니다.';
$l['greater_than_or_equal_to'] = '다음보다 크거나 같음';
$l['greater_than'] = '보다 큰';
$l['equal_to'] = '같음';
$l['less_than_or_equal_to'] = '작거나 같음';
$l['less_than'] = '보다 작음';
$l['reputation_count'] = '평판 수';
$l['reputation_count_desc'] = '요구되는 평판의 양을 입력하세요. 이를 포함하려면 필수 값으로 평판을 선택해야 합니다. 평판 비교 유형을 선택합니다.';
$l['referral_count'] = '추천 수';
$l['referral_count_desc'] = '필요한 추천 수를 입력하세요. 이를 포함하려면 추천 수를 필수 값으로 선택해야 합니다. 추천 비교 유형을 선택합니다.';
$l['warning_points'] = '경고 포인트';
$l['warning_points_desc'] = '필요한 경고 지점 수를 입력합니다. 이를 포함하려면 필수 값으로 경고 포인트를 선택해야 합니다. 경고 지점의 비교 유형을 선택합니다.';
$l['post_count_desc'] = '필요한 게시물 수를 입력하세요. 이를 포함하려면 필수 값으로 게시물 수를 선택해야 합니다. 게시물의 비교 유형을 선택합니다.';
$l['thread_count_desc'] = '필요한 스레드 수를 입력합니다. 이를 포함하려면 스레드 수를 필수 값으로 선택해야 합니다. 스레드의 비교 유형을 선택합니다.';
$l['hours'] = '시간';
$l['days'] = '일';
$l['weeks'] = '주';
$l['months'] = '월';
$l['years'] = '연';
$l['time_registered_desc'] = '이 사용자가 등록되어야 하는 시간, 일, 주, 월 또는 년 수를 입력하십시오. 등록된 시간이 포함되려면 필수 값으로 선택해야 합니다. 등록된 시간을 시간, 일, 주, 월, 년 단위로 계산할지 선택합니다.';
$l['time_online_desc'] = '이 사용자가 온라인에 있어야 하는 시간, 일, 주, 월 또는 년 수를 입력합니다. 이를 포함하려면 온라인 시간을 필수 값으로 선택해야 합니다. 온라인에서 보낸 시간을 시간, 일, 주, 월 또는 년 단위로 계산할지 선택합니다.';
$l['all_user_groups'] = '모든 사용자 그룹';
$l['orig_user_group'] = '기존 사용자 그룹';
$l['orig_user_group_desc'] = '프로모션을 실행하기 위해 사용자가 속해야 하는 사용자 그룹을 선택합니다. Ctrl 키를 누르면 여러 그룹이 선택됩니다.';
$l['new_user_group'] = '새로운 사용자 그룹';
$l['new_user_group_desc'] = '이번 승격 이후 사용자가 이동할 사용자 그룹을 선택하세요.';
$l['primary_user_group'] = '기본 사용자 그룹';
$l['secondary_user_group'] = '보조 사용자 그룹';
$l['user_group_change_type'] = '사용자 그룹 변경 유형';
$l['user_group_change_type_desc'] = '사용자의 기본 사용자 그룹을 새 사용자 그룹으로 변경해야 하는 경우 \'기본 사용자 그룹\'을 선택합니다. 사용자의 프로필에 새 사용자 그룹을 보조 사용자 그룹으로 추가해야 하는 경우 \'보조 사용자 그룹\'을 선택합니다.';
$l['enabled'] = '활성화?';
$l['enable_logging'] = '로깅을 사용?';
$l['promotion_logs'] = '프로모션 로그';
$l['view_promotion_logs'] = '프로모션 로그 보기';
$l['view_promotion_logs_desc'] = '여기에서 이전에 실행된 프로모션 로그를 볼 수 있습니다.';
$l['promoted_user'] = '프로모션된 사용자';
$l['time_promoted'] = '프로모션 시간';
$l['no_promotion_logs'] = '현재 등록된 프로모션이 없습니다.';
$l['promotion_manager'] = '프로모션 관리자';
$l['promotion'] = '프로모션';
$l['disable_promotion'] = '프로모션 비활성화';
$l['enable_promotion'] = '프로모션 활성화';
$l['delete_promotion'] = '프로모션 삭제';
$l['no_promotions_set'] = '현재 세트 프로모션이 없습니다.';
$l['update_promotion'] = '프로모션 저장';
$l['multiple_usergroups'] = '여러 사용자 그룹';
$l['secondary'] = 'Secondary';
$l['primary'] = 'Primary';
$l['error_no_promo_id'] = '프로모션 ID를 입력하지 않았습니다.';
$l['error_invalid_promo_id'] = '유효한 프로모션 ID를 입력하지 않았습니다.';
$l['error_no_title'] = '이 프로모션의 제목을 입력하지 않았습니다.';
$l['error_no_desc'] = '이 프로모션에 대한 설명을 입력하지 않았습니다.';
$l['error_no_requirements'] = '이 프로모션에 대한 요구 사항을 하나 이상 선택하지 않았습니다.';
$l['error_no_orig_usergroup'] = '이 프로모션에 대한 원래 사용자 그룹을 하나 이상 선택하지 않았습니다.';
$l['error_no_new_usergroup'] = '이 프로모션에 대해 하나 이상의 새 사용자 그룹을 선택하지 않았습니다.';
$l['error_no_usergroup_change_type'] = '이 프로모션에 대해 사용자 그룹 변경 유형을 하나 이상 선택하지 않았습니다.';
$l['success_promo_disabled'] = '선택한 그룹 프로모션이 비활성화되었습니다.';
$l['success_promo_deleted'] = '선택한 그룹 프로모션이 성공적으로 삭제되었습니다.';
$l['success_promo_enabled'] = '선택한 그룹 프로모션이 활성화되었습니다.';
$l['success_promo_updated'] = '선택한 그룹 프로모션이 성공적으로 업데이트되었습니다.';
$l['success_promo_added'] = '프로모션이 성공적으로 생성되었습니다.';
$l['confirm_promo_disable'] = '이 프로모션을 비활성화하시겠습니까?';
$l['confirm_promo_deletion'] = '이 프로모션을 삭제하시겠습니까?';
