<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 05 Jul 2024 04:16:46 +0000
// --------------------------------------------------------------------------------

$l['admin_permissions'] = '관리자 권한';
$l['user_permissions'] = '사용자 권한';
$l['user_permissions_desc'] = '여기에서 개별 사용자의 관리자 권한을 관리할 수 있습니다. 이를 통해 Admin CP의 다른 영역에서 특정 관리자를 효과적으로 잠글 수 있습니다.';
$l['group_permissions'] = '그룹 권한';
$l['group_permissions_desc'] = '관리자 권한은 Admin CP에 액세스할 수 있는 권한이 있는 사용자 그룹에도 적용될 수 있습니다. 마찬가지로 이 도구를 사용하여 전체 관리 그룹이 관리 CP의 다른 영역에 액세스하지 못하도록 잠글 수 있습니다.';
$l['default_permissions'] = '기본 권한';
$l['default_permissions_desc'] = '기본 관리 권한은 사용자 정의 관리자 권한이 설정되어 있지 않거나 그룹 관리자 권한을 상속받지 않는 사용자에게 적용되는 권한입니다.';
$l['admin_permissions_updated'] = '관리자 권한이 성공적으로 업데이트되었습니다.';
$l['revoke_permissions'] = '권한 취소';
$l['edit_permissions'] = '권한 편집';
$l['set_permissions'] = '권한 설정';
$l['edit_permissions_desc'] = '여기서 전체 탭 또는 개별 페이지에 대한 액세스를 제한할 수 있습니다. "홈" 탭은 모든 관리자가 액세스할 수 있습니다.';
$l['update_permissions'] = '권한 업데이트';
$l['view_log'] = '로그 보기';
$l['permissions_type_group'] = '그룹의 권한 유형';
$l['permissions_type_user'] = '사용자의 권한 유형';
$l['no_group_perms'] = '현재 설정된 그룹 권한이 없습니다.';
$l['no_user_perms'] = '현재 설정된 사용자 권한이 없습니다.';
$l['edit_user'] = '사용자 프로필 편집';
$l['using_individual_perms'] = '개별 권한 사용';
$l['using_custom_perms'] = '사용자 정의 권한 사용';
$l['using_group_perms'] = '그룹 권한 사용';
$l['using_default_perms'] = '기본 권한 사용';
$l['last_active'] = '마지막 활동';
$l['user'] = '사용자';
$l['edit_group'] = '그룹 편집';
$l['default'] = '기본';
$l['group'] = '그룹';
$l['error_super_admin'] = '죄송합니다. 지정된 사용자는 최고 관리자이므로 해당 사용자에 대해 이 작업을 수행할 수 없습니다.';
$l['error_delete_no_uid'] = '관리자/사용자 그룹 권한 ID를 입력하지 않았습니다.';
$l['error_delete_invalid_uid'] = '유효한 관리자/사용자 그룹 권한 ID를 입력하지 않았습니다.';
$l['success_perms_deleted'] = '관리 사용자/사용자 그룹 권한이 성공적으로 취소되었습니다.';
$l['confirm_perms_deletion'] = '이 관리 사용자/사용자 그룹 권한을 취소하시겠습니까?';
$l['confirm_perms_deletion2'] = '이 사용자의 권한을 취소하시겠습니까?';
$l['confirm_perms_deletion3'] = '이 그룹의 권한을 취소하시겠습니까?';
