<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Fri, 05 Jul 2024 04:12:41 +0000
// --------------------------------------------------------------------------------

$l['banning'] = '차단';
$l['banned_accounts'] = '차단된 계정';
$l['banned_accounts_desc'] = '여기서는 보드 접근이 차단된 사용자 계정을 관리할 수 있습니다.';
$l['ban_a_user'] = '사용자 차단';
$l['ban_a_user_desc'] = '여기에서 사용자를 차단할 수 있습니다.';
$l['edit_ban'] = '차단 수정';
$l['edit_ban_desc'] = '여기에서 현재 차단된 사용자의 이유와 기간을 편집할 수 있습니다.';
$l['banned_ips'] = '차단된 IP';
$l['disallowed_usernames'] = '허용되지 않는 사용자 이름';
$l['disallowed_email_addresses'] = '허용되지 않는 이메일 주소';
$l['error_invalid_ban'] = '편집할 수 없는 차단을 선택했습니다.';
$l['error_invalid_username'] = '입력한 사용자 이름은 유효하지 않으며 존재하지 않습니다.';
$l['error_no_perm_to_ban'] = '이 사용자를 차단할 권한이 없습니다.';
$l['error_already_banned'] = '이 사용자는 이미 금지된 그룹에 속해 있으므로 새 그룹에 추가할 수 없습니다.';
$l['error_ban_self'] = '자신을 차단할 수는 없습니다.';
$l['error_no_reason'] = '이 사용자를 차단하는 이유를 입력하지 않았습니다.';
$l['success_ban_lifted'] = '선택한 차단이 해제되었습니다.';
$l['success_banned'] = '선택한 사용자가 성공적으로 차단되었습니다.';
$l['success_ban_updated'] = '선택한 차단이 성공적으로 업데이트되었습니다.';
$l['success_pruned'] = '선택한 사용자의 게시물과 글타래가 성공적으로 정리되었습니다.';
$l['confirm_lift_ban'] = '이 차단 사항을 해제하시겠습니까?';
$l['confirm_prune'] = '이 사용자가 작성한 모든 글타래와 게시물을 정리하시겠습니까?';
$l['ban_username'] = '사용자 이름 <em>*</em>';
$l['autocomplete_enabled'] = '이 필드에서는 자동 완성이 활성화됩니다.';
$l['ban_reason'] = '차단 사유';
$l['ban_group'] = '차단된 그룹 <em>*</em>';
$l['ban_group_desc'] = '이 사용자를 차단하려면 차단된 그룹으로 이동해야 합니다.';
$l['ban_time'] = '차단 기간 <em>*</em>';
$l['user'] = '사용자';
$l['moderation'] = '중재';
$l['ban_lifts_on'] = '차단 해제';
$l['time_left'] = '남은 시간';
$l['permenantly'] = '영구적으로';
$l['na'] = 'N/A';
$l['for'] = 'for';
$l['bannedby_x_on_x'] = '<strong>{1}</strong><br /><small>{3} {4}에 {2}에 의해 차단됨</small>';
$l['lift'] = 'Lift';
$l['no_banned_users'] = '현재 차단된 사용자가 없습니다.';
$l['prune_threads_and_posts'] = '글타래 &amp; 게시물 정리';
$l['ban_user'] = '사용자 차단';
$l['update_ban'] = '차단 업데이트';
