<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Korean (South Korea)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1838
// Last edited in MyBB Editor by : zardkim
// Last edited date : Tue, 02 Jul 2024 07:18:45 +0000
// --------------------------------------------------------------------------------

$l['user_titles'] = '사용자 타이틀';
$l['user_titles_desc'] = '이 섹션에서는 사용자 타이틀을 관리할 수 있습니다. 사용자 타이틀은 사용자가 작성한 게시물 수에 따라 사용자에게 할당되며 사용자가 보유한 게시물 수에 따라 사용자 정의 \'별\' 이미지가 표시될 수도 있습니다.';
$l['add_new_user_title'] = '새 사용자 타이틀 추가';
$l['add_new_user_title_desc'] = '이 섹션에서는 새로운 사용자 타이틀을 추가할 수 있습니다. <i>참고: 이는 <u><a href="index.php?module=user-group_promotions">프로모션 시스템</a></u></i>이 <strong>아닙니다</strong>.';
$l['error_missing_title'] = '이 사용자 타이틀에 대한 타이틀을 입력하지 않았습니다.';
$l['error_missing_posts'] = '이 사용자 타이틀에 대한 최소 게시물 수를 입력하지 않았습니다.';
$l['error_cannot_have_same_posts'] = '이 사용자 타이틀은 다른 제목과 동일한 최소 게시물 수를 가질 수 없습니다.';
$l['error_invalid_user_title'] = '잘못된 사용자 타이틀을 지정했습니다.';
$l['success_user_title_created'] = '새 사용자 타이틀이 성공적으로 생성되었습니다.';
$l['success_user_title_updated'] = '사용자 타이틀이 성공적으로 업데이트되었습니다.';
$l['success_user_title_deleted'] = '지정된 사용자 타이틀이 성공적으로 삭제되었습니다.';
$l['title_to_assign'] = '할당한 타이틀';
$l['title_to_assign_desc'] = '이 타이틀은 사용자 정의 타이틀 세트가 없는 경우 사용자의 이름 아래에 표시됩니다.';
$l['minimum_posts'] = '최소 게시물';
$l['minimum_posts_desc'] = '사용자에게 이 사용자 타이틀을 할당하기 전에 사용자가 보유해야 하는 최소 게시물 수입니다.';
$l['number_of_stars'] = '별의 수';
$l['number_of_stars_desc'] = '이 사용자 제목 아래에 표시할 별표 수를 입력하세요. 별표를 표시하지 않으려면 0으로 설정하세요.';
$l['star_image'] = '별 이미지';
$l['star_image_desc'] = '이 사용자 제목에 별표가 표시되어야 하는 경우 여기에 별표 이미지의 경로를 입력하세요. 비어 있으면 사용자 그룹 별 이미지가 표시됩니다. 시청자의 현재 테마에 대한 이미지 디렉터리를 지정하려면 {theme}을 사용하세요.';
$l['save_user_title'] = '사용자 타이틀 저장';
$l['edit_user_title'] = '사용자 타이틀 편집';
$l['edit_user_title_desc'] = '이 섹션에서는 사용자 타이틀을 편집할 수 있습니다.';
$l['user_title_deletion_confirmation'] = '이 사용자 타이틀을 삭제하시겠습니까?';
$l['manage_user_titles'] = '사용자 타이틀 관리';
$l['user_title'] = '사용자 타이틀';
$l['no_user_titles'] = '현재 정의된 사용자 타이틀이 없습니다.';
